using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// Whether what somebody has done to you before changes what they do to you
    /// now, using only the shipped mechanisms.
    ///
    /// N earlier times Daniel goes through her things, each on its own day and
    /// each perceived by her; then long enough that nothing is still felt; then
    /// one later event built identically in every arm. The only difference
    /// between arms is how many times it happened before. Built on S1.7's
    /// harness (`S17`), which is ordinary scenario data: no rule, number or line
    /// of `Fallow.Core` was added or changed for this experiment.
    ///
    /// Writes `Docs/experiments/accumulated-history/measurements.md`.
    /// </summary>
    public class AccumulatedHistoryExperimentTests
    {
        static readonly int[] Curve = { 0, 1, 2, 3, 4, 6, 8, 10, 12, 16 };
        const int Seeds = 10;

        /// <summary>Long enough that nothing the earlier events stirred is still felt (S1.7).</summary>
        const double Settled = 40.0;

        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load() => _content = Baselines.Primary();

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Accumulated interpersonal history: measurements");
            sb.AppendLine();
            sb.AppendLine("Generated by `AccumulatedHistoryExperimentTests` on the primary baseline, using S1.7's harness. Each arm lives N earlier times of the same thing, then waits until nothing is felt, then meets one later event built identically in every arm. Nothing in `Fallow.Core` or the data was changed.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "accumulated-history");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "measurements.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);

        static double Belief(Mind mind, string predicate, params string[] args)
            => mind.Beliefs.Confidence(predicate, args.ToList());

        static S17Arm Arm(string subject, int priors, string probe, bool answerable, bool sees = true)
            => new S17Arm
            {
                Label = "N=" + priors,
                Subject = subject,
                Other = "daniel",
                PriorSlights = priors,
                SubjectSeesPriors = sees,
                Answerable = answerable,
                LagFades = Settled,
                ProbeKind = probe,
                Room = "back_room",
                Present = new List<string> { "daniel" },
                Hunger = 0.50
            };

        // ------------------------------------------------------------------ 1

        [Test, Timeout(1800000)]
        public void H1_WhatTheSameEventMeansAfterNTimes()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 1. What the same event means, after it has happened N times before");
            sb.AppendLine();
            sb.AppendLine("Every arm: the subject in the back room with Daniel, hunger 0.50, " + Settled + " units of fading since the last earlier time, then the same later event. **Label** is the winning reading; **weight** is what it won with; **margin** is how far ahead of the next reading it was.");
            sb.AppendLine();

            foreach (var subject in new[] { "elena", "mara" })
            foreach (var probe in new[] { S17.Search, S17.Observe })
            foreach (var answerable in new[] { true, false })
            {
                sb.AppendLine("### " + subject + ", " + (probe == S17.Search ? "he goes through her things again" : "he watches her") +
                              ", " + (answerable ? "and she believes she is answerable for the missing can" : "and she is not answerable"));
                sb.AppendLine();
                sb.AppendLine("Beliefs are as they stood **before** the later event. What she starts with at N=0 is whatever her character file seeds: Mara's says she already believes Daniel treats her like a child (0.55); Elena's says nothing of the kind.");
                sb.AppendLine();
                sb.AppendLine("| Earlier times | `treats_me_like_a_child` | `does_not_respect_me` | `answerable_for` | Label | Weight | Runner-up | Margin | Stirred | Chose |");
                sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|");

                string firstLabel = null;
                var labels = new List<string>();
                foreach (var n in Curve)
                {
                    var c = S17.Run(_content, Arm(subject, n, probe, answerable));
                    // As they stood BEFORE the later event: the event itself
                    // nudges them, and that is not what this column is about.
                    var child = c.Belief("tendency(daniel,treats_me_like_a_child)");
                    var respect = c.Belief("tendency(daniel,does_not_respect_me)");
                    var answer = Belief(c.Mind, "answerable_for", subject, "missing_can");
                    firstLabel = firstLabel ?? c.Meaning;
                    labels.Add(c.Meaning);
                    sb.AppendLine("| " + n + " | " + F(child) + " | " + F(respect) + " | " + F(answer) + " | " +
                                  (c.Meaning == firstLabel ? c.Meaning : "**" + c.Meaning + "**") + " | " + F(c.Weight) + " | " +
                                  (c.RunnerUp ?? "none") + " " + F(c.RunnerUpWeight) + " | " + F(c.Weight - c.RunnerUpWeight) + " | " +
                                  (c.Stirring.Length == 0 ? "nothing" : c.Stirring) + " | " + c.Chosen + " |");
                }
                sb.AppendLine();
                var flipped = labels.Distinct().Count() > 1;
                sb.AppendLine(flipped
                    ? "**The reading changes**: " + string.Join(" -> ", labels.Select((l, i) => Curve[i] + ": " + l).Where((l, i) => i == 0 || labels[i] != labels[i - 1]))
                    : "**The reading never changes**: " + labels[0] + " at every number of earlier times.");
                sb.AppendLine();
            }
            Record("1", sb.ToString());
        }

        // ------------------------------------------------------------------ 2

        [Test, Timeout(1800000)]
        public void H2_WhatChangesWithTheReading()
        {
            // Where the label flips, what does it take with it? The three levels
            // the brief asks for, side by side, for both subjects.
            var sb = new StringBuilder();
            sb.AppendLine("## 2. No history, small history, accumulated history");
            sb.AppendLine();
            sb.AppendLine("The same later event (he goes through her things), the same room, the same company, the same hunger, and she believes she is answerable for the missing can. Only the number of earlier times differs.");
            sb.AppendLine();

            foreach (var subject in new[] { "elena", "mara" })
            {
                var arms = new[] { 0, 1, 12 }.Select(n => (N: n, C: S17.Run(_content, Arm(subject, n, S17.Search, true)))).ToList();
                sb.AppendLine("### " + subject);
                sb.AppendLine();
                sb.AppendLine("| | none (N=0) | small (N=1) | accumulated (N=12) |");
                sb.AppendLine("|---|---|---|---|");
                sb.AppendLine("| Her belief `treats_me_like_a_child`, before it | " + string.Join(" | ", arms.Select(a => F(a.C.Belief("tendency(daniel,treats_me_like_a_child)")))) + " |");
                sb.AppendLine("| Her belief `does_not_respect_me`, before it | " + string.Join(" | ", arms.Select(a => F(a.C.Belief("tendency(daniel,does_not_respect_me)")))) + " |");
                sb.AppendLine("| ... of which seeded by her character file | " + string.Join(" | ", arms.Select(a => subject == "mara" ? "0.550 of the first" : "none")) + " |");
                sb.AppendLine("| Memories of him going through her things | " + string.Join(" | ", arms.Select(a => a.C.Mind.Experiences.Count(x => x.ActorId == "daniel" && x.Topic == "missing_can").ToString())) + " |");
                sb.AppendLine("| **She read it as** | " + string.Join(" | ", arms.Select(a => "**" + a.C.Meaning + "** " + F(a.C.Weight))) + " |");
                sb.AppendLine("| Next reading | " + string.Join(" | ", arms.Select(a => (a.C.RunnerUp ?? "none") + " " + F(a.C.RunnerUpWeight))) + " |");
                sb.AppendLine("| The rules that read it | " + string.Join(" | ", arms.Select(a => a.C.RulesDetail ?? "-")) + " |");
                sb.AppendLine("| It stirred | " + string.Join(" | ", arms.Select(a => a.C.Stirring.Length == 0 ? "nothing" : a.C.Stirring)) + " |");
                sb.AppendLine("| She was left feeling | " + string.Join(" | ", arms.Select(a => string.Join(", ", a.C.Emotions.OrderByDescending(x => x.Value).Take(4).Select(x => x.Key + " " + F(x.Value))))) + " |");
                sb.AppendLine("| She wanted | " + string.Join(" | ", arms.Select(a => string.Join(", ", a.C.Wants.OrderByDescending(x => x.Value).Take(4).Select(x => x.Key + " " + F(x.Value))))) + " |");
                sb.AppendLine("| She chose | " + string.Join(" | ", arms.Select(a => a.C.Chosen + " for " + a.C.LeadingWant + ", " + a.C.Resolution)) + " |");
                sb.AppendLine("| Everything downstream, identical to N=0? | - | " + string.Join(" | ", arms.Skip(1).Select(a => a.C.Downstream == arms[0].C.Downstream ? "identical" : "**different**")) + " |");
                sb.AppendLine();
            }

            // Controls: she was not there for them; and taking the history away again.
            sb.AppendLine("### Controls");
            sb.AppendLine();
            sb.AppendLine("| | elena | mara |");
            sb.AppendLine("|---|---|---|");
            foreach (var (label, make) in new (string, Func<string, S17Chain>)[]
            {
                ("N=0, run twice: identical", s => S17.Run(_content, Arm(s, 0, S17.Search, true))),
                ("N=12 but she was never there to see them", s => S17.Run(_content, Arm(s, 12, S17.Search, true, sees: false))),
                ("N=12, then the history taken away again (N=0)", s => S17.Run(_content, Arm(s, 0, S17.Search, true)))
            })
            {
                sb.AppendLine("| " + label + " | " + string.Join(" | ", new[] { "elena", "mara" }.Select(s =>
                {
                    var baseline = S17.Run(_content, Arm(s, 0, S17.Search, true));
                    var arm = make(s);
                    return arm.Meaning + " " + F(arm.Weight) + (arm.Downstream == baseline.Downstream ? ", downstream identical to N=0" : ", downstream differs from N=0");
                })) + " |");
            }
            Record("2", sb.ToString());

            // The unseen history must leave her exactly as no history does.
            foreach (var s in new[] { "elena", "mara" })
            {
                var none = S17.Run(_content, Arm(s, 0, S17.Search, true));
                var unseen = S17.Run(_content, Arm(s, 12, S17.Search, true, sees: false));
                Assert.AreEqual(none.Meaning, unseen.Meaning, s + ": history she never saw must change nothing");
                Assert.AreEqual(none.Downstream, unseen.Downstream, s + ": downstream");
            }
        }

        // ------------------------------------------------------------------ 3

        [Test, Timeout(3600000)]
        public void H3_TheSameQuestionInALiveMorning()
        {
            // The same later event, put into a live morning at the same minute,
            // with the history written into the days before it.
            var sb = new StringBuilder();
            sb.AppendLine("## 3. The same question in a live morning");
            sb.AppendLine();
            sb.AppendLine("The history is written into the backstory (S1.7's `WithHistory`), so the morning starts with her already carrying it. The same later event is put into the morning at the same minute in every arm, at the first minute after 10 at which she and Daniel are in the same room in the no-history run. Her circumstances at that moment are checked, because the history may already have changed her morning.");
            sb.AppendLine();
            sb.AppendLine("Each subject is run in the condition of the house where she has reason to believe she is answerable for the missing can (`mara_ate_it` for Mara, `elena_fed_mara` for Elena), so that the later event has a competing reading for history to overtake.");
            sb.AppendLine();
            sb.AppendLine("| Subject | Seed | Probe at | Her morning up to then, identical to N=0 | N=0 read it as | N=1 | N=12 | Her next act, N=0 | N=12 | Her reason, N=0 -> N=12 |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|");

            var skipped = new List<string>();
            var labelChanged = 0;
            var weightChanged = 0;
            var actChanged = 0;
            var reasonChanged = 0;
            var comparable = 0;
            var total = 0;

            foreach (var subject in new[] { "elena", "mara" })
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var minute = ProbeMinute(_content, subject, seed);
                if (minute < 0) { skipped.Add(subject + " seed " + seed); continue; }
                total++;

                var arms = new[] { 0, 1, 12 }.Select(n =>
                {
                    var content = n == 0 ? _content : S17.WithHistory(_content, n, "daniel", subject);
                    return (N: n, Run: RunWithProbe(content, subject, seed, minute));
                }).ToList();

                // Comparable only if nothing about her had already diverged: same
                // circumstances and the same decisions all morning up to then.
                var same = arms.All(a => a.Run.Circumstance == arms[0].Run.Circumstance && a.Run.Before == arms[0].Run.Before);
                if (same) comparable++;
                if (same && arms[2].Run.Label != arms[0].Run.Label) labelChanged++;
                if (same && Math.Abs(arms[2].Run.Weight - arms[0].Run.Weight) > 1e-9) weightChanged++;
                if (same && arms[2].Run.NextAct != arms[0].Run.NextAct) actChanged++;
                if (same && arms[2].Run.NextAct == arms[0].Run.NextAct && arms[2].Run.NextReason != arms[0].Run.NextReason) reasonChanged++;

                sb.AppendLine("| " + subject + " | " + seed + " | m" + minute + " | " + (same ? "yes" : "**no**") + " | " +
                              arms[0].Run.Label + " " + F(arms[0].Run.Weight) + " | " + arms[1].Run.Label + " " + F(arms[1].Run.Weight) + " | " +
                              arms[2].Run.Label + " " + F(arms[2].Run.Weight) + " | " + arms[0].Run.NextAct + " | " +
                              (arms[2].Run.NextAct == arms[0].Run.NextAct ? "the same" : "**" + arms[2].Run.NextAct + "**") + " | " +
                              arms[0].Run.NextReason + " -> " + (arms[2].Run.NextReason == arms[0].Run.NextReason ? "the same" : "**" + arms[2].Run.NextReason + "**") + " |");
            }

            sb.AppendLine();
            if (skipped.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("**" + skipped.Count + " runs could not be used**, because the two of them were never in the same room after minute 10, so the later event could not happen to her at all: " + string.Join(", ", skipped) + ".");
            }
            sb.AppendLine();
            sb.AppendLine("Of " + total + " runs, **" + comparable + "** had identical circumstances at the moment of the later event in all three arms. Among those: the **label** differed between no history and accumulated history in **" + labelChanged + "**, the **weight** in **" + weightChanged + "**, and the **act she then chose** in **" + actChanged + "**, and the act was the same but her **reason** for it differed in **" + reasonChanged + "**.");
            Record("3", sb.ToString());
        }

        sealed class Probed
        {
            public string Circumstance;
            public string Label;
            public double Weight;
            public string NextAct;
            public string NextReason;
            /// <summary>Her own decisions before the later event, to tell a cascade from the event.</summary>
            public string Before = "";
        }

        /// <summary>
        /// The condition of the house in which this subject has reason to believe
        /// she is answerable for the missing can, so that the later event has a
        /// competing reading for history to overtake.
        /// </summary>
        static string VariantFor(string subject) => subject == "mara" ? "mara_ate_it" : "elena_fed_mara";

        /// <summary>The first minute after 30 at which the subject and Daniel are in the same room, with no history.</summary>
        static int ProbeMinute(Scenario001Content content, string subject, ulong seed)
        {
            var run = Scenario001.Prepare(content, VariantFor(subject), seed);
            for (var i = 0; i < content.Morning.Minutes; i++)
            {
                run.Morning.Step();
                if (run.World.Minute >= 10 && run.World.RoomOf(subject) == run.World.RoomOf("daniel")) return run.World.Minute;
            }
            return -1;
        }

        static Probed RunWithProbe(Scenario001Content content, string subject, ulong seed, int minute)
        {
            var run = Scenario001.Prepare(content, VariantFor(subject), seed);
            var probed = new Probed { Label = "-", NextAct = "-", NextReason = "-" };
            var seen = false;
            var before = new List<string>();
            run.Morning.Decided = m =>
            {
                if (m.CharacterId != subject) return;
                if (!seen)
                {
                    before.Add("m" + m.Minute + " " + m.Decision.Chosen.Key + " for " + (m.Decision.Leading?.Key ?? "nothing"));
                    return;
                }
                if (probed.NextAct != "-") return;
                probed.NextAct = m.Decision.Chosen.Key;
                probed.NextReason = m.Decision.Leading?.Key ?? "nothing";
            };

            for (var i = 0; i < content.Morning.Minutes; i++)
            {
                run.Morning.Step();
                if (run.World.Minute != minute) continue;
                var room = run.World.RoomOf(subject);
                probed.Circumstance = "room " + room + "; with " + string.Join(",", run.World.WithMe(subject).OrderBy(x => x, StringComparer.Ordinal)) +
                                      "; hunger " + F(run.World.HungerOf(subject));
                if (run.World.RoomOf("daniel") != room) { probed.Label = "not in the same room"; return probed; }

                var witnesses = run.World.InRoom(room).Where(id => id != "daniel").ToList();
                var probe = S17.Probe(S17.Search, "daniel", subject, content.Morning.Day, witnesses);
                var outcome = run.Morning.Happen(probe);
                var hers = outcome.ByCharacter[subject];
                probed.Label = hers.Meaning;
                probed.Weight = hers.InterpretationWeight;
                probed.Before = string.Join(" | ", before);
                seen = true;
            }
            return probed;
        }
    }
}
