using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// DIAGNOSTIC ONLY, for the action representation audit. Read-only: it runs
    /// mornings and looks at what they produced (decisions through the decision
    /// hook, the morning's world events, what each mind kept of them, and the
    /// trace). It changes nothing in `Fallow.Core`, in the data or in any run.
    ///
    /// The question it answers with numbers, where the code answers it in
    /// principle: when two people do the same physical thing for different
    /// reasons, can anything after the choice tell the two apart? Writes
    /// `Docs/experiments/action-representation/diagnostic.md`.
    /// </summary>
    public class ActionRepresentationAuditTests
    {
        const int Seeds = 10;

        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);
        static Survey _primary;
        static Survey _modelA;

        [OneTimeSetUp]
        public void Load()
        {
            var primary = Baselines.Primary();
            _primary = Survey.Run(primary, "B (primary)", Seeds);
            _modelA = Survey.Run(Baselines.ModelA(primary), "A (before)", Seeds);
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Action representation: diagnostic");
            sb.AppendLine();
            sb.AppendLine("Generated by `ActionRepresentationAuditTests`, a diagnostic-only, read-only test. It runs the five design conditions, seeds 1-" + Seeds + ", under the primary baseline (and Model A for comparison where stated), and looks at what each morning produced: every decision through the decision hook, every world event the morning created, what each mind kept of each event, and the trace. It changes nothing in `Fallow.Core`, the data, or any run.");
            sb.AppendLine();
            sb.AppendLine("An act is linked to the world event it produced by its actor and time: the events a person authors after a decision and before their next one are that act's (a walk makes up to two, leaving and arriving, and only if somebody is there; standing still makes none; an act stopped part way makes none). An act that was stopped, thought over and carried on has two decisions and one event, which is counted with the later decision.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "action-representation");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "diagnostic.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string P(double part, double whole) => whole == 0 ? "n/a" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + " %";
        static string Or(string s) => string.IsNullOrEmpty(s) ? "null" : s;

        // ------------------------------------------------------------------ data

        /// <summary>One act, from the decision that chose it to what the house made of it.</summary>
        internal sealed class Act
        {
            public string Variant;
            public ulong Seed;
            public int Minute;
            public string Who;
            public string Room;
            public int Present;
            public bool FoodWithinReach;
            public bool FoodKeptHere;
            public int OthersWorthDoing;
            public int KindsWorthDoing;
            public string Kind;
            public string Key;
            public string Leading;
            public string LeadingName;
            public double LeadingUrgency;
            public string Because;
            public List<(string Want, string Name, string Proposal, double Amount)> Credits = new List<(string, string, string, double)>();
            public double Appeal, Cost, Score, Margin;
            public bool Ambiguous;
            public string Competitors;
            public List<(string Key, double U)> Raised = new List<(string, double)>();
            public string Holding;
            public string Commitment;
            public string Forms;
            public int DecisionTraceId;
            public string Outcome;
            public List<WorldEvent> Events = new List<WorldEvent>();

            /// <summary>For each event: perceiver -> (meaning, own intention, dominant feeling, access).</summary>
            public Dictionary<string, List<(string Who, string Meaning, bool Own, string Felt, string Access)>> Readings =
                new Dictionary<string, List<(string, string, bool, string, string)>>(StringComparer.Ordinal);

            public Dictionary<string, int> EventParents = new Dictionary<string, int>(StringComparer.Ordinal);
            public bool AnyReadingReachesTheDecision;

            public int WantsCrediting => Credits.Select(c => c.Want).Distinct().Count();
        }

        internal sealed class Survey
        {
            public string Label;
            public List<Act> Acts = new List<Act>();
            public int Mornings;

            public static Survey Run(Scenario001Content c, string label, int seeds)
            {
                var s = new Survey { Label = label };
                foreach (var v in c.Morning.Variants.Select(x => x.Id))
                for (ulong seed = 1; seed <= (ulong)seeds; seed++)
                {
                    var run = Scenario001.Prepare(c, v, seed);
                    var byDecision = new Dictionary<int, Act>();
                    run.Morning.Decided = m =>
                    {
                        var d = m.Decision;
                        var chosen = d.ChosenScored;
                        var lead = d.Leading;
                        var a = new Act
                        {
                            Variant = v, Seed = seed, Minute = m.Minute, Who = m.CharacterId, Room = m.Percept.Room?.Id,
                            Present = m.Percept.Present.Count, Kind = d.Chosen.KindName, Key = d.Chosen.Key,
                            FoodWithinReach = m.Percept.FoodWithinReach == true, FoodKeptHere = m.Percept.RoomHoldsFood,
                            OthersWorthDoing = d.Considered.Count(r => r.Score > 0.0 && !r.Option.SameAs(d.Chosen)),
                            KindsWorthDoing = d.Considered.Where(r => r.Score > 0.0).Select(r => r.Option.KindName).Distinct().Count(),
                            Leading = lead?.Key, LeadingName = lead?.Name, LeadingUrgency = lead?.Urgency ?? 0.0,
                            Because = lead?.Because,
                            Appeal = chosen.Appeal, Cost = chosen.Cost, Score = chosen.Score, Margin = d.Margin,
                            Ambiguous = d.Resolution == Resolution.Ambiguous,
                            Competitors = string.Join("; ", d.Considered.Where(r => !r.Option.SameAs(d.Chosen)).Take(3)
                                .Select(r => r.Option.Key + " " + r.Score.ToString("+0.000;-0.000", CultureInfo.InvariantCulture))),
                            Holding = d.Holding?.MotiveKey, Commitment = d.Commitment, Forms = d.Forms?.MotiveKey,
                            DecisionTraceId = d.TraceId
                        };
                        foreach (var x in chosen.Contributions.Where(x => x.Amount > 0.0))
                            a.Credits.Add((x.MotiveKey, x.MotiveName, x.ProposalId, x.Amount));
                        foreach (var w in m.Motives) a.Raised.Add((w.Key, w.Urgency));
                        byDecision[d.TraceId] = a;
                    };
                    run.Morning.Run(c.Morning.Minutes);
                    s.Mornings++;

                    var result = run.Result;
                    var acts = new List<Act>();
                    foreach (var record in result.Actions)
                    {
                        var a = byDecision[record.DecisionTraceId];
                        a.Outcome = record.Outcome;
                        acts.Add(a);
                    }

                    // Each event a person authored belongs to their latest decision before it.
                    var eventRecords = run.Trace.All.Where(r => r.Kind == TraceKind.Event && r.EventId != null)
                        .GroupBy(r => r.EventId).ToDictionary(g => g.Key, g => g.First(), StringComparer.Ordinal);
                    foreach (var e in result.Events.Where(e => e.ActorId != null))
                    {
                        var owner = acts.Where(x => x.Who == e.ActorId && x.Minute < e.Minute).OrderBy(x => x.Minute).LastOrDefault();
                        if (owner == null) continue;
                        owner.Events.Add(e);
                        owner.EventParents[e.Id] = eventRecords.TryGetValue(e.Id, out var er) ? er.ParentIds.Count : -1;

                        var perceivers = new[] { e.ActorId }.Concat(e.Witnesses).Concat(e.Overhearers).Distinct().ToList();
                        var readings = new List<(string, string, bool, string, string)>();
                        foreach (var p in perceivers)
                        {
                            var x = run.Minds[p].Experiences.LastOrDefault(k => k.EventId == e.Id);
                            if (x == null) continue;
                            readings.Add((p, x.Meaning, x.FromOwnIntent, x.DominantEmotion ?? "nothing", x.Access.ToString().ToLowerInvariant()));

                            // Can what this person made of it be walked back to why it was done?
                            var chain = run.Trace.Chain(x.TraceId);
                            if (chain.Any(r => r.Id == owner.DecisionTraceId ||
                                               (r.CharacterId == e.ActorId && (r.Kind == TraceKind.Deliberation || r.Kind == TraceKind.Motive))))
                                owner.AnyReadingReachesTheDecision = true;
                        }
                        owner.Readings[e.Id] = readings;
                    }
                    s.Acts.AddRange(acts);
                }
                return s;
            }

            public IEnumerable<Act> Of(string kind) => Acts.Where(a => a.Kind == kind);
        }

        static readonly string[] Kinds = ActionOption.AllNames.ToArray();

        /// <summary>What the act's own record says, with names taken out.</summary>
        static string WhyNoEvent(Act a)
        {
            var o = a.Outcome;
            if (o == null) return "stopped part way, or the morning ended first";
            if (o.StartsWith("thought again", StringComparison.Ordinal)) return "thought again and carried on (the event is the later decision's)";
            if (o.Contains("had gone before")) return "the person had gone";
            if (o.StartsWith("went to", StringComparison.Ordinal)) return "walked, and nobody was there to see it";
            if (o.StartsWith("stayed", StringComparison.Ordinal)) return "stood still: no event by design";
            // A completion note on the record and no event of its own: it was
            // stopped, thought again and carried on, and the event it made
            // belongs to the decision that carried it on.
            if (o.StartsWith("found", StringComparison.Ordinal) || o.StartsWith("went through", StringComparison.Ordinal) ||
                o.StartsWith("sat with", StringComparison.Ordinal) || o.StartsWith("watched", StringComparison.Ordinal))
                return "completed after being carried on; the event is the later decision's";
            return "other: " + o;
        }

        static string Signature(WorldEvent e)
            => "action=" + Or(e.Action) + ", target=" + (e.TargetId == null ? "none" : "a person") + ", topic=" + Or(e.Topic) +
               ", tone=" + Or(e.Tone) + ", valence=" + Or(e.Valence) + ", intent=" + Or(e.Intent) + ", act=" + Or(e.Act);

        // ------------------------------------------------------------------ 1

        [Test]
        public void D1_WhatEachActPutsIntoTheWorld()
        {
            var s = _primary;
            var sb = new StringBuilder();
            sb.AppendLine("## 1. What each act puts into the world");
            sb.AppendLine();
            sb.AppendLine(s.Mornings + " mornings, " + s.Acts.Count + " decisions, primary baseline. For each kind of act: how often it was chosen, for how many different leading wants, how many world events it produced, and every value each field of those events took.");
            sb.AppendLine();
            sb.AppendLine("| Act | Chosen | Leading wants (distinct) | Events | Acts with no event, and why (from the act's record) | Event fields seen (all values) | `intent` on any event |");
            sb.AppendLine("|---|---|---|---|---|---|---|");
            foreach (var k in Kinds)
            {
                var acts = s.Of(k).ToList();
                if (acts.Count == 0) { sb.AppendLine("| " + k + " | 0 | | | | | |"); continue; }
                var events = acts.SelectMany(a => a.Events).ToList();
                string Values(Func<WorldEvent, string> f) => string.Join("/", events.Select(f).Select(Or).Distinct().OrderBy(x => x, StringComparer.Ordinal));
                var fields = events.Count == 0 ? "none" :
                    "action " + Values(e => e.Action) + "; topic " + Values(e => e.Topic) + "; tone " + Values(e => e.Tone) + "; valence " + Values(e => e.Valence) + "; target " + Values(e => e.TargetId == null ? null : "a person");
                var none = acts.Where(a => a.Events.Count == 0).GroupBy(a => WhyNoEvent(a)).OrderByDescending(g => g.Count()).Select(g => g.Key + " " + g.Count());
                sb.AppendLine("| " + k + " | " + acts.Count + " (" + P(acts.Count, s.Acts.Count) + ") | " + acts.Select(a => a.LeadingName ?? "nothing").Distinct().Count() + " | " + events.Count + " | " + acts.Count(a => a.Events.Count == 0) + ": " + string.Join("; ", none) + " | " + fields + " | " + events.Count(e => e.Intent != null) + " of " + events.Count + " |");
            }
            sb.AppendLine();
            var all = s.Acts.SelectMany(a => a.Events).ToList();
            sb.AppendLine("Of " + all.Count + " world events the morning's acts produced, **" + all.Count(e => e.Intent != null) + "** carry an intent. Every field of every event is set in `SilentMorning.Complete`, `Walk` or `Happened` from the kind of act, its target, the room and the state of the house (the pantry's count decides a valence); none is taken from the decision.");
            Record("1", sb.ToString());

            Assert.AreEqual(0, all.Count(e => e.Intent != null), "no morning act carries an intent");
        }

        // ------------------------------------------------------------------ 2

        [Test]
        public void D2_TheSameActForDifferentReasons()
        {
            var s = _primary;
            var sb = new StringBuilder();
            sb.AppendLine("## 2. The same act, for different reasons");
            sb.AppendLine();
            sb.AppendLine("For each kind of act, the events it produced grouped by everything an event carries except who, where and when (its *signature*). If the reason survived into the world, acts done for different leading wants would produce different signatures.");
            sb.AppendLine();
            sb.AppendLine("| Act | Acts with an event | Leading wants among them | Distinct signatures | Signatures produced for more than one leading want | Acts whose signature is shared with another want |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var shared = 0;
            var withEvent = 0;
            foreach (var k in Kinds)
            {
                var acts = s.Of(k).Where(a => a.Events.Count > 0).ToList();
                if (acts.Count == 0) continue;
                var bySig = acts.SelectMany(a => a.Events.Select(e => (Sig: Signature(e), Want: a.LeadingName ?? "nothing", Act: a)))
                    .GroupBy(x => x.Sig).ToList();
                var multi = bySig.Where(g => g.Select(x => x.Want).Distinct().Count() > 1).ToList();
                var sharedActs = multi.SelectMany(g => g.Select(x => x.Act)).Distinct().Count();
                shared += sharedActs;
                withEvent += acts.Count;
                sb.AppendLine("| " + k + " | " + acts.Count + " | " + string.Join(", ", acts.GroupBy(a => a.LeadingName ?? "nothing").OrderByDescending(g => g.Count()).Select(g => g.Key + " " + g.Count())) + " | " + bySig.Count + " | " + multi.Count + " | " + sharedActs + " (" + P(sharedActs, acts.Count) + ") |");
            }
            sb.AppendLine();
            sb.AppendLine("**" + shared + " of " + withEvent + " acts that produced an event (" + P(shared, withEvent) + ") produced exactly the event an act of the same kind produced for a different reason.**");
            sb.AppendLine();

            // Concrete pairs: the first two acts of a kind whose leading wants differ.
            sb.AppendLine("### Pairs, side by side");
            sb.AppendLine();
            foreach (var k in Kinds)
            {
                var acts = s.Of(k).Where(a => a.Events.Count > 0).ToList();
                Act first = null, second = null;
                foreach (var a in acts)
                {
                    if (first == null) { first = a; continue; }
                    if ((a.LeadingName ?? "nothing") != (first.LeadingName ?? "nothing") && Signature(a.Events[0]) == Signature(first.Events[0])) { second = a; break; }
                }
                if (first == null || second == null) continue;
                sb.AppendLine("**" + k + "**");
                sb.AppendLine();
                sb.AppendLine("| | " + Describe(first) + " | " + Describe(second) + " |");
                sb.AppendLine("|---|---|---|");
                sb.AppendLine("| Why, as deliberated | " + Why(first) + " | " + Why(second) + " |");
                sb.AppendLine("| World event | " + Signature(first.Events[0]) + " | " + Signature(second.Events[0]) + " |");
                sb.AppendLine("| Summary | " + first.Events[0].Summary + " | " + second.Events[0].Summary + " |");
                sb.AppendLine("| What the actor kept | " + Kept(first, true) + " | " + Kept(second, true) + " |");
                sb.AppendLine("| What the others kept | " + Kept(first, false) + " | " + Kept(second, false) + " |");
                sb.AppendLine("| Event's trace record rests on | " + (first.EventParents[first.Events[0].Id] == 0 ? "nothing" : first.EventParents[first.Events[0].Id] + " records") + " | " + (second.EventParents[second.Events[0].Id] == 0 ? "nothing" : second.EventParents[second.Events[0].Id] + " records") + " |");
                sb.AppendLine();
            }
            Record("2", sb.ToString());
        }

        static string Describe(Act a) => a.Who + ", " + a.Variant + " s" + a.Seed + " m" + a.Minute + ", " + a.Key + " in the " + a.Room;

        static string Why(Act a)
            => (a.Leading == null ? "led by nothing" : "led by **" + a.Leading + "** " + F(a.LeadingUrgency)) +
               (a.Credits.Count == 0 ? "" : "; credited by " + string.Join(", ", a.Credits.Select(c => c.Want + " via " + c.Proposal + " " + F(c.Amount))));

        static string Kept(Act a, bool actor)
        {
            var e = a.Events[0];
            var r = a.Readings.TryGetValue(e.Id, out var list) ? list : new List<(string, string, bool, string, string)>();
            var sel = r.Where(x => (x.Item1 == a.Who) == actor).ToList();
            if (sel.Count == 0) return actor ? "nothing" : "nobody else perceived it";
            return string.Join("; ", sel.Select(x => (actor ? "" : x.Item1 + ": ") + x.Item2 + (x.Item3 ? " (own intention)" : " (" + x.Item5 + ")") + ", felt " + x.Item4));
        }

        // ------------------------------------------------------------------ 3

        [Test]
        public void D3_WhereTheReasonCouldBeRecovered()
        {
            var s = _primary;
            var acts = s.Acts.Where(a => a.Events.Count > 0).ToList();
            var events = acts.SelectMany(a => a.Events).ToList();
            var readings = acts.SelectMany(a => a.Readings.Values.SelectMany(x => x)).ToList();
            var own = acts.SelectMany(a => a.Readings.Values.SelectMany(x => x.Where(y => y.Item1 == a.Who))).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("## 3. Whether the reason can be recovered after the act");
            sb.AppendLine();
            sb.AppendLine("| Downstream of the choice | Carries the reason? | Measured |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| The world event's `intent` | no | " + events.Count(e => e.Intent != null) + " of " + events.Count + " events carry one |");
            sb.AppendLine("| The actor's own reading of the act | no: read like a witness | " + own.Count(x => x.Item3) + " of " + own.Count + " are \"own intention\"; the actor's meanings were " + string.Join(", ", own.GroupBy(x => x.Item2).OrderByDescending(g => g.Count()).Select(g => g.Key + " " + g.Count())) + " |");
            sb.AppendLine("| The event's trace record | no: rests on nothing | " + acts.Sum(a => a.EventParents.Values.Count(p => p == 0)) + " of " + events.Count + " event records have no parent |");
            sb.AppendLine("| Anybody's memory of it, walked back through the trace | no | " + acts.Count(a => a.AnyReadingReachesTheDecision) + " of " + acts.Count + " acts have a reading whose chain reaches the actor's decision or wants |");
            sb.AppendLine("| Another person's reading | only their own interpretation of the visible act | " + string.Join(", ", readings.Where(x => !x.Item3).GroupBy(x => x.Item2).OrderByDescending(g => g.Count()).Select(g => g.Key + " " + g.Count())) + " |");
            sb.AppendLine();
            sb.AppendLine("**The actor's own reading, by the want that led the act** (meanings kept by the person who acted):");
            sb.AppendLine();
            sb.AppendLine("| Act | Leading want | Acts | What the actor kept |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var g in acts.GroupBy(a => (a.Kind, Want: a.LeadingName ?? "nothing")).OrderBy(g => g.Key.Kind, StringComparer.Ordinal).ThenByDescending(g => g.Count()))
            {
                var kept = g.SelectMany(a => a.Readings.Values.SelectMany(x => x.Where(y => y.Item1 == a.Who))).GroupBy(x => x.Item2).OrderByDescending(x => x.Count()).Select(x => x.Key + " " + x.Count());
                sb.AppendLine("| " + g.Key.Kind + " | " + g.Key.Want + " | " + g.Count() + " | " + string.Join(", ", kept) + " |");
            }
            Record("3", sb.ToString());

            Assert.AreEqual(0, own.Count(x => x.Item3), "no actor knows their own intention for a morning act");
        }

        // ------------------------------------------------------------------ 4

        [Test]
        public void D4_OneWantManyActs()
        {
            var s = _primary;
            var sb = new StringBuilder();
            sb.AppendLine("## 4. One want, many acts");
            sb.AppendLine();
            sb.AppendLine("For each want, the acts it led, and the acts it contributed to without leading. A want expressed through several acts, and through different targets and destinations, has more than one means.");
            sb.AppendLine();
            sb.AppendLine("| Want | Decisions raised | Led | Acts it led (kind: count) | Distinct acts led (with target/destination) | Of its leads, standing still | Credited the act chosen without leading |");
            sb.AppendLine("|---|---|---|---|---|---|---|");
            foreach (var want in s.Acts.SelectMany(a => a.Raised.Select(r => r.Key.Split(':')[0])).Distinct().OrderBy(x => x, StringComparer.Ordinal))
            {
                var raised = s.Acts.Count(a => a.Raised.Any(r => r.Key.Split(':')[0] == want));
                var led = s.Acts.Where(a => a.LeadingName == want).ToList();
                var helped = s.Acts.Count(a => a.LeadingName != want && a.Credits.Any(c => c.Name == want));
                sb.AppendLine("| " + want + " | " + raised + " | " + led.Count + " (" + P(led.Count, raised) + ") | " +
                              string.Join(", ", led.GroupBy(a => a.Kind).OrderByDescending(g => g.Count()).Select(g => g.Key + ": " + g.Count())) + " | " +
                              led.Select(a => a.Key).Distinct().Count() + " | " + P(led.Count(a => a.Kind == "wait"), led.Count) + " | " + helped + " |");
            }
            sb.AppendLine("| (nothing) | | " + s.Acts.Count(a => a.LeadingName == null) + " | " + string.Join(", ", s.Acts.Where(a => a.LeadingName == null).GroupBy(a => a.Kind).Select(g => g.Key + ": " + g.Count())) + " | | | |");
            sb.AppendLine();

            // Means in sequence: a walk carries the want across, and on arrival what does it become?
            var walks = s.Acts.Where(a => a.Kind == "go_to" && a.Forms != null).ToList();
            sb.AppendLine("### Means in sequence: an intention carried across a walk");
            sb.AppendLine();
            sb.AppendLine("A walk is the only act that leaves an intention standing (`SilentMorning.cs` 288). On arrival the intention restricts the choice to what serves it, unless it lapses. " + walks.Count + " walks set out with an intention; what the next decision did with it:");
            sb.AppendLine();
            sb.AppendLine("| Intention carried | Walks | Held on arrival | Act then chosen, when held | Lapsed: no longer wanted / nothing serves it / not worth it | Interrupted before arriving |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var arrivals = s.Acts.Where(a => a.Holding != null).ToList();
            foreach (var g in walks.GroupBy(a => a.Forms.Split(':')[0]).OrderByDescending(g => g.Count()))
            {
                var here = arrivals.Where(a => a.Holding.Split(':')[0] == g.Key).ToList();
                var held = here.Where(a => a.Commitment == Commitment.Held).ToList();
                sb.AppendLine("| " + g.Key + " | " + g.Count() + " | " + held.Count + " | " + string.Join(", ", held.GroupBy(a => a.Kind).OrderByDescending(x => x.Count()).Select(x => x.Key + " " + x.Count())) + " | " +
                              here.Count(a => a.Commitment == Commitment.NoLongerWanted) + " / " + here.Count(a => a.Commitment == Commitment.Impossible) + " / " + here.Count(a => a.Commitment == Commitment.NotWorthIt) + " | " +
                              (g.Count() - here.Count) + " |");
            }
            Record("4", sb.ToString());
        }

        // ------------------------------------------------------------------ 5

        [Test]
        public void D5_StandingStill()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 5. Standing still");
            sb.AppendLine();
            sb.AppendLine("| | " + _primary.Label + " | " + _modelA.Label + " |");
            sb.AppendLine("|---|---|---|");
            foreach (var (label, f) in new (string, Func<Survey, string>)[]
            {
                ("Chosen", x => { var w = x.Of("wait").Count(); return w + " of " + x.Acts.Count + " (" + P(w, x.Acts.Count) + ")"; }),
                ("... with nothing crediting it (appeal 0)", x => { var w = x.Of("wait").ToList(); var k = w.Count(a => a.Appeal <= 0.0); return k + " (" + P(k, w.Count) + ")"; }),
                ("... credited by exactly one want", x => { var w = x.Of("wait").ToList(); var k = w.Count(a => a.WantsCrediting == 1); return k + " (" + P(k, w.Count) + ")"; }),
                ("... credited by two or more", x => { var w = x.Of("wait").ToList(); var k = w.Count(a => a.WantsCrediting >= 2); return k + " (" + P(k, w.Count) + ")"; }),
                ("... what it cost", x => { var w = x.Of("wait").ToList(); return w.Count == 0 ? "-" : "always " + string.Join("/", w.Select(a => F(a.Cost)).Distinct()); }),
                ("... led by (want: count)", x => string.Join(", ", x.Of("wait").GroupBy(a => a.LeadingName ?? "nothing").OrderByDescending(g => g.Count()).Select(g => g.Key + " " + g.Count()))),
                ("... settled by the seed", x => { var w = x.Of("wait").ToList(); var k = w.Count(a => a.Ambiguous); return k + " (" + P(k, w.Count) + ")"; }),
                ("... led by guarding the supplies (`leave_it_alone`, \"not eating is a thing you do\")", x => x.Of("wait").Count(a => a.LeadingName == "guard_supplies").ToString()),
                ("... ... of which with no food within reach, so that not eating was not a choice", x => { var w = x.Of("wait").Where(a => a.LeadingName == "guard_supplies").ToList(); var k = w.Count(a => !a.FoodWithinReach); return k + " (" + P(k, w.Count) + ")"; }),
                ("... ... of which in a room where food is not even kept", x => { var w = x.Of("wait").Where(a => a.LeadingName == "guard_supplies").ToList(); var k = w.Count(a => !a.FoodKeptHere); return k + " (" + P(k, w.Count) + ")"; }),
                ("... chosen while some other act was worth doing (score above 0)", x => { var w = x.Of("wait").ToList(); var k = w.Count(a => a.OthersWorthDoing > 0); return k + " (" + P(k, w.Count) + ")"; }),
                ("... world events produced", x => x.Of("wait").Sum(a => a.Events.Count).ToString()),
                ("... what the record says came of it", x => string.Join(", ", x.Of("wait").Select(a => a.Outcome ?? "(still going, or stopped)").Distinct())),
                ("... an intention formed by the deliberator (`Decision.Forms`) / kept by the morning", x => x.Of("wait").Count(a => a.Forms != null) + " / 0")
            })
                sb.AppendLine("| " + label + " | " + f(_primary) + " | " + f(_modelA) + " |");
            sb.AppendLine();
            sb.AppendLine("The deliberator forms an intention for every decision a want led; the morning keeps it only for a walk (`SilentMorning.cs` 288), so for standing still it is formed and dropped in the same step.");
            Record("5", sb.ToString());
        }

        // ------------------------------------------------------------------ 6

        [Test]
        public void D6_Hubs()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 6. Hubs: acts many wants feed");
            sb.AppendLine();
            sb.AppendLine("Measured on the acts actually chosen. *Wants that credited it* counts the distinct wants that added something to the chosen option across all its choosings; *per choosing* is how many wants credited that one choice.");
            sb.AppendLine();
            foreach (var s in new[] { _primary, _modelA })
            {
                sb.AppendLine("**" + s.Label + "**");
                sb.AppendLine();
                sb.AppendLine("| Act | Chosen | Wants that credited it | Proposals that credited it | Distinct leading wants | Wants per choosing (mean) | Choosings credited by 2 or more wants | Leading want's share of the act's appeal (mean) | Targets / destinations | Choosings with another act worth doing (another kind) |");
                sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|");
                foreach (var g in s.Acts.GroupBy(a => a.Kind).OrderByDescending(g => g.SelectMany(a => a.Credits.Select(c => c.Name)).Distinct().Count()).ThenByDescending(g => g.Count()))
                {
                    var acts = g.ToList();
                    var share = acts.Where(a => a.Appeal > 0 && a.Leading != null).Select(a => a.Credits.Where(c => c.Want == a.Leading).Sum(c => c.Amount) / a.Appeal).ToList();
                    sb.AppendLine("| " + g.Key + " | " + acts.Count + " | " + acts.SelectMany(a => a.Credits.Select(c => c.Name)).Distinct().Count() + " (" + string.Join(", ", acts.SelectMany(a => a.Credits.Select(c => c.Name)).Distinct().OrderBy(x => x, StringComparer.Ordinal)) + ") | " +
                                  acts.SelectMany(a => a.Credits.Select(c => c.Proposal)).Distinct().Count() + " | " + acts.Select(a => a.LeadingName ?? "nothing").Distinct().Count() + " | " +
                                  acts.Average(a => a.WantsCrediting).ToString("0.00", CultureInfo.InvariantCulture) + " | " + P(acts.Count(a => a.WantsCrediting >= 2), acts.Count) + " | " +
                                  (share.Count == 0 ? "-" : share.Average().ToString("0.00", CultureInfo.InvariantCulture)) + " | " + acts.Select(a => a.Key).Distinct().Count() + " | " +
                                  P(acts.Count(a => a.OthersWorthDoing > 0), acts.Count) + " (" + P(acts.Count(a => a.KindsWorthDoing >= 2), acts.Count) + ") |");
                }
                sb.AppendLine();
            }
            Record("6", sb.ToString());
        }

        // ------------------------------------------------------------------ 7

        [Test]
        public void D7_FiveCases()
        {
            // The first decision (conditions and seeds in order, then minute, then
            // person) led by each want; for a want that never leads, the first
            // decision whose chosen act it credits.
            var s = _primary;
            var sb = new StringBuilder();
            sb.AppendLine("## 7. Five cases, boundary by boundary");
            sb.AppendLine();
            sb.AppendLine("Chosen by rule: the first act (conditions, seeds, minutes, people in order) that the want led **and that produced a world event**; if there is none, the first it led; if it never led, the first act it credited. Each row says what crossed the boundary.");
            sb.AppendLine();
            foreach (var (letter, want) in new[] { ("A", "find_out"), ("B", "restore_standing"), ("C", "guard_supplies"), ("D", "avoid_exposure"), ("E", "look_after") })
            {
                var pick = s.Acts.FirstOrDefault(a => a.LeadingName == want && a.Events.Count > 0)
                           ?? s.Acts.FirstOrDefault(a => a.LeadingName == want)
                           ?? s.Acts.FirstOrDefault(a => a.Credits.Any(c => c.Name == want));
                var how = pick == null ? "never" : pick.LeadingName == want ? (pick.Events.Count > 0 ? "led it" : "led it; no act it led produced an event") : "never led an act; credited this one";
                sb.AppendLine("### Case " + letter + ": " + want + " (" + how + ", " + s.Acts.Count(a => a.LeadingName == want) + " leads in " + s.Mornings + " mornings)");
                sb.AppendLine();
                if (pick == null) { sb.AppendLine("No decision in these mornings credited it at all."); sb.AppendLine(); continue; }
                var e = pick.Events.FirstOrDefault();
                var mine = pick.Credits.Where(c => c.Name == want).ToList();
                sb.AppendLine("| Boundary | What is there | Survives into the next? |");
                sb.AppendLine("|---|---|---|");
                sb.AppendLine("| Circumstance | " + Describe(pick) + ", " + (pick.Present == 0 ? "alone" : pick.Present + " others present") + " | the percept is rebuilt every decision |");
                sb.AppendLine("| Want | " + (pick.LeadingName == want ? pick.Leading + " " + F(pick.LeadingUrgency) + ": " + pick.Because : want + " (not leading)") + " | its urgency and key, as a `Motive` |");
                sb.AppendLine("| Proposal | " + (mine.Count == 0 ? "none" : string.Join("; ", mine.Select(c => c.Proposal + " = " + F(c.Amount)))) + " | only as a `Contribution` on the option; the proposal id is read by nothing but the trace |");
                sb.AppendLine("| Scored option | " + pick.Key + ": for " + F(pick.Appeal) + " (" + string.Join(", ", pick.Credits.Select(c => c.Want + " " + F(c.Amount))) + "), against " + F(pick.Cost) + ", score " + F(pick.Score) + " | the appeal is summed; which wants made it survives on the `Decision` |");
                sb.AppendLine("| Deliberation | " + (pick.Ambiguous ? "too close to call; the seed settled it" : "clear by " + F(pick.Margin)) + "; next: " + pick.Competitors + " | margin and competitors: trace and `ActionRecord` only |");
                sb.AppendLine("| Selected | " + pick.Key + ", led by " + (pick.Leading ?? "nothing") + (pick.Holding == null ? "" : ", carrying " + pick.Holding + " (" + pick.Commitment + ")") + " | the option; the leading want's key only if it is a walk (`Intention`) |");
                sb.AppendLine("| Intention | " + (pick.Forms == null ? "none formed" : pick.Kind == "go_to" ? pick.Forms + ", formed and kept across the walk" : pick.Forms + ", formed and dropped: not a walk") + " | key and name only, and only across a walk |");
                sb.AppendLine("| Execution | " + (pick.Outcome ?? "(no record)") + " | constants per kind of act, and the house |");
                sb.AppendLine("| World event | " + (e == null ? "none" : Signature(e) + ": \"" + e.Summary + "\"") + " | " + (e == null ? "-" : "intent " + Or(e.Intent) + "; its trace record rests on " + (pick.EventParents[e.Id] == 0 ? "nothing" : pick.EventParents[e.Id] + " records")) + " |");
                sb.AppendLine("| Perception and memory | " + (e == null ? "nothing to perceive" : string.Join("; ", pick.Readings[e.Id].Select(x => x.Item1 + (x.Item1 == pick.Who ? " (actor)" : "") + ": " + x.Item2 + ", felt " + x.Item4))) + " | " + (e == null ? "-" : "meaning only; " + (pick.AnyReadingReachesTheDecision ? "some" : "no") + " reading walks back to the decision") + " |");
                sb.AppendLine();
            }
            Record("7", sb.ToString());
        }
    }
}
