using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Data;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// Evidence that the primary experimental baseline is what the shipped data
    /// runs, and that Model A is still there to compare it with.
    ///
    /// The baseline is Model B (S1.5, `dispositions: respond`) with both S1.6
    /// fixes: a walk credited to a want only when its end could be worth doing
    /// (M2, `means: end`), and the scripted events of the lived day carrying the
    /// minute they happened (M1). Nothing in `Fallow.Core` was changed to make
    /// it so; it is three settings in the data. Writes
    /// `Docs/experiments/decision-sensitivity/baseline.md`.
    /// </summary>
    public class BaselineTests
    {
        static Scenario001Content _primary;
        static Scenario001Content _modelA;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        /// <summary>
        /// Model A's mornings, fingerprinted on the data as it was committed
        /// before the change (dd9065c), by loading it directly, before
        /// <see cref="Baselines.ModelA()"/> existed to be tested against it. If
        /// Model A as selected now ever stops being that runtime, this moves.
        /// </summary>
        const string ModelAFingerprintBeforeTheChange = "3e544cc8f2be569d";

        static IReadOnlyList<string> Design => _primary.Morning.Variants.Select(v => v.Id).ToList();

        [OneTimeSetUp]
        public void Load()
        {
            _primary = Baselines.Primary();
            _modelA = Baselines.ModelA(_primary);
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Baseline verification");
            sb.AppendLine();
            sb.AppendLine("Generated by `BaselineTests`. The primary experimental baseline is the shipped data: Model B (`dispositions: respond`) with both S1.6 fixes (`means: end`, and `minute: 0` on the four scripted events of the lived day). Model A is selected by `Baselines.ModelA()`, which restores the three settings the data had before, and nothing else.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "decision-sensitivity");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "baseline.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);

        static IEnumerable<WorldEvent> LivedDayScript(Scenario001Content c)
            => c.Backstory.Events.Where(e => e.Day == c.Morning.Day).Concat(new[] { c.Morning.Opening });

        // ---- 1 ----

        [Test]
        public void B1_TheShippedDataIsModelBWithBothS16Fixes()
        {
            var raw = File.ReadAllText(Path.Combine(TestPaths.Rules, "decisions.json"));
            StringAssert.Contains("\"dispositions\": \"respond\"", raw, "the baseline is named in the data, not left to a code default");
            StringAssert.Contains("\"means\": \"end\"", raw, "the baseline is named in the data, not left to a code default");

            Assert.AreEqual(DispositionMode.Respond, _primary.Rules.Deciding.Dispositions);
            Assert.AreEqual(MeansMode.End, _primary.Rules.Deciding.Means);

            var script = LivedDayScript(_primary).ToList();
            Assert.AreEqual(4, script.Count, "three day-4 events of the backstory and the opening");
            foreach (var e in script) Assert.AreEqual(0, e.Minute, e.Id + " carries the minute it happened");

            var problems = new List<string>();
            problems.AddRange(_primary.Cast.Values.SelectMany(p => ProfileValidator.Validate(p, _primary.Vocabulary)));
            problems.AddRange(ScenarioValidator.Validate(_primary.Backstory, _primary.Vocabulary, _primary.Cast));
            problems.AddRange(RuleSetValidator.Validate(_primary.Rules, _primary.Vocabulary));
            problems.AddRange(DecisionRuleValidator.Validate(_primary.Rules, _primary.Vocabulary));
            problems.AddRange(MorningValidator.Validate(_primary.Morning, _primary.Vocabulary, _primary.Cast));
            Assert.IsEmpty(problems, string.Join("\n", problems));

            var sb = new StringBuilder();
            sb.AppendLine("## 1. What the shipped data now runs");
            sb.AppendLine();
            sb.AppendLine("| Setting | Where | Model A (before) | Primary baseline (now) |");
            sb.AppendLine("|---|---|---|---|");
            sb.AppendLine("| How traits and values enter a want | `decisions.json`, `deciding.dispositions` | `standing` (absent; code default) | **`" + _primary.Rules.Deciding.Dispositions + "`** |");
            sb.AppendLine("| How a walk is credited to a want | `decisions.json`, `deciding.means` | `want` (absent; code default) | **`" + _primary.Rules.Deciding.Means + "`** |");
            sb.AppendLine("| When the lived day's scripted events happened | `backstory.json` p01-p03, `morning.json` opening | no minute (-1) | **" + string.Join(", ", script.Select(e => e.Id + " " + e.Minute)) + "** |");
            sb.AppendLine();
            sb.AppendLine("The shipped content validates with every validator the slice has. The code defaults in `DecisionDynamics` are unchanged (`standing`, `want`), so a rule file that names neither still runs Model A; the shipped one names both.");
            Record("1", sb.ToString());
        }

        // ---- 2 ----

        [Test]
        public void B2_ModelAIsStillThereAndDiffersInExactlyThoseThreeThings()
        {
            // Printed first, and for the raw load too: run on the data as it was
            // committed before the change, the raw load is Model A, and that is
            // where the constant above came from.
            var fingerprint = Fingerprint(_modelA, 3);
            TestContext.WriteLine("fingerprint of Model A as selected: " + fingerprint);
            TestContext.WriteLine("fingerprint of the data as loaded: " + Fingerprint(_primary, 3));

            Assert.AreEqual(DispositionMode.Standing, _modelA.Rules.Deciding.Dispositions);
            Assert.AreEqual(MeansMode.Want, _modelA.Rules.Deciding.Means);
            foreach (var e in LivedDayScript(_modelA)) Assert.AreEqual(-1, e.Minute, e.Id + " is untimed in Model A");

            // Everything else about the two is the same object or the same value.
            var a = _modelA.Rules.Deciding;
            var b = _primary.Rules.Deciding;
            Assert.AreEqual(b.AmbiguityBand, a.AmbiguityBand);
            Assert.AreEqual(b.InterruptIntensity, a.InterruptIntensity);
            Assert.AreEqual(b.VisibleDistress, a.VisibleDistress);
            Assert.AreEqual(b.HungerPerMinute, a.HungerPerMinute);
            Assert.AreEqual(b.PortionRelief, a.PortionRelief);
            Assert.AreEqual(b.LowPortions, a.LowPortions);
            Assert.AreEqual(b.ComfortSettling, a.ComfortSettling);
            Assert.AreEqual(b.UrgencyKnee, a.UrgencyKnee);
            Assert.AreEqual(b.RecallHalfLife, a.RecallHalfLife);
            Assert.AreEqual(b.WatchingGoesStaleAfter, a.WatchingGoesStaleAfter);
            Assert.AreSame(b.ActionMinutes, a.ActionMinutes);
            Assert.AreSame(b.DistressShows, a.DistressShows);
            Assert.AreSame(b.ComfortSettles, a.ComfortSettles);
            Assert.AreSame(_primary.Rules.Motivation, _modelA.Rules.Motivation);
            Assert.AreSame(_primary.Rules.Proposals, _modelA.Rules.Proposals);
            Assert.AreSame(_primary.Rules.Costs, _modelA.Rules.Costs);
            Assert.AreSame(_primary.Rules.Interpretation, _modelA.Rules.Interpretation);
            Assert.AreSame(_primary.Rules.Appraisal, _modelA.Rules.Appraisal);
            Assert.AreSame(_primary.Cast, _modelA.Cast);
            Assert.AreEqual(_primary.Backstory.Events.Count, _modelA.Backstory.Events.Count);
            for (var i = 0; i < _primary.Backstory.Events.Count; i++)
            {
                var p = _primary.Backstory.Events[i];
                var q = _modelA.Backstory.Events[i];
                Assert.AreEqual(p.Id, q.Id);
                if (p.Day != _primary.Morning.Day) Assert.AreSame(p, q, p.Id + " is not on the lived day and is untouched");
            }

            // Model A can be run, and it is its own runtime rather than a label.
            var ranA = Scenario001.Run(_modelA, "daniel_ate_it", 1);
            var ranB = Scenario001.Run(_primary, "daniel_ate_it", 1);
            Assert.Greater(ranA.Result.Actions.Count, 0);
            Assert.Greater(ranB.Result.Actions.Count, 0);
            CollectionAssert.AreNotEqual(
                ranA.Result.Actions.Select(x => x.ToString()).ToArray(),
                ranB.Result.Actions.Select(x => x.ToString()).ToArray());

            // And it is the runtime that shipped before the change, decision for decision.
            Assert.AreEqual(ModelAFingerprintBeforeTheChange, fingerprint,
                "Model A as selected runs every decision of 15 mornings exactly as the data committed before the change did");

            var sb = new StringBuilder();
            sb.AppendLine("## 2. Model A is still there");
            sb.AppendLine();
            sb.AppendLine("`Baselines.ModelA()` differs from the shipped content in the three settings above and nothing else: every other decision number, rule list, profile and event is the same object or the same value. It runs (" + ranA.Result.Actions.Count + " decisions on `daniel_ate_it` seed 1, against " + ranB.Result.Actions.Count + " under the primary baseline, and not the same ones).");
            sb.AppendLine();
            sb.AppendLine("**It is the runtime that shipped before the change, decision for decision.** Every decision of 15 mornings (the five design conditions, seeds 1-3: minute, person, act, room, leading want, urgency, resolution and margin) hashes to `" + fingerprint + "`, the value the same fingerprint took on the data as committed at `dd9065c`, loaded directly. Every test written before the change now selects Model A explicitly (34 fixtures), so every document they generate is expected to regenerate byte-identical.");
            Record("2", sb.ToString());
        }

        /// <summary>A hash of every decision in the design conditions, seeds 1..n.</summary>
        internal static string Fingerprint(Scenario001Content c, int seeds)
        {
            ulong h = 1469598103934665603UL;
            void Mix(string s)
            {
                foreach (var ch in s) { h ^= ch; h *= 1099511628211UL; }
                h ^= '\n'; h *= 1099511628211UL;
            }

            foreach (var v in c.Morning.Variants.Select(x => x.Id))
            for (ulong seed = 1; seed <= (ulong)seeds; seed++)
            {
                var run = Scenario001.Run(c, v, seed);
                foreach (var a in run.Result.Actions)
                    Mix(v + "/" + seed + " " + a + " | " + a.LeadingMotive + " " + a.LeadingUrgency.ToString("R", CultureInfo.InvariantCulture) +
                        " | " + a.Resolution + " " + a.Margin.ToString("R", CultureInfo.InvariantCulture));
            }
            return h.ToString("x16", CultureInfo.InvariantCulture);
        }

        // ---- 3 ----

        [Test]
        public void B3_ModelBRaisesNoWantFromTraitsAndValuesAlone()
        {
            // A bench: each member of the cast, with their own traits and values
            // and nothing else. Nothing has happened to them, they believe
            // nothing, they are not hungry, and they are standing in a kitchen
            // with food in it, alone, and then with somebody.
            var sb = new StringBuilder();
            sb.AppendLine("## 3. No want from traits and values alone");
            sb.AppendLine();
            sb.AppendLine("**On the bench.** Each member of the cast with their own traits and values and nothing else: no memory, no belief, no feeling, not hungry, in a kitchen with food, alone and then with one other person.");
            sb.AppendLine();
            sb.AppendLine("| Person | Model A, alone | Model A, with somebody | Primary, alone | Primary, with somebody |");
            sb.AppendLine("|---|---|---|---|---|");

            var totalA = 0;
            foreach (var who in _primary.Cast.Keys.OrderBy(k => k, StringComparer.Ordinal))
            {
                var p = _primary.Cast[who];
                var bare = new Mind(new Profile(p.Id, p.DisplayName, p.Age, p.FamilyRole,
                    p.Traits, p.Values, p.Perceptiveness, new Dictionary<string, double>(), new List<BeliefSeed>()));
                var other = _primary.Cast.Keys.First(k => k != who);
                var alone = Bench.Standing(who);
                var company = Bench.Standing(who, present: new List<string> { other });

                string Wants(Scenario001Content c, Percept at)
                {
                    var ms = new Motivator(c.Rules).Raise(bare, at, _primary.Morning.Day, new TraceLog(), 0);
                    return ms.Count == 0 ? "nothing" : string.Join(", ", ms.Select(m => m.Key + " " + F(m.Urgency)));
                }

                var inA = new Motivator(_modelA.Rules).Raise(bare, company, _primary.Morning.Day, new TraceLog(), 0);
                totalA += inA.Count;
                Assert.IsEmpty(new Motivator(_primary.Rules).Raise(bare, alone, _primary.Morning.Day, new TraceLog(), 0), who + " alone");
                Assert.IsEmpty(new Motivator(_primary.Rules).Raise(bare, company, _primary.Morning.Day, new TraceLog(), 0), who + " with " + other);

                sb.AppendLine("| " + who + " | " + Wants(_modelA, alone) + " | " + Wants(_modelA, company) + " | " + Wants(_primary, alone) + " | " + Wants(_primary, company) + " |");
            }
            Assert.Greater(totalA, 0, "Model A does raise wants from traits and values alone, which is the difference");

            // In real mornings: every want the primary baseline raises has
            // something other than a trait or a value behind it.
            var wants = 0;
            var onDispositionsAlone = 0;
            var unsupported = 0;
            var unsupportedA = 0;
            var wantsA = 0;
            foreach (var (c, isA) in new[] { (_primary, false), (_modelA, true) })
            foreach (var v in Design)
            {
                var run = Scenario001.Prepare(c, v, 1);
                run.Morning.Decided = m =>
                {
                    foreach (var w in m.Motives)
                    {
                        var behind = w.Terms.Where(t => t.Amount > 0.0).ToList();
                        var onlyDispositions = behind.Count > 0 && behind.All(t => MotivationSources.SourceOf(t) == Source.Disposition);
                        var support = MotivationSources.Of(w).Class;
                        if (isA)
                        {
                            wantsA++;
                            if (support == Support.Unsupported) unsupportedA++;
                        }
                        else
                        {
                            wants++;
                            if (onlyDispositions) onDispositionsAlone++;
                            if (support == Support.Unsupported) unsupported++;
                        }
                    }
                };
                run.Morning.Run(c.Morning.Minutes);
            }
            Assert.AreEqual(0, onDispositionsAlone, "a want on traits and values alone");

            sb.AppendLine();
            sb.AppendLine("**In real mornings** (the five design conditions, seed 1): of " + wants + " wants the primary baseline raised, **" + onDispositionsAlone + "** rest on traits and values alone, and " + unsupported +
                          " (" + (100.0 * unsupported / Math.Max(1, wants)).ToString("0.0", CultureInfo.InvariantCulture) + " %) have nothing that happened behind them (a belief written into the character file, such as Daniel's that he leads, is the rest). Model A on the same mornings: " +
                          unsupportedA + " of " + wantsA + " (" + (100.0 * unsupportedA / Math.Max(1, wantsA)).ToString("0.0", CultureInfo.InvariantCulture) + " %).");
            Record("3", sb.ToString());
        }

        // ---- 4 ----

        [Test, Timeout(1800000)]
        public void B4_TheMeansEndCheckIsActive()
        {
            var walksB = S16.Walks(_primary, Design, 1, 3);
            var walksA = S16.Walks(_modelA, Design, 1, 3);
            var pointlessB = walksB.Count(w => !w.Foreseen.WorthIt);
            var pointlessA = walksA.Count(w => !w.Foreseen.WorthIt);

            // Every walk credited to a want was foreseen worth it first, and the
            // deliberation says so; some walks are refused on the record.
            var credited = 0;
            var creditedAndForeseen = 0;
            var refusals = 0;
            string example = null;
            var run = Scenario001.Prepare(_primary, "daniel_ate_it", 1);
            run.Morning.Decided = m =>
            {
                var r = run.Trace.Get(m.Decision.TraceId);
                r.Data.TryGetValue("foresaw", out var foresaw);
                foreach (var walk in m.Decision.Ranked.Where(o => o.Option.Kind == ActionKind.GoTo && o.Appeal > 0.0))
                {
                    credited++;
                    if (foresaw != null && foresaw.Split(';').Any(s => s.Trim().StartsWith(walk.Option.Key + " for ", StringComparison.Ordinal)
                                                                        && !s.Contains("not worth walking for") && !s.Contains("nothing there serves it")))
                        creditedAndForeseen++;
                }
                if (foresaw != null && foresaw.Contains("not worth walking for"))
                {
                    refusals++;
                    example = example ?? m.CharacterId + " at minute " + m.Minute + ": " + foresaw.Split(';').First(s => s.Contains("not worth walking for")).Trim();
                }
            };
            run.Morning.Run(_primary.Morning.Minutes);
            var runA = Scenario001.Run(_modelA, "daniel_ate_it", 1);
            var foresightInA = runA.Result.Actions.Count(a => runA.Trace.Get(a.DecisionTraceId).Data.ContainsKey("foresaw"));

            Assert.AreEqual(0, pointlessB, "no walk is set out on whose end was foreseeably not worth doing");
            Assert.Greater(pointlessA, 0, "Model A does set out on such walks, which is the difference");
            Assert.Greater(credited, 0);
            Assert.AreEqual(credited, creditedAndForeseen, "every walk credited to a want was foreseen worth doing, on the record");
            Assert.Greater(refusals, 0, "some walk was refused credit because its end was not worth it");
            Assert.AreEqual(0, foresightInA, "Model A weighs no walk by its end");

            var sb = new StringBuilder();
            sb.AppendLine("## 4. The means-end check is active");
            sb.AppendLine();
            sb.AppendLine("Measured with S1.6's foresight instrument (`S16.Walks`), which imagines the destination from what the walker knows and weighs it with the deliberator itself, on the five design conditions, seeds 1-3.");
            sb.AppendLine();
            sb.AppendLine("| | Model A | Primary |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Walks set out on | " + walksA.Count + " | " + walksB.Count + " |");
            sb.AppendLine("| ... whose end was foreseeably not worth doing | " + pointlessA + " | **" + pointlessB + "** |");
            sb.AppendLine("| ... given up on arrival | " + walksA.Count(w => w.Lapsed) + " | " + walksB.Count(w => w.Lapsed) + " |");
            sb.AppendLine("| ... given up with somebody in the room | " + walksA.Count(w => w.Lapsed && w.PresentOnArrival > 0) + " | " + walksB.Count(w => w.Lapsed && w.PresentOnArrival > 0) + " |");
            sb.AppendLine("| Walks credited to a want, and foreseen worth it on the record (daniel_ate_it seed 1) | no foresight recorded (" + foresightInA + " decisions) | " + creditedAndForeseen + " of " + credited + " |");
            sb.AppendLine("| Decisions refusing a walk credit because its end was not worth it (same morning) | - | " + refusals + " |");
            sb.AppendLine();
            if (example != null) sb.AppendLine("A walk refused on the record: `" + example + "`.");
            Record("4", sb.ToString());
        }

        // ---- 5 ----

        [Test]
        public void B5_TheLivedDayIsNotRememberedAsTimeless()
        {
            // Nobody, at the end of any morning, holds a memory of the lived day
            // with no minute on it: S1.6's stale memory cannot come back through
            // the scripted events.
            var untimedB = 0;
            var untimedA = 0;
            foreach (var v in Design)
            {
                var b = Scenario001.Run(_primary, v, 1);
                var a = Scenario001.Run(_modelA, v, 1);
                untimedB += b.Minds.Values.Sum(m => m.Experiences.Count(x => x.Day == _primary.Morning.Day && x.Minute < 0));
                untimedA += a.Minds.Values.Sum(m => m.Experiences.Count(x => x.Day == _primary.Morning.Day && x.Minute < 0));
            }
            Assert.AreEqual(0, untimedB, "a memory of the lived day with no minute");
            Assert.Greater(untimedA, 0, "Model A keeps them untimed, which is the difference");

            // And so a want resting on them fades: Leo's wish to find out, over
            // the morning, first ten minutes against the last ten (S1.6 P3).
            (double first, double last) FindOut(Scenario001Content c)
            {
                double f = 0, l = 0; int nf = 0, nl = 0;
                for (ulong seed = 1; seed <= 10; seed++)
                {
                    var run = Scenario001.Prepare(c, "daniel_ate_it", seed);
                    run.Morning.Decided = m =>
                    {
                        if (m.CharacterId != "leo") return;
                        var u = m.Motives.FirstOrDefault(x => x.Name == "find_out")?.Urgency ?? 0.0;
                        if (m.Minute < 10) { f += u; nf++; }
                        if (m.Minute >= c.Morning.Minutes - 10) { l += u; nl++; }
                    };
                    run.Morning.Run(c.Morning.Minutes);
                }
                return (f / Math.Max(1, nf), l / Math.Max(1, nl));
            }

            var inB = FindOut(_primary);
            var inAWithRespond = FindOut(S15.Mode(_modelA, DispositionMode.Respond));
            Assert.Less(inB.last, 0.5 * inB.first, "Leo's wish to find out fades over the morning");

            var sb = new StringBuilder();
            sb.AppendLine("## 5. The stale memory is not reintroduced");
            sb.AppendLine();
            sb.AppendLine("Memories of the lived day with no minute, held by anybody at the end of the five design mornings (seed 1): Model A **" + untimedA + "**, primary **" + untimedB + "**.");
            sb.AppendLine();
            sb.AppendLine("Leo's wish to find out, mean urgency over his decisions, first ten minutes against the last ten (`daniel_ate_it`, seeds 1-10): primary " + F(inB.first) + " -> " + F(inB.last) +
                          "; the same dispositions with the events untimed (S1.6's B) " + F(inAWithRespond.first) + " -> " + F(inAWithRespond.last) + ". S1.6 reported 0.38 -> 0.09 under M1 on its design seeds.");
            Record("5", sb.ToString());
        }

        // ---- 6 ----

        [Test, Timeout(1800000)]
        public void B6_ThePrimaryBaselineIsS16sBothFixesDecisionForDecision()
        {
            // S1.6 measured its recommendation as a condition built in code from
            // the content (`B timed end`). The shipped data is now that condition.
            // Built from Model A, the way S1.6 built it, it must run every
            // decision of every morning exactly as the shipped data does.
            var s16 = S16.Conditions.Single(x => x.Label == "B timed end").Make(_modelA);
            var mornings = 0;
            var decisions = 0;
            foreach (var v in Design)
            for (ulong seed = 1; seed <= 5; seed++)
            {
                var shipped = Scenario001.Run(_primary, v, seed);
                var built = Scenario001.Run(s16, v, seed);
                string Line(ActionRecord a) => a + " | " + a.LeadingMotive + " " + a.LeadingUrgency.ToString("R", CultureInfo.InvariantCulture) +
                                              " | " + a.Resolution + " " + a.Margin.ToString("R", CultureInfo.InvariantCulture);
                CollectionAssert.AreEqual(
                    built.Result.Actions.Select(Line).ToArray(),
                    shipped.Result.Actions.Select(Line).ToArray(), v + " seed " + seed);
                Assert.AreEqual(built.World.Portions, shipped.World.Portions);
                mornings++;
                decisions += shipped.Result.Actions.Count;
            }

            // Same seed, same morning.
            var again = Scenario001.Run(_primary, "daniel_ate_it", 11);
            var once = Scenario001.Run(_primary, "daniel_ate_it", 11);
            CollectionAssert.AreEqual(once.Result.Actions.Select(x => x.ToString()).ToArray(), again.Result.Actions.Select(x => x.ToString()).ToArray());

            var sb = new StringBuilder();
            sb.AppendLine("## 6. S1.6's behaviour is reproduced exactly");
            sb.AppendLine();
            sb.AppendLine("S1.6 measured its recommendation as a condition built in code, `B timed end` (`S16.Conditions`). Built from Model A the way S1.6 built it, it runs **every decision of " + mornings + " mornings (" + decisions + " decisions) identically** to the shipped data: the same act, minute, room, leading want and urgency, resolution and margin to the last bit, and the same portions left. The same seed gives the same morning. S1.6's own experiment and held-out tests go on building their six conditions from Model A, so their documents and numbers are unchanged.");
            Record("6", sb.ToString());
        }
    }
}
