using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using Candidate = Fallow.Tests.Core.IntentionSelector.Candidate;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// What information must a representation hold to tell "the same reason
    /// written twice" from "two different reasons that depend on the same
    /// fact"?
    ///
    /// Evidence, route and intention are kept apart. A route is one declared
    /// explanation of why some evidence supports an intention; its key is an
    /// experiment-only name for that declared meaning, and nothing else. The
    /// declarations live in `Data/Experiments/causal-routes.json`, committed
    /// with the predictions. Four representations read the same statements:
    /// A (the current anonymous sum, the control), B (evidence identity), C
    /// (reason-signature identity) and D (declared causal routes). D-alt,
    /// D-enablers and G are diagnostics.
    ///
    /// Nothing here is production. Writes
    /// `Docs/experiments/causal-routes/measurements.md`.
    /// </summary>
    public class CausalRouteExperimentTests
    {
        const string FrozenSha = "61e6412e8a7cb77674f0c7685e4cb0e5f7dca5db3ad05f928a63f34dfb099d92";
        const string RoutesSha = "781b776d3a1cbbba78cc215c85af4750261a79f998c317f6a1ee920c4c37828a";
        const double Tie = 1e-9;
        const int MorningSeeds = 10;

        static Scenario001Content _content;
        static IReadOnlyList<Candidate> _frozen;
        static string _frozenPath;
        static string _routesPath;
        static JObject _routesJson;
        static RoomGraph _house;
        static string _kitchen;
        static string _elsewhere;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static readonly string[] Wants =
            { "avoid_exposure", "find_out", "get_food", "guard_supplies", "keep_peace", "look_after", "restore_standing" };
        static readonly string[] Circumstances = { "in company", "alone" };
        static readonly string[] Cast = { "daniel", "elena", "leo", "mara" };
        static readonly string[] HeldOut = { "hollow", "warden", "drifter", "firebrand" };

        static List<string> _sweepTraits;
        static List<double> _levels;
        static List<string> _ring;
        static List<List<BeliefSeed>> _beliefSets;
        static Mind[] _minds;
        static Percept[] _company;
        static Percept[] _alone;

        [OneTimeSetUp]
        public void Load()
        {
            _content = Baselines.Primary();
            _frozenPath = Path.Combine(TestPaths.DataRoot, "Experiments", "intentions.json");
            _routesPath = Path.Combine(TestPaths.DataRoot, "Experiments", "causal-routes.json");
            _frozen = IntentionSelector.Load(_frozenPath);
            _routesJson = JObject.Parse(File.ReadAllText(_routesPath));

            var root = JObject.Parse(File.ReadAllText(Path.Combine(TestPaths.DataRoot, "Experiments", "held-out-people.json")));
            var s = (JObject)root["sweep"];
            _sweepTraits = ((JArray)s["traits"]).Select(x => x.Value<string>()).ToList();
            _levels = ((JArray)s["levels"]).Select(x => x.Value<double>()).ToList();
            _ring = ((JArray)s["value_ring"]).Select(x => x.Value<string>()).ToList();
            _beliefSets = ((JArray)s["belief_sets"]).Select(set => ((JArray)set).Select(b => new BeliefSeed(
                b["predicate"].Value<string>(),
                ((JArray)b["args"]).Select(a => a.Value<string>()).ToList(),
                b["confidence"].Value<double>())).ToList()).ToList();

            var run = Scenario001.Prepare(_content, _content.Morning.Variants[0].Id, 1);
            _house = run.World.House;
            _kitchen = _house.Rooms.First(r => r.HasTag(ActionCatalog.PantryTag)).Id;
            _elsewhere = _house.Rooms.First(r => !r.HasTag(ActionCatalog.PantryTag)).Id;

            var n = (int)Math.Pow(_levels.Count, _sweepTraits.Count);
            _minds = new Mind[n];
            _company = new Percept[n];
            _alone = new Percept[n];
            for (var i = 0; i < n; i++)
            {
                _minds[i] = SweepMind(i);
                _company[i] = At(_minds[i].Id, Others);
                _alone[i] = At(_minds[i].Id, Nobody);
            }
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Causal routes: measurements");
            sb.AppendLine();
            sb.AppendLine("Generated by `CausalRouteExperimentTests` against the frozen candidate rules and the route declarations, both hashed at the start and the end of the run. The predictions, the declarations, the synthetic families and the annotation protocol were committed before this fixture existed. There is no randomness anywhere.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "causal-routes");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "measurements.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string F9(double v) => v.ToString("0.000000000", CultureInfo.InvariantCulture);
        static string Pc(double part, double whole)
            => whole == 0 ? "n/a" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + " %";

        static string Sha(string path)
        {
            using (var sha = SHA256.Create())
                return string.Concat(sha.ComputeHash(File.ReadAllBytes(path)).Select(b => b.ToString("x2")));
        }

        // ============================================================ people and moments

        static Mind Person(string id, IReadOnlyDictionary<string, double> traits,
            IReadOnlyList<string> values, IReadOnlyList<BeliefSeed> beliefs)
        {
            var profile = new Profile(id, id, 30, "sibling", traits, values, 0.5,
                new Dictionary<string, double>(), new List<BeliefSeed>());
            var mind = new Mind(profile);
            foreach (var b in beliefs ?? new List<BeliefSeed>())
                mind.Beliefs.Seed(new BeliefSeed(
                    b.Predicate, b.Args.Select(a => a == "$self" ? id : a).ToList(), b.Confidence));
            return mind;
        }

        static Mind SweepMind(int i)
        {
            var traits = new Dictionary<string, double>(StringComparer.Ordinal);
            var n = i;
            foreach (var name in _sweepTraits)
            {
                traits[name] = _levels[n % _levels.Count];
                n /= _levels.Count;
            }
            var shift = i % _ring.Count;
            var values = _ring.Skip(shift).Concat(_ring.Take(shift)).ToList();
            return Person("p" + i, traits, values, _beliefSets[i % _beliefSets.Count]);
        }

        static Dictionary<string, double> TraitsOf(Mind m)
            => _sweepTraits.ToDictionary(t => t, t => m.Profile.Trait(t), StringComparer.Ordinal);

        static List<BeliefSeed> SeedsOf(Mind m)
            => m.Beliefs.All.Select(b => new BeliefSeed(b.Predicate, b.Args, b.Confidence)).ToList();

        static readonly IReadOnlyList<string> Nobody = new List<string>();
        static readonly IReadOnlyList<string> Others = new List<string> { "a", "b", "c" };

        static Percept At(string who, IReadOnlyList<string> present, double hunger = 0.3, string roomId = null)
        {
            var room = _house.Get(roomId ?? _kitchen);
            var holdsFood = room.HasTag(ActionCatalog.PantryTag);
            return new Percept(who, 10, room, present, _house.Adjacent(room.Id), hunger,
                holdsFood, holdsFood ? (bool?)true : null, false, _house, false, null, null);
        }

        static Motive Want(string key, string target = null)
            => new Motive(key, key == "look_after" ? target ?? "a" : null, 0.6, new List<string>(), new List<ScalerTerm>());

        static int Cells => _minds.Length * Wants.Length * 2;
        static int Cell(int i, int wi, int ci) => (i * Wants.Length + wi) * 2 + ci;
        static int Groups => Wants.Length * 2;
        static Percept Moment(int i, int ci) => ci == 0 ? _company[i] : _alone[i];
        static string GroupName(int g) => "`" + Wants[g / 2] + "` " + Circumstances[g % 2];

        // ============================================================ declared rules

        /// <summary>
        /// A rule with every statement's declared route and role. Statement 0 is
        /// the base; statement k is scaler k - 1. The route of a statement is
        /// what it is declared to be a reason for; the rule is only a container.
        /// </summary>
        sealed class RouteRule
        {
            public Candidate C;
            public string[] Routes;
            public string[] Roles;
        }

        /// <summary>A rule set with its declarations: the rules, the alternative groups, and a renaming to undo when comparing.</summary>
        sealed class Declared
        {
            public List<RouteRule> Rules = new List<RouteRule>();
            public List<List<string>> Alternatives = new List<List<string>>();
            public Dictionary<string, string> Rename = new Dictionary<string, string>(StringComparer.Ordinal);

            public Declared With(IEnumerable<RouteRule> rules)
                => new Declared { Rules = rules.ToList(), Alternatives = Alternatives, Rename = Rename };
        }

        static string EvidenceKey(Scaler s)
        {
            switch (s.Kind)
            {
                case ScalerKind.Trait: return "trait:" + s.Name;
                case ScalerKind.Value: return "value:" + s.Name;
                case ScalerKind.Belief: return "belief:" + s.Predicate + "(" + string.Join(",", s.Args ?? new List<string>()) + ")";
                case ScalerKind.Emotion: return "emotion:" + s.Name + "@" + (s.Target ?? "situation");
                case ScalerKind.Constant: return CircumstancePrefix + (s.Name ?? "any");
                default: return s.Kind + ":" + (s.Name ?? s.Predicate ?? s.Entry ?? "");
            }
        }

        static string GateKey(SituationCondition w)
        {
            var parts = new List<string>();
            if (w.Alone.HasValue) parts.Add(w.Alone.Value ? "alone" : "not alone");
            if (w.OthersPresentMin.HasValue) parts.Add("others>=" + w.OthersPresentMin.Value);
            if (w.InOwnRoom.HasValue) parts.Add(w.InOwnRoom.Value ? "own room" : "not own room");
            if (w.InSomebodyElsesRoom.HasValue) parts.Add(w.InSomebodyElsesRoom.Value ? "somebody else's room" : "not somebody else's room");
            if (w.RoomHoldsFood.HasValue) parts.Add(w.RoomHoldsFood.Value ? "food here" : "no food here");
            if (w.SearchedThisRoomMyself.HasValue) parts.Add(w.SearchedThisRoomMyself.Value ? "searched here" : "not searched here");
            return parts.Count == 0 ? "any" : string.Join(",", parts);
        }

        const string CircumstancePrefix = "circumstance:";

        static RouteRule Uniform(Candidate c, string route, IDictionary<string, string> roles = null)
            => new RouteRule
            {
                C = c,
                Routes = Enumerable.Repeat(route, c.ScaledBy.Count + 1).ToArray(),
                Roles = new[] { (string)null }.Concat(c.ScaledBy.Select(s => roles != null && roles.TryGetValue(EvidenceKey(s), out var r) ? r : null)).ToArray()
            };

        static Declared _frozenDeclared;
        static Dictionary<string, string> _frozenRouteOf;
        static Dictionary<string, string> _frozenMeans;

        static Declared FrozenDeclared()
        {
            if (_frozenDeclared != null) return _frozenDeclared;
            _frozenRouteOf = new Dictionary<string, string>(StringComparer.Ordinal);
            _frozenMeans = new Dictionary<string, string>(StringComparer.Ordinal);
            var roles = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal);
            foreach (var r in (JArray)_routesJson["frozen"]["routes"])
            {
                var id = r["rule"].Value<string>();
                _frozenRouteOf[id] = r["route"].Value<string>();
                _frozenMeans[r["route"].Value<string>()] = r["means"].Value<string>();
                roles[id] = (r["roles"] as JObject)?.Properties().ToDictionary(p => p.Name, p => p.Value.Value<string>(), StringComparer.Ordinal)
                            ?? new Dictionary<string, string>();
            }
            _frozenDeclared = new Declared { Rules = _frozen.Select(c => Uniform(c, _frozenRouteOf[c.Id], roles[c.Id])).ToList() };
            return _frozenDeclared;
        }

        static Declared FrozenWhatIf()
        {
            var d = FrozenDeclared();
            return new Declared
            {
                Rules = d.Rules,
                Alternatives = ((JArray)_routesJson["frozen"]["what_if_alternatives"]).Select(g => ((JArray)g).Select(x => x.Value<string>()).ToList()).ToList()
            };
        }

        static Candidate ParseRule(JToken c, IReadOnlyList<string> motives)
            => new Candidate
            {
                Id = c["id"].Value<string>(),
                Motives = motives.ToList(),
                Intent = c["intent"].Value<string>(),
                When = new SituationCondition(),
                Base = c["base"]?.Value<double>() ?? 0.0,
                ScaledBy = ((JArray)c["scaled_by"]).Select(s => new Scaler
                {
                    Kind = s["kind"]?.Value<string>(),
                    Name = s["name"]?.Value<string>(),
                    Predicate = s["predicate"]?.Value<string>(),
                    Args = (s["args"] as JArray ?? new JArray()).Select(a => a.Value<string>()).ToList(),
                    Target = s["target"]?.Value<string>(),
                    Factor = s["factor"]?.Value<double>() ?? 0.0
                }).ToList()
            };

        static Dictionary<string, Declared> _variants;
        static string _synthWant;

        static Dictionary<string, Declared> Variants()
        {
            if (_variants != null) return _variants;
            var syn = (JObject)_routesJson["synthetic"];
            _synthWant = syn["want"].Value<string>();
            var fd = FrozenDeclared();
            var rivals = ((JArray)syn["rivals"]).Select(x => x.Value<string>()).Select(id => fd.Rules.First(r => r.C.Id == id)).ToList();
            var relations = syn["variant_relations"] as JObject ?? new JObject();
            var renamings = syn["renamings"] as JObject ?? new JObject();
            _variants = new Dictionary<string, Declared>(StringComparer.Ordinal);
            foreach (var v in ((JObject)syn["variants"]).Properties())
            {
                var d = new Declared();
                foreach (var c in (JArray)v.Value)
                    d.Rules.Add(Uniform(ParseRule(c, new[] { _synthWant }), c["route"].Value<string>()));
                d.Rules.AddRange(rivals);
                if (relations[v.Name] is JArray rel)
                    foreach (var g in rel.Where(x => x["type"].Value<string>() == "alternative"))
                        d.Alternatives.Add(((JArray)g["routes"]).Select(x => x.Value<string>()).ToList());
                if (renamings[v.Name] is JObject map)
                    foreach (var p in map.Properties()) d.Rename[p.Name] = p.Value.Value<string>();
                _variants[v.Name] = d;
            }
            return _variants;
        }

        // ============================================================ stages 1 to 3

        sealed class Statement
        {
            public string Key;
            public double Coef;
            public double Amount;
            public bool IsBase;
            public string Route;
            public string Role;
            public string RuleId;
        }

        sealed class RuleEval
        {
            public RouteRule R;
            public double Weight;
            public string Gate;
            public string Signature;
            public List<Statement> Statements;
        }

        sealed class Staged
        {
            public readonly List<string> Available = new List<string>();
            public readonly List<string> Compatible = new List<string>();
            public readonly List<RuleEval> Rules = new List<RuleEval>();
        }

        /// <summary>
        /// Stages 1 to 3, in the selector's own order and arithmetic. A constant
        /// scaler named for a gate is a base carried inside a merged rule, and is
        /// read as that base.
        /// </summary>
        static Staged Stage(Declared d, Mind mind, Percept p, string want, string target = null)
        {
            var s = new Staged();
            var motive = Want(want, target);
            var ctx = new DecisionContext(p, mind.Id, motive.TargetId, _content.Morning.Day, _content.Rules.Deciding.RecallHalfLife);
            foreach (var rr in d.Rules)
            {
                var c = rr.C;
                if (!c.Motives.Contains(want, StringComparer.Ordinal)) continue;
                if (!s.Available.Contains(c.Intent)) s.Available.Add(c.Intent);
                if (!c.When.Matches(p)) continue;
                if (!s.Compatible.Contains(c.Intent)) s.Compatible.Add(c.Intent);
                var terms = ScalerEval.Evaluate(c.ScaledBy, mind, ctx);
                if (terms.Count != c.ScaledBy.Count) throw new InvalidOperationException(c.Id + ": a scaler was not evaluated");
                var gate = GateKey(c.When);
                var statements = new List<Statement>();
                if (c.Base != 0.0)
                    statements.Add(new Statement { Key = CircumstancePrefix + gate, Coef = c.Base, Amount = c.Base, IsBase = true, Route = rr.Routes[0], RuleId = c.Id });
                for (var k = 0; k < terms.Count; k++)
                {
                    var sc = c.ScaledBy[k];
                    var isBase = sc.Kind == ScalerKind.Constant;
                    statements.Add(new Statement
                    {
                        Key = EvidenceKey(sc), Coef = sc.Factor, Amount = terms[k].Amount, IsBase = isBase,
                        Route = rr.Routes[k + 1], Role = rr.Roles[k + 1], RuleId = c.Id
                    });
                }
                s.Rules.Add(new RuleEval
                {
                    R = rr,
                    Weight = c.Base + terms.Sum(t => t.Amount),
                    Gate = gate,
                    Signature = c.Intent + "|" + gate + "|" + string.Join(",", statements.Where(x => !x.IsBase).Select(x => x.Key).Distinct().OrderBy(x => x, StringComparer.Ordinal)),
                    Statements = statements
                });
            }
            return s;
        }

        static IntentionSelector.Formed Form(IReadOnlyList<Candidate> rules, Mind mind, Percept p, string want)
            => IntentionSelector.Form(rules, mind, p, Want(want), _content.Morning.Day, _content.Rules.Deciding.RecallHalfLife);

        // ============================================================ the representations

        enum Rep { A, B, C, D, DAlt, DEnablers, G }

        static readonly Rep[] Battery = { Rep.A, Rep.B, Rep.C, Rep.D };

        static string Name(Rep r)
        {
            switch (r)
            {
                case Rep.DAlt: return "D-alt";
                case Rep.DEnablers: return "D-enablers";
                default: return r.ToString();
            }
        }

        sealed class Scored
        {
            public readonly List<string> Candidates = new List<string>();
            public readonly Dictionary<string, double> Score = new Dictionary<string, double>(StringComparer.Ordinal);
            public readonly Dictionary<string, string> Trace = new Dictionary<string, string>(StringComparer.Ordinal);
            public readonly Dictionary<string, Dictionary<string, double>> RouteTotals = new Dictionary<string, Dictionary<string, double>>(StringComparer.Ordinal);
            public readonly Dictionary<string, Dictionary<string, double>> Counted = new Dictionary<string, Dictionary<string, double>>(StringComparer.Ordinal);
            public int Restated;
            public int Conflicts;
            public int Suspicious;
            public int RoleMismatch;
            public int InactiveRoutes;
            public int ProvenanceGaps;
        }

        static bool Same(double a, double b) => Math.Abs(a - b) < 1e-12;

        static Statement Strongest(IEnumerable<Statement> xs)
            => xs.OrderByDescending(x => Math.Abs(x.Coef)).ThenByDescending(x => x.Coef).First();

        static void Count(Scored sc, string intent, string key, double amount)
        {
            if (!sc.Counted.TryGetValue(intent, out var m)) sc.Counted[intent] = m = new Dictionary<string, double>(StringComparer.Ordinal);
            m.TryGetValue(key, out var v);
            m[key] = v + amount;
        }

        static string Content(IEnumerable<Statement> xs)
            => string.Join(";", xs.OrderBy(x => x.Key, StringComparer.Ordinal).Select(x => x.Key + ":" + x.Coef.ToString("R", CultureInfo.InvariantCulture)));

        static Scored Score(Rep rep, Staged s, Declared d)
        {
            var sc = new Scored();
            string Canon(string route) => route != null && d.Rename.TryGetValue(route, out var r) ? r : route;
            switch (rep)
            {
                case Rep.A:
                {
                    var parts = new Dictionary<string, List<string>>(StringComparer.Ordinal);
                    foreach (var r in s.Rules)
                    {
                        if (r.Weight <= 0.0) continue;
                        var i = r.R.C.Intent;
                        if (!sc.Score.ContainsKey(i)) { sc.Score[i] = 0.0; sc.Candidates.Add(i); parts[i] = new List<string>(); }
                        sc.Score[i] += r.Weight;
                        parts[i].Add(r.Gate + "{" + Content(r.Statements) + "}=" + F9(r.Weight));
                        foreach (var st in r.Statements) Count(sc, i, st.Key, st.Amount);
                    }
                    foreach (var kv in parts) sc.Trace[kv.Key] = string.Join(" + ", kv.Value.OrderBy(x => x, StringComparer.Ordinal));
                    break;
                }

                case Rep.B:
                case Rep.G:
                {
                    var stated = s.Compatible.ToDictionary(i => i, i => new Dictionary<string, List<Statement>>(StringComparer.Ordinal), StringComparer.Ordinal);
                    foreach (var r in s.Rules)
                    foreach (var st in r.Statements)
                    {
                        var byKey = stated[r.R.C.Intent];
                        if (!byKey.TryGetValue(st.Key, out var list)) { byKey[st.Key] = new List<Statement> { st }; continue; }
                        if (list.Any(x => Same(x.Coef, st.Coef))) { sc.Restated++; continue; }
                        sc.Conflicts++;
                        list.Add(st);
                    }
                    var kept = stated.ToDictionary(kv => kv.Key, kv => kv.Value.ToDictionary(x => x.Key, x => Strongest(x.Value), StringComparer.Ordinal), StringComparer.Ordinal);
                    if (rep == Rep.G)
                    {
                        // The negative control: each fact is given to one intention only,
                        // the one that states it most strongly.
                        var keys = kept.Values.SelectMany(m => m.Keys).Where(k => !k.StartsWith(CircumstancePrefix, StringComparison.Ordinal)).Distinct().ToList();
                        foreach (var key in keys)
                        {
                            var holders = kept.Where(kv => kv.Value.ContainsKey(key)).ToList();
                            if (holders.Count < 2) continue;
                            var owner = holders.OrderByDescending(h => Math.Abs(h.Value[key].Coef)).ThenBy(h => h.Key, StringComparer.Ordinal).First().Key;
                            foreach (var h in holders.Where(h => h.Key != owner)) h.Value.Remove(key);
                        }
                    }
                    foreach (var i in s.Compatible)
                    {
                        sc.Candidates.Add(i);
                        var total = 0.0;
                        foreach (var kv in kept[i].OrderBy(x => x.Key, StringComparer.Ordinal)) { total += kv.Value.Amount; Count(sc, i, kv.Key, kv.Value.Amount); }
                        sc.Score[i] = total;
                        sc.Trace[i] = string.Join(";", kept[i].OrderBy(x => x.Key, StringComparer.Ordinal).Select(x => x.Key + "=" + F9(x.Value.Amount)));
                    }
                    break;
                }

                case Rep.C:
                {
                    var reasons = s.Compatible.ToDictionary(i => i, i => new Dictionary<string, List<RuleEval>>(StringComparer.Ordinal), StringComparer.Ordinal);
                    foreach (var r in s.Rules)
                    {
                        var bySig = reasons[r.R.C.Intent];
                        if (!bySig.TryGetValue(r.Signature, out var list)) bySig[r.Signature] = list = new List<RuleEval>();
                        list.Add(r);
                    }
                    foreach (var i in s.Compatible)
                    {
                        sc.Candidates.Add(i);
                        var total = 0.0;
                        var parts = new List<string>();
                        foreach (var kv in reasons[i].OrderBy(x => x.Key, StringComparer.Ordinal))
                        {
                            var vectors = kv.Value.Select(Vector).ToList();
                            var chosen = vectors[0];
                            if (vectors.Count > 1)
                            {
                                var canon = vectors.Select(v => string.Join(";", v.OrderBy(x => x.Key, StringComparer.Ordinal).Select(x => x.Key + "=" + x.Value.Item1.ToString("R", CultureInfo.InvariantCulture)))).ToList();
                                if (canon.All(x => x == canon[0])) sc.Restated += vectors.Count - 1;
                                else sc.Conflicts += vectors.Count - 1;
                                chosen = new Dictionary<string, Tuple<double, double>>(StringComparer.Ordinal);
                                foreach (var key in vectors.SelectMany(v => v.Keys).Distinct())
                                    chosen[key] = vectors.Where(v => v.ContainsKey(key)).Select(v => v[key]).OrderByDescending(t => Math.Abs(t.Item1)).ThenByDescending(t => t.Item1).First();
                            }
                            var reasonTotal = 0.0;
                            foreach (var st in chosen.OrderBy(x => x.Key, StringComparer.Ordinal)) { reasonTotal += st.Value.Item2; Count(sc, i, st.Key, st.Value.Item2); }
                            total += reasonTotal;
                            parts.Add(kv.Key + "=" + F9(reasonTotal));
                        }
                        sc.Score[i] = total;
                        sc.Trace[i] = string.Join(" + ", parts);
                    }
                    break;
                }

                default:
                {
                    // D: per intention, per declared route, per piece of evidence. The same
                    // statement again within a route counts once; a different strength for
                    // the same fact within a route is a conflict, flagged. Different routes
                    // keep their own statements. Routes combine by their declared relation.
                    var stated = s.Compatible.ToDictionary(i => i, i => new Dictionary<string, Dictionary<string, List<Statement>>>(StringComparer.Ordinal), StringComparer.Ordinal);
                    foreach (var r in s.Rules)
                    foreach (var st in r.Statements)
                    {
                        if (st.RuleId == null || st.Route == null) sc.ProvenanceGaps++;
                        if ((st.Role == "driver" && st.Coef < 0.0) || (st.Role == "inhibitor" && st.Coef > 0.0)) sc.RoleMismatch++;
                        var byRoute = stated[r.R.C.Intent];
                        if (!byRoute.TryGetValue(st.Route, out var byKey)) byRoute[st.Route] = byKey = new Dictionary<string, List<Statement>>(StringComparer.Ordinal);
                        if (!byKey.TryGetValue(st.Key, out var list)) { byKey[st.Key] = new List<Statement> { st }; continue; }
                        if (list.Any(x => Same(x.Coef, st.Coef))) { sc.Restated++; continue; }
                        sc.Conflicts++;
                        list.Add(st);
                    }
                    foreach (var i in s.Compatible)
                    {
                        sc.Candidates.Add(i);
                        var totals = new Dictionary<string, double>(StringComparer.Ordinal);
                        var contents = new Dictionary<string, string>(StringComparer.Ordinal);
                        var parts = new List<string>();
                        foreach (var route in stated[i].OrderBy(x => x.Key, StringComparer.Ordinal))
                        {
                            var kept = route.Value.ToDictionary(x => x.Key, x => Strongest(x.Value), StringComparer.Ordinal);
                            var inactive = rep == Rep.DEnablers && kept.Values.Any(x => x.Role == "enabler" && x.Amount == 0.0);
                            if (inactive) sc.InactiveRoutes++;
                            var total = 0.0;
                            foreach (var kv in kept.OrderBy(x => x.Key, StringComparer.Ordinal))
                            {
                                var amount = inactive ? 0.0 : kv.Value.Amount;
                                total += amount;
                                Count(sc, i, kv.Key, amount);
                            }
                            totals[route.Key] = total;
                            contents[route.Key] = Content(kept.Values);
                            parts.Add(Canon(route.Key) + "{" + string.Join(";", kept.OrderBy(x => x.Key, StringComparer.Ordinal)
                                .Select(x => x.Key + "=" + F9(inactive ? 0.0 : x.Value.Amount))) + "}");
                        }
                        // Two different routes for one intention that state exactly the same
                        // evidence at exactly the same strengths: not merged, flagged.
                        var routeList = contents.Keys.ToList();
                        for (var a = 0; a < routeList.Count; a++)
                            for (var b = a + 1; b < routeList.Count; b++)
                                if (contents[routeList[a]] == contents[routeList[b]]) sc.Suspicious++;
                        var alternatives = rep == Rep.DAlt || d.Alternatives.Count > 0 ? d.Alternatives : new List<List<string>>();
                        var inGroup = new HashSet<string>(alternatives.SelectMany(g => g), StringComparer.Ordinal);
                        var score = 0.0;
                        foreach (var kv in totals.OrderBy(x => x.Key, StringComparer.Ordinal))
                            if (!inGroup.Contains(kv.Key)) score += kv.Value;
                        foreach (var g in alternatives)
                        {
                            var present = g.Where(totals.ContainsKey).ToList();
                            if (present.Count > 0) score += present.Max(r => totals[r]);
                        }
                        sc.Score[i] = score;
                        sc.RouteTotals[i] = totals.ToDictionary(kv => Canon(kv.Key), kv => kv.Value, StringComparer.Ordinal);
                        sc.Trace[i] = string.Join(" + ", parts.OrderBy(x => x, StringComparer.Ordinal));
                    }
                    break;
                }
            }
            return sc;
        }

        static Dictionary<string, Tuple<double, double>> Vector(RuleEval r)
        {
            var v = new Dictionary<string, Tuple<double, double>>(StringComparer.Ordinal);
            foreach (var st in r.Statements)
                v[st.Key] = v.TryGetValue(st.Key, out var t) ? Tuple.Create(t.Item1 + st.Coef, t.Item2 + st.Amount) : Tuple.Create(st.Coef, st.Amount);
            return v;
        }

        sealed class Outcome
        {
            public string Token;
            public string Winner;
            public bool Tie;
            public string Second;
            public double TopScore;
            public double SecondScore;
            public int Candidates;
            public Scored Scored;
            public string Trace;

            public int Recognised => Scored.Restated + Scored.Conflicts;
            public double Margin => Second == null ? double.PositiveInfinity : TopScore - SecondScore;
            public double Support(string intent) => Scored.Score.TryGetValue(intent, out var v) ? v : double.NaN;
        }

        static bool Beats(double s1, string n1, double s2, string n2)
            => s1 > s2 || (s1 == s2 && string.CompareOrdinal(n1, n2) < 0);

        static Outcome Decide(Rep rep, Staged s, Declared d, Func<string, string> unrename = null)
        {
            var sc = Score(rep, s, d);
            string N(string x) => unrename == null ? x : unrename(x);
            var o = new Outcome
            {
                Candidates = sc.Candidates.Count, Scored = sc,
                Trace = string.Join(" | ", sc.Trace.OrderBy(kv => N(kv.Key), StringComparer.Ordinal).Select(kv => N(kv.Key) + ": " + kv.Value))
            };
            if (sc.Candidates.Count == 0) { o.Token = "none"; return o; }
            if (rep == Rep.A)
            {
                string best = null, second = null;
                double b = 0, sd = 0;
                foreach (var i in sc.Candidates)
                {
                    var v = sc.Score[i];
                    if (best == null || Beats(v, i, b, best)) { second = best; sd = b; best = i; b = v; }
                    else if (second == null || Beats(v, i, sd, second)) { second = i; sd = v; }
                }
                o.Winner = N(best);
                o.Token = o.Winner;
                o.TopScore = b;
                o.Second = second == null ? null : N(second);
                o.SecondScore = sd;
                return o;
            }
            var top = sc.Candidates.Max(i => sc.Score[i]);
            var tied = sc.Candidates.Where(i => sc.Score[i] >= top - Tie).Select(N).OrderBy(x => x, StringComparer.Ordinal).ToList();
            var rest = sc.Candidates.Where(i => sc.Score[i] < top - Tie).OrderByDescending(i => sc.Score[i]).ThenBy(N, StringComparer.Ordinal).ToList();
            o.TopScore = top;
            if (tied.Count > 1)
            {
                o.Tie = true;
                o.Token = "tie(" + string.Join("=", tied) + ")";
                o.Second = tied[1];
                o.SecondScore = top;
            }
            else
            {
                o.Winner = tied[0];
                o.Token = o.Winner;
                if (rest.Count > 0) { o.Second = N(rest[0]); o.SecondScore = sc.Score[rest[0]]; }
            }
            return o;
        }

        static Outcome[] DecideAll(Staged s, Declared d, IReadOnlyList<Rep> reps, Func<string, string> unrename = null)
            => reps.Select(r => Decide(r, s, d, unrename)).ToArray();

        /// <summary>D's why at the level of routes: the winner's routes, strongest first.</summary>
        static string LeadRoute(Outcome o)
            => o.Winner == null || !o.Scored.RouteTotals.TryGetValue(o.Winner, out var t) || t.Count == 0
                ? "none" : t.OrderByDescending(kv => kv.Value).ThenBy(kv => kv.Key, StringComparer.Ordinal).First().Key;

        static bool SameSupport(Outcome x, Outcome y)
        {
            Dictionary<string, double> Of(Outcome o) =>
                o.Winner != null && o.Scored.Counted.TryGetValue(o.Winner, out var m)
                    ? m.Where(kv => !kv.Key.StartsWith(CircumstancePrefix, StringComparison.Ordinal)).ToDictionary(kv => kv.Key, kv => kv.Value)
                    : new Dictionary<string, double>();
            var a = Of(x);
            var b = Of(y);
            return a.Keys.Union(b.Keys).All(k => Math.Abs((a.TryGetValue(k, out var u) ? u : 0.0) - (b.TryGetValue(k, out var v) ? v : 0.0)) <= 1e-9);
        }

        // ============================================================ rewriting declared rules, in memory

        static Scaler Copy(Scaler s, double scale)
            => new Scaler
            {
                Kind = s.Kind, Name = s.Name, Predicate = s.Predicate, Args = s.Args, Entry = s.Entry,
                About = s.About, Topic = s.Topic, By = s.By, Until = s.Until, Target = s.Target,
                Factor = s.Factor * scale
            };

        static Candidate Make(Candidate c, string id, string intent = null, IReadOnlyList<string> motives = null,
            SituationCondition when = null, double? baseWeight = null, IReadOnlyList<Scaler> scalers = null)
            => new Candidate
            {
                Id = id, Note = c.Note,
                Motives = (motives ?? c.Motives).ToList(),
                Intent = intent ?? c.Intent,
                When = when ?? c.When,
                Base = baseWeight ?? c.Base,
                ScaledBy = (scalers ?? c.ScaledBy).Select(s => Copy(s, 1.0)).ToList()
            };

        static RouteRule Like(RouteRule r, Candidate c, IEnumerable<int> scalerIndices = null, string route = null)
        {
            var idx = (scalerIndices ?? Enumerable.Range(0, r.C.ScaledBy.Count)).ToList();
            return new RouteRule
            {
                C = c,
                Routes = new[] { route ?? r.Routes[0] }.Concat(idx.Select(k => route ?? r.Routes[k + 1])).ToArray(),
                Roles = new[] { (string)null }.Concat(idx.Select(k => r.Roles[k + 1])).ToArray()
            };
        }

        static Declared Plus(Declared d, params RouteRule[] extra) => d.With(d.Rules.Concat(extra));
        static Declared Without(Declared d, RouteRule r, params RouteRule[] extra) => d.With(d.Rules.Where(x => !ReferenceEquals(x, r)).Concat(extra));

        static RouteRule Scaled(RouteRule r, string id, double scale) => Like(r, r.C.CloneAs(id, scale));

        sealed class PerRule
        {
            public string Key;
            public string Label;
            public Func<Declared, RouteRule, Declared> Build;
        }

        static readonly PerRule[] PerRuleTests =
        {
            new PerRule { Key = "R4a", Label = "an exact copy, in the same route", Build = (d, r) => Plus(d, Scaled(r, r.C.Id + "_again", 1.0)) },
            new PerRule { Key = "R4b", Label = "a reworded copy (terms reversed, new id), in the same route",
                Build = (d, r) => Plus(d, Like(r, Make(r.C, r.C.Id + "_restated", scalers: r.C.ScaledBy.Reverse().ToList()), Enumerable.Range(0, r.C.ScaledBy.Count).Reverse())) },
            new PerRule { Key = "R4c", Label = "a 0.99 copy, in the same route", Build = (d, r) => Plus(d, Scaled(r, r.C.Id + "_nearly", 0.99)) },
            new PerRule { Key = "R4d", Label = "a partial copy (last term dropped), in the same route",
                Build = (d, r) => Plus(d, Like(r, Make(r.C, r.C.Id + "_partly", scalers: r.C.ScaledBy.Take(r.C.ScaledBy.Count - 1).ToList()), Enumerable.Range(0, r.C.ScaledBy.Count - 1))) },
            new PerRule { Key = "R4new", Label = "an exact copy **declared as a new route**",
                Build = (d, r) => Plus(d, Like(r, r.C.CloneAs(r.C.Id + "_again"), null, r.Routes[0] + "#copy")) },
            new PerRule { Key = "R5a", Label = "W -> W/2 + W/2, in the same route",
                Build = (d, r) => Without(d, r, Scaled(r, r.C.Id + "_a", 0.5), Scaled(r, r.C.Id + "_b", 0.5)) },
            new PerRule { Key = "R6", Label = "W -> 2W", Build = (d, r) => Without(d, r, Scaled(r, r.C.Id + "_double", 2.0)) },
            new PerRule { Key = "R7", Label = "base and positive factors x 2",
                Build = (d, r) => Without(d, r, Like(r, Make(r.C, r.C.Id + "_stronger", baseWeight: r.C.Base * 2.0,
                    scalers: r.C.ScaledBy.Select(s => Copy(s, s.Factor > 0.0 ? 2.0 : 1.0)).ToList()))) },
            new PerRule { Key = "R9a", Label = "split by term, every piece in the rule's route",
                Build = (d, r) => Without(d, r, new[] { Like(r, Make(r.C, r.C.Id + "_base", scalers: new List<Scaler>()), new int[0]) }
                    .Concat(Enumerable.Range(0, r.C.ScaledBy.Count).Select(k => Like(r, Make(r.C, r.C.Id + "_term" + k, baseWeight: 0.0, scalers: new[] { r.C.ScaledBy[k] }), new[] { k })))
                    .ToArray()) },
        };

        static int PerRuleIndex(string key) => Array.FindIndex(PerRuleTests, t => t.Key == key);

        static readonly string[] Intentions =
            { "assert_authority", "prevent_argument", "protect", "share_information", "take_responsibility", "took_what_was_not_mine" };

        static string RenameIntent(string intent) => (char)('a' + Intentions.Length - 1 - Array.IndexOf(Intentions, intent)) + "_" + intent;
        static string UnrenameIntent(string renamed) => renamed.Substring(2);

        static bool CompatibleIn(Candidate r, int wi, int ci)
            => r.Motives.Contains(Wants[wi], StringComparer.Ordinal) && r.When.Matches(Moment(0, ci));

        /// <summary>
        /// One rule per (want, intention, circumstance), holding every statement
        /// its co-compatible rules made, each still in its own route. A base goes
        /// in as a constant scaler named for its gate, so that it keeps its route.
        /// </summary>
        static Declared Merged(Declared d)
        {
            var list = new List<RouteRule>();
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var gate = ci == 0 ? new SituationCondition { OthersPresentMin = 1 } : new SituationCondition { Alone = true };
                var compatible = d.Rules.Where(r => CompatibleIn(r.C, wi, ci)).ToList();
                foreach (var intent in compatible.Select(r => r.C.Intent).Distinct().ToList())
                {
                    var parts = compatible.Where(r => r.C.Intent == intent).ToList();
                    var scalers = new List<Scaler>();
                    var routes = new List<string> { parts[0].Routes[0] };
                    var roles = new List<string> { null };
                    foreach (var p in parts)
                    {
                        if (p.C.Base != 0.0)
                        {
                            scalers.Add(new Scaler { Kind = ScalerKind.Constant, Name = GateKey(p.C.When), Factor = p.C.Base });
                            routes.Add(p.Routes[0]);
                            roles.Add(null);
                        }
                        for (var k = 0; k < p.C.ScaledBy.Count; k++)
                        {
                            scalers.Add(p.C.ScaledBy[k]);
                            routes.Add(p.Routes[k + 1]);
                            roles.Add(p.Roles[k + 1]);
                        }
                    }
                    list.Add(new RouteRule
                    {
                        C = Make(parts[0].C, Wants[wi] + "_" + ci + "_" + intent, motives: new[] { Wants[wi] }, when: gate, baseWeight: 0.0, scalers: scalers),
                        Routes = routes.ToArray(),
                        Roles = roles.ToArray()
                    });
                }
            }
            return d.With(list);
        }

        sealed class Whole
        {
            public string Key;
            public string Label;
            public Func<Declared, Declared> Build;
            public Func<string, string> Unrename;
        }

        static readonly Whole[] WholeTests =
        {
            new Whole { Key = "R1", Label = "reverse the rule order", Build = d => d.With(Enumerable.Reverse(d.Rules)) },
            new Whole { Key = "R2", Label = "give every rule a new id", Build = d => d.With(d.Rules.Select((r, k) => Like(r, r.C.CloneAs("rule_" + k)))) },
            new Whole { Key = "R3", Label = "rename the intentions", Build = d => d.With(d.Rules.Select(r => Like(r, Make(r.C, r.C.Id, intent: RenameIntent(r.C.Intent))))), Unrename = UnrenameIntent },
            new Whole { Key = "R9b", Label = "merge co-compatible rules, every statement in its own route", Build = Merged },
            new Whole { Key = "R11", Label = "rename every route key", Build = d =>
                {
                    var keys = d.Rules.SelectMany(r => r.Routes).Distinct().OrderBy(x => x, StringComparer.Ordinal).ToList();
                    var map = keys.Select((x, k) => new { x, k }).ToDictionary(v => v.x, v => "r" + (keys.Count - v.k).ToString("00"), StringComparer.Ordinal);
                    var renamed = d.With(d.Rules.Select(r => new RouteRule { C = r.C, Routes = r.Routes.Select(x => map[x]).ToArray(), Roles = r.Roles }));
                    renamed.Rename = map.ToDictionary(kv => kv.Value, kv => kv.Key, StringComparer.Ordinal);
                    return renamed;
                } },
        };

        // ============================================================ the frozen baseline

        static Staged[] _staged;
        static Outcome[][] _base;       // [cell][battery]
        static int _formMismatch;
        static int _formWeightMismatch;

        static void EnsureBaseline()
        {
            if (_base != null) return;
            var d = FrozenDeclared();
            _staged = new Staged[Cells];
            _base = new Outcome[Cells][];
            for (var i = 0; i < _minds.Length; i++)
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var cell = Cell(i, wi, ci);
                _staged[cell] = Stage(d, _minds[i], Moment(i, ci), Wants[wi]);
                _base[cell] = DecideAll(_staged[cell], d, Battery);
                var f = Form(_frozen, _minds[i], Moment(i, ci), Wants[wi]);
                if (f.Intent != _base[cell][0].Winner) _formMismatch++;
                else if (f.Intent != null && !f.Weight.Equals(_base[cell][0].TopScore)) _formWeightMismatch++;
            }
        }

        // ============================================================ 0

        [Test, Order(0)]
        public void TheFilesTheControlAndTheDeclarations()
        {
            EnsureBaseline();
            var sha = Sha(_frozenPath);
            var routesSha = Sha(_routesPath);
            var d = FrozenDeclared();
            var sb = new StringBuilder();
            sb.AppendLine("## 0. What is frozen, whether A is the selector, and what is declared");
            sb.AppendLine();
            sb.AppendLine("| | sha256 at the start of this run | Expected | Match |");
            sb.AppendLine("|---|---|---|---|");
            sb.AppendLine("| `intentions.json` | `" + sha + "` | `" + FrozenSha + "` | " + (sha == FrozenSha ? "**yes**" : "**NO**") + " |");
            sb.AppendLine("| `causal-routes.json` | `" + routesSha + "` | `" + RoutesSha + "` | " + (routesSha == RoutesSha ? "**yes**" : "**NO**") + " |");
            sb.AppendLine();
            sb.AppendLine("A, rebuilt from its stages, differs from `IntentionSelector.Form` in **" + _formMismatch + "** of " + Cells + " cells; winning weights not equal to the bit: **" + _formWeightMismatch + "**.");
            sb.AppendLine();
            sb.AppendLine("### The route declared for each frozen rule");
            sb.AppendLine();
            sb.AppendLine("| Rule | Route | Intention | What the route means | Declared roles |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var r in d.Rules)
            {
                var roles = Enumerable.Range(0, r.C.ScaledBy.Count).Where(k => r.Roles[k + 1] != null)
                    .Select(k => "`" + EvidenceKey(r.C.ScaledBy[k]) + "` " + r.Roles[k + 1]).ToList();
                sb.AppendLine("| `" + r.C.Id + "` | `" + r.Routes[0] + "` | " + r.C.Intent + " | " + _frozenMeans[r.Routes[0]] + " | "
                              + (roles.Count == 0 ? "sign" : string.Join(", ", roles)) + " |");
            }
            sb.AppendLine();
            var suspicious = Enumerable.Range(0, Cells).Count(c => Score(Rep.D, _staged[c], d).Suspicious > 0);
            var mismatch = Enumerable.Range(0, Cells).Count(c => Score(Rep.D, _staged[c], d).RoleMismatch > 0);
            sb.AppendLine("Cells in which D finds two different routes stating identical evidence: **" + suspicious + "**. Cells with a declared role contradicting its sign: **" + mismatch + "**.");
            Record("0", sb.ToString());

            Assert.AreEqual(FrozenSha, sha);
            Assert.AreEqual(RoutesSha, routesSha);
            Assert.AreEqual(0, _formMismatch);
            Assert.AreEqual(0, _formWeightMismatch);
        }

        // ============================================================ 1

        static readonly Rep[] FamilyReps = { Rep.A, Rep.B, Rep.C, Rep.D, Rep.G };

        [Test, Order(1), Timeout(3600000)]
        public void A_TheCriticalPairAndTheFamilies()
        {
            var variants = Variants();
            var n = _minds.Length;
            var outs = new Dictionary<string, Outcome[][]>(StringComparer.Ordinal);   // [variant][profile][rep]
            foreach (var v in variants)
            {
                var arr = new Outcome[n][];
                for (var i = 0; i < n; i++)
                    arr[i] = DecideAll(Stage(v.Value, _minds[i], _company[i], _synthWant), v.Value, FamilyReps);
                outs[v.Key] = arr;
            }

            var sb = new StringBuilder();
            sb.AppendLine("## 1. The critical pair, and the five families");
            sb.AppendLine();
            sb.AppendLine("Each variant is evaluated for `" + _synthWant + "`, in company, over all " + n + " sweep profiles, against the two frozen rivals. The rule contents of every variant are in `causal-routes.json`. Passing is as fixed in the predictions: a **same** pair must leave protect's support and the representation's explanation identical in every cell; a **different** pair must change protect's support somewhere; a **structure** pair must keep the support and change the explanation; a **malformed** variant must be flagged; a **reuse** pair must leave protect's support identical.");
            sb.AppendLine();
            sb.AppendLine("| Pair | Declared | What it tests | " + string.Join(" | ", Battery.Select(Name)) + " |");
            sb.AppendLine("|---|---|---|" + string.Concat(Enumerable.Repeat("---|", Battery.Length)));
            var passed = Battery.ToDictionary(r => r, r => 0);
            var total = 0;
            string gReuse = null;
            foreach (var pair in (JArray)_routesJson["synthetic"]["pairs"])
            {
                var a = pair["a"].Value<string>();
                var b = pair["b"].Value<string>();
                var declared = pair["declared"].Value<string>();
                total++;
                var cells = new List<string>();
                foreach (var rep in FamilyReps)
                {
                    var ri = Array.IndexOf(FamilyReps, rep);
                    int supportDiff = 0, traceDiff = 0, outcomeDiff = 0, flagged = 0;
                    for (var i = 0; i < n; i++)
                    {
                        var x = outs[a][i][ri];
                        var y = outs[b][i][ri];
                        if (Math.Abs(x.Support("protect") - y.Support("protect")) > 1e-9) supportDiff++;
                        if (x.Trace != y.Trace) traceDiff++;
                        if (x.Token != y.Token) outcomeDiff++;
                        if (y.Recognised > x.Recognised) flagged++;
                    }
                    bool pass;
                    switch (declared)
                    {
                        case "same": pass = supportDiff == 0 && traceDiff == 0; break;
                        case "different": pass = supportDiff > 0; break;
                        case "structure": pass = supportDiff == 0 && traceDiff > 0; break;
                        case "malformed": pass = flagged > 0; break;
                        default: pass = supportDiff == 0; break;
                    }
                    var cell = (pass ? "pass" : "**fail**") + " (support " + supportDiff + ", explanation " + traceDiff + ", outcome " + outcomeDiff + (declared == "malformed" ? ", flagged " + flagged : "") + ")";
                    if (rep == Rep.G) { if (declared == "reuse") gReuse = cell; continue; }
                    if (pass) passed[rep]++;
                    cells.Add(cell);
                }
                sb.AppendLine("| " + a + " " + b + " | " + declared + " | " + pair["tests"].Value<string>() + " | " + string.Join(" | ", cells) + " |");
            }
            sb.AppendLine("| **Passed** | | | " + string.Join(" | ", Battery.Select(r => "**" + passed[r] + " of " + total + "**")) + " |");
            sb.AppendLine();
            sb.AppendLine("Counts in brackets are cells, of " + n + ", where the pair differ in protect's support, in the representation's explanation, and in the outcome.");
            sb.AppendLine();
            sb.AppendLine("**The negative control G** (each fact given to one intention only) on C0 C1: " + gReuse + ". The reuse test fails when evidence is consumed, as it should.");
            sb.AppendLine();

            // The critical pair, in numbers, for one profile.
            var p = Enumerable.Range(0, n).First(i => _minds[i].Profile.Trait("empathetic") > 0.8 && _minds[i].Profile.ValueWeight("closeness") >= 0.75);
            sb.AppendLine("### The critical pair for one profile (p" + p + ": empathetic " + F(_minds[p].Profile.Trait("empathetic")) + ", closeness weight " + F(_minds[p].Profile.ValueWeight("closeness")) + ")");
            sb.AppendLine();
            sb.AppendLine("| Variant | " + string.Join(" | ", Battery.Select(r => Name(r) + ": protect's support")) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", Battery.Length)));
            foreach (var v in new[] { "A0", "A1", "B1" })
                sb.AppendLine("| " + v + " | " + string.Join(" | ", Battery.Select(r => F(outs[v][p][Array.IndexOf(FamilyReps, r)].Support("protect")))) + " |");
            sb.AppendLine();
            sb.AppendLine("D's explanation, A1: `" + outs["A1"][p][3].Scored.Trace["protect"] + "` (" + outs["A1"][p][3].Scored.Restated + " restated statements recognised).");
            sb.AppendLine();
            sb.AppendLine("D's explanation, B1: `" + outs["B1"][p][3].Scored.Trace["protect"] + "` (" + outs["B1"][p][3].Scored.Suspicious + " pair of different routes flagged as stating identical evidence: *confirm these are two reasons*).");
            sb.AppendLine();

            sb.AppendLine("### Agreement with the declared structure, per variant");
            sb.AppendLine();
            sb.AppendLine("Cells, of " + n + ", in which the representation reaches the same outcome as D, which computes the declared structure by construction.");
            sb.AppendLine();
            sb.AppendLine("| Variant | A | B | C |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var v in variants.Keys)
                sb.AppendLine("| " + v + " | " + string.Join(" | ", new[] { Rep.A, Rep.B, Rep.C }.Select(r =>
                {
                    var agree = Enumerable.Range(0, n).Count(i => outs[v][i][Array.IndexOf(FamilyReps, r)].Token == outs[v][i][3].Token);
                    return agree == n ? "all" : "**" + agree + "**";
                })) + " |");
            Record("1", sb.ToString());

            Assert.AreEqual(total, passed[Rep.D], "D must pass every family: it computes what is declared");
            CollectionAssert.AreEqual(outs["A1"].Select(o => o[0].Token).ToList(), outs["B1"].Select(o => o[0].Token).ToList(), "the theorem: A cannot tell the critical pair apart");
            CollectionAssert.AreEqual(outs["A1"].Select(o => o[1].Token).ToList(), outs["B1"].Select(o => o[1].Token).ToList(), "the theorem: B cannot tell the critical pair apart");
            CollectionAssert.AreEqual(outs["A1"].Select(o => o[2].Token).ToList(), outs["B1"].Select(o => o[2].Token).ToList(), "the theorem: C cannot tell the critical pair apart");
        }

        // ============================================================ 2

        sealed class Tally
        {
            public int Changed;
            public int ChangedUnflagged;
            public int Toward;
            public int Away;
            public int Outside;
            public int CandidateMismatch;
            public int Suspicious;
        }

        static Tally[][][] _perRule;   // [test][rule][battery]
        static Tally[][] _whole;       // [test][battery]
        static int _provenanceChecked;
        static int _provenanceFailed;

        static void Compare(Tally t, Outcome was, Outcome now, bool exposed, string intent, int compatible)
        {
            if (now.Candidates != compatible) t.CandidateMismatch++;
            if (now.Scored.Suspicious > was.Scored.Suspicious) t.Suspicious++;
            if (was.Token == now.Token) return;
            t.Changed++;
            if (now.Recognised <= was.Recognised && now.Scored.Suspicious <= was.Scored.Suspicious) t.ChangedUnflagged++;
            if (intent != null && now.Winner == intent) t.Toward++;
            else if (intent != null && was.Winner == intent) t.Away++;
            if (!exposed) t.Outside++;
        }

        static void EnsureBattery()
        {
            if (_perRule != null) return;
            EnsureBaseline();
            var d = FrozenDeclared();
            _perRule = PerRuleTests.Select(_ => d.Rules.Select(__ => Battery.Select(___ => new Tally()).ToArray()).ToArray()).ToArray();
            for (var ri = 0; ri < d.Rules.Count; ri++)
            {
                var rule = d.Rules[ri];
                var sets = PerRuleTests.Select(t => t.Build(d, rule)).ToArray();
                for (var i = 0; i < _minds.Length; i++)
                for (var wi = 0; wi < Wants.Length; wi++)
                for (var ci = 0; ci < 2; ci++)
                {
                    var cell = Cell(i, wi, ci);
                    var exposed = CompatibleIn(rule.C, wi, ci);
                    for (var t = 0; t < sets.Length; t++)
                    {
                        var staged = Stage(sets[t], _minds[i], Moment(i, ci), Wants[wi]);
                        var outs = DecideAll(staged, sets[t], Battery);
                        for (var a = 0; a < Battery.Length; a++)
                            Compare(_perRule[t][ri][a], _base[cell][a], outs[a], exposed, rule.C.Intent, staged.Compatible.Count);
                    }
                }
            }
            _whole = WholeTests.Select(_ => Battery.Select(__ => new Tally()).ToArray()).ToArray();
            for (var t = 0; t < WholeTests.Length; t++)
            {
                var set = WholeTests[t].Build(d);
                for (var i = 0; i < _minds.Length; i++)
                for (var wi = 0; wi < Wants.Length; wi++)
                for (var ci = 0; ci < 2; ci++)
                {
                    var cell = Cell(i, wi, ci);
                    var staged = Stage(set, _minds[i], Moment(i, ci), Wants[wi]);
                    var outs = DecideAll(staged, set, Battery, WholeTests[t].Unrename);
                    for (var a = 0; a < Battery.Length; a++)
                        Compare(_whole[t][a], _base[cell][a], outs[a], true, null, staged.Compatible.Count);
                }
            }

            // R15: every winner under D is traceable, and the trace reconstructs its score.
            for (var c = 0; c < Cells; c++)
            {
                var o = _base[c][3];
                if (o.Winner == null) continue;
                _provenanceChecked++;
                var totals = o.Scored.RouteTotals[o.Winner];
                var reconstructed = totals.Values.Sum();
                var everyStatementNamed = _staged[c].Rules.Where(r => r.R.C.Intent == o.Winner).SelectMany(r => r.Statements).All(s => s.RuleId != null && s.Route != null);
                if (Math.Abs(reconstructed - o.TopScore) > 1e-9 || !everyStatementNamed || o.Scored.ProvenanceGaps > 0) _provenanceFailed++;
            }
        }

        [Test, Order(2), Timeout(3600000)]
        public void B_TheRetainedAndTheNewInvariants()
        {
            EnsureBattery();
            var d = FrozenDeclared();
            var sb = new StringBuilder();
            sb.AppendLine("## 2. The invariants, on the frozen file and the whole sweep");
            sb.AppendLine();
            sb.AppendLine("Cells, of " + Cells + ", whose outcome changed; per-rule rewrites summed over the ten rules (" + (Cells * d.Rules.Count) + " (rule, cell) pairs). In brackets: changes the representation did not flag, as a restatement, a conflict, or two routes stating identical evidence.");
            sb.AppendLine();
            sb.AppendLine("| | Rewrite | " + string.Join(" | ", Battery.Select(Name)) + " |");
            sb.AppendLine("|---|---|" + string.Concat(Enumerable.Repeat("---|", Battery.Length)));
            Tally Total(IEnumerable<Tally> ts)
            {
                var s = new Tally();
                foreach (var t in ts)
                {
                    s.Changed += t.Changed; s.ChangedUnflagged += t.ChangedUnflagged; s.Toward += t.Toward; s.Away += t.Away;
                    s.Outside += t.Outside; s.CandidateMismatch += t.CandidateMismatch; s.Suspicious += t.Suspicious;
                }
                return s;
            }
            string CellOf(Tally t) => t.Changed == 0 ? "0" : "**" + t.Changed + "** (" + t.ChangedUnflagged + " unflagged)";
            var rows = new List<Tuple<string, string, Tally[]>>();
            for (var t = 0; t < WholeTests.Length; t++) rows.Add(Tuple.Create(WholeTests[t].Key, WholeTests[t].Label, _whole[t]));
            for (var t = 0; t < PerRuleTests.Length; t++)
                rows.Add(Tuple.Create(PerRuleTests[t].Key, PerRuleTests[t].Label, Enumerable.Range(0, Battery.Length).Select(a => Total(_perRule[t].Select(r => r[a]))).ToArray()));
            foreach (var key in new[] { "R1", "R2", "R3", "R4a", "R4b", "R4c", "R4d", "R4new", "R5a", "R6", "R7", "R9a", "R9b", "R11" })
            {
                var row = rows.First(r => r.Item1 == key);
                sb.AppendLine("| " + row.Item1 + " | " + row.Item2 + " | " + string.Join(" | ", row.Item3.Select(CellOf)) + " |");
            }
            sb.AppendLine();
            var r7 = rows.First(r => r.Item1 == "R7").Item3;
            var r4new = rows.First(r => r.Item1 == "R4new").Item3;
            sb.AppendLine("| | " + string.Join(" | ", Battery.Select(Name)) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", Battery.Length)));
            sb.AppendLine("| R7: changes toward / **away** from the strengthened intention | " + string.Join(" | ", r7.Select(t => t.Toward + " / **" + t.Away + "**")) + " |");
            sb.AppendLine("| R8: changes outside where the rewritten rule applies, all per-rule rewrites | " + string.Join(" | ", Enumerable.Range(0, Battery.Length).Select(a => PerRuleTests.Select((_, t) => _perRule[t].Sum(r => r[a].Outside)).Sum().ToString())) + " |");
            sb.AppendLine("| R10: cells whose candidates are not the compatible set, frozen file | " + string.Join(" | ", Enumerable.Range(0, Battery.Length).Select(a => Enumerable.Range(0, Cells).Count(c => _base[c][a].Candidates != _staged[c].Compatible.Count).ToString())) + " |");
            sb.AppendLine("| R4new: cells where D flags two routes stating identical evidence | " + string.Join(" | ", r4new.Select(t => t.Suspicious.ToString())) + " |");
            sb.AppendLine();
            sb.AppendLine("**R15, provenance**: under D, " + (_provenanceChecked - _provenanceFailed) + " of " + _provenanceChecked + " winning intentions have a trace, from route to evidence to coefficient and sign to the level read, that reconstructs their score to within 1e-9, with every statement naming the rule that stated it.");
            Record("2", sb.ToString());

            Assert.AreEqual(0, _provenanceFailed, "R15");
            Assert.AreEqual(0, Enumerable.Range(0, Battery.Length).Sum(a => PerRuleTests.Select((_, t) => _perRule[t].Sum(r => r[a].Outside)).Sum()), "R8");
        }

        // ============================================================ 3

        static readonly string[] Attributes =
        {
            "trait:anxious", "trait:cautious", "trait:dominant", "trait:empathetic", "trait:honest", "trait:impulsive", "trait:proud",
            "value ranks 1-2", "value ranks 2-3", "value ranks 3-4", "value ranks 4-5", "value ranks 5-6",
            "belief:role_claim", "belief:answerable_for"
        };

        static List<Tuple<int, Mind>> Moves(Mind m)
        {
            var moves = new List<Tuple<int, Mind>>();
            for (var t = 0; t < _sweepTraits.Count; t++)
                foreach (var level in _levels)
                {
                    if (level.Equals(m.Profile.Trait(_sweepTraits[t]))) continue;
                    var traits = TraitsOf(m);
                    traits[_sweepTraits[t]] = level;
                    moves.Add(Tuple.Create(Array.IndexOf(Attributes, "trait:" + _sweepTraits[t]), Person(m.Id, traits, m.Profile.Values, SeedsOf(m))));
                }
            for (var k = 0; k < m.Profile.Values.Count - 1; k++)
            {
                var values = m.Profile.Values.ToList();
                var swap = values[k];
                values[k] = values[k + 1];
                values[k + 1] = swap;
                moves.Add(Tuple.Create(7 + k, Person(m.Id, TraitsOf(m), values, SeedsOf(m))));
            }
            foreach (var (predicate, second, confidence, attr) in new[] { ("role_claim", "leads_family", 0.80, 12), ("answerable_for", "missing_can", 0.90, 13) })
            {
                var seeds = SeedsOf(m);
                var held = seeds.Any(b => b.Predicate == predicate);
                seeds = held ? seeds.Where(b => b.Predicate != predicate).ToList()
                    : seeds.Concat(new[] { new BeliefSeed(predicate, new[] { m.Id, second }, confidence) }).ToList();
                moves.Add(Tuple.Create(attr, Person(m.Id, TraitsOf(m), m.Profile.Values, seeds)));
            }
            return moves;
        }

        [Test, Order(3), Timeout(3600000)]
        public void C_TheFrozenFileUnderDeclaredRoutes()
        {
            EnsureBaseline();
            var d = FrozenDeclared();
            var whatIf = FrozenWhatIf();
            var sb = new StringBuilder();
            sb.AppendLine("## 3. The frozen file under declared routes");
            sb.AppendLine();

            // D against the others.
            string Diff(int a, int b) => Enumerable.Range(0, Cells).Count(c => _base[c][a].Token != _base[c][b].Token).ToString();
            sb.AppendLine("| Cells where the outcomes differ | A | B | C |");
            sb.AppendLine("|---|---|---|---|");
            sb.AppendLine("| **D** | " + Diff(3, 0) + " (" + Enumerable.Range(0, Cells).Count(c => _base[c][3].Token != _base[c][0].Token && _base[c][3].Tie) + " of them ties D reports) | " + Diff(3, 1) + " | " + Diff(3, 2) + " |");
            sb.AppendLine();

            // The diagnostics.
            var alt = new Outcome[Cells];
            var en = new Outcome[Cells];
            for (var c = 0; c < Cells; c++)
            {
                alt[c] = Decide(Rep.DAlt, _staged[c], whatIf);
                en[c] = Decide(Rep.DEnablers, _staged[c], d);
            }
            var altDiff = Enumerable.Range(0, Cells).Where(c => alt[c].Token != _base[c][3].Token).ToList();
            var enDiff = Enumerable.Range(0, Cells).Where(c => en[c].Token != _base[c][3].Token).ToList();
            int GroupOf(int c) => (c / 2 % Wants.Length) * 2 + c % 2;
            bool Innocent(int c) => _minds[c / 2 / Wants.Length].Beliefs.Confidence("answerable_for", new[] { _minds[c / 2 / Wants.Length].Id, "missing_can" }) <= 0.0;
            sb.AppendLine("### How much the relation and the role judgments move");
            sb.AppendLine();
            sb.AppendLine("| Diagnostic | Declared differently | Cells changed | By group |");
            sb.AppendLine("|---|---|---|---|");
            sb.AppendLine("| **D-alt** | `standing_in_the_way` / `shielding_from_afar`, and the two authority routes, as alternatives | **" + altDiff.Count + "** | "
                          + string.Join(", ", altDiff.GroupBy(GroupOf).OrderBy(g => g.Key).Select(g => GroupName(g.Key) + " " + g.Count())) + " |");
            sb.AppendLine("| **D-enablers** | `answerable_for` honoured as the condition of `owning_the_night` | **" + enDiff.Count + "** | "
                          + string.Join(", ", enDiff.GroupBy(GroupOf).OrderBy(g => g.Key).Select(g => GroupName(g.Key) + " " + g.Count())) + " |");
            sb.AppendLine();
            var lookAfterCo = Enumerable.Range(0, _minds.Length).Select(i => Cell(i, Array.IndexOf(Wants, "look_after"), 0)).ToList();
            sb.AppendLine("Under D-alt, `look_after -> protect` in company: " + Pc(lookAfterCo.Count(c => alt[c].Winner == "protect"), lookAfterCo.Count) + " (D: " + Pc(lookAfterCo.Count(c => _base[c][3].Winner == "protect"), lookAfterCo.Count) + ").");
            sb.AppendLine();
            var tookD = Enumerable.Range(0, Cells).Where(c => _base[c][3].Winner == "took_what_was_not_mine").ToList();
            var tookE = Enumerable.Range(0, Cells).Where(c => en[c].Winner == "took_what_was_not_mine").ToList();
            var unmotivated = Enumerable.Range(0, Cells).Count(c => en[c].Winner != null && Math.Abs(en[c].TopScore) < Tie);
            sb.AppendLine("| `took_what_was_not_mine` formed | D | D-enablers |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| by a profile believing it is answerable | " + tookD.Count(c => !Innocent(c)) + " | " + tookE.Count(c => !Innocent(c)) + " |");
            sb.AppendLine("| by a profile holding no such belief | **" + tookD.Count(Innocent) + "** | **" + tookE.Count(Innocent) + "** |");
            sb.AppendLine("| ...of which with zero support, as the only candidate: an intention formed for no reason | " + tookD.Count(c => Innocent(c) && Math.Abs(_base[c][3].TopScore) < Tie) + " | **" + tookE.Count(c => Innocent(c) && Math.Abs(en[c].TopScore) < Tie) + "** |");
            sb.AppendLine();
            sb.AppendLine("Every cell D-enablers changes is one in which D had a profile without the belief form the theft: " + enDiff.Count(Innocent) + " of " + enDiff.Count + ". Cells anywhere in which D-enablers forms an intention with zero support: **" + unmotivated + "**.");
            sb.AppendLine();

            // What was proven, under D.
            var hungry = 0;
            var room = 0;
            var replay = 0;
            for (var i = 0; i < _minds.Length; i++)
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var present = ci == 0 ? Others : Nobody;
                var c = Cell(i, wi, ci);
                if (Decide(Rep.D, Stage(d, _minds[i], At(_minds[i].Id, present, 0.95), Wants[wi]), d).Token != _base[c][3].Token) hungry++;
                if (Decide(Rep.D, Stage(d, _minds[i], At(_minds[i].Id, present, 0.3, _elsewhere), Wants[wi]), d).Token != _base[c][3].Token) room++;
            }
            for (var k = 0; k < 300; k++)
            {
                var i = k * 7 % _minds.Length;
                for (var wi = 0; wi < Wants.Length; wi++)
                    if (Decide(Rep.D, Stage(d, SweepMind(i), _company[i], Wants[wi]), d).Token == _base[Cell(i, wi, 0)][3].Token) replay++;
            }
            var names = Cast.Concat(HeldOut).ToList();
            var hits = d.Rules.Sum(r => names.Count(nm => (r.C.Id + " " + string.Join(" ", r.Routes) + " " + string.Join(" ", r.C.ScaledBy.Select(EvidenceKey))).IndexOf(nm, StringComparison.OrdinalIgnoreCase) >= 0));
            var sigs = Enumerable.Range(0, _minds.Length).Select(i => string.Join("|", Enumerable.Range(0, Wants.Length).Select(wi => _base[Cell(i, wi, 0)][3].Token))).Distinct().Count();
            var arrival = Enumerable.Range(0, _minds.Length).Sum(i => Enumerable.Range(0, Wants.Length).Count(wi => _base[Cell(i, wi, 0)][3].Token != _base[Cell(i, wi, 1)][3].Token));

            // Fixed-candidate sensitivity, A against D.
            var pairs = new int[2];
            var moved = new int[2];
            var fixedPairs = new int[2];
            var fixedMoved = new int[2];
            var reps = new[] { Rep.A, Rep.D };
            for (var i = 0; i < _minds.Length; i++)
                foreach (var mv in Moves(_minds[i]))
                    for (var wi = 0; wi < Wants.Length; wi++)
                    for (var ci = 0; ci < 2; ci++)
                    {
                        var c = Cell(i, wi, ci);
                        if (_staged[c].Compatible.Count < 2) continue;
                        var after = Stage(d, mv.Item2, Moment(i, ci), Wants[wi]);
                        for (var a = 0; a < 2; a++)
                        {
                            var was = _base[c][a == 0 ? 0 : 3];
                            var now = Decide(reps[a], after, d);
                            pairs[a]++;
                            var same = new HashSet<string>(was.Scored.Candidates).SetEquals(now.Scored.Candidates);
                            if (was.Token != now.Token) moved[a]++;
                            if (!same) continue;
                            fixedPairs[a]++;
                            if (was.Token != now.Token) fixedMoved[a]++;
                        }
                    }

            sb.AppendLine("### What was proven, under D");
            sb.AppendLine();
            sb.AppendLine("| | Published for A | D |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Cells with one candidate | 28.6 % | " + Pc(_base.Count(o => o[3].Candidates == 1), Cells) + " |");
            sb.AppendLine("| Distinct signatures in company | 56 (64 with the 25 ties reported) | " + sigs + " |");
            sb.AppendLine("| Cells changed by company arriving | 8407 (8412 with ties reported) | " + arrival + " |");
            sb.AppendLine("| Hunger 0.30 -> 0.95 / a room with no food changed | 0 / 0 | " + hungry + " / " + room + " |");
            sb.AppendLine("| Replay, 300 profiles x 7 wants rebuilt | exact | " + replay + " of 2100 |");
            sb.AppendLine("| Character names in any rule or route | 0 | " + hits + " |");
            sb.AppendLine("| K >= 2, candidates fixed: a single-attribute move changes the intention | 6.1 % (A here: " + Pc(fixedMoved[0], fixedPairs[0]) + ") | **" + Pc(fixedMoved[1], fixedPairs[1]) + "** |");
            Record("3", sb.ToString());

            Assert.AreEqual(0, hungry);
            Assert.AreEqual(0, room);
            Assert.AreEqual(2100, replay);
            Assert.AreEqual(0, hits);
        }

        // ============================================================ 4

        sealed class PantryCase
        {
            public string Label;
            public string Who;
            public string Want;
            public Outcome[] Own;
            public List<Tuple<string, Outcome[]>> Partners = new List<Tuple<string, Outcome[]>>();
            public int[] LabelByCopy = new int[3];
            public int[] LeadByCopy = new int[3];
            public int[] LabelByPartial = new int[3];
            public int[] LeadByPartial = new int[3];
            public int[] LabelByNewRoute = new int[3];
            public int[] LeadByNewRoute = new int[3];
            public int FlaggedNewRoute;
        }

        static readonly Rep[] LiveReps = { Rep.A, Rep.B, Rep.C, Rep.D, Rep.DAlt, Rep.DEnablers };

        [Test, Order(4), Timeout(3600000)]
        public void D_RealMornings()
        {
            var d = FrozenDeclared();
            var whatIf = FrozenWhatIf();
            var pantryWants = _content.Rules.Proposals.Where(p => p.Action == "check_pantry").Select(p => p.Motive).Distinct().OrderBy(x => x, StringComparer.Ordinal).ToList();
            var copies = d.Rules.Select(r => Plus(d, Scaled(r, r.C.Id + "_again", 1.0))).ToList();
            var partials = d.Rules.Select(r => Plus(d, Like(r, Make(r.C, r.C.Id + "_partly", scalers: r.C.ScaledBy.Take(r.C.ScaledBy.Count - 1).ToList()), Enumerable.Range(0, r.C.ScaledBy.Count - 1)))).ToList();
            var newRoutes = d.Rules.Select(r => Plus(d, Like(r, r.C.CloneAs(r.C.Id + "_again"), null, r.Routes[0] + "#copy"))).ToList();
            var cases = new List<PantryCase>();
            var stabilityReps = new[] { Rep.A, Rep.C, Rep.D };

            foreach (var variant in _content.Morning.Variants.Select(v => v.Id))
            for (ulong seed = 1; seed <= MorningSeeds; seed++)
            {
                var run = Scenario001.Prepare(_content, variant, seed);
                var label = variant + "/" + seed;
                run.Morning.Decided = moment =>
                {
                    var dec = moment.Decision;
                    var leading = dec.Leading;
                    if (dec.Chosen == null || dec.Chosen.KindName != "check_pantry" || leading == null || !pantryWants.Contains(leading.Name)) return;
                    var p = moment.Percept;
                    var target = p.Present.FirstOrDefault();
                    Outcome[] Read(Mind mind)
                    {
                        var st = Stage(d, mind, p, leading.Name, target);
                        return LiveReps.Select(r => Decide(r, st, r == Rep.DAlt ? whatIf : d)).ToArray();
                    }
                    var c = new PantryCase { Label = label + " m" + moment.Minute, Who = moment.CharacterId, Want = leading.Name, Own = Read(moment.Mind) };
                    foreach (var y in Cast.Where(x => x != moment.CharacterId))
                        c.Partners.Add(Tuple.Create(y, Read(run.Simulation.Minds[y])));
                    for (var ri = 0; ri < d.Rules.Count; ri++)
                        for (var s = 0; s < stabilityReps.Length; s++)
                        {
                            var rep = stabilityReps[s];
                            var own = c.Own[Array.IndexOf(LiveReps, rep)];
                            string LeadOf(Outcome o) => rep == Rep.D ? LeadRoute(o) : o.Winner ?? "none";
                            var copy = Decide(rep, Stage(copies[ri], moment.Mind, p, leading.Name, target), copies[ri]);
                            var part = Decide(rep, Stage(partials[ri], moment.Mind, p, leading.Name, target), partials[ri]);
                            var fresh = Decide(rep, Stage(newRoutes[ri], moment.Mind, p, leading.Name, target), newRoutes[ri]);
                            if (copy.Token != own.Token) c.LabelByCopy[s]++; else if (!SameSupport(copy, own) || LeadOf(copy) != LeadOf(own)) c.LeadByCopy[s]++;
                            if (part.Token != own.Token) c.LabelByPartial[s]++; else if (!SameSupport(part, own) || LeadOf(part) != LeadOf(own)) c.LeadByPartial[s]++;
                            if (fresh.Token != own.Token) { c.LabelByNewRoute[s]++; if (rep == Rep.D && fresh.Scored.Suspicious > own.Scored.Suspicious) c.FlaggedNewRoute++; }
                            else if (!SameSupport(fresh, own) || LeadOf(fresh) != LeadOf(own)) c.LeadByNewRoute[s]++;
                        }
                    cases.Add(c);
                };
                run.Morning.Run(_content.Morning.Minutes);
            }

            var pairs = cases.SelectMany(c => c.Partners.Select(p => Tuple.Create(c, p.Item1, p.Item2))).ToList();
            var sb = new StringBuilder();
            sb.AppendLine("## 4. Real mornings");
            sb.AppendLine();
            sb.AppendLine("**" + cases.Count + " real pantry-checks** in 50 baseline mornings, for the wants whose shipped proposals lead to `check_pantry` (" + string.Join(", ", pantryWants.Select(w => "`" + w + "`")) + "), each matched with every other member of the cast at the same minute of the same morning: **" + pairs.Count + " pairs**.");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", LiveReps.Select(Name)) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", LiveReps.Length)));
            string Row(string l, Func<int, string> f) => "| " + l + " | " + string.Join(" | ", Enumerable.Range(0, LiveReps.Length).Select(f)) + " |";
            sb.AppendLine(Row("The same act carried by different intentions across people", a => { var n = pairs.Count(x => x.Item1.Own[a].Token != x.Item3[a].Token); return n + " (" + Pc(n, pairs.Count) + ")"; }));
            sb.AppendLine(Row("Same intention: the person evidence behind it differs", a =>
            {
                var same = pairs.Where(x => x.Item1.Own[a].Token == x.Item3[a].Token && x.Item1.Own[a].Winner != null).ToList();
                return same.Count(x => !SameSupport(x.Item1.Own[a], x.Item3[a])) + " of " + same.Count;
            }));
            var di = Array.IndexOf(LiveReps, Rep.D);
            var sameD = pairs.Where(x => x.Item1.Own[di].Token == x.Item3[di].Token && x.Item1.Own[di].Winner != null).ToList();
            sb.AppendLine();
            sb.AppendLine("Under D, of the " + sameD.Count + " pairs forming the same intention, the **leading route** differs in **" + sameD.Count(x => LeadRoute(x.Item1.Own[di]) != LeadRoute(x.Item3[di])) + "**, and the person evidence in **" + sameD.Count(x => !SameSupport(x.Item1.Own[di], x.Item3[di])) + "**.");
            sb.AppendLine();
            sb.AppendLine(Row("Real decisions changed against D", a => cases.Sum(c => (c.Own[a].Token != c.Own[di].Token ? 1 : 0) + c.Partners.Count(p => p.Item2[a].Token != p.Item2[di].Token)).ToString()));
            sb.AppendLine();

            sb.AppendLine("### Does authoring alone change a real decision, or its stated reason?");
            sb.AppendLine();
            sb.AppendLine("Each real pantry-check re-decided with one rule copied, for each of the ten rules (" + (cases.Count * d.Rules.Count) + " re-decisions per row). \"Reason changed\" means the same intention with different person evidence behind it, or, under D, a different leading route.");
            sb.AppendLine();
            sb.AppendLine("| Rewrite | " + string.Join(" | ", stabilityReps.Select(r => Name(r) + ": intention / reason changed")) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", stabilityReps.Length)));
            sb.AppendLine("| Copied, same route | " + string.Join(" | ", Enumerable.Range(0, stabilityReps.Length).Select(s => cases.Sum(c => c.LabelByCopy[s]) + " / " + cases.Sum(c => c.LeadByCopy[s]))) + " |");
            sb.AppendLine("| Partly copied, same route | " + string.Join(" | ", Enumerable.Range(0, stabilityReps.Length).Select(s => cases.Sum(c => c.LabelByPartial[s]) + " / " + cases.Sum(c => c.LeadByPartial[s]))) + " |");
            sb.AppendLine("| Copied, **declared a new route** | " + string.Join(" | ", Enumerable.Range(0, stabilityReps.Length).Select(s => cases.Sum(c => c.LabelByNewRoute[s]) + " / " + cases.Sum(c => c.LeadByNewRoute[s]))) + " |");
            sb.AppendLine();
            sb.AppendLine("Of D's changes from a copy declared a new route, flagged as two routes stating identical evidence: **" + cases.Sum(c => c.FlaggedNewRoute) + " of " + cases.Sum(c => c.LabelByNewRoute[2]) + "**.");
            sb.AppendLine();

            var enI = Array.IndexOf(LiveReps, Rep.DEnablers);
            var enChanged = cases.SelectMany(c => new[] { Tuple.Create(c.Who, c.Own) }.Concat(c.Partners)).Where(x => x.Item2[enI].Token != x.Item2[di].Token).ToList();
            sb.AppendLine("### Real decisions the diagnostics change");
            sb.AppendLine();
            sb.AppendLine("| Diagnostic | Real decisions changed, of " + (cases.Count + pairs.Count) + " | What changed |");
            sb.AppendLine("|---|---|---|");
            var altI = Array.IndexOf(LiveReps, Rep.DAlt);
            var altChanged = cases.SelectMany(c => new[] { Tuple.Create(c.Who, c.Own) }.Concat(c.Partners)).Where(x => x.Item2[altI].Token != x.Item2[di].Token).ToList();
            sb.AppendLine("| D-alt | " + altChanged.Count + " | " + string.Join(", ", altChanged.GroupBy(x => x.Item1 + ": " + x.Item2[di].Token + " -> " + x.Item2[altI].Token).Select(g => g.Key + " (" + g.Count() + ")")) + " |");
            sb.AppendLine("| D-enablers | " + enChanged.Count + " | " + string.Join(", ", enChanged.GroupBy(x => x.Item1 + ": " + x.Item2[di].Token + " -> " + x.Item2[enI].Token).Select(g => g.Key + " (" + g.Count() + ")")) + " |");
            Record("4", sb.ToString());

            var dStab = Array.IndexOf(stabilityReps, Rep.D);
            Assert.AreEqual(0, cases.Sum(c => c.LabelByCopy[dStab] + c.LeadByCopy[dStab] + c.LabelByPartial[dStab] + c.LeadByPartial[dStab]), "restatement immunity on real decisions");
        }

        // ============================================================ 5

        static double Fleiss(IReadOnlyList<Dictionary<string, int>> counts, IReadOnlyList<string> categories)
        {
            var n = counts[0].Values.Sum();
            var pi = counts.Select(c => (c.Values.Sum(x => x * (x - 1.0))) / (n * (n - 1.0))).Average();
            var pj = categories.Select(cat => counts.Sum(c => c.TryGetValue(cat, out var v) ? v : 0) / (double)(counts.Count * n)).ToList();
            var pe = pj.Sum(p => p * p);
            return Math.Abs(1.0 - pe) < 1e-12 ? double.NaN : (pi - pe) / (1.0 - pe);
        }

        [Test, Order(5)]
        public void E_TheBlindAnnotation()
        {
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "causal-routes", "annotation");
            var itemsJson = JObject.Parse(File.ReadAllText(Path.Combine(dir, "items.json")));
            var items = ((JArray)itemsJson["items"]).ToList();
            var key = (JObject)itemsJson["answer_key"];
            var neutral = items.Select((it, k) => new { Id = it["id"].Value<string>(), N = "item-" + (k + 1).ToString("00") }).ToDictionary(x => x.N, x => x.Id);
            var files = Directory.GetFiles(Path.Combine(dir, "responses"), "reviewer-*.json").OrderBy(f => f, StringComparer.Ordinal).ToList();
            var reviewers = files.Select(f => JObject.Parse(File.ReadAllText(f))).ToList();

            string Judgment(JToken a)
            {
                var q1 = a?["q1"]?.Value<string>();
                var q2 = a?["q2"]?.Value<string>();
                if (q1 == "yes" && q2 == "no") return "restatement";
                if (q1 == "no" && q2 == "yes") return "different";
                return "unclear";
            }
            string Combine(JToken a)
            {
                var q3 = a?["q3"]?.Value<string>();
                return q3 == "both" || q3 == "one_or_other" ? q3 : "unclear";
            }
            JToken AnswerOf(JObject r, string itemId) => ((JArray)r["answers"]).FirstOrDefault(x => neutral[x["id"].Value<string>()] == itemId);

            var sb = new StringBuilder();
            sb.AppendLine("## 5. The blind annotation");
            sb.AppendLine();
            sb.AppendLine(reviewers.Count + " reviewers (" + string.Join(", ", reviewers.Select(r => "#" + r["reviewer"] + " " + r["model"])) + "), each a fresh subagent shown only the items, in the rotated and swapped order the protocol fixes, under neutral ids. **They are language models, not people.** Agreement below is evidence about whether the distinctions are legible and reproducible, and says nothing about whether they are true.");
            sb.AppendLine();
            sb.AppendLine("| Item | Source | Declared | Judgments (restatement / different / unclear) | Majority | Matches the key | Q3 (both / one or other / unclear) | Declared Q3 |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            var judgmentCounts = new List<Dictionary<string, int>>();
            var combineCounts = new List<Dictionary<string, int>>();
            var matches = 0;
            var pairItems = 0;
            var q3Matches = 0;
            var q3Items = new List<string>();
            foreach (var it in items)
            {
                var id = it["id"].Value<string>();
                if (it["single"]?.Value<bool>() == true) continue;
                pairItems++;
                var j = reviewers.Select(r => Judgment(AnswerOf(r, id))).ToList();
                var q3 = reviewers.Select(r => Combine(AnswerOf(r, id))).ToList();
                var jc = new[] { "restatement", "different", "unclear" }.ToDictionary(c => c, c => j.Count(x => x == c));
                var qc = new[] { "both", "one_or_other", "unclear" }.ToDictionary(c => c, c => q3.Count(x => x == c));
                judgmentCounts.Add(jc);
                var majority = jc.OrderByDescending(kv => kv.Value).First();
                var declared = key[id]["judgment"].Value<string>();
                var declaredQ3 = key[id]["combine"].Value<string>();
                if (majority.Key == declared) matches++;
                if (declared == "different")
                {
                    combineCounts.Add(qc);
                    var q3Majority = qc.OrderByDescending(kv => kv.Value).First().Key;
                    if (q3Majority == declaredQ3) q3Matches++;
                    else q3Items.Add("`" + id + "` (declared " + declaredQ3 + ", majority " + q3Majority + " " + qc[q3Majority] + " of " + reviewers.Count + ")");
                }
                sb.AppendLine("| `" + id + "` | " + it["source"].Value<string>() + " | " + declared + " | " + jc["restatement"] + " / " + jc["different"] + " / " + jc["unclear"]
                              + " | " + majority.Key + " (" + majority.Value + " of " + reviewers.Count + ")" + " | " + (majority.Key == declared ? "yes" : "**no**")
                              + " | " + (declared == "different" ? qc["both"] + " / " + qc["one_or_other"] + " / " + qc["unclear"] : "-") + " | " + (declared == "different" ? declaredQ3 : "-") + " |");
            }
            sb.AppendLine();
            var role = items.First(it => it["single"]?.Value<bool>() == true);
            var q5 = reviewers.Select(r => AnswerOf(r, role["id"].Value<string>())?["q5"]?.Value<string>() ?? "missing").ToList();
            var kJ = Fleiss(judgmentCounts, new[] { "restatement", "different", "unclear" });
            var kQ3 = Fleiss(combineCounts, new[] { "both", "one_or_other", "unclear" });
            var q3Agree = combineCounts.Select(c => c.Values.Max() / (double)reviewers.Count).Average();
            sb.AppendLine("| | |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Majority judgment matches the key | **" + matches + " of " + pairItems + "** two-reason items |");
            sb.AppendLine("| Fleiss' kappa, judgment (restatement / different / unclear), " + pairItems + " items | **" + F(kJ) + "** |");
            sb.AppendLine("| Fleiss' kappa, Q3 (both / one or other / unclear), the " + combineCounts.Count + " items declared different | **" + F(kQ3) + "**; mean share agreeing with the item's majority " + Pc(q3Agree, 1.0) + " |");
            sb.AppendLine("| Q3 majority matches the declared relation | **" + q3Matches + " of " + combineCounts.Count + "** items declared different. Not matching: " + (q3Items.Count == 0 ? "none" : string.Join("; ", q3Items)) + " |");
            sb.AppendLine("| Q5, the role item (`" + role["id"] + "`): precondition / contributing / unclear | " + q5.Count(x => x == "precondition") + " / " + q5.Count(x => x == "contributing") + " / " + q5.Count(x => x == "unclear") + " (declared: precondition) |");
            sb.AppendLine();
            sb.AppendLine("### Q4, verbatim: what an explanation would need to show");
            sb.AppendLine();
            foreach (var it in items)
            {
                var id = it["id"].Value<string>();
                sb.AppendLine("**`" + id + "`**");
                sb.AppendLine();
                foreach (var r in reviewers)
                    sb.AppendLine("- #" + r["reviewer"] + " " + r["model"] + ": " + (AnswerOf(r, id)?["q4"]?.Value<string>() ?? "(missing)"));
                sb.AppendLine();
            }
            Record("5", sb.ToString());
        }

        // ============================================================ Z

        [Test, Order(9)]
        public void Z_TheFilesAreUntouchedAfterEverything()
        {
            var sha = Sha(_frozenPath);
            var routes = Sha(_routesPath);
            Record("Z", "## Z. The files after the whole run\n\n| | sha256 | |\n|---|---|---|\n| `intentions.json` | `" + sha + "` | "
                        + (sha == FrozenSha ? "unchanged" : "**CHANGED**") + " |\n| `causal-routes.json` | `" + routes + "` | " + (routes == RoutesSha ? "unchanged" : "**CHANGED**") + " |\n\nEvery rewritten rule set and every representation above lived in memory.\n");
            Assert.AreEqual(FrozenSha, sha);
            Assert.AreEqual(RoutesSha, routes);
        }
    }
}
