using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// One small episode of a life, run in a live morning: Daniel goes through
    /// Mara's things while she is standing there, and half an hour later he
    /// watches her across the room. Both are put into the morning by the
    /// experiment (SETUP) through the existing `SilentMorning.Happen`, which
    /// reaches people by exactly the route their own acts reach each other.
    /// Everything between and after is whatever the simulation does.
    ///
    /// Three conditions on the same seed and the same random streams: she was
    /// there and saw it; the same thing happened and she did not perceive it;
    /// and it never happened. Nothing is scripted about what she does next: no
    /// rule names this memory, and no rule was added or changed for this
    /// experiment.
    ///
    /// Writes `Docs/experiments/episode/measurements.md`.
    /// </summary>
    public class EpisodeExperimentTests
    {
        const int Seeds = 10;
        const string Saw = "A: she saw it";
        const string Missed = "C: she did not see it";
        const string Never = "B: it never happened";
        static readonly string[] Conditions = { Saw, Missed, Never };

        /// <summary>The morning is 90 minutes; the two moments are looked for from here.</summary>
        const int IntrusionFrom = 8;
        const int EncounterFrom = 38;

        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load() => _content = Baselines.Primary();

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# One episode: measurements");
            sb.AppendLine();
            sb.AppendLine("Generated by `EpisodeExperimentTests` on the primary baseline. Two events are put into a live morning by the experiment; everything else is the simulation. The three conditions share a seed, and the random stream is forked per person and minute, so it cannot shift between them.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "episode");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "measurements.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string P(double part, double whole) => whole == 0 ? "n/a" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + " %";

        // ------------------------------------------------------------------ the two events

        static WorldEvent Intrusion(int day, int minute, IReadOnlyList<string> witnesses)
            => new WorldEvent(
                "e-intrusion", day, 5000, EventKind.Action, "daniel", "mara",
                null, "search_belongings", "missing_can", "neutral", "direct", "neutral",
                null, "Daniel empties Mara's bag out while she is standing there.",
                witnesses, new List<string>(), new List<LedgerEffect>(), null, minute);

        static WorldEvent Watching(int day, int minute, IReadOnlyList<string> witnesses)
            => new WorldEvent(
                "e-watching", day, 6000, EventKind.Action, "daniel", "mara",
                null, "observe", null, "neutral", "direct", "neutral",
                null, "Daniel watches Mara across the room and says nothing.",
                witnesses, new List<string>(), new List<LedgerEffect>(), null, minute);

        // ------------------------------------------------------------------ watching a morning

        sealed class Moment
        {
            public int Minute;
            public string Who;
            public string Chosen;
            public string Leading;
            public string Feelings;
            public string Options;
            public bool Ambiguous;
            public Dictionary<string, double> Wants = new Dictionary<string, double>(StringComparer.Ordinal);

            public string Line => "m" + Minute + " " + Who + " " + Chosen + " for " + (Leading ?? "nothing");
            public string WantLine => string.Join(", ", Wants.OrderByDescending(x => x.Value).Select(x => x.Key + " " + F(x.Value)));
        }

        sealed class Episode
        {
            public string Condition;
            public string Variant;
            public ulong Seed;
            public bool Usable = true;
            public string Why;
            public int IntrusionAt = -1;
            public int WatchingAt = -1;
            public PerceptionOutcome HerIntrusion;
            public PerceptionOutcome HerWatching;
            public Dictionary<string, double> BeliefsAfter = new Dictionary<string, double>(StringComparer.Ordinal);
            public List<Moment> Decisions = new List<Moment>();
            public IReadOnlyList<ActionRecord> Actions;
            public IReadOnlyList<WorldEvent> Events;
            public IReadOnlyDictionary<string, Mind> Minds;
            public TraceLog Trace;
            public string Fingerprint;

            /// <summary>Whether what happened stopped her doing what she was doing.</summary>
            public bool StoppedHer;

            public IEnumerable<Moment> Hers => Decisions.Where(d => d.Who == "mara");
            public Moment HerNext(int after) => Hers.FirstOrDefault(d => d.Minute > after);
            public IEnumerable<ActionRecord> HerActs => Actions.Where(a => a.CharacterId == "mara");

            /// <summary>Times somebody sat with her, and who.</summary>
            public List<WorldEvent> SatWithHer => Events.Where(e => e.Action == "comfort" && e.TargetId == "mara").ToList();
            public List<WorldEvent> HerDistressShowing => Events.Where(e => e.Action == "show_distress" && e.TargetId == "mara").ToList();
            public int SheComfortedDaniel => Actions.Count(a => a.CharacterId == "mara" && a.Action.Key == "comfort:daniel");
        }

        static readonly string[] Watched = { "tendency(daniel,treats_me_like_a_child)", "tendency(daniel,does_not_respect_me)" };

        static double Belief(Mind mind, string key)
        {
            var open = key.IndexOf('(');
            var predicate = key.Substring(0, open);
            var args = key.Substring(open + 1, key.Length - open - 2).Split(',').Select(a => a.Trim()).ToList();
            return mind.Beliefs.Confidence(predicate, args);
        }

        static Episode RunEpisode(string variant, ulong seed, string condition, int intrusionAt, int watchingAt)
        {
            var run = Scenario001.Prepare(_content, variant, seed);
            var ep = new Episode { Condition = condition, Variant = variant, Seed = seed };
            run.Morning.Decided = m =>
            {
                var d = m.Decision;
                var mo = new Moment
                {
                    Minute = m.Minute, Who = m.CharacterId, Chosen = d.Chosen.Key, Leading = d.Leading?.Key,
                    Ambiguous = d.Resolution == Resolution.Ambiguous,
                    Options = string.Join("; ", d.Considered.Take(4).Select(r => r.Option.Key + " " + r.Score.ToString("+0.000;-0.000", CultureInfo.InvariantCulture))),
                    Feelings = string.Join(", ", m.Mind.Emotions.Live.OrderByDescending(e => e.Intensity)
                        .Select(e => e.Type + (e.TargetId == null ? "" : ":" + e.TargetId) + " " + F(e.Intensity)))
                };
                foreach (var x in m.Motives) mo.Wants[x.Key] = x.Urgency;
                ep.Decisions.Add(mo);
            };

            for (var i = 0; i < _content.Morning.Minutes; i++)
            {
                run.Morning.Step();
                var now = run.World.Minute;
                var together = run.World.RoomOf("daniel") == run.World.RoomOf("mara");

                // In every condition, her beliefs are read at the same minute,
                // so that the three are comparable.
                if (now == intrusionAt && condition == Never)
                    foreach (var k in Watched) ep.BeliefsAfter[k] = Belief(run.Minds["mara"], k);

                if (now == intrusionAt && condition != Never)
                {
                    if (!together) { ep.Usable = false; ep.Why = "they were not in the same room at minute " + now; }
                    else
                    {
                        var room = run.World.RoomOf("daniel");
                        var inTheRoom = run.World.InRoom(room).Where(id => id != "daniel").ToList();
                        var witnesses = condition == Saw ? inTheRoom : inTheRoom.Where(id => id != "mara").ToList();
                        var outcome = run.Morning.Happen(Intrusion(_content.Morning.Day, now, witnesses));
                        ep.IntrusionAt = now;
                        ep.HerIntrusion = outcome.ByCharacter["mara"];
                        foreach (var k in Watched) ep.BeliefsAfter[k] = Belief(run.Minds["mara"], k);
                    }
                }

                if (now == watchingAt)
                {
                    if (!together) { ep.Usable = false; ep.Why = "they were not in the same room at minute " + now; }
                    else
                    {
                        var room = run.World.RoomOf("daniel");
                        var witnesses = run.World.InRoom(room).Where(id => id != "daniel").ToList();
                        var outcome = run.Morning.Happen(Watching(_content.Morning.Day, now, witnesses));
                        ep.WatchingAt = now;
                        ep.HerWatching = outcome.ByCharacter["mara"];
                    }
                }
            }

            ep.StoppedHer = run.Morning.Interruptions.Any(i => i.CharacterId == "mara" && i.EventId == "e-intrusion");
            ep.Actions = run.Result.Actions;
            ep.Events = run.Result.Events;
            ep.Minds = run.Minds;
            ep.Trace = run.Trace;
            ep.Fingerprint = string.Join("\n", ep.Actions.Select(a => a.ToString()));
            if (ep.BeliefsAfter.Count == 0) foreach (var k in Watched) ep.BeliefsAfter[k] = Belief(run.Minds["mara"], k);
            return ep;
        }

        /// <summary>The minutes at which the two moments can happen, found in an untouched morning.</summary>
        static (int Intrusion, int Watching) Moments(string variant, ulong seed)
        {
            var run = Scenario001.Prepare(_content, variant, seed);
            var intrusion = -1;
            var watching = -1;
            for (var i = 0; i < _content.Morning.Minutes; i++)
            {
                run.Morning.Step();
                var now = run.World.Minute;
                var together = run.World.RoomOf("daniel") == run.World.RoomOf("mara");
                if (together && intrusion < 0 && now >= IntrusionFrom) intrusion = now;
                if (together && watching < 0 && now >= EncounterFrom) watching = now;
            }
            return (intrusion, watching);
        }

        static string Reading(PerceptionOutcome o)
        {
            if (o == null) return "-";
            if (o.Access == Access.None) return "nothing reached her";
            return o.Meaning + " (" + F(o.InterpretationWeight) + ")" +
                   (o.RunnerUpMeaning == null ? "" : ", next " + o.RunnerUpMeaning) +
                   "; stirred " + (o.Emotions.Count == 0 ? "nothing" : string.Join(", ", o.Emotions.Select(e => e.Type + " " + F(e.Intensity))));
        }

        // ------------------------------------------------------------------ 1

        [Test, Timeout(1800000)]
        public void E1_TheEpisodeOnOneMorning()
        {
            var variant = "daniel_ate_it";
            ulong seed = 0;
            (int Intrusion, int Watching) at = (-1, -1);
            for (ulong s = 1; s <= (ulong)Seeds && seed == 0; s++)
            {
                var m = Moments(variant, s);
                if (m.Intrusion > 0 && m.Watching > 0) { seed = s; at = m; }
            }
            Assert.Greater(seed, 0UL, "some seed has them in the same room twice");

            var runs = Conditions.ToDictionary(c => c, c => RunEpisode(variant, seed, c, at.Intrusion, at.Watching));
            foreach (var r in runs.Values) Assert.IsTrue(r.Usable, r.Condition + ": " + r.Why);
            var a = runs[Saw];
            var c = runs[Missed];
            var b = runs[Never];

            var sb = new StringBuilder();
            sb.AppendLine("## 1. The episode, one morning, minute by minute");
            sb.AppendLine();
            sb.AppendLine("`" + variant + "`, seed " + seed + ". Daniel goes through Mara's things at minute " + at.Intrusion + " (**SETUP**) and watches her at minute " + at.Watching + " (**SETUP**). Both were put in at the first minute after " + IntrusionFrom + " and " + EncounterFrom + " at which the two of them were in the same room, found in an untouched morning.");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", Conditions) + " |");
            sb.AppendLine("|---|---|---|---|");
            sb.AppendLine("| **The intrusion**, as it reached her | " + Reading(a.HerIntrusion) + " | " + Reading(c.HerIntrusion) + " | it never happened |");
            foreach (var k in Watched)
                sb.AppendLine("| Her belief `" + k + "` just after | " + F(a.BeliefsAfter[k]) + " | " + F(c.BeliefsAfter[k]) + " | " + F(b.BeliefsAfter[k]) + " |");

            var afterIntrusion = Conditions.Select(x => runs[x].HerNext(at.Intrusion)).ToList();
            sb.AppendLine("| Her next decision | " + string.Join(" | ", afterIntrusion.Select(m => m == null ? "-" : "m" + m.Minute + " " + m.Chosen + " for " + (m.Leading ?? "nothing"))) + " |");
            sb.AppendLine("| What she was feeling there | " + string.Join(" | ", afterIntrusion.Select(m => m == null ? "-" : (m.Feelings.Length == 0 ? "nothing" : m.Feelings))) + " |");
            sb.AppendLine("| What she wanted there | " + string.Join(" | ", afterIntrusion.Select(m => m == null ? "-" : m.WantLine)) + " |");
            sb.AppendLine("| It stopped what she was doing | " + string.Join(" | ", Conditions.Select(x => runs[x].StoppedHer ? "yes" : "no")) + " |");
            sb.AppendLine("| Her distress showing, after it | " + string.Join(" | ", Conditions.Select(x => { var l = runs[x].HerDistressShowing.Where(e => e.Minute >= at.Intrusion).ToList(); return l.Count == 0 ? "never" : string.Join("; ", l.Take(2).Select(e => "m" + e.Minute + " seen by " + string.Join(", ", e.Witnesses))); })) + " |");
            sb.AppendLine("| Somebody sat with her, after it | " + string.Join(" | ", Conditions.Select(x => { var l = runs[x].SatWithHer.Where(e => e.Minute >= at.Intrusion).ToList(); return l.Count == 0 ? "nobody" : string.Join("; ", l.Select(e => "m" + e.Minute + " " + e.ActorId)); })) + " |");
            sb.AppendLine("| **The watching**, as it reached her | " + string.Join(" | ", Conditions.Select(x => Reading(runs[x].HerWatching))) + " |");

            var afterWatching = Conditions.Select(x => runs[x].HerNext(at.Watching)).ToList();
            sb.AppendLine("| Her next decision after that | " + string.Join(" | ", afterWatching.Select(m => m == null ? "-" : "m" + m.Minute + " " + m.Chosen + " for " + (m.Leading ?? "nothing"))) + " |");
            sb.AppendLine("| What she was feeling there | " + string.Join(" | ", afterWatching.Select(m => m == null ? "-" : (m.Feelings.Length == 0 ? "nothing" : m.Feelings))) + " |");
            sb.AppendLine("| What she wanted there | " + string.Join(" | ", afterWatching.Select(m => m == null ? "-" : m.WantLine)) + " |");
            sb.AppendLine("| Her acts over the morning | " + string.Join(" | ", Conditions.Select(x => string.Join(", ", runs[x].HerActs.GroupBy(r => r.Action.KindName).OrderByDescending(g => g.Count()).Select(g => g.Key + " " + g.Count())))) + " |");
            sb.AppendLine("| She sat with Daniel | " + string.Join(" | ", Conditions.Select(x => runs[x].SheComfortedDaniel.ToString())) + " |");
            sb.AppendLine("| Decisions differing from **A**, everybody, by order | - | " + Different(a, c) + " | " + Different(a, b) + " |");
            var dc = HerDivergence(a, c);
            var db = HerDivergence(a, b);
            sb.AppendLine("| **Her own** decisions differing from **A**, lined up by minute | - | " + dc.Differing + " of " + dc.Total + ", the last at minute " + dc.Last + " | " + db.Differing + " of " + db.Total + ", the last at minute " + db.Last + " |");
            sb.AppendLine();

            sb.AppendLine("**Where A and C part.** " + FirstParting(a, c));
            sb.AppendLine();
            sb.AppendLine("**Where A and B part.** " + FirstParting(a, b));
            sb.AppendLine();
            sb.AppendLine("**Mara herself, C against B** (she did not see it, against it never happening): " + (SameForMara(c, b) ? "the same, decision for decision, until somebody else's behaviour reaches her" : "different, see below") + ".");
            sb.AppendLine();

            // Her morning in A, in full, as the trace has it.
            sb.AppendLine("### Mara's morning in A, decision by decision");
            sb.AppendLine();
            sb.AppendLine("| Minute | She chose | For | Feeling | Wants at 0.10 or more |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var m in a.Hers)
                sb.AppendLine("| " + m.Minute + (m.Minute == a.IntrusionAt + 1 ? " (just after the intrusion)" : m.Minute == a.WatchingAt + 1 ? " (just after the watching)" : "") + " | " + m.Chosen + " | " + (m.Leading ?? "nothing") + " | " + (m.Feelings.Length == 0 ? "nothing" : m.Feelings) + " | " + string.Join(", ", m.Wants.Where(x => x.Value >= 0.1).OrderByDescending(x => x.Value).Select(x => x.Key + " " + F(x.Value))) + " |");
            sb.AppendLine();
            sb.AppendLine("### The same morning in C (she did not see it)");
            sb.AppendLine();
            sb.AppendLine("| Minute | She chose | For | Feeling |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var m in c.Hers)
                sb.AppendLine("| " + m.Minute + " | " + m.Chosen + " | " + (m.Leading ?? "nothing") + " | " + (m.Feelings.Length == 0 ? "nothing" : m.Feelings) + " |");
            Record("1", sb.ToString());

            Assert.AreEqual(Access.Witnessed, a.HerIntrusion.Access, "she was there for it in A");
            Assert.AreEqual(Access.None, c.HerIntrusion.Access, "and not in C");
        }

        /// <summary>
        /// Her own decisions, lined up by the minute she took them, since an
        /// event that stops somebody changes when they next decide as well as
        /// what they decide.
        /// </summary>
        static (int Differing, int Total, int Last) HerDivergence(Episode x, Episode y)
        {
            string Line(Moment m) => m == null ? "(no decision)" : m.Chosen + " for " + (m.Leading ?? "nothing");
            var a = x.Hers.ToDictionary(m => m.Minute, m => m);
            var b = y.Hers.ToDictionary(m => m.Minute, m => m);
            var minutes = a.Keys.Union(b.Keys).OrderBy(m => m).ToList();
            var differing = 0;
            var last = -1;
            foreach (var m in minutes)
            {
                a.TryGetValue(m, out var p);
                b.TryGetValue(m, out var q);
                if (Line(p) == Line(q)) continue;
                differing++;
                last = m;
            }
            return (differing, minutes.Count, last);
        }

        static string Different(Episode x, Episode y)
        {
            var n = 0;
            var p = x.Decisions.Select(d => d.Line).ToList();
            var q = y.Decisions.Select(d => d.Line).ToList();
            for (var i = 0; i < Math.Min(p.Count, q.Count); i++) if (p[i] != q[i]) n++;
            return (n + Math.Abs(p.Count - q.Count)) + " of " + p.Count;
        }

        static string FirstParting(Episode x, Episode y)
        {
            var p = x.Decisions.Select(d => d.Line).ToList();
            var q = y.Decisions.Select(d => d.Line).ToList();
            for (var i = 0; i < Math.Min(p.Count, q.Count); i++)
                if (p[i] != q[i]) return "at decision " + (i + 1) + ": `" + p[i] + "` against `" + q[i] + "`.";
            return "they never part.";
        }

        static bool SameForMara(Episode x, Episode y)
        {
            var p = x.Hers.Select(d => d.Line + " | " + d.Feelings).ToList();
            var q = y.Hers.Select(d => d.Line + " | " + d.Feelings).ToList();
            return p.SequenceEqual(q);
        }

        // ------------------------------------------------------------------ 2

        [Test, Timeout(1800000)]
        public void E2_TheSameEpisodeOverSeeds()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 2. The same episode over seeds and conditions");
            sb.AppendLine();
            sb.AppendLine("Seeds 1-" + Seeds + " of two conditions of the house: `daniel_ate_it`, in which Mara took nothing, and `mara_ate_it`, in which she is the one who took the can. A seed is used only if Daniel and Mara are in the same room at both moments, in every arm.");
            sb.AppendLine();

            foreach (var variant in new[] { "daniel_ate_it", "mara_ate_it" })
            {
                int usable = 0, readingDiffered = 0, weightDiffered = 0, feelingsDiffered = 0, wantsDiffered = 0,
                    actDiffered = 0, morningDiffered = 0, satWithHer = 0, satWithHerC = 0, showed = 0, showedC = 0,
                    sheSatWithDaniel = 0, sheSatWithDanielC = 0,
                    nowFeelings = 0, nowWants = 0, nowAct = 0, stopped = 0;
                var weights = new List<(double A, double C)>();
                var firstPartings = new List<string>();
                var rows = new List<string>();
                var gaps = new List<int>();
                var lasts = new List<int>();

                for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
                {
                    var at = Moments(variant, seed);
                    if (at.Intrusion < 0 || at.Watching < 0) continue;
                    var a = RunEpisode(variant, seed, Saw, at.Intrusion, at.Watching);
                    var c = RunEpisode(variant, seed, Missed, at.Intrusion, at.Watching);
                    if (!a.Usable || !c.Usable) continue;
                    usable++;

                    if (a.HerWatching != null && c.HerWatching != null)
                    {
                        if (a.HerWatching.Meaning != c.HerWatching.Meaning) readingDiffered++;
                        if (Math.Abs(a.HerWatching.InterpretationWeight - c.HerWatching.InterpretationWeight) > 1e-9) weightDiffered++;
                        weights.Add((a.HerWatching.InterpretationWeight, c.HerWatching.InterpretationWeight));
                    }

                    // Right after the intrusion.
                    var na = a.HerNext(at.Intrusion);
                    var nc = c.HerNext(at.Intrusion);
                    var nf = na != null && nc != null && na.Feelings != nc.Feelings;
                    var nw = na != null && nc != null && na.WantLine != nc.WantLine;
                    var nact = na != null && nc != null && (na.Chosen != nc.Chosen || na.Minute != nc.Minute);
                    if (a.StoppedHer) stopped++;
                    if (nf) nowFeelings++;
                    if (nw) nowWants++;
                    if (nact) nowAct++;

                    // An hour later, at the watching.
                    var ma = a.HerNext(at.Watching);
                    var mc = c.HerNext(at.Watching);
                    var lf = ma != null && mc != null && ma.Feelings != mc.Feelings;
                    var lw = ma != null && mc != null && ma.WantLine != mc.WantLine;
                    var lact = ma != null && mc != null && ma.Chosen != mc.Chosen;
                    if (lf) feelingsDiffered++;
                    if (lw) wantsDiffered++;
                    if (lact) actDiffered++;

                    var div = HerDivergence(a, c);
                    gaps.Add(at.Watching - at.Intrusion);
                    lasts.Add(div.Last);
                    rows.Add("| " + seed + " | " + at.Intrusion + " | " + at.Watching + " | " + (at.Watching - at.Intrusion) + " | " +
                             (nf ? "yes" : "no") + " | " + (nw ? "yes" : "no") + " | " + (nact ? "**yes**" : "no") + " | " +
                             (lf ? "yes" : "no") + " | " + (lw ? "yes" : "no") + " | " + (lact ? "**yes**" : "no") + " | " +
                             div.Differing + " of " + div.Total + " | " + (div.Last < 0 ? "-" : "m" + div.Last) + " |");
                    if (a.Fingerprint != c.Fingerprint)
                    {
                        morningDiffered++;
                        if (firstPartings.Count < 5) firstPartings.Add("seed " + seed + ", " + FirstParting(a, c));
                    }
                    if (a.SatWithHer.Any(e => e.Minute >= at.Intrusion)) satWithHer++;
                    if (c.SatWithHer.Any(e => e.Minute >= at.Intrusion)) satWithHerC++;
                    if (a.HerDistressShowing.Any(e => e.Minute >= at.Intrusion)) showed++;
                    if (c.HerDistressShowing.Any(e => e.Minute >= at.Intrusion)) showedC++;
                    sheSatWithDaniel += a.SheComfortedDaniel;
                    sheSatWithDanielC += c.SheComfortedDaniel;
                }

                sb.AppendLine("### " + variant);
                sb.AppendLine();
                sb.AppendLine("Seed by seed. \"Right after\" is her first decision after the intrusion; \"an hour later\" is her first decision after the watching. Her decisions are lined up by the minute she took them.");
                sb.AppendLine();
                sb.AppendLine("| Seed | Intrusion | Watching | Gap | Right after: feelings | wants | act | An hour later: feelings | wants | act | Her decisions differing | Last one |");
                sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|---|");
                foreach (var r in rows) sb.AppendLine(r);
                sb.AppendLine();
                sb.AppendLine("| | A (she saw it) | C (she did not) |");
                sb.AppendLine("|---|---|---|");
                sb.AppendLine("| Seeds used | " + usable + " of " + Seeds + " | |");
                sb.AppendLine("| Gap between the two moments (median) | " + (gaps.Count == 0 ? "-" : gaps.OrderBy(x => x).ElementAt(gaps.Count / 2) + " minutes") + " | |");
                sb.AppendLine("| **Right after the intrusion**: her feelings differed | **" + nowFeelings + " of " + usable + "** | |");
                sb.AppendLine("| ... her wants differed | **" + nowWants + " of " + usable + "** | |");
                sb.AppendLine("| ... what she did differed (the act, or the minute she next decided) | **" + nowAct + " of " + usable + "** | |");
                sb.AppendLine("| ... of which it stopped her doing what she was doing | " + stopped + " of " + usable + " | |");
                sb.AppendLine("| The last decision of hers that differs at all | " + (lasts.Count == 0 ? "-" : "median minute " + lasts.OrderBy(x => x).ElementAt(lasts.Count / 2)) + " | |");
                sb.AppendLine("| Her **reading** of the later watching differed | " + readingDiffered + " of " + usable + " | |");
                sb.AppendLine("| ... its **weight** differed | " + weightDiffered + " of " + usable + " | " + (weights.Count == 0 ? "" : "mean " + F(weights.Average(w => w.A)) + " against " + F(weights.Average(w => w.C))) + " |");
                sb.AppendLine("| Her **feelings** at the next decision differed | " + feelingsDiffered + " of " + usable + " | |");
                sb.AppendLine("| Her **wants** there differed | " + wantsDiffered + " of " + usable + " | |");
                sb.AppendLine("| The **act** she then chose differed | **" + actDiffered + " of " + usable + "** | |");
                sb.AppendLine("| Her **whole morning** differed | **" + morningDiffered + " of " + usable + "** | |");
                sb.AppendLine("| Her distress showed after the intrusion | " + showed + " of " + usable + " | " + showedC + " of " + usable + " |");
                sb.AppendLine("| Somebody sat with her after it | " + satWithHer + " of " + usable + " | " + satWithHerC + " of " + usable + " |");
                sb.AppendLine("| She sat with Daniel (total acts) | " + sheSatWithDaniel + " | " + sheSatWithDanielC + " |");
                sb.AppendLine();
                if (firstPartings.Count > 0)
                {
                    foreach (var f in firstPartings) sb.AppendLine("- " + f);
                    sb.AppendLine();
                }
            }
            Record("2", sb.ToString());
        }

        // ------------------------------------------------------------------ 3

        [Test, Timeout(1800000)]
        public void E3_NothingInjectedIsTheShippedMorning()
        {
            // The harness itself must change nothing: a morning stepped by hand
            // with no event put into it is the shipped morning.
            foreach (var variant in new[] { "daniel_ate_it", "mara_ate_it" })
            for (ulong seed = 1; seed <= 3; seed++)
            {
                var plain = Scenario001.Run(_content, variant, seed);
                var stepped = RunEpisode(variant, seed, Never, -1, -1);
                CollectionAssert.AreEqual(
                    plain.Result.Actions.Select(a => a.ToString()).ToArray(),
                    stepped.Actions.Select(a => a.ToString()).ToArray(),
                    variant + " seed " + seed);
            }

            var sb = new StringBuilder();
            sb.AppendLine("## 3. The harness changes nothing by itself");
            sb.AppendLine();
            sb.AppendLine("Six mornings stepped by hand with nothing put into them are the shipped mornings, act for act. The only differences measured above therefore come from the two events and from what the simulation made of them.");
            Record("3", sb.ToString());
        }
    }
}
