using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using Candidate = Fallow.Tests.Core.IntentionSelector.Candidate;
using Formed = Fallow.Tests.Core.IntentionSelector.Formed;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The intention-formation experiment: can a plausible intention be derived
    /// from an existing want and the person's circumstances, without a universal
    /// Want -> Intention table?
    ///
    /// Three things are kept apart throughout. The **want** is what a person is
    /// driven toward; the **intention** is what they take themselves to be
    /// accomplishing; the **act** is what they do. The previous experiment showed
    /// the third is independent of the second. This one tests whether the second
    /// is independent of the first.
    ///
    /// Everything hand-authored lives in `Data/Experiments/intentions.json`,
    /// which nothing in `Fallow.Core` loads. It was written blind, from the
    /// character sheets and the vocabulary, and committed before any case ran, so
    /// every case here is held out from authoring. There is no new code in
    /// `Fallow.Core`; the selector below is thirty lines over the shipped
    /// `ScalerEval` and the shipped `SituationCondition`, and it uses no
    /// randomness of any kind.
    ///
    /// Writes `Docs/experiments/intention-formation/measurements.md`.
    /// </summary>
    public class IntentionFormationExperimentTests
    {
        const int Seeds = 10;

        static Scenario001Content _content;
        static IReadOnlyList<Candidate> _candidates;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static readonly string[] People = { "daniel", "elena", "leo", "mara" };

        [OneTimeSetUp]
        public void Load()
        {
            _content = Baselines.Primary();
            _candidates = LoadCandidates(Path.Combine(TestPaths.DataRoot, "Experiments", "intentions.json"));
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Intention formation: measurements");
            sb.AppendLine();
            sb.AppendLine("Generated by `IntentionFormationExperimentTests` on the primary baseline. The candidate rules in `Assets/_Project/Data/Experiments/intentions.json` were authored blind and committed before any case here was run, so every case is held out from authoring. The selector has no randomness.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "intention-formation");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "measurements.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string Or(string s) => string.IsNullOrEmpty(s) ? "none" : s;
        static string Pc(double part, double whole)
            => whole == 0 ? "n/a" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + " %";

        // ============================================================ the mechanism

        // The candidate rules, the parser and the selector live in
        // `IntentionSelector`, shared with the generalization experiment so that
        // both run the same mechanism rather than two copies that could drift.

        static IReadOnlyList<Candidate> LoadCandidates(string path) => IntentionSelector.Load(path);

        static Formed Form(Mind mind, Percept percept, Motive motive, int today)
            => IntentionSelector.Form(
                _candidates, mind, percept, motive, today, _content.Rules.Deciding.RecallHalfLife);

        // ============================================================ probes

        /// <summary>
        /// A person as the scenario starts them: their real profile, their real
        /// seeded beliefs, and nothing that a morning has yet done to them.
        /// </summary>
        static Mind Fresh(string who)
        {
            var mind = new Mind(_content.Cast[who]);
            foreach (var s in _content.Cast[who].InitialBeliefs) mind.Beliefs.Seed(s);
            return mind;
        }

        sealed class Probe
        {
            public Scenario001Run Run;
            public Percept Base;
        }

        /// <summary>
        /// A real house and real people, taken at the top of the morning before
        /// anything has happened, so that a circumstance can be varied against a
        /// real background rather than an invented one.
        /// </summary>
        static Probe Stage()
        {
            var run = Scenario001.Prepare(_content, _content.Morning.Variants[0].Id, 1);
            return new Probe { Run = run, Base = run.Morning.See("daniel") };
        }

        static Percept In(Probe p, string who, string room, IReadOnlyList<string> present)
            => p.Run.Morning.See(who).Imagine(room, present, ActionCatalog.PantryTag);

        static Motive Want(string key, double urgency = 0.6, string target = null)
            => new Motive(key, target, urgency, new List<string>(), new List<ScalerTerm>());

        /// <summary>Every want that any candidate can serve, in a stable order.</summary>
        static IReadOnlyList<string> Wants
            => _candidates.SelectMany(c => c.Motives).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();

        // ============================================================ N1

        [Test]
        public void WhatIsAuthored()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## N1. The whole of the hand-authored surface");
            sb.AppendLine();
            sb.AppendLine("Counted from the file, not asserted. Every rule is listed; there is nothing else.");
            sb.AppendLine();
            sb.AppendLine("| Rule | Intention | Wants it is available to | Circumstance it needs | Base | Weighed by |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var c in _candidates)
                sb.AppendLine("| `" + c.Id + "` | `" + c.Intent + "` | " + string.Join(", ", c.Motives.Select(m => "`" + m + "`"))
                              + " | " + (c.When.IsEmpty ? "any" : Describe(c.When)) + " | " + F(c.Base)
                              + " | " + string.Join("; ", c.ScaledBy.Select(s => s.Describe() + " x " + F(s.Factor))) + " |");
            sb.AppendLine();
            sb.AppendLine("**" + _candidates.Count + " rules, " + _candidates.Select(c => c.Intent).Distinct().Count()
                          + " intentions, " + Wants.Count + " wants.**");
            sb.AppendLine();

            sb.AppendLine("The test that separates a constraint from a mapping: how many intentions each want can reach at all.");
            sb.AppendLine();
            sb.AppendLine("| Want | Intentions reachable | Which |");
            sb.AppendLine("|---|---|---|");
            var single = 0;
            foreach (var w in Wants)
            {
                var reach = _candidates.Where(c => c.Motives.Contains(w, StringComparer.Ordinal))
                    .Select(c => c.Intent).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();
                if (reach.Count < 2) single++;
                sb.AppendLine("| `" + w + "` | " + reach.Count + " | " + string.Join(", ", reach.Select(r => "`" + r + "`")) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**Wants with only one reachable intention (which would be a lookup table): " + single + ".**");
            sb.AppendLine();
            sb.AppendLine("And the other direction, which is what P5 asks about:");
            sb.AppendLine();
            sb.AppendLine("| Intention | Wants that can express it |");
            sb.AppendLine("|---|---|");
            foreach (var i in _candidates.Select(c => c.Intent).Distinct().OrderBy(s => s, StringComparer.Ordinal))
                sb.AppendLine("| `" + i + "` | " + string.Join(", ", _candidates.Where(c => c.Intent == i)
                    .SelectMany(c => c.Motives).Distinct().OrderBy(s => s, StringComparer.Ordinal)
                    .Select(m => "`" + m + "`")) + " |");
            sb.AppendLine();
            sb.AppendLine("A circumstance can gate a candidate but can never be the reason one beats another: `SituationCondition` has six fields and none of them is a trait, a value, a feeling or a need. That is the type, not a convention. Everything about the person is in the scalers, which the shipped `ScalerEval` evaluates.");
            Record("N1", sb.ToString());

            Assert.AreEqual(0, single, "a want with one reachable intention would be a lookup table");
            foreach (var c in _candidates)
            {
                Assert.IsTrue(_content.Vocabulary.Contains("self_meanings", c.Intent), c.Id + ": invented intention");
                foreach (var m in c.Motives)
                    Assert.IsTrue(_content.Vocabulary.Contains("motives", m), c.Id + ": invented want " + m);
                foreach (var s in c.ScaledBy)
                    Assert.Contains(s.Kind, ScalerKind.All.ToList(), c.Id + ": unknown scaler kind");
            }
        }

        static string Describe(SituationCondition w)
        {
            var parts = new List<string>();
            if (w.Alone.HasValue) parts.Add(w.Alone.Value ? "alone" : "not alone");
            if (w.OthersPresentMin.HasValue) parts.Add("at least " + w.OthersPresentMin.Value + " present");
            if (w.InOwnRoom.HasValue) parts.Add(w.InOwnRoom.Value ? "in my own room" : "not in my own room");
            if (w.InSomebodyElsesRoom.HasValue) parts.Add(w.InSomebodyElsesRoom.Value ? "in somebody else's room" : "not in somebody else's room");
            if (w.RoomHoldsFood.HasValue) parts.Add(w.RoomHoldsFood.Value ? "food is kept here" : "no food here");
            if (w.SearchedThisRoomMyself.HasValue) parts.Add(w.SearchedThisRoomMyself.Value ? "I have searched here" : "I have not searched here");
            return string.Join(", ", parts);
        }

        // ============================================================ N2

        [Test]
        public void SameWantDifferentContext()
        {
            var p = Stage();
            var kitchen = "kitchen";
            var alone = new List<string>();
            var company = new List<string> { "elena", "leo", "mara" };

            var sb = new StringBuilder();
            sb.AppendLine("## N2. The same want, in company and alone");
            sb.AppendLine();
            sb.AppendLine("One person, one want, one room, one moment. The only difference is whether anybody else is standing there. Nothing about the person changes between the two columns.");
            sb.AppendLine();

            var moved = 0;
            var pairs = 0;
            foreach (var who in People)
            {
                var mind = Fresh(who);
                sb.AppendLine("### " + who);
                sb.AppendLine();
                sb.AppendLine("| Want | With the others in the room | Alone | Changed |");
                sb.AppendLine("|---|---|---|---|");
                foreach (var want in Wants)
                {
                    var target = want == "look_after" ? (who == "elena" ? "mara" : "elena") : null;
                    var withThem = Form(mind, In(p, who, kitchen, company), Want(want, 0.6, target), _content.Morning.Day);
                    var byHimself = Form(mind, In(p, who, kitchen, alone), Want(want, 0.6, target), _content.Morning.Day);
                    pairs++;
                    var changed = withThem.Intent != byHimself.Intent;
                    if (changed) moved++;
                    sb.AppendLine("| `" + want + "` | " + withThem.Line + " | " + byHimself.Line + " | "
                                  + (changed ? "**yes**" : "no") + " |");
                }
                sb.AppendLine();
            }

            sb.AppendLine("**" + moved + " of " + pairs + " (person, want) pairs formed a different intention with an audience than without one.**");
            sb.AppendLine();
            sb.AppendLine("The want is identical in both columns, and so is everything about the person. Where the intention moved, the only thing that moved it was who else was in the room.");
            Record("N2", sb.ToString());

            Assert.Greater(moved, 0, "P1/P2: context must be able to change the intention");
        }

        // ============================================================ N3

        [Test]
        public void SamePlaceSameWantDifferentPeople()
        {
            var p = Stage();
            var company = new List<string> { "daniel", "elena", "leo", "mara" };

            var sb = new StringBuilder();
            sb.AppendLine("## N3. The same want, the same room, four different people");
            sb.AppendLine();
            sb.AppendLine("Everything circumstantial is held identical: the same room, the same company, the same minute, the same urgency. Only the person differs, and they differ only by what the shipped character sheets say they are.");
            sb.AppendLine();
            sb.AppendLine("| Want | daniel | elena | leo | mara | Distinct |");
            sb.AppendLine("|---|---|---|---|---|---|");

            var disagreed = 0;
            foreach (var want in Wants)
            {
                var cells = new List<string>();
                var chosen = new List<string>();
                foreach (var who in People)
                {
                    var others = company.Where(x => x != who).ToList();
                    var target = want == "look_after" ? others[0] : null;
                    var f = Form(Fresh(who), In(p, who, "kitchen", others), Want(want, 0.6, target), _content.Morning.Day);
                    cells.Add(f.Line);
                    chosen.Add(Or(f.Intent));
                }
                var distinct = chosen.Distinct().Count();
                if (distinct > 1) disagreed++;
                sb.AppendLine("| `" + want + "` | " + string.Join(" | ", cells) + " | " + distinct + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**Wants on which the four disagreed: " + disagreed + " of " + Wants.Count + ".**");
            sb.AppendLine();

            sb.AppendLine("### Why they disagree, taken apart");
            sb.AppendLine();
            sb.AppendLine("`restore_standing` in company, every candidate and every term:");
            sb.AppendLine();
            foreach (var who in People)
            {
                var others = company.Where(x => x != who).ToList();
                var f = Form(Fresh(who), In(p, who, "kitchen", others), Want("restore_standing"), _content.Morning.Day);
                sb.AppendLine("**" + who + "** -> `" + Or(f.Intent) + "`");
                sb.AppendLine();
                foreach (var w in f.Considered)
                {
                    sb.AppendLine("- `" + w.Intent + "` " + F(w.Weight) + " from " + string.Join(", ", w.Rules));
                    foreach (var why in w.Why) sb.AppendLine("  - " + why);
                }
                sb.AppendLine();
            }
            Record("N3", sb.ToString());

            Assert.Greater(disagreed, 0, "P3: the person must be able to change the intention");
        }

        // ============================================================ N4

        [Test]
        public void CounterfactualSensitivity()
        {
            var p = Stage();
            var sb = new StringBuilder();
            sb.AppendLine("## N4. What moves it and what does not");
            sb.AppendLine();
            sb.AppendLine("Three perturbations against the same baseline moment. Two of them change something a rule reads; one changes something no rule in the file reads at all.");
            sb.AppendLine();
            sb.AppendLine("| Person | Want | Baseline (alone, kitchen) | +company (read) | in her own room (read by no rule here) | hungry (read by no rule here) |");
            sb.AppendLine("|---|---|---|---|---|---|");

            var relevantMoved = 0;
            var irrelevantMoved = 0;
            var cells = 0;
            foreach (var who in People)
            foreach (var want in Wants)
            {
                var mind = Fresh(who);
                var day = _content.Morning.Day;
                var here = In(p, who, "kitchen", new List<string>());
                var basis = Form(mind, here, Want(want), day);

                var withCompany = Form(mind, In(p, who, "kitchen", new List<string> { "elena", "leo" }), Want(want), day);

                // The same room and the same company; only a circumstance no rule
                // in the file asks about is different.
                var elsewhere = In(p, who, p.Run.World.House.Rooms.Select(r => r.Id)
                    .FirstOrDefault(r => r != "kitchen") ?? "kitchen", new List<string>());
                var moved = Form(mind, elsewhere, Want(want), day);

                var hungry = Form(mind, Starving(here), Want(want), day);

                cells++;
                if (basis.Intent != withCompany.Intent) relevantMoved++;
                if (basis.Intent != hungry.Intent) irrelevantMoved++;

                sb.AppendLine("| " + who + " | `" + want + "` | " + basis.Line + " | " + withCompany.Line
                              + " | " + moved.Line + " | " + hungry.Line + " |");
            }
            sb.AppendLine();
            sb.AppendLine("| | Count | Share of " + cells + " |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Adding company changed the intention | " + relevantMoved + " | " + Pc(relevantMoved, cells) + " |");
            sb.AppendLine("| Making them hungry changed the intention | **" + irrelevantMoved + "** | " + Pc(irrelevantMoved, cells) + " |");
            sb.AppendLine();
            sb.AppendLine("Hunger is a real scaler kind that the shipped motivation rules use heavily. No rule in the candidate file reads it, and the measurement confirms it never moves an intention. Moving the person to another room changes the room and the tags on it; the column is there so that a circumstance which *is* structurally available but unread by these rules can be seen not to matter either, except where being in a different room changes who is present.");
            Record("N4", sb.ToString());

            Assert.AreEqual(0, irrelevantMoved, "P9: a circumstance no rule reads must never change the intention");
            Assert.Greater(relevantMoved, 0, "P9: a circumstance the rules do read must sometimes change it");
        }

        static Percept Starving(Percept p)
            => new Percept(p.CharacterId, p.Minute, p.Room, p.Present, p.Adjacent, 1.0,
                p.RoomHoldsFood, p.FoodWithinReach, p.SearchedThisRoomMyself, null,
                p.LookedInThePantryMyself, p.JustWatched, p.RoomsIHaveSearched);

        // ============================================================ N5

        [Test]
        public void SameStateSameIntention()
        {
            var p = Stage();
            var sb = new StringBuilder();
            sb.AppendLine("## N5. Reproducibility");
            sb.AppendLine();
            sb.AppendLine("The selector draws no random number, so this should be exact rather than probable.");
            sb.AppendLine();

            var repeats = 0;
            var stable = 0;
            foreach (var who in People)
            foreach (var want in Wants)
            {
                var first = Form(Fresh(who), In(p, who, "kitchen", new List<string> { "leo" }), Want(want), _content.Morning.Day);
                for (var i = 0; i < 5; i++)
                {
                    var again = Form(Fresh(who), In(p, who, "kitchen", new List<string> { "leo" }), Want(want), _content.Morning.Day);
                    repeats++;
                    if (again.Intent == first.Intent && Math.Abs(again.Weight - first.Weight) < 1e-12) stable++;
                    Assert.AreEqual(first.Intent, again.Intent, who + " " + want);
                }
            }
            sb.AppendLine("**" + stable + " of " + repeats + " replays identical**, intention and weight, to full precision.");
            sb.AppendLine();

            // And a whole morning, replayed with the selector installed.
            var a = RunWithSelector("replay 1", _content.Morning.Variants[0].Id, 1);
            var b = RunWithSelector("replay 2", _content.Morning.Variants[0].Id, 1);
            sb.AppendLine("A whole morning run twice with the selector installed: "
                          + (a.Fingerprint == b.Fingerprint ? "**identical**" : "**differs**")
                          + ", and the intentions formed: " + (a.IntentLine == b.IntentLine ? "**identical**" : "**differ**") + ".");
            Record("N5", sb.ToString());

            Assert.AreEqual(a.Fingerprint, b.Fingerprint);
            Assert.AreEqual(a.IntentLine, b.IntentLine);
        }

        // ============================================================ live mornings

        sealed class Act
        {
            public string Variant;
            public ulong Seed;
            public int Minute;
            public string Who;
            public string Want;
            public string WantTarget;
            public double Urgency;
            public string Action;
            public string Target;
            public string Destination;
            public Formed Formed;
            public string Competing;
            public string Beliefs;
            public string Feelings;
            public string Memories;
            public string Room;
            public double Answerable;
            public IReadOnlyList<string> Present;
        }

        sealed class MorningRun
        {
            public string Fingerprint;
            public string IntentLine;
            public List<Act> Acts = new List<Act>();
            public IReadOnlyList<WorldEvent> Events;
        }

        /// <summary>
        /// A whole morning with the selector installed on the intent hook. The
        /// intention is formed from the circumstances at the moment the person
        /// decided, not the moment the act finished, because that is when a
        /// person forms one.
        /// </summary>
        static MorningRun RunWithSelector(string label, string variant, ulong seed, bool install = true)
        {
            var run = Scenario001.Prepare(_content, variant, seed);
            var m = new MorningRun();
            var atDecision = new Dictionary<int, Act>();

            run.Morning.Decided = moment =>
            {
                var d = moment.Decision;
                var leading = d.Leading;
                var act = new Act
                {
                    Variant = variant,
                    Seed = seed,
                    Minute = moment.Minute,
                    Who = moment.CharacterId,
                    Want = leading?.Name,
                    WantTarget = leading?.TargetId,
                    Urgency = leading?.Urgency ?? 0.0,
                    Action = d.Chosen.Key,
                    Target = d.Chosen.TargetId,
                    Destination = d.Chosen.DestinationRoomId,
                    Room = moment.Percept.Room?.Id,
                    Answerable = moment.Mind.Beliefs.Confidence("answerable_for", new[] { moment.CharacterId, "missing_can" }),
                    Present = moment.Percept.Present.OrderBy(x => x, StringComparer.Ordinal).ToList(),
                    Competing = string.Join(", ", moment.Motives.OrderByDescending(x => x.Urgency)
                        .ThenBy(x => x.Key, StringComparer.Ordinal).Take(4)
                        .Select(x => x.Key + " " + F(x.Urgency))),
                    Beliefs = string.Join(", ", moment.Mind.Beliefs.All.Where(b => b.Confidence > 0.0)
                        .Select(b => b.Key + " " + F(b.Confidence))),
                    Feelings = string.Join(", ", moment.Mind.Emotions.Live.OrderByDescending(e => e.Intensity)
                        .Take(3).Select(e => e.Type + (e.TargetId == null ? "" : ":" + e.TargetId) + " " + F(e.Intensity))),
                    Memories = string.Join(", ", moment.Mind.Experiences
                        .Where(x => x.Day == _content.Morning.Day).Reverse().Take(3)
                        .Select(x => "m" + x.Minute + " " + x.Meaning))
                };
                act.Formed = leading == null
                    ? new Formed()
                    : Form(moment.Mind, moment.Percept, leading, _content.Morning.Day);
                atDecision[d.TraceId] = act;
                m.Acts.Add(act);
            };

            if (install)
                run.Morning.IntentOfAct = (who, action, decision) =>
                    decision != null && atDecision.TryGetValue(decision.TraceId, out var a) ? a.Formed.Intent : null;

            run.Morning.Run(_content.Morning.Minutes);
            m.Events = run.Result.Events;
            m.Fingerprint = string.Join("\n", run.Result.Actions.Select(x =>
                x.ToString() + " | " + x.Resolution + " " + x.Margin.ToString("R", CultureInfo.InvariantCulture)));
            m.IntentLine = string.Join("\n", m.Acts.Select(x => x.Minute + " " + x.Who + " " + Or(x.Want) + (x.WantTarget == null ? "" : ":" + x.WantTarget) + " -> " + Or(x.Formed.Intent)));
            return m;
        }

        static string BaselineFingerprint(string variant, ulong seed)
        {
            var run = Scenario001.Prepare(_content, variant, seed);
            run.Morning.Run(_content.Morning.Minutes);
            return string.Join("\n", run.Result.Actions.Select(x =>
                x.ToString() + " | " + x.Resolution + " " + x.Margin.ToString("R", CultureInfo.InvariantCulture)));
        }

        // ============================================================ N6

        [Test]
        [Timeout(600000)]
        public void FiftyHeldOutMornings()
        {
            var acts = new List<Act>();
            var runs = new List<MorningRun>();
            foreach (var v in _content.Morning.Variants.Select(x => x.Id))
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var m = RunWithSelector("live", v, seed);
                runs.Add(m);
                acts.AddRange(m.Acts);
            }

            var sb = new StringBuilder();
            sb.AppendLine("## N6. Fifty mornings, all of them held out from authoring");
            sb.AppendLine();
            sb.AppendLine("The candidate rules were committed before any of this ran. Every decision below is a case the rules were not written against.");
            sb.AppendLine();
            sb.AppendLine("**" + acts.Count + " decisions across " + runs.Count + " mornings.**");
            sb.AppendLine();

            var withWant = acts.Where(a => a.Want != null && a.Want != "nothing pressing").ToList();
            var withIntent = withWant.Where(a => a.Formed.Intent != null).ToList();
            sb.AppendLine("| | Count | Share |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Decisions with a leading want | " + withWant.Count + " | " + Pc(withWant.Count, acts.Count) + " |");
            sb.AppendLine("| ...that formed an intention | " + withIntent.Count + " | " + Pc(withIntent.Count, withWant.Count) + " |");
            sb.AppendLine("| ...that formed none | " + (withWant.Count - withIntent.Count) + " | " + Pc(withWant.Count - withIntent.Count, withWant.Count) + " |");
            sb.AppendLine();

            sb.AppendLine("### What each want turned into");
            sb.AppendLine();
            sb.AppendLine("| Want | Decisions | Distinct intentions | Distribution |");
            sb.AppendLine("|---|---|---|---|");
            var singleValued = new List<string>();
            foreach (var g in withWant.GroupBy(a => a.Want).OrderByDescending(g => g.Count()))
            {
                var dist = g.GroupBy(a => Or(a.Formed.Intent)).OrderByDescending(x => x.Count())
                    .ThenBy(x => x.Key, StringComparer.Ordinal).ToList();
                var distinct = dist.Count(x => x.Key != "none");
                if (distinct <= 1) singleValued.Add(g.Key);
                sb.AppendLine("| `" + g.Key + "` | " + g.Count() + " | " + distinct + " | "
                              + string.Join(", ", dist.Select(x => "`" + x.Key + "` " + x.Count() + " (" + Pc(x.Count(), g.Count()) + ")")) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**Wants that produced more than one intention in practice: "
                          + withWant.GroupBy(a => a.Want).Count(g => g.Select(a => a.Formed.Intent).Where(i => i != null).Distinct().Count() > 1)
                          + " of " + withWant.GroupBy(a => a.Want).Count() + ".** "
                          + (singleValued.Count == 0 ? "None was single-valued." : "Single-valued in practice: " + string.Join(", ", singleValued.Select(s => "`" + s + "`")) + "."));
            sb.AppendLine();

            sb.AppendLine("### The same want, split by who wanted it");
            sb.AppendLine();
            sb.AppendLine("| Want | daniel | elena | leo | mara |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var g in withWant.GroupBy(a => a.Want).OrderByDescending(g => g.Count()))
            {
                var cells = People.Select(who =>
                {
                    var mine = g.Where(a => a.Who == who).ToList();
                    if (mine.Count == 0) return "-";
                    return string.Join(", ", mine.GroupBy(a => Or(a.Formed.Intent)).OrderByDescending(x => x.Count())
                        .Select(x => x.Key + " " + x.Count()));
                });
                sb.AppendLine("| `" + g.Key + "` | " + string.Join(" | ", cells) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### The same act, carrying different intentions");
            sb.AppendLine();
            sb.AppendLine("| Physical action | Times chosen | Wants behind it | Distinct intentions | Which |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var g in withWant.GroupBy(a => a.Action).OrderByDescending(g => g.Count()))
            {
                var intents = g.Select(a => a.Formed.Intent).Where(i => i != null).Distinct()
                    .OrderBy(s => s, StringComparer.Ordinal).ToList();
                sb.AppendLine("| `" + g.Key + "` | " + g.Count() + " | " + g.Select(a => a.Want).Distinct().Count()
                              + " | " + intents.Count + " | " + (intents.Count == 0 ? "-" : string.Join(", ", intents.Select(i => "`" + i + "`"))) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### Intentions reached from more than one want");
            sb.AppendLine();
            sb.AppendLine("| Intention | Times formed | Wants it came from |");
            sb.AppendLine("|---|---|---|");
            var many = 0;
            foreach (var g in withIntent.GroupBy(a => a.Formed.Intent).OrderByDescending(g => g.Count()))
            {
                var from = g.Select(a => a.Want).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();
                if (from.Count > 1) many++;
                sb.AppendLine("| `" + g.Key + "` | " + g.Count() + " | " + from.Count + ": " + string.Join(", ", from.Select(f => "`" + f + "`")) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**Intentions reached from more than one want: " + many + ".**");
            sb.AppendLine();

            sb.AppendLine("### Is the belief doing the work, or the rule");
            sb.AppendLine();
            sb.AppendLine("`took_what_was_not_mine` is the one intention whose heaviest scaler is a belief: that I am answerable for the missing can. If the belief is carrying it, only people who hold that belief should form it. If the rule's other terms were carrying it, innocent people would form it too. This is measurable rather than arguable.");
            sb.AppendLine();
            var guilt = withIntent.Where(a => a.Formed.Intent == "took_what_was_not_mine").ToList();
            var innocent = guilt.Count(a => a.Answerable <= 0.0);
            sb.AppendLine("| | Value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Times `took_what_was_not_mine` was formed | " + guilt.Count + " |");
            sb.AppendLine("| ...by somebody who believes they are answerable | " + (guilt.Count - innocent) + " |");
            sb.AppendLine("| ...**by somebody who holds no such belief at all** | **" + innocent + "** |");
            if (guilt.Count > 0)
            {
                sb.AppendLine("| Lowest belief among those who formed it | " + F(guilt.Min(a => a.Answerable)) + " |");
                sb.AppendLine("| Highest | " + F(guilt.Max(a => a.Answerable)) + " |");
            }
            sb.AppendLine();
            var couldHave = withWant.Where(a => a.Want == "get_food" || a.Want == "avoid_exposure").ToList();
            sb.AppendLine("Of the " + couldHave.Count + " decisions where that intention was even reachable, "
                          + couldHave.Count(a => a.Answerable > 0.0) + " were taken by somebody who believes they are answerable, and "
                          + couldHave.Count(a => a.Answerable > 0.0 && a.Formed.Intent == "took_what_was_not_mine")
                          + " of those formed it.");
            sb.AppendLine();

            sb.AppendLine("### How close the competition was");
            sb.AppendLine();
            var contested = withIntent.Count(a => a.Formed.RunnerUp != null);
            var close = withIntent.Count(a => a.Formed.RunnerUp != null && a.Formed.Margin < 0.10);
            sb.AppendLine("| | Count | Share of " + withIntent.Count + " |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Formations with a runner-up at all | " + contested + " | " + Pc(contested, withIntent.Count) + " |");
            sb.AppendLine("| ...decided by less than 0.10 | " + close + " | " + Pc(close, withIntent.Count) + " |");
            sb.AppendLine();
            sb.AppendLine("A mechanism whose winner is never contested is a table with extra steps. One whose winner is usually a coin-flip is noise. This is neither.");
            sb.AppendLine();

            sb.AppendLine("### Eight traces, taken in order from the first morning");
            sb.AppendLine();
            foreach (var a in runs[0].Acts.Where(x => x.Formed.Intent != null).Take(8))
            {
                sb.AppendLine("```");
                sb.AppendLine("m" + a.Minute + "  " + a.Who + " in " + Or(a.Room)
                              + " with " + (a.Present.Count == 0 ? "nobody" : string.Join(", ", a.Present)));
                sb.AppendLine("  want        " + Or(a.Want) + (a.WantTarget == null ? "" : " about " + a.WantTarget) + " at urgency " + F(a.Urgency));
                sb.AppendLine("  competing   " + Or(a.Competing));
                sb.AppendLine("  beliefs     " + Or(a.Beliefs));
                sb.AppendLine("  feelings    " + Or(a.Feelings));
                sb.AppendLine("  memories    " + Or(a.Memories));
                sb.AppendLine("  act         " + a.Action + (a.Target == null ? "" : " -> " + a.Target)
                              + (a.Destination == null ? "" : " -> " + a.Destination));
                sb.AppendLine("  candidates  " + string.Join("; ", a.Formed.Considered.Select(w => w.Long)));
                foreach (var w in a.Formed.Considered)
                foreach (var why in w.Why)
                    sb.AppendLine("      " + w.Intent + ": " + why);
                sb.AppendLine("  INTENTION   " + a.Formed.Intent + " by " + F(a.Formed.Margin) + " over " + Or(a.Formed.RunnerUp));
                sb.AppendLine("```");
                sb.AppendLine();
            }
            Record("N6", sb.ToString());

            Assert.Greater(withIntent.Count, 0, "P10: the rules must produce something on held-out cases");
            Assert.Greater(withWant.GroupBy(a => a.Want)
                .Count(g => g.Select(a => a.Formed.Intent).Where(i => i != null).Distinct().Count() > 1), 1,
                "P7: at least two wants must be many-valued in practice");
        }

        // ============================================================ N7

        [Test]
        [Timeout(600000)]
        public void TheControls()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## N7. Controls");
            sb.AppendLine();
            sb.AppendLine("The selector must be able to be taken away without trace, or nothing measured above is attributable to it.");
            sb.AppendLine();
            sb.AppendLine("| Condition | Seed | Selector off | Selector installed, returning null | Selector installed and forming |");
            sb.AppendLine("|---|---|---|---|---|");

            var offSame = 0;
            var nullSame = 0;
            var formedDiffered = 0;
            var total = 0;
            foreach (var v in _content.Morning.Variants.Select(x => x.Id))
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var baseline = BaselineFingerprint(v, seed);
                var off = RunWithSelector("off", v, seed, install: false);
                var nulled = NullSelector(v, seed);
                var on = RunWithSelector("on", v, seed);

                total++;
                if (off.Fingerprint == baseline) offSame++;
                if (nulled == baseline) nullSame++;
                if (on.Fingerprint != baseline) formedDiffered++;

                if (off.Fingerprint != baseline || nulled != baseline || seed == 1)
                    sb.AppendLine("| `" + v + "` | " + seed + " | " + (off.Fingerprint == baseline ? "identical" : "**differs**")
                                  + " | " + (nulled == baseline ? "identical" : "**differs**")
                                  + " | " + (on.Fingerprint == baseline ? "identical" : "differs") + " |");

                Assert.AreEqual(baseline, off.Fingerprint, v + " " + seed + ": C1");
                Assert.AreEqual(baseline, nulled, v + " " + seed + ": C2");
            }
            sb.AppendLine();
            sb.AppendLine("| | Count | Share |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| C1: selector off reproduces the shipped baseline | " + offSame + " of " + total + " | " + Pc(offSame, total) + " |");
            sb.AppendLine("| C2: selector installed but returning null does too | " + nullSame + " of " + total + " | " + Pc(nullSame, total) + " |");
            sb.AppendLine("| Mornings the formed intentions changed | " + formedDiffered + " of " + total + " | " + Pc(formedDiffered, total) + " |");
            sb.AppendLine();
            sb.AppendLine("The last row is not a control but a consequence: it is how often intentions formed by this mechanism, and read by the three shipped appraisal rules that read any intention at all, went on to change what somebody did.");
            Record("N7", sb.ToString());
        }

        static string NullSelector(string variant, ulong seed)
        {
            var run = Scenario001.Prepare(_content, variant, seed);
            run.Morning.IntentOfAct = (who, action, decision) => null;
            run.Morning.Run(_content.Morning.Minutes);
            return string.Join("\n", run.Result.Actions.Select(x =>
                x.ToString() + " | " + x.Resolution + " " + x.Margin.ToString("R", CultureInfo.InvariantCulture)));
        }
    }
}
