using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using Candidate = Fallow.Tests.Core.IntentionSelector.Candidate;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// What must an intention-selection mechanism satisfy to be a causal
    /// mechanism rather than a numerical ranking, and which of those properties
    /// does the current one have?
    ///
    /// The ten candidate rules stay frozen and hashed, and `IntentionSelector`
    /// is not touched. The selector is taken apart into the five stages it
    /// already has, so that they can be measured separately:
    ///
    ///   availability   a rule lists the want               (the want)
    ///   compatibility  its `when` matches the moment        (the circumstance)
    ///   support        base + factor x level, by ScalerEval (the person)
    ///   preference     an intention's score from its rules  (the aggregation)
    ///   selection      the highest score, ties by name      (the alphabet)
    ///
    /// Every alternative rule set is built in memory, and every alternative
    /// aggregator is a pure function in this file and nowhere else. They are
    /// instruments for asking which invariants a way of ranking keeps, not
    /// candidates for production, and none of them has a parameter to tune.
    ///
    /// No production change of any kind. Writes
    /// `Docs/experiments/intention-ranking/measurements.md`.
    /// </summary>
    public class IntentionRankingExperimentTests
    {
        const string FrozenSha = "61e6412e8a7cb77674f0c7685e4cb0e5f7dca5db3ad05f928a63f34dfb099d92";

        /// <summary>Two scores closer than this are a tie in the real numbers, whatever the floating point says.</summary>
        const double Tie = 1e-9;

        static Scenario001Content _content;
        static IReadOnlyList<Candidate> _rules;
        static string _rulePath;
        static RoomGraph _house;
        static string _kitchen;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static readonly string[] Wants =
            { "avoid_exposure", "find_out", "get_food", "guard_supplies", "keep_peace", "look_after", "restore_standing" };
        static readonly string[] Circumstances = { "in company", "alone" };

        // The sweep, rebuilt exactly as the generalization experiment builds it.
        static List<string> _sweepTraits;
        static List<double> _levels;
        static List<string> _ring;
        static List<List<BeliefSeed>> _beliefSets;
        static Mind[] _minds;
        static Percept[] _company;
        static Percept[] _alone;

        [OneTimeSetUp]
        public void Load()
        {
            _content = Baselines.Primary();
            _rulePath = Path.Combine(TestPaths.DataRoot, "Experiments", "intentions.json");
            _rules = IntentionSelector.Load(_rulePath);

            var root = JObject.Parse(File.ReadAllText(Path.Combine(TestPaths.DataRoot, "Experiments", "held-out-people.json")));
            var s = (JObject)root["sweep"];
            _sweepTraits = ((JArray)s["traits"]).Select(x => x.Value<string>()).ToList();
            _levels = ((JArray)s["levels"]).Select(x => x.Value<double>()).ToList();
            _ring = ((JArray)s["value_ring"]).Select(x => x.Value<string>()).ToList();
            _beliefSets = ((JArray)s["belief_sets"]).Select(set => ((JArray)set).Select(b => new BeliefSeed(
                b["predicate"].Value<string>(),
                ((JArray)b["args"]).Select(a => a.Value<string>()).ToList(),
                b["confidence"].Value<double>())).ToList()).ToList();

            var run = Scenario001.Prepare(_content, _content.Morning.Variants[0].Id, 1);
            _house = run.World.House;
            _kitchen = _house.Rooms.First(r => r.HasTag(ActionCatalog.PantryTag)).Id;

            var n = (int)Math.Pow(_levels.Count, _sweepTraits.Count);
            _minds = new Mind[n];
            _company = new Percept[n];
            _alone = new Percept[n];
            for (var i = 0; i < n; i++)
            {
                _minds[i] = SweepMind(i);
                _company[i] = At(_minds[i].Id, Others);
                _alone[i] = At(_minds[i].Id, Nobody);
            }
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Intention ranking: measurements");
            sb.AppendLine();
            sb.AppendLine("Generated by `IntentionRankingExperimentTests` against the frozen candidate rules, whose hash is checked at the start and the end of the run. The predictions, the transformations and the aggregators were committed before this fixture existed. There is no randomness anywhere.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "intention-ranking");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "measurements.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string Or(string s) => string.IsNullOrEmpty(s) ? "none" : s;
        static string Pc(double part, double whole)
            => whole == 0 ? "n/a" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + " %";

        static string Sha(string path)
        {
            using (var sha = SHA256.Create())
                return string.Concat(sha.ComputeHash(File.ReadAllBytes(path)).Select(b => b.ToString("x2")));
        }

        // ============================================================ people and moments

        static Mind Person(string id, IReadOnlyDictionary<string, double> traits,
            IReadOnlyList<string> values, IReadOnlyList<BeliefSeed> beliefs)
        {
            var profile = new Profile(id, id, 30, "sibling", traits, values, 0.5,
                new Dictionary<string, double>(), new List<BeliefSeed>());
            var mind = new Mind(profile);
            foreach (var b in beliefs ?? new List<BeliefSeed>())
                mind.Beliefs.Seed(new BeliefSeed(
                    b.Predicate, b.Args.Select(a => a == "$self" ? id : a).ToList(), b.Confidence));
            return mind;
        }

        /// <summary>
        /// Profile i of the sweep: traits are the base-3 digits of i, values are
        /// the ring rotated by i, beliefs are set (i mod 4). The same function as
        /// in the generalization experiment, and checked against its numbers.
        /// </summary>
        static Mind SweepMind(int i)
        {
            var traits = new Dictionary<string, double>(StringComparer.Ordinal);
            var n = i;
            foreach (var name in _sweepTraits)
            {
                traits[name] = _levels[n % _levels.Count];
                n /= _levels.Count;
            }
            var shift = i % _ring.Count;
            var values = _ring.Skip(shift).Concat(_ring.Take(shift)).ToList();
            return Person("p" + i, traits, values, _beliefSets[i % _beliefSets.Count]);
        }

        static Dictionary<string, double> TraitsOf(Mind m)
            => _sweepTraits.ToDictionary(t => t, t => m.Profile.Trait(t), StringComparer.Ordinal);

        static List<BeliefSeed> Seeds(Mind m)
            => m.Beliefs.All.Select(b => new BeliefSeed(b.Predicate, b.Args, b.Confidence)).ToList();

        static readonly IReadOnlyList<string> Nobody = new List<string>();
        static readonly IReadOnlyList<string> Others = new List<string> { "a", "b", "c" };

        static Percept At(string who, IReadOnlyList<string> present)
        {
            var room = _house.Get(_kitchen);
            return new Percept(who, 10, room, present, _house.Adjacent(room.Id), 0.3,
                true, true, false, _house, false, null, null);
        }

        static Motive Want(string key)
            => new Motive(key, key == "look_after" ? "a" : null, 0.6, new List<string>(), new List<ScalerTerm>());

        // A cell is one (profile, want, circumstance). Circumstance 0 is company.
        static int Cells => _minds.Length * Wants.Length * 2;
        static int Cell(int i, int wi, int ci) => (i * Wants.Length + wi) * 2 + ci;
        static int Group(int wi, int ci) => wi * 2 + ci;
        static Percept Moment(int i, int ci) => ci == 0 ? _company[i] : _alone[i];
        static string GroupName(int g) => "`" + Wants[g / 2] + "` " + Circumstances[g % 2];

        // ============================================================ the five stages

        sealed class Contribution
        {
            public Candidate Rule;
            public double Weight;
        }

        /// <summary>What each stage let through, for one want in one moment of one person.</summary>
        sealed class Staged
        {
            public readonly List<string> Available = new List<string>();
            public readonly List<string> Compatible = new List<string>();
            public readonly List<Contribution> Contributions = new List<Contribution>();

            public IEnumerable<string> Supported
                => Contributions.Where(c => c.Weight > 0.0).Select(c => c.Rule.Intent).Distinct();
        }

        /// <summary>
        /// Stages 1 to 3, done exactly as `IntentionSelector.Form` does them and
        /// in the same order, so that the sum over what comes out is bit for bit
        /// the selector's own. That is checked on every cell, not assumed.
        /// </summary>
        static Staged Stage(IReadOnlyList<Candidate> rules, Mind mind, Percept p, string want)
        {
            var s = new Staged();
            var motive = Want(want);
            var ctx = new DecisionContext(p, mind.Id, motive.TargetId, _content.Morning.Day,
                _content.Rules.Deciding.RecallHalfLife);
            foreach (var c in rules)
            {
                if (!c.Motives.Contains(want, StringComparer.Ordinal)) continue;
                if (!s.Available.Contains(c.Intent)) s.Available.Add(c.Intent);
                if (!c.When.Matches(p)) continue;
                if (!s.Compatible.Contains(c.Intent)) s.Compatible.Add(c.Intent);
                var terms = ScalerEval.Evaluate(c.ScaledBy, mind, ctx);
                s.Contributions.Add(new Contribution { Rule = c, Weight = c.Base + terms.Sum(t => t.Amount) });
            }
            return s;
        }

        static IntentionSelector.Formed Form(IReadOnlyList<Candidate> rules, Mind mind, Percept p, string want)
            => IntentionSelector.Form(rules, mind, p, Want(want), _content.Morning.Day, _content.Rules.Deciding.RecallHalfLife);

        /// <summary>Stages 4 and 5 under one aggregator.</summary>
        sealed class Outcome
        {
            public string Winner;
            public double Score;
            public string RunnerUp;
            public double RunnerUpScore;
            public int Supported;

            public double Margin => RunnerUp == null ? double.PositiveInfinity : Score - RunnerUpScore;
            public string Line => Winner == null ? "none"
                : Winner + " " + F(Score) + (RunnerUp == null ? "" : " over " + RunnerUp + " " + F(RunnerUpScore));
        }

        sealed class Aggregator
        {
            public string Name;
            public string Definition;
            public Func<IReadOnlyList<Contribution>, double> Score;
        }

        /// <summary>
        /// The family, fixed in the predictions before anything ran. Each scores
        /// one intention from its positive contributions in rule order. Ties
        /// break by name for all six, as they do now, so that only the
        /// aggregation varies.
        /// </summary>
        static readonly Aggregator[] Family =
        {
            new Aggregator
            {
                Name = "sum", Definition = "the sum of its positive contributions; the current mechanism",
                Score = cs => { var t = 0.0; foreach (var c in cs) t += c.Weight; return t; }
            },
            new Aggregator
            {
                Name = "max", Definition = "its largest contribution",
                Score = cs => { var m = double.NegativeInfinity; foreach (var c in cs) if (c.Weight > m) m = c.Weight; return m; }
            },
            new Aggregator
            {
                Name = "mean", Definition = "the mean of its positive contributions",
                Score = cs => { var t = 0.0; foreach (var c in cs) t += c.Weight; return t / cs.Count; }
            },
            new Aggregator
            {
                Name = "normalized max", Definition = "the largest contribution / that rule's own attainable maximum",
                Score = cs => { var m = double.NegativeInfinity; foreach (var c in cs) { var v = c.Weight / Ceiling(c.Rule); if (v > m) m = v; } return m; }
            },
            new Aggregator
            {
                Name = "noisy-OR", Definition = "1 - product(1 - normalized contribution)",
                Score = cs => { var miss = 1.0; foreach (var c in cs) miss *= 1.0 - c.Weight / Ceiling(c.Rule); return 1.0 - miss; }
            },
            new Aggregator
            {
                Name = "deduplicated sum", Definition = "the sum, counting rules identical in all but their id once",
                Score = cs =>
                {
                    var seen = new HashSet<string>(StringComparer.Ordinal);
                    var t = 0.0;
                    foreach (var c in cs) if (seen.Add(ContentKey(c.Rule))) t += c.Weight;
                    return t;
                }
            },
        };

        const int Sum = 0;
        const int Max = 1;

        static bool Beats(double s1, string n1, double s2, string n2)
            => s1 > s2 || (s1 == s2 && string.CompareOrdinal(n1, n2) < 0);

        /// <summary>
        /// Rank the supported intentions under every aggregator. A contribution at
        /// or below zero is discarded before aggregation, as the selector does.
        /// </summary>
        static Outcome[] Decide(Staged s, Func<string, string> unrename = null)
        {
            var order = new List<string>();
            var by = new Dictionary<string, List<Contribution>>(StringComparer.Ordinal);
            foreach (var c in s.Contributions)
            {
                if (c.Weight <= 0.0) continue;
                if (!by.TryGetValue(c.Rule.Intent, out var list))
                {
                    by[c.Rule.Intent] = list = new List<Contribution>();
                    order.Add(c.Rule.Intent);
                }
                list.Add(c);
            }

            var outcomes = new Outcome[Family.Length];
            for (var a = 0; a < Family.Length; a++)
            {
                var o = new Outcome { Supported = order.Count };
                foreach (var intent in order)
                {
                    var score = Family[a].Score(by[intent]);
                    if (o.Winner == null || Beats(score, intent, o.Score, o.Winner))
                    {
                        o.RunnerUp = o.Winner;
                        o.RunnerUpScore = o.Score;
                        o.Winner = intent;
                        o.Score = score;
                    }
                    else if (o.RunnerUp == null || Beats(score, intent, o.RunnerUpScore, o.RunnerUp))
                    {
                        o.RunnerUp = intent;
                        o.RunnerUpScore = score;
                    }
                }
                if (unrename != null)
                {
                    o.Winner = o.Winner == null ? null : unrename(o.Winner);
                    o.RunnerUp = o.RunnerUp == null ? null : unrename(o.RunnerUp);
                }
                outcomes[a] = o;
            }
            return outcomes;
        }

        /// <summary>The same sum without the discard: a non-positive contribution counts as what it is.</summary>
        static string DecideWithoutDiscard(Staged s)
        {
            var totals = new Dictionary<string, double>(StringComparer.Ordinal);
            var order = new List<string>();
            foreach (var c in s.Contributions)
            {
                if (!totals.ContainsKey(c.Rule.Intent)) { totals[c.Rule.Intent] = 0.0; order.Add(c.Rule.Intent); }
                totals[c.Rule.Intent] += c.Weight;
            }
            string best = null;
            foreach (var i in order)
                if (best == null || Beats(totals[i], i, totals[best], best)) best = i;
            return best;
        }

        static readonly Dictionary<Candidate, double> _ceilings = new Dictionary<Candidate, double>();
        static readonly Dictionary<Candidate, string> _keys = new Dictionary<Candidate, string>();

        /// <summary>
        /// The most a rule could ever weigh for anybody. Every level it reads
        /// (trait, value weight, belief confidence, feeling) lies in 0..1.
        /// </summary>
        static double Ceiling(Candidate c)
        {
            if (_ceilings.TryGetValue(c, out var v)) return v;
            v = c.Base;
            foreach (var s in c.ScaledBy) v += Math.Max(0.0, s.Factor);
            _ceilings[c] = v;
            return v;
        }

        static string R(double v) => v.ToString("R", CultureInfo.InvariantCulture);

        /// <summary>Everything about a rule except its id.</summary>
        static string ContentKey(Candidate c)
        {
            if (_keys.TryGetValue(c, out var k)) return k;
            var w = c.When;
            var sb = new StringBuilder();
            sb.Append(c.Intent).Append('|').Append(string.Join(",", c.Motives)).Append('|')
              .Append(w.Alone).Append(',').Append(w.InOwnRoom).Append(',').Append(w.InSomebodyElsesRoom).Append(',')
              .Append(w.RoomHoldsFood).Append(',').Append(w.SearchedThisRoomMyself).Append(',').Append(w.OthersPresentMin)
              .Append('|').Append(R(c.Base));
            foreach (var s in c.ScaledBy)
                sb.Append('|').Append(s.Kind).Append(':').Append(s.Name).Append(':').Append(s.Predicate).Append(':')
                  .Append(string.Join(",", s.Args ?? new List<string>())).Append(':').Append(s.Entry).Append(':')
                  .Append(s.About).Append(':').Append(s.Topic).Append(':').Append(s.By).Append(':').Append(s.Target).Append(':')
                  .Append(string.Join(",", s.Until ?? new List<string>())).Append(':').Append(R(s.Factor));
            _keys[c] = k = sb.ToString();
            return k;
        }

        // ============================================================ rewriting rules, in memory only

        static Scaler Copy(Scaler s, double scale)
            => new Scaler
            {
                Kind = s.Kind, Name = s.Name, Predicate = s.Predicate, Args = s.Args, Entry = s.Entry,
                About = s.About, Topic = s.Topic, By = s.By, Until = s.Until, Target = s.Target,
                Factor = s.Factor * scale
            };

        static Candidate Make(Candidate c, string id, string intent = null, IReadOnlyList<string> motives = null,
            SituationCondition when = null, double? baseWeight = null, IReadOnlyList<Scaler> scalers = null)
            => new Candidate
            {
                Id = id,
                Note = c.Note,
                Motives = (motives ?? c.Motives).ToList(),
                Intent = intent ?? c.Intent,
                When = when ?? c.When,
                Base = baseWeight ?? c.Base,
                ScaledBy = (scalers ?? c.ScaledBy).Select(s => Copy(s, 1.0)).ToList()
            };

        static List<Candidate> Without(Candidate r) => _rules.Where(x => !ReferenceEquals(x, r)).ToList();

        /// <summary>A rule's base as one rule, and each of its scalers as a rule of its own.</summary>
        static IEnumerable<Candidate> ByTerm(Candidate c)
        {
            yield return Make(c, c.Id + "_base", scalers: new List<Scaler>());
            for (var k = 0; k < c.ScaledBy.Count; k++)
                yield return Make(c, c.Id + "_term" + k, baseWeight: 0.0, scalers: new[] { c.ScaledBy[k] });
        }

        sealed class PerRule
        {
            public string Key;
            public string Label;
            public string Should;
            public Func<Candidate, List<Candidate>> Build;
        }

        /// <summary>The per-rule transformations T4 to T9, in the order the predictions list them.</summary>
        static readonly PerRule[] PerRuleTransforms =
        {
            new PerRule { Key = "T4", Label = "duplicate one rule", Should = "yes: an exact copy says nothing new about the person",
                Build = r => _rules.Concat(new[] { r.CloneAs(r.Id + "_again") }).ToList() },
            new PerRule { Key = "T5", Label = "near-duplicate one rule (x 0.99)", Should = "yes: behaves as T4",
                Build = r => _rules.Concat(new[] { r.CloneAs(r.Id + "_nearly", 0.99) }).ToList() },
            new PerRule { Key = "T6", Label = "split one rule into two halves", Should = "depends on what a rule is",
                Build = r => Without(r).Concat(new[] { r.CloneAs(r.Id + "_a", 0.5), r.CloneAs(r.Id + "_b", 0.5) }).ToList() },
            new PerRule { Key = "T7", Label = "split one rule into four quarters", Should = "depends on what a rule is",
                Build = r => Without(r).Concat(Enumerable.Range(0, 4).Select(k => r.CloneAs(r.Id + "_q" + k, 0.25))).ToList() },
            new PerRule { Key = "T8", Label = "split one rule by term", Should = "yes: the same reasons, grouped differently",
                Build = r => Without(r).Concat(ByTerm(r)).ToList() },
            new PerRule { Key = "T9", Label = "scale one rule x 2 (2W)", Should = "**no**: a stronger reason must be able to win",
                Build = r => Without(r).Concat(new[] { r.CloneAs(r.Id + "_double", 2.0) }).ToList() },
        };

        const int T4 = 0, T5 = 1, T6 = 2, T7 = 3, T8 = 4, T9 = 5;

        /// <summary>
        /// One rule per (want, intention, circumstance): every set of rules that
        /// are compatible together is merged, base added to base and scalers
        /// concatenated. Equivalent to the frozen set in the two circumstances
        /// tested, and in no others.
        /// </summary>
        static List<Candidate> Merged()
        {
            var list = new List<Candidate>();
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var p = Moment(0, ci);
                var gate = ci == 0 ? new SituationCondition { OthersPresentMin = 1 } : new SituationCondition { Alone = true };
                var compatible = _rules.Where(r => r.Motives.Contains(Wants[wi], StringComparer.Ordinal) && r.When.Matches(p)).ToList();
                foreach (var intent in compatible.Select(r => r.Intent).Distinct().ToList())
                {
                    var parts = compatible.Where(r => r.Intent == intent).ToList();
                    var b = 0.0;
                    foreach (var r in parts) b += r.Base;
                    list.Add(Make(parts[0], Wants[wi] + "_" + ci + "_" + intent, motives: new[] { Wants[wi] }, when: gate,
                        baseWeight: b, scalers: parts.SelectMany(r => r.ScaledBy).ToList()));
                }
            }
            return list;
        }

        static readonly string[] Intentions =
            { "assert_authority", "prevent_argument", "protect", "share_information", "take_responsibility", "took_what_was_not_mine" };

        /// <summary>A prefix that reverses the alphabetical order of the six intentions.</summary>
        static string Rename(string intent)
            => (char)('a' + Intentions.Length - 1 - Array.IndexOf(Intentions, intent)) + "_" + intent;

        static string Unrename(string renamed) => renamed.Substring(2);

        sealed class Whole
        {
            public string Key;
            public string Label;
            public string Should;
            public Func<List<Candidate>> Build;
            public Func<string, string> Unrename;
        }

        static readonly Whole[] WholeTransforms =
        {
            new Whole { Key = "T1", Label = "reverse the order of the rules", Should = "yes",
                Build = () => _rules.Reverse().ToList() },
            new Whole { Key = "T2", Label = "give every rule a new id", Should = "yes",
                Build = () => _rules.Select((r, k) => r.CloneAs("rule_" + k)).ToList() },
            new Whole { Key = "T3", Label = "rename the intentions (reverse their alphabetical order)", Should = "yes: a label is not psychology",
                Build = () => _rules.Select(r => Make(r, r.Id, intent: Rename(r.Intent))).ToList(), Unrename = Unrename },
            new Whole { Key = "T10", Label = "merge co-compatible rules into one per want, intention and circumstance", Should = "yes: the same reasons, grouped differently",
                Build = Merged },
            new Whole { Key = "T11", Label = "duplicate every rule", Should = "yes: nothing is relatively stronger",
                Build = () => _rules.Concat(_rules.Select(r => r.CloneAs(r.Id + "_again"))).ToList() },
        };

        // ============================================================ the baseline

        static Staged[] _staged;
        static Outcome[][] _base;
        static string[] _baseForm;
        static int _formWinnerMismatch;
        static int _formWeightMismatch;

        static void EnsureBaseline()
        {
            if (_base != null) return;
            _staged = new Staged[Cells];
            _base = new Outcome[Cells][];
            _baseForm = new string[Cells];
            for (var i = 0; i < _minds.Length; i++)
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var cell = Cell(i, wi, ci);
                _staged[cell] = Stage(_rules, _minds[i], Moment(i, ci), Wants[wi]);
                _base[cell] = Decide(_staged[cell]);
                var f = Form(_rules, _minds[i], Moment(i, ci), Wants[wi]);
                _baseForm[cell] = f.Intent;
                if (f.Intent != _base[cell][Sum].Winner) _formWinnerMismatch++;
                else if (f.Intent != null && !f.Weight.Equals(_base[cell][Sum].Score)) _formWeightMismatch++;
            }
        }

        static bool CompatibleIn(Candidate r, int wi, int ci)
            => r.Motives.Contains(Wants[wi], StringComparer.Ordinal) && r.When.Matches(Moment(0, ci));

        // ============================================================ the transformations, run once

        sealed class Tally
        {
            public int Changed;
            public int AtTie;
            public int Toward;
            public int Away;
            public int Outside;
        }

        static Tally[][][] _perRule;           // [transform][rule][aggregator]
        static Tally[][] _whole;               // [transform][aggregator]
        static int[][] _formChanged;           // [transform][rule], through IntentionSelector.Form
        static int _formMismatch;              // Form against the stage-wise sum, over every Form-checked variant
        static int[][][] _pairwise;            // [rule][aggregator][pair] disagreements among W, 2 x W/2, 4 x W/4, 2W, W + W
        static int[] _dupFlipsPerCell;         // under the sum: how many single-rule duplications reverse this cell
        static int[] _dupFlipsPerWant;
        static int _dupFlipsEverySeventh;

        static readonly string[] Representations = { "W", "2 x W/2", "4 x W/4", "2W", "W + W" };

        static void EnsureTransforms()
        {
            if (_perRule != null) return;
            EnsureBaseline();

            _perRule = PerRuleTransforms.Select(_ => _rules.Select(__ => Family.Select(___ => new Tally()).ToArray()).ToArray()).ToArray();
            _formChanged = PerRuleTransforms.Select(_ => new int[_rules.Count]).ToArray();
            _pairwise = _rules.Select(_ => Family.Select(__ => new int[10]).ToArray()).ToArray();
            _dupFlipsPerCell = new int[Cells];
            _dupFlipsPerWant = new int[Wants.Length];
            var formChecked = new[] { T4, T6, T7, T9 };

            for (var ri = 0; ri < _rules.Count; ri++)
            {
                var rule = _rules[ri];
                var sets = PerRuleTransforms.Select(t => t.Build(rule)).ToArray();
                for (var i = 0; i < _minds.Length; i++)
                for (var wi = 0; wi < Wants.Length; wi++)
                for (var ci = 0; ci < 2; ci++)
                {
                    var cell = Cell(i, wi, ci);
                    var p = Moment(i, ci);
                    var exposed = CompatibleIn(rule, wi, ci);
                    var outs = new Outcome[sets.Length][];
                    for (var t = 0; t < sets.Length; t++)
                    {
                        outs[t] = Decide(Stage(sets[t], _minds[i], p, Wants[wi]));
                        for (var a = 0; a < Family.Length; a++)
                        {
                            var was = _base[cell][a];
                            var now = outs[t][a];
                            if (was.Winner == now.Winner) continue;
                            var tally = _perRule[t][ri][a];
                            tally.Changed++;
                            if (was.Margin < Tie || now.Margin < Tie) tally.AtTie++;
                            if (now.Winner == rule.Intent) tally.Toward++;
                            else if (was.Winner == rule.Intent) tally.Away++;
                            if (!exposed) tally.Outside++;
                            if (t == T4 && a == Sum)
                            {
                                _dupFlipsPerCell[cell]++;
                                _dupFlipsPerWant[wi]++;
                            }
                        }
                    }

                    foreach (var t in formChecked)
                    {
                        var f = Form(sets[t], _minds[i], p, Wants[wi]);
                        if (f.Intent != outs[t][Sum].Winner) _formMismatch++;
                        if (f.Intent != _baseForm[cell])
                        {
                            _formChanged[t][ri]++;
                            if (t == T4 && i % 7 == 0) _dupFlipsEverySeventh++;
                        }
                    }

                    // C: the five representations of one rule's weight, compared pairwise.
                    var rep = new[] { _base[cell], outs[T6], outs[T7], outs[T9], outs[T4] };
                    for (var a = 0; a < Family.Length; a++)
                    {
                        var k = 0;
                        for (var x = 0; x < rep.Length; x++)
                        for (var y = x + 1; y < rep.Length; y++, k++)
                            if (rep[x][a].Winner != rep[y][a].Winner) _pairwise[ri][a][k]++;
                    }
                }
            }

            _whole = WholeTransforms.Select(_ => Family.Select(__ => new Tally()).ToArray()).ToArray();
            for (var t = 0; t < WholeTransforms.Length; t++)
            {
                var set = WholeTransforms[t].Build();
                for (var i = 0; i < _minds.Length; i++)
                for (var wi = 0; wi < Wants.Length; wi++)
                for (var ci = 0; ci < 2; ci++)
                {
                    var cell = Cell(i, wi, ci);
                    var outs = Decide(Stage(set, _minds[i], Moment(i, ci), Wants[wi]), WholeTransforms[t].Unrename);
                    for (var a = 0; a < Family.Length; a++)
                    {
                        var was = _base[cell][a];
                        if (was.Winner == outs[a].Winner) continue;
                        _whole[t][a].Changed++;
                        if (was.Margin < Tie || outs[a].Margin < Tie) _whole[t][a].AtTie++;
                    }
                }
            }
        }

        // ============================================================ one attribute of a person at a time

        sealed class Move
        {
            public int Attribute;
            public string Description;
            public Mind Mind;
        }

        static readonly string[] Attributes =
        {
            "trait anxious", "trait cautious", "trait dominant", "trait empathetic", "trait honest", "trait impulsive", "trait proud",
            "value ranks 1 <-> 2", "value ranks 2 <-> 3", "value ranks 3 <-> 4", "value ranks 4 <-> 5", "value ranks 5 <-> 6",
            "belief role_claim", "belief answerable_for"
        };

        /// <summary>
        /// The 21 single-attribute moves of one sweep profile: each trait to each
        /// of its other two levels, each adjacent pair of value ranks swapped,
        /// each belief toggled between absent and its sweep confidence.
        /// </summary>
        static List<Move> Moves(int i)
        {
            var m = _minds[i];
            var moves = new List<Move>();
            for (var t = 0; t < _sweepTraits.Count; t++)
                foreach (var level in _levels)
                {
                    var was = m.Profile.Trait(_sweepTraits[t]);
                    if (level.Equals(was)) continue;
                    var traits = TraitsOf(m);
                    traits[_sweepTraits[t]] = level;
                    moves.Add(new Move
                    {
                        Attribute = Array.IndexOf(Attributes, "trait " + _sweepTraits[t]),
                        Description = _sweepTraits[t] + " " + F(was) + " -> " + F(level),
                        Mind = Person(m.Id, traits, m.Profile.Values, Seeds(m))
                    });
                }
            for (var k = 0; k < m.Profile.Values.Count - 1; k++)
            {
                var values = m.Profile.Values.ToList();
                var swap = values[k];
                values[k] = values[k + 1];
                values[k + 1] = swap;
                moves.Add(new Move
                {
                    Attribute = Array.IndexOf(Attributes, "value ranks " + (k + 1) + " <-> " + (k + 2)),
                    Description = values[k + 1] + " and " + values[k] + " swap ranks " + (k + 1) + " and " + (k + 2),
                    Mind = Person(m.Id, TraitsOf(m), values, Seeds(m))
                });
            }
            foreach (var (predicate, second, confidence) in new[] { ("role_claim", "leads_family", 0.80), ("answerable_for", "missing_can", 0.90) })
            {
                var seeds = Seeds(m);
                var held = seeds.Any(b => b.Predicate == predicate);
                seeds = held
                    ? seeds.Where(b => b.Predicate != predicate).ToList()
                    : seeds.Concat(new[] { new BeliefSeed(predicate, new[] { m.Id, second }, confidence) }).ToList();
                moves.Add(new Move
                {
                    Attribute = Array.IndexOf(Attributes, "belief " + predicate),
                    Description = predicate + (held ? " dropped" : " taken up at " + F(confidence)),
                    Mind = Person(m.Id, TraitsOf(m), m.Profile.Values, seeds)
                });
            }
            return moves;
        }

        static int[][][] _pairs;            // [group][attribute][aggregator]  all pairs (same for every aggregator)
        static int[][][] _moved;            // [group][attribute][aggregator]  winner changed
        static int[][] _fixedPairs;         // [group][attribute]              candidate set (supported) identical
        static int[][][] _fixedMoved;       // [group][attribute][aggregator]  ... and the winner changed
        static int _compatibleChanged;
        static int _supportedChanged;
        static int _supportedChangedByDiscard;
        static readonly List<string> _examples = new List<string>();

        static bool SameSet(IEnumerable<string> a, IEnumerable<string> b)
            => new HashSet<string>(a, StringComparer.Ordinal).SetEquals(b);

        static void EnsurePerturbations()
        {
            if (_pairs != null) return;
            EnsureBaseline();
            var groups = Wants.Length * 2;
            _pairs = Enumerable.Range(0, groups).Select(_ => Attributes.Select(__ => new int[Family.Length]).ToArray()).ToArray();
            _moved = Enumerable.Range(0, groups).Select(_ => Attributes.Select(__ => new int[Family.Length]).ToArray()).ToArray();
            _fixedPairs = Enumerable.Range(0, groups).Select(_ => new int[Attributes.Length]).ToArray();
            _fixedMoved = Enumerable.Range(0, groups).Select(_ => Attributes.Select(__ => new int[Family.Length]).ToArray()).ToArray();
            var exampleFor = new HashSet<int>();

            for (var i = 0; i < _minds.Length; i++)
                foreach (var move in Moves(i))
                    for (var wi = 0; wi < Wants.Length; wi++)
                    for (var ci = 0; ci < 2; ci++)
                    {
                        var g = Group(wi, ci);
                        var cell = Cell(i, wi, ci);
                        var before = _staged[cell];
                        var after = Stage(_rules, move.Mind, Moment(i, ci), Wants[wi]);
                        var outs = Decide(after);

                        if (!SameSet(before.Compatible, after.Compatible)) _compatibleChanged++;
                        var fixedSet = SameSet(before.Supported, after.Supported);
                        if (!fixedSet)
                        {
                            _supportedChanged++;
                            var differ = new HashSet<string>(before.Supported, StringComparer.Ordinal);
                            differ.SymmetricExceptWith(after.Supported);
                            var discarded = before.Contributions.Concat(after.Contributions)
                                .Where(c => c.Weight <= 0.0).Select(c => c.Rule.Intent);
                            if (differ.IsSubsetOf(discarded)) _supportedChangedByDiscard++;
                        }
                        else _fixedPairs[g][move.Attribute]++;

                        for (var a = 0; a < Family.Length; a++)
                        {
                            _pairs[g][move.Attribute][a]++;
                            if (outs[a].Winner == _base[cell][a].Winner) continue;
                            _moved[g][move.Attribute][a]++;
                            if (fixedSet) _fixedMoved[g][move.Attribute][a]++;
                        }

                        if (fixedSet && before.Compatible.Count >= 2 && outs[Sum].Winner != _base[cell][Sum].Winner && exampleFor.Add(g))
                            _examples.Add("| " + GroupName(g) + " | p" + i + " | " + move.Description + " | "
                                          + _base[cell][Sum].Line + " | " + outs[Sum].Line + " |");
                    }
        }

        // ============================================================ structure: what can win at all

        /// <summary>
        /// A rule's contribution as a linear function of what it reads. Every
        /// level lies in 0..1, so its range over all possible people is the
        /// constant plus the positive coefficients, or plus the negative ones.
        /// </summary>
        sealed class Linear
        {
            public double Const;
            public readonly Dictionary<string, double> Coef = new Dictionary<string, double>(StringComparer.Ordinal);

            public void Add(Linear o, double sign)
            {
                Const += sign * o.Const;
                foreach (var kv in o.Coef)
                {
                    Coef.TryGetValue(kv.Key, out var c);
                    Coef[kv.Key] = c + sign * kv.Value;
                }
            }

            public double Highest => Const + Coef.Values.Sum(v => Math.Max(0.0, v));
            public double Lowest => Const + Coef.Values.Sum(v => Math.Min(0.0, v));
        }

        static string VarKey(Scaler s)
            => s.Kind == ScalerKind.Belief ? "belief " + s.Predicate : s.Kind + " " + s.Name;

        static Linear LinearOf(Candidate c)
        {
            var l = new Linear { Const = c.Base };
            foreach (var s in c.ScaledBy)
            {
                l.Coef.TryGetValue(VarKey(s), out var v);
                l.Coef[VarKey(s)] = v + s.Factor;
            }
            return l;
        }

        /// <summary>
        /// An upper bound, over every person in the unit box, on how far X can
        /// outscore Y under the sum. A rule of X that can fall to zero may be
        /// discarded, so both cases are bounded. Y's discards only raise Y.
        /// Relaxing value ranks to independent weights only widens the box, so a
        /// negative bound is a proof that X never beats Y.
        /// </summary>
        static double BestMargin(IReadOnlyList<Candidate> x, IReadOnlyList<Candidate> y)
        {
            var sure = x.Where(r => LinearOf(r).Lowest > 0.0).ToList();
            var fragile = x.Where(r => LinearOf(r).Lowest <= 0.0).ToList();
            var best = double.NegativeInfinity;
            for (var mask = 0; mask < 1 << fragile.Count; mask++)
            {
                var kept = sure.Concat(fragile.Where((r, k) => (mask & (1 << k)) != 0)).ToList();
                if (kept.Count == 0) continue;
                var d = new Linear();
                foreach (var r in kept) d.Add(LinearOf(r), +1);
                foreach (var r in y) d.Add(LinearOf(r), -1);
                best = Math.Max(best, d.Highest);
            }
            return best;
        }

        sealed class Standing
        {
            public int Group;
            public string Intent;
            public bool Witnessed;
            public string DominatedBy;
            public double Margin;
        }

        static List<Candidate> CompatibleRules(int wi, int ci, string intent = null)
            => _rules.Where(r => CompatibleIn(r, wi, ci) && (intent == null || r.Intent == intent)).ToList();

        static List<Standing> Standings()
        {
            EnsureBaseline();
            var list = new List<Standing>();
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var intents = CompatibleRules(wi, ci).Select(r => r.Intent).Distinct().ToList();
                if (intents.Count < 2) continue;
                var winners = new HashSet<string>(Enumerable.Range(0, _minds.Length)
                    .Select(i => _base[Cell(i, wi, ci)][Sum].Winner), StringComparer.Ordinal);
                foreach (var x in intents)
                {
                    var st = new Standing { Group = Group(wi, ci), Intent = x, Witnessed = winners.Contains(x), Margin = double.PositiveInfinity };
                    foreach (var y in intents.Where(y => y != x))
                    {
                        var m = BestMargin(CompatibleRules(wi, ci, x), CompatibleRules(wi, ci, y));
                        if (m < -Tie && m < st.Margin) { st.Margin = m; st.DominatedBy = y; }
                    }
                    list.Add(st);
                }
            }
            return list;
        }

        // ============================================================ 0

        [Test, Order(0)]
        public void TheRulesAreFrozenAndTheStagesAreTheSelector()
        {
            EnsureBaseline();
            var sha = Sha(_rulePath);
            var sb = new StringBuilder();
            sb.AppendLine("## 0. What is frozen, and whether taking the selector apart changed it");
            sb.AppendLine();
            sb.AppendLine("| | |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| File | `Assets/_Project/Data/Experiments/intentions.json` |");
            sb.AppendLine("| sha256 at the start of this run | `" + sha + "` |");
            sb.AppendLine("| Expected | `" + FrozenSha + "` |");
            sb.AppendLine("| Match | " + (sha == FrozenSha ? "**yes**" : "**NO**") + " |");
            sb.AppendLine("| Rules | " + _rules.Count + " |");
            sb.AppendLine("| Profiles | " + _minds.Length + " |");
            sb.AppendLine("| Cells (profile x want x circumstance) | " + Cells + " |");
            sb.AppendLine();

            sb.AppendLine("### The stages reproduce the selector");
            sb.AppendLine();
            sb.AppendLine("This fixture runs stages 1 to 3 itself and aggregates what comes out, so that the aggregation can be swapped. Under the sum it must be the selector, and it is checked against `IntentionSelector.Form` on every cell rather than assumed.");
            sb.AppendLine();
            sb.AppendLine("| | Cells |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Winner differs from `IntentionSelector.Form` | **" + _formWinnerMismatch + "** of " + Cells + " |");
            sb.AppendLine("| Same winner, but its weight is not bit-for-bit equal | **" + _formWeightMismatch + "** |");
            sb.AppendLine();

            var single = _base.Count(o => o[Sum].Supported <= 1);
            var signatures = Enumerable.Range(0, _minds.Length)
                .Select(i => string.Join("|", Enumerable.Range(0, Wants.Length).Select(wi => Or(_base[Cell(i, wi, 0)][Sum].Winner))))
                .Distinct().Count();
            var arrival = 0;
            for (var i = 0; i < _minds.Length; i++)
                for (var wi = 0; wi < Wants.Length; wi++)
                    if (_base[Cell(i, wi, 0)][Sum].Winner != _base[Cell(i, wi, 1)][Sum].Winner) arrival++;
            sb.AppendLine("### The same sweep as the generalization experiment");
            sb.AppendLine();
            sb.AppendLine("| Published there | Reproduced here |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| 28.6 % of 30618 cells with one intention in the running | " + Pc(single, Cells) + " (" + single + ") |");
            sb.AppendLine("| 56 distinct signatures in company | " + signatures + " |");
            sb.AppendLine("| 8407 cells changed by company arriving | " + arrival + " |");
            sb.AppendLine("| 2898 changes from cloning a rule, every seventh profile | in section A |");
            sb.AppendLine();

            sb.AppendLine("### What each stage lets through, by want");
            sb.AppendLine();
            sb.AppendLine("Stage 1 depends on the want alone and stage 2 on the want and the circumstance, so this table is the whole of both. A rule in brackets is gated out.");
            sb.AppendLine();
            sb.AppendLine("| Want | Available (stage 1) | Compatible in company (stage 2) | Compatible alone (stage 2) |");
            sb.AppendLine("|---|---|---|---|");
            for (var wi = 0; wi < Wants.Length; wi++)
            {
                var inScope = _rules.Where(r => r.Motives.Contains(Wants[wi], StringComparer.Ordinal)).ToList();
                string Cols(int ci) => string.Join("; ", inScope.Select(r => r.Intent).Distinct().Select(x =>
                    x + " " + string.Join(" + ", inScope.Where(r => r.Intent == x)
                        .Select(r => CompatibleIn(r, wi, ci) ? "`" + r.Id + "`" : "(`" + r.Id + "`)"))));
                sb.AppendLine("| `" + Wants[wi] + "` | " + string.Join(", ", inScope.Select(r => r.Intent).Distinct())
                              + " | " + Cols(0) + " | " + Cols(1) + " |");
            }
            Record("0", sb.ToString());

            Assert.AreEqual(FrozenSha, sha, "the rule file must be byte-identical to the one the predictions were written against");
            Assert.AreEqual(0, _formWinnerMismatch, "the stage-wise sum must be the selector");
            Assert.AreEqual(0, _formWeightMismatch, "the stage-wise sum must be the selector, to the bit");
        }

        // ============================================================ A

        [Test, Order(1), Timeout(3600000)]
        public void A_DuplicatingOneRule()
        {
            EnsureTransforms();
            var sb = new StringBuilder();
            sb.AppendLine("## A. Duplicating one rule");
            sb.AppendLine();
            sb.AppendLine("Each rule in turn is added again under a new id: same person, same state, same circumstances, one extra line in the rule file that says nothing it did not already say. Counted through `IntentionSelector.Form` itself, on all " + Cells + " cells.");
            sb.AppendLine();
            sb.AppendLine("| Rule duplicated | Intention | Cells where it is compatible | **Winner changed** | of all cells | of cells where compatible | toward its own intention | elsewhere | where it is not compatible |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|");
            var total = 0;
            for (var ri = 0; ri < _rules.Count; ri++)
            {
                var r = _rules[ri];
                var exposed = 0;
                for (var wi = 0; wi < Wants.Length; wi++)
                    for (var ci = 0; ci < 2; ci++)
                        if (CompatibleIn(r, wi, ci)) exposed += _minds.Length;
                var t = _perRule[T4][ri][Sum];
                var changed = _formChanged[T4][ri];
                total += changed;
                sb.AppendLine("| `" + r.Id + "` | `" + r.Intent + "` | " + exposed + " | **" + changed + "** | " + Pc(changed, Cells)
                              + " | " + Pc(changed, exposed) + " | " + t.Toward + " | " + (t.Changed - t.Toward) + " | " + t.Outside + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**Over " + Cells + " cells and " + _rules.Count + " rules, duplicating one rule changed the intention " + total
                          + " times.** On every seventh profile, the subset the generalization experiment used, it changed it "
                          + _dupFlipsEverySeventh + " times (published: 2898).");
            sb.AppendLine();

            sb.AppendLine("### By want");
            sb.AppendLine();
            sb.AppendLine("| Want | Changes from duplicating some one rule, summed over the ten |");
            sb.AppendLine("|---|---|");
            for (var wi = 0; wi < Wants.Length; wi++)
                sb.AppendLine("| `" + Wants[wi] + "` | " + _dupFlipsPerWant[wi] + " |");
            sb.AppendLine();

            var fragile = _dupFlipsPerCell.Count(c => c > 0);
            sb.AppendLine("### How many conclusions one copied line can reverse");
            sb.AppendLine();
            sb.AppendLine("| Rules whose duplication alone reverses the cell | Cells |");
            sb.AppendLine("|---|---|");
            for (var k = 0; k <= _dupFlipsPerCell.Max(); k++)
                sb.AppendLine("| " + k + " | " + _dupFlipsPerCell.Count(c => c == k) + " |");
            sb.AppendLine();
            sb.AppendLine("**" + fragile + " of " + Cells + " cells (" + Pc(fragile, Cells) + ") have a conclusion that copying a single existing rule, and changing nothing about the person, reverses.**");
            Record("A", sb.ToString());

            Assert.AreEqual(0, _formMismatch, "the stage-wise sum must be the selector on every transformed rule set too");
            Assert.AreEqual(0, _perRule[T4].Sum(r => r[Sum].Outside), "a rule that is not compatible cannot change anything by being copied");
        }

        // ============================================================ B

        [Test, Order(2), Timeout(3600000)]
        public void B_SplittingOneRule()
        {
            EnsureTransforms();
            var sb = new StringBuilder();
            sb.AppendLine("## B. Splitting one rule");
            sb.AppendLine();
            sb.AppendLine("Each rule in turn is replaced by equal parts that together weigh what it weighed. Counted through `IntentionSelector.Form`, on all " + Cells + " cells. This is the regression invariant the generalization experiment found, and it is asserted.");
            sb.AppendLine();
            sb.AppendLine("| Rule split | Intention | Changed by two halves | Changed by four quarters |");
            sb.AppendLine("|---|---|---|---|");
            for (var ri = 0; ri < _rules.Count; ri++)
                sb.AppendLine("| `" + _rules[ri].Id + "` | `" + _rules[ri].Intent + "` | " + _formChanged[T6][ri] + " | " + _formChanged[T7][ri] + " |");
            var halves = _formChanged[T6].Sum();
            var quarters = _formChanged[T7].Sum();
            sb.AppendLine();
            sb.AppendLine("**Over " + (Cells * _rules.Count) + " (rule, cell) pairs: splitting into halves changed " + halves
                          + "; into quarters, " + quarters + ".**");
            Record("B", sb.ToString());

            Assert.AreEqual(0, halves, "B1: splitting a rule into halves preserves its weight and must change nothing");
        }

        // ============================================================ C

        [Test, Order(3), Timeout(3600000)]
        public void C_WeightAgainstRepresentation()
        {
            EnsureTransforms();
            var sb = new StringBuilder();
            sb.AppendLine("## C. Weight against representation");
            sb.AppendLine();
            sb.AppendLine("Five ways of writing one rule: as it is (**W**), as two rules at half weight (**2 x W/2**), as four at a quarter (**4 x W/4**), as one rule at double weight (**2W**), and as itself twice (**W + W**). The first three carry the same total weight, the last two the same doubled weight. Cells in which two representations reach different intentions, under the current mechanism:");
            sb.AppendLine();
            var pairNames = new List<string>();
            for (var x = 0; x < Representations.Length; x++)
                for (var y = x + 1; y < Representations.Length; y++)
                    pairNames.Add(Representations[x] + " vs " + Representations[y]);
            sb.AppendLine("| Rule | " + string.Join(" | ", pairNames) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", pairNames.Count)));
            for (var ri = 0; ri < _rules.Count; ri++)
                sb.AppendLine("| `" + _rules[ri].Id + "` | " + string.Join(" | ", _pairwise[ri][Sum]) + " |");
            sb.AppendLine("| **all ten** | " + string.Join(" | ", Enumerable.Range(0, pairNames.Count).Select(k => "**" + _rules.Indices().Sum(ri => _pairwise[ri][Sum][k]) + "**")) + " |");
            sb.AppendLine();

            sb.AppendLine("### Which representations each aggregator treats as the same");
            sb.AppendLine();
            sb.AppendLine("Two representations are the same to an aggregator if they never reach different intentions, for any of the ten rules, in any cell. The classes:");
            sb.AppendLine();
            sb.AppendLine("| Aggregator | Equivalence classes | " + string.Join(" | ", pairNames) + " |");
            sb.AppendLine("|---|---|" + string.Concat(Enumerable.Repeat("---|", pairNames.Count)));
            for (var a = 0; a < Family.Length; a++)
            {
                var totals = Enumerable.Range(0, pairNames.Count).Select(k => _rules.Indices().Sum(ri => _pairwise[ri][a][k])).ToArray();
                var cls = Enumerable.Range(0, Representations.Length).ToArray();
                var kk = 0;
                for (var x = 0; x < Representations.Length; x++)
                for (var y = x + 1; y < Representations.Length; y++, kk++)
                    if (totals[kk] == 0)
                    {
                        var from = cls[y];
                        var to = cls[x];
                        for (var z = 0; z < cls.Length; z++) if (cls[z] == from) cls[z] = to;
                    }
                var classes = cls.Distinct().Select(c => "{" + string.Join(", ", Enumerable.Range(0, cls.Length).Where(z => cls[z] == c).Select(z => Representations[z])) + "}");
                sb.AppendLine("| " + Family[a].Name + " | " + string.Join(" ", classes) + " | " + string.Join(" | ", totals) + " |");
            }
            Record("C", sb.ToString());
        }

        // ============================================================ D

        [Test, Order(4), Timeout(3600000)]
        public void D_CandidateSets()
        {
            EnsurePerturbations();
            var standings = Standings();
            var sb = new StringBuilder();
            sb.AppendLine("## D. How many candidates, and how much the person can matter with each number");
            sb.AppendLine();
            sb.AppendLine("The number of **compatible** intentions depends on the want and the circumstance only, so it is a property of the 14 (want, circumstance) groups. The number of **supported** ones (a positive contribution) can be smaller, and depends on the person. Sensitivity is the share of the 21 single-attribute moves of a profile (section F) that change its intention, pooled over all 2187 profiles.");
            sb.AppendLine();
            sb.AppendLine("| Group | K compatible | Compatible | Supported, min-max | Winners across the sweep | Entropy (bits) | Sensitivity |");
            sb.AppendLine("|---|---|---|---|---|---|---|");

            var byK = new SortedDictionary<int, List<int>>();
            var groupWinners = new int[Wants.Length * 2];
            var groupSensitivity = new double[Wants.Length * 2];
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var g = Group(wi, ci);
                var k = _staged[Cell(0, wi, ci)].Compatible.Count;
                if (!byK.ContainsKey(k)) byK[k] = new List<int>();
                byK[k].Add(g);
                var dist = new Dictionary<string, int>(StringComparer.Ordinal);
                var minSup = int.MaxValue;
                var maxSup = 0;
                for (var i = 0; i < _minds.Length; i++)
                {
                    var o = _base[Cell(i, wi, ci)][Sum];
                    dist.TryGetValue(Or(o.Winner), out var c);
                    dist[Or(o.Winner)] = c + 1;
                    minSup = Math.Min(minSup, o.Supported);
                    maxSup = Math.Max(maxSup, o.Supported);
                }
                var entropy = -dist.Values.Select(v => (double)v / _minds.Length).Sum(p => p * Math.Log(p, 2));
                var pairs = _pairs[g].Sum(x => x[Sum]);
                var moved = _moved[g].Sum(x => x[Sum]);
                groupWinners[g] = dist.Count;
                groupSensitivity[g] = (double)moved / pairs;
                sb.AppendLine("| " + GroupName(g) + " | " + k + " | " + string.Join(", ", _staged[Cell(0, wi, ci)].Compatible)
                              + " | " + minSup + "-" + maxSup + " | "
                              + string.Join(", ", dist.OrderByDescending(d => d.Value).ThenBy(d => d.Key, StringComparer.Ordinal).Select(d => d.Key + " " + Pc(d.Value, _minds.Length)))
                              + " | " + F(Math.Abs(entropy)) + " | " + Pc(moved, pairs) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### By number of compatible candidates");
            sb.AppendLine();
            sb.AppendLine("| K | Groups | Cells | Share of cells | Groups with one winner across the whole sweep | Mean winners per group | Pooled sensitivity | Least and most sensitive group |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            foreach (var kv in byK)
            {
                var gs = kv.Value;
                var pairs = gs.Sum(g => _pairs[g].Sum(x => x[Sum]));
                var moved = gs.Sum(g => _moved[g].Sum(x => x[Sum]));
                var least = gs.OrderBy(g => groupSensitivity[g]).First();
                var most = gs.OrderByDescending(g => groupSensitivity[g]).First();
                sb.AppendLine("| " + kv.Key + " | " + gs.Count + " | " + (gs.Count * _minds.Length) + " | " + Pc(gs.Count * _minds.Length, Cells)
                              + " | " + gs.Count(g => groupWinners[g] == 1) + " | " + F(gs.Average(g => (double)groupWinners[g]))
                              + " | " + Pc(moved, pairs) + " | " + GroupName(least) + " " + Pc(groupSensitivity[least], 1.0)
                              + "; " + GroupName(most) + " " + Pc(groupSensitivity[most], 1.0) + " |");
            }
            var oneWinner = Enumerable.Range(0, Wants.Length * 2).Where(g => groupWinners[g] == 1).ToList();
            sb.AppendLine();
            sb.AppendLine("**Cells in a group where every one of the 2187 profiles forms the same intention: " + (oneWinner.Count * _minds.Length)
                          + " (" + Pc(oneWinner.Count * _minds.Length, Cells) + ")**, in " + string.Join(", ", oneWinner.Select(GroupName)) + ".");
            sb.AppendLine();

            sb.AppendLine("### Which compatible intentions can win at all");
            sb.AppendLine();
            sb.AppendLine("For every group with two or more compatible intentions, each intention is **witnessed** if it wins for some profile in the sweep, **dominated** if some rival outscores it for every possible person (a bound over the whole unit box, with value ranks relaxed to independent weights, which can only widen it), or neither.");
            sb.AppendLine();
            sb.AppendLine("| | (group, intention) pairs |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Witnessed | " + standings.Count(s => s.Witnessed) + " |");
            sb.AppendLine("| Dominated, so never able to win for anybody | " + standings.Count(s => s.DominatedBy != null) + " |");
            sb.AppendLine("| Neither: could win, never did in the sweep | " + standings.Count(s => !s.Witnessed && s.DominatedBy == null) + " |");
            sb.AppendLine("| Total | " + standings.Count + " |");
            sb.AppendLine();
            sb.AppendLine("| Group | Intention | Status |");
            sb.AppendLine("|---|---|---|");
            foreach (var s in standings.Where(s => !s.Witnessed || s.DominatedBy != null))
                sb.AppendLine("| " + GroupName(s.Group) + " | " + s.Intent + " | "
                              + (s.DominatedBy != null ? "**dominated** by " + s.DominatedBy + ": its best margin over every possible person is " + F(s.Margin)
                                                       : "not dominated, never won in the sweep") + " |");
            sb.AppendLine();

            sb.AppendLine("### Which things a rule reads can decide anything");
            sb.AppendLine();
            sb.AppendLine("A thing a rule reads can only change a winner in a group where at least two intentions that are not dominated weigh it differently. If every live rival weighs it the same, it cancels; if only a dominated or a lone intention reads it, it is idle. Measured changes are from the single-attribute moves of section F, pooled over all groups.");
            sb.AppendLine();
            sb.AppendLine("| Read | Groups where it can decide | Moves of it that changed an intention |");
            sb.AppendLine("|---|---|---|");
            var vars = _rules.SelectMany(r => r.ScaledBy).Select(VarKey).Distinct().OrderBy(v => v, StringComparer.Ordinal).ToList();
            foreach (var v in vars)
            {
                var live = new List<int>();
                for (var wi = 0; wi < Wants.Length; wi++)
                for (var ci = 0; ci < 2; ci++)
                {
                    var g = Group(wi, ci);
                    var contenders = standings.Where(s => s.Group == g && s.DominatedBy == null).Select(s => s.Intent).ToList();
                    if (contenders.Count < 2) continue;
                    var coefs = contenders.Select(x => CompatibleRules(wi, ci, x).Sum(r => { LinearOf(r).Coef.TryGetValue(v, out var c); return c; })).ToList();
                    if (coefs.Max() - coefs.Min() > 1e-12) live.Add(g);
                }
                var attr = Array.IndexOf(Attributes, v);
                var measured = attr < 0
                    ? (v.StartsWith("value") ? "no single-value move exists: values weigh by rank" : "not varied by the sweep")
                    : Enumerable.Range(0, Wants.Length * 2).Sum(g => _moved[g][attr][Sum]) + " of "
                      + Enumerable.Range(0, Wants.Length * 2).Sum(g => _pairs[g][attr][Sum]);
                sb.AppendLine("| " + v + " | " + (live.Count == 0 ? "**none**" : live.Count + ": " + string.Join(", ", live.Select(GroupName))) + " | " + measured + " |");
            }
            Record("D", sb.ToString());

            foreach (var g in byK.TryGetValue(1, out var ones) ? ones : new List<int>())
                Assert.AreEqual(0, _moved[g].Sum(x => x[Sum]), "D4: with one candidate the person cannot matter");
        }

        // ============================================================ E

        [Test, Order(5), Timeout(3600000)]
        public void E_GatingAgainstPreference()
        {
            EnsureBaseline();
            var sb = new StringBuilder();
            sb.AppendLine("## E. Gating against preference");
            sb.AppendLine();
            sb.AppendLine("A gate is a rule's `when`. It can only name circumstances. This section asks what a gate does to an intention the person would otherwise have preferred.");
            sb.AppendLine();
            sb.AppendLine("### The gates, and what they exclude");
            sb.AppendLine();
            sb.AppendLine("| Rule | Intention | Gate | Note, as authored | Gated out in | There, the intention is |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var gated = _rules.Where(r => !r.When.IsEmpty).ToList();
            foreach (var r in gated)
            {
                var gate = r.When.Alone == true ? "alone" : r.When.OthersPresentMin.HasValue ? "others present >= " + r.When.OthersPresentMin : "other";
                var outIn = new List<string>();
                var still = new List<string>();
                for (var wi = 0; wi < Wants.Length; wi++)
                for (var ci = 0; ci < 2; ci++)
                {
                    if (!r.Motives.Contains(Wants[wi], StringComparer.Ordinal) || CompatibleIn(r, wi, ci)) continue;
                    outIn.Add(GroupName(Group(wi, ci)));
                    still.Add(CompatibleRules(wi, ci, r.Intent).Count > 0
                        ? "kept by `" + string.Join("`, `", CompatibleRules(wi, ci, r.Intent).Select(x => x.Id)) + "`"
                        : "**excluded**");
                }
                sb.AppendLine("| `" + r.Id + "` | " + r.Intent + " | " + gate + " | " + (r.Note ?? "") + " | "
                              + string.Join("<br>", outIn) + " | " + string.Join("<br>", still) + " |");
            }
            sb.AppendLine();

            // Intention-level exclusions: lift the gates of that intention's rules only.
            sb.AppendLine("### Intentions a gate excludes outright");
            sb.AppendLine();
            sb.AppendLine("For each available intention that no rule leaves compatible, its own rules' gates are lifted, in memory, and nothing else. Its would-be support is what the person would give it; the last column is how often that would have won.");
            sb.AppendLine();
            sb.AppendLine("| Group | Excluded intention | Would-be support: min, median, max | Would have won, of 2187 profiles | Reading |");
            sb.AppendLine("|---|---|---|---|---|");
            var exclusions = 0;
            var overriding = 0;
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var s0 = _staged[Cell(0, wi, ci)];
                foreach (var x in s0.Available.Where(a => !s0.Compatible.Contains(a)))
                {
                    exclusions++;
                    var lifted = _rules.Select(r => r.Intent == x && r.Motives.Contains(Wants[wi], StringComparer.Ordinal)
                        ? Make(r, r.Id, when: new SituationCondition()) : r).ToList();
                    var support = new List<double>();
                    var wins = 0;
                    for (var i = 0; i < _minds.Length; i++)
                    {
                        var st = Stage(lifted, _minds[i], Moment(i, ci), Wants[wi]);
                        support.Add(st.Contributions.Where(c => c.Rule.Intent == x && c.Weight > 0.0).Sum(c => c.Weight));
                        if (Decide(st)[Sum].Winner == x) wins++;
                    }
                    support.Sort();
                    var reading = wins == 0 ? "idle: the gate decides nothing"
                        : wins == _minds.Length ? "total: the gate is all that stops it"
                        : "**overrides a preference that depends on the person**";
                    if (wins > 0 && wins < _minds.Length) overriding++;
                    sb.AppendLine("| " + GroupName(Group(wi, ci)) + " | " + x + " | " + F(support.First()) + ", " + F(support[support.Count / 2]) + ", " + F(support.Last())
                                  + " | " + wins + " (" + Pc(wins, _minds.Length) + ") | " + reading + " |");
                }
            }
            sb.AppendLine();
            sb.AppendLine("**" + exclusions + " intention-level exclusions; in " + overriding + " of them the gate overrides a preference that would have gone one way for some people and the other way for others.**");
            sb.AppendLine();

            // Reason-level exclusions: lift one rule's gate where its intention survives anyway.
            sb.AppendLine("### Reasons a gate removes while the intention stays available");
            sb.AppendLine();
            sb.AppendLine("| Group | Rule gated out | Intention kept by | Winner changed by lifting only this gate |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var r in gated)
                for (var wi = 0; wi < Wants.Length; wi++)
                for (var ci = 0; ci < 2; ci++)
                {
                    if (!r.Motives.Contains(Wants[wi], StringComparer.Ordinal) || CompatibleIn(r, wi, ci)) continue;
                    var keepers = CompatibleRules(wi, ci, r.Intent);
                    if (keepers.Count == 0) continue;
                    var lifted = _rules.Select(x => ReferenceEquals(x, r) ? Make(r, r.Id, when: new SituationCondition()) : x).ToList();
                    var changed = 0;
                    for (var i = 0; i < _minds.Length; i++)
                        if (Decide(Stage(lifted, _minds[i], Moment(i, ci), Wants[wi]))[Sum].Winner != _base[Cell(i, wi, ci)][Sum].Winner) changed++;
                    sb.AppendLine("| " + GroupName(Group(wi, ci)) + " | `" + r.Id + "` | `" + string.Join("`, `", keepers.Select(k => k.Id)) + "` | "
                                  + changed + " (" + Pc(changed, _minds.Length) + ") |");
                }
            sb.AppendLine();

            // Every gate lifted at once.
            var open = _rules.Select(r => Make(r, r.Id, when: new SituationCondition())).ToList();
            var byWant = new int[Wants.Length, 2];
            var openChanged = new int[2];
            for (var i = 0; i < _minds.Length; i++)
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
                if (Decide(Stage(open, _minds[i], Moment(i, ci), Wants[wi]))[Sum].Winner != _base[Cell(i, wi, ci)][Sum].Winner)
                {
                    byWant[wi, ci]++;
                    openChanged[ci]++;
                }
            sb.AppendLine("### Every gate lifted at once");
            sb.AppendLine();
            sb.AppendLine("| Want | Changed in company | Changed alone |");
            sb.AppendLine("|---|---|---|");
            for (var wi = 0; wi < Wants.Length; wi++)
                sb.AppendLine("| `" + Wants[wi] + "` | " + Pc(byWant[wi, 0], _minds.Length) + " | " + Pc(byWant[wi, 1], _minds.Length) + " |");
            sb.AppendLine("| **all** | **" + Pc(openChanged[0], Cells / 2) + "** | **" + Pc(openChanged[1], Cells / 2) + "** |");
            sb.AppendLine();
            sb.AppendLine("**With every gate lifted, " + (openChanged[0] + openChanged[1]) + " of " + Cells + " cells (" + Pc(openChanged[0] + openChanged[1], Cells)
                          + ") form a different intention.** In those cells the circumstance, through a gate, is what decided.");
            sb.AppendLine();

            // The discard.
            var discardCells = new List<int>();
            var discardProfiles = new HashSet<int>();
            var discardGroups = new HashSet<int>();
            var supportedShrunk = 0;
            var discardWinner = 0;
            for (var i = 0; i < _minds.Length; i++)
            for (var wi = 0; wi < Wants.Length; wi++)
            for (var ci = 0; ci < 2; ci++)
            {
                var cell = Cell(i, wi, ci);
                var s = _staged[cell];
                if (!s.Contributions.Any(c => c.Weight <= 0.0)) continue;
                discardCells.Add(cell);
                discardProfiles.Add(i);
                discardGroups.Add(Group(wi, ci));
                if (s.Supported.Count() < s.Compatible.Count) supportedShrunk++;
                if (DecideWithoutDiscard(s) != _base[cell][Sum].Winner) discardWinner++;
            }
            var discardedRules = discardCells.SelectMany(c => _staged[c].Contributions.Where(x => x.Weight <= 0.0))
                .GroupBy(x => x.Rule.Id).Select(x => "`" + x.Key + "` down to " + F(x.Min(y => y.Weight))).ToList();
            sb.AppendLine("### The discard: where a person removes a candidate");
            sb.AppendLine();
            sb.AppendLine("The selector throws away a contribution at or below zero instead of counting it. That is the one place in the mechanism where something about the person, rather than the circumstance, takes a compatible candidate out of the running.");
            sb.AppendLine();
            sb.AppendLine("| | |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Cells with a compatible contribution at or below zero | **" + discardCells.Count + "** |");
            sb.AppendLine("| Profiles | " + discardProfiles.Count + " |");
            sb.AppendLine("| Groups | " + string.Join(", ", discardGroups.OrderBy(g => g).Select(GroupName)) + " |");
            sb.AppendLine("| Rules | " + string.Join(", ", discardedRules) + " |");
            sb.AppendLine("| Cells where it shrinks the supported set below the compatible set | " + supportedShrunk + " |");
            sb.AppendLine("| Cells where counting it instead would change the winner | **" + discardWinner + "** |");
            Record("E", sb.ToString());
        }

        // ============================================================ F

        [Test, Order(6), Timeout(3600000)]
        public void F_PreferenceWithTheCandidatesFixed()
        {
            EnsurePerturbations();
            var sb = new StringBuilder();
            sb.AppendLine("## F. Preference, with the candidate set held fixed");
            sb.AppendLine();
            sb.AppendLine("The circumstance is held, so the compatible set cannot move. One attribute of the person moves: each trait to each of its other two sweep levels, each adjacent pair of value ranks swapped, each belief toggled. Where the supported set is also identical, only preference is left to change the answer.");
            sb.AppendLine();
            var allPairs = _pairs.Sum(g => g.Sum(x => x[Sum]));
            var fixedPairs = _fixedPairs.Sum(g => g.Sum());
            sb.AppendLine("| | Pairs |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| (profile, move, want, circumstance) pairs | " + allPairs + " |");
            sb.AppendLine("| Compatible set changed by moving the person | **" + _compatibleChanged + "** |");
            sb.AppendLine("| Supported set changed | " + _supportedChanged + ", of which explained by the discard: " + _supportedChangedByDiscard + " |");
            sb.AppendLine("| Supported set identical | " + fixedPairs + " |");
            sb.AppendLine();

            sb.AppendLine("### By number of compatible candidates, candidate set identical");
            sb.AppendLine();
            sb.AppendLine("| K | Pairs with the candidate set identical | Winner changed | Share |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var k in Enumerable.Range(0, Wants.Length * 2).Select(g => _staged[Cell(0, g / 2, g % 2)].Compatible.Count).Distinct().OrderBy(x => x))
            {
                var gs = Enumerable.Range(0, Wants.Length * 2).Where(g => _staged[Cell(0, g / 2, g % 2)].Compatible.Count == k).ToList();
                var p = gs.Sum(g => _fixedPairs[g].Sum());
                var m = gs.Sum(g => _fixedMoved[g].Sum(x => x[Sum]));
                sb.AppendLine("| " + k + " | " + p + " | " + m + " | " + Pc(m, p) + " |");
            }
            var contested = Enumerable.Range(0, Wants.Length * 2).Where(g => _staged[Cell(0, g / 2, g % 2)].Compatible.Count >= 2).ToList();
            var contestedPairs = contested.Sum(g => _fixedPairs[g].Sum());
            var contestedMoved = contested.Sum(g => _fixedMoved[g].Sum(x => x[Sum]));
            sb.AppendLine();
            sb.AppendLine("**With two or more candidates and the candidate set identical, moving one attribute of the person changed the intention in "
                          + contestedMoved + " of " + contestedPairs + " pairs (" + Pc(contestedMoved, contestedPairs) + ").** That is preference, separated from candidate generation.");
            sb.AppendLine();

            sb.AppendLine("### By attribute, candidate set identical, K >= 2");
            sb.AppendLine();
            sb.AppendLine("| Attribute moved | Pairs | Winner changed | Share |");
            sb.AppendLine("|---|---|---|---|");
            for (var at = 0; at < Attributes.Length; at++)
            {
                var p = contested.Sum(g => _fixedPairs[g][at]);
                var m = contested.Sum(g => _fixedMoved[g][at][Sum]);
                sb.AppendLine("| " + Attributes[at] + " | " + p + " | " + m + " | " + Pc(m, p) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### One of each, as it happened");
            sb.AppendLine();
            sb.AppendLine("The first profile in each contested group where one move changed the intention with the candidate set identical.");
            sb.AppendLine();
            sb.AppendLine("| Group | Profile | Move | Before | After |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var e in _examples) sb.AppendLine(e);
            sb.AppendLine();

            // Candidate generation, for contrast: the circumstance moves and the person does not.
            var availability = 0;
            var lost = 0;
            var reason = 0;
            for (var i = 0; i < _minds.Length; i++)
            for (var wi = 0; wi < Wants.Length; wi++)
            {
                var alone = _base[Cell(i, wi, 1)][Sum].Winner;
                var company = _base[Cell(i, wi, 0)][Sum].Winner;
                if (alone == company) continue;
                if (!_staged[Cell(i, wi, 1)].Compatible.Contains(company)) availability++;
                else if (!_staged[Cell(i, wi, 0)].Compatible.Contains(alone)) lost++;
                else reason++;
            }
            var arrivals = availability + lost + reason;
            sb.AppendLine("### For contrast: the circumstance moves and the person does not");
            sb.AppendLine();
            sb.AppendLine("The same person, alone and then with three others in the room. Each change is classified by what made it:");
            sb.AppendLine();
            sb.AppendLine("| Cause | Changes | Share |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| **Availability**: the new winner is an intention no rule offers alone | " + availability + " | " + Pc(availability, arrivals) + " |");
            sb.AppendLine("| Lost availability: the old winner is not offered in company | " + lost + " | " + Pc(lost, arrivals) + " |");
            sb.AppendLine("| **A reason gated in or out**: both intentions are available in both, and a gated rule re-weighted them | " + reason + " | " + Pc(reason, arrivals) + " |");
            sb.AppendLine("| Total | " + arrivals + " | |");
            Record("F", sb.ToString());

            Assert.AreEqual(0, _compatibleChanged, "E2/F1: the compatible set cannot depend on the person");
            Assert.AreEqual(_supportedChanged, _supportedChangedByDiscard, "F2: only the discard can move the supported set");
            Assert.AreEqual(0, Enumerable.Range(0, Wants.Length * 2).Sum(g => _moved[g][Array.IndexOf(Attributes, "trait impulsive")][Sum]),
                "F4: a trait no rule reads cannot change anything");
        }

        // ============================================================ G

        [Test, Order(7), Timeout(3600000)]
        public void G_TheAggregationFamily()
        {
            EnsurePerturbations();
            var sb = new StringBuilder();
            sb.AppendLine("## G. The aggregation family, over the same contributions");
            sb.AppendLine();
            sb.AppendLine("Stages 1 to 3 are held; only the way an intention's contributions become its score changes. None of these is proposed. Each is here to show which invariants a way of aggregating keeps and which it gives up, and none has a parameter that could be tuned toward an answer that looks human.");
            sb.AppendLine();
            sb.AppendLine("| Aggregator | Score of an intention |");
            sb.AppendLine("|---|---|");
            foreach (var a in Family) sb.AppendLine("| **" + a.Name + "** | " + a.Definition + " |");
            sb.AppendLine();

            var lookAfter = Array.IndexOf(Wants, "look_after");
            sb.AppendLine("| Aggregator | Cells whose winner differs from the sum | Distinct signatures in company | `look_after -> protect` in company | Groups with one winner across the sweep | Exact ties | Ties within 1e-9 |");
            sb.AppendLine("|---|---|---|---|---|---|---|");
            for (var a = 0; a < Family.Length; a++)
            {
                var differs = _base.Count(o => o[a].Winner != o[Sum].Winner);
                var sigs = Enumerable.Range(0, _minds.Length)
                    .Select(i => string.Join("|", Enumerable.Range(0, Wants.Length).Select(wi => Or(_base[Cell(i, wi, 0)][a].Winner))))
                    .Distinct().Count();
                var protect = Enumerable.Range(0, _minds.Length).Count(i => _base[Cell(i, lookAfter, 0)][a].Winner == "protect");
                var one = 0;
                for (var wi = 0; wi < Wants.Length; wi++)
                    for (var ci = 0; ci < 2; ci++)
                        if (Enumerable.Range(0, _minds.Length).Select(i => _base[Cell(i, wi, ci)][a].Winner).Distinct().Count() == 1) one++;
                var exact = _base.Count(o => o[a].RunnerUp != null && o[a].Margin == 0.0);
                var near = _base.Count(o => o[a].RunnerUp != null && o[a].Margin < Tie);
                sb.AppendLine("| " + Family[a].Name + " | " + differs + " (" + Pc(differs, Cells) + ") | " + sigs + " | " + Pc(protect, _minds.Length)
                              + " | " + one + " of " + (Wants.Length * 2) + " | " + exact + " | " + near + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### Which traits can move an intention, under each");
            sb.AppendLine();
            sb.AppendLine("Share of single-trait moves, in all groups, that change the intention. Gating is the same for all six, so the " + Pc(_base.Count(o => o[Sum].Supported <= 1), Cells) + " of cells with one candidate are the same for all six too.");
            sb.AppendLine();
            var traitAttrs = Enumerable.Range(0, Attributes.Length).Where(x => Attributes[x].StartsWith("trait")).ToList();
            var beliefAttrs = Enumerable.Range(0, Attributes.Length).Where(x => Attributes[x].StartsWith("belief")).ToList();
            var cols = traitAttrs.Concat(beliefAttrs).ToList();
            sb.AppendLine("| Aggregator | " + string.Join(" | ", cols.Select(x => "`" + Attributes[x].Split(' ')[1] + "`")) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", cols.Count)));
            for (var a = 0; a < Family.Length; a++)
                sb.AppendLine("| " + Family[a].Name + " | " + string.Join(" | ", cols.Select(x =>
                {
                    var p = Enumerable.Range(0, Wants.Length * 2).Sum(g => _pairs[g][x][a]);
                    var m = Enumerable.Range(0, Wants.Length * 2).Sum(g => _moved[g][x][a]);
                    return m == 0 ? "**0**" : Pc(m, p);
                })) + " |");
            Record("G", sb.ToString());
        }

        // ============================================================ H

        [Test, Order(8), Timeout(3600000)]
        public void H_RepresentationInvariance()
        {
            EnsureTransforms();
            var sb = new StringBuilder();
            sb.AppendLine("## H. Representation invariance");
            sb.AppendLine();
            sb.AppendLine("Each transformation rewrites the rule file without changing anything about any person. The count is of cells, over all " + Cells
                          + ", whose intention changed; for a per-rule transformation it is summed over the ten rules. In brackets, how many of those changes were in a cell where the top two were within 1e-9 of each other before or after: a tie in the real numbers, decided by the alphabet or by rounding.");
            sb.AppendLine();
            sb.AppendLine("| | Transformation | Should it preserve the conclusion? | " + string.Join(" | ", Family.Select(a => a.Name)) + " |");
            sb.AppendLine("|---|---|---|" + string.Concat(Enumerable.Repeat("---|", Family.Length)));

            string Cellf(int changed, int atTie) => changed == 0 ? "0" : "**" + changed + "**" + (atTie > 0 ? " (" + atTie + ")" : "");
            var rows = new List<Tuple<string, string, string, int[], int[]>>();
            for (var t = 0; t < WholeTransforms.Length; t++)
                rows.Add(Tuple.Create(WholeTransforms[t].Key, WholeTransforms[t].Label, WholeTransforms[t].Should,
                    _whole[t].Select(x => x.Changed).ToArray(), _whole[t].Select(x => x.AtTie).ToArray()));
            for (var t = 0; t < PerRuleTransforms.Length; t++)
                rows.Add(Tuple.Create(PerRuleTransforms[t].Key, PerRuleTransforms[t].Label, PerRuleTransforms[t].Should,
                    Enumerable.Range(0, Family.Length).Select(a => _perRule[t].Sum(r => r[a].Changed)).ToArray(),
                    Enumerable.Range(0, Family.Length).Select(a => _perRule[t].Sum(r => r[a].AtTie)).ToArray()));
            foreach (var row in rows.OrderBy(r => int.Parse(r.Item1.Substring(1))))
                sb.AppendLine("| " + row.Item1 + " | " + row.Item2 + " | " + row.Item3 + " | "
                              + string.Join(" | ", Enumerable.Range(0, Family.Length).Select(a => Cellf(row.Item4[a], row.Item5[a]))) + " |");
            sb.AppendLine();

            sb.AppendLine("### Preserved or violated, counting only changes that are not ties");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", Family.Select(a => a.Name)) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", Family.Length)));
            var clear = new Dictionary<string, int[]>();
            foreach (var row in rows.OrderBy(r => int.Parse(r.Item1.Substring(1))))
            {
                clear[row.Item1] = Enumerable.Range(0, Family.Length).Select(a => row.Item4[a] - row.Item5[a]).ToArray();
                sb.AppendLine("| " + row.Item1 + " | " + string.Join(" | ", clear[row.Item1].Select(c => c == 0 ? "P" : "**V**")) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### Monotonicity: where a duplicate sends the answer");
            sb.AppendLine();
            sb.AppendLine("Adding a copy of a reason for X should never make X lose. Changes from T4, by where they went:");
            sb.AppendLine();
            sb.AppendLine("| Aggregator | Toward the duplicated rule's intention | **Away from it** | Between two others | In a cell where the rule is not compatible |");
            sb.AppendLine("|---|---|---|---|---|");
            for (var a = 0; a < Family.Length; a++)
            {
                var toward = _perRule[T4].Sum(r => r[a].Toward);
                var away = _perRule[T4].Sum(r => r[a].Away);
                var changed = _perRule[T4].Sum(r => r[a].Changed);
                var outside = PerRuleTransforms.Indices().Sum(t => _perRule[t].Sum(r => r[a].Outside));
                sb.AppendLine("| " + Family[a].Name + " | " + toward + " | " + (away == 0 ? "0" : "**" + away + "**") + " | " + (changed - toward - away) + " | " + outside + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### Splitting by term, rule by rule, under the sum");
            sb.AppendLine();
            sb.AppendLine("| Rule | Changed | At a tie |");
            sb.AppendLine("|---|---|---|");
            for (var ri = 0; ri < _rules.Count; ri++)
                sb.AppendLine("| `" + _rules[ri].Id + "` | " + _perRule[T8][ri][Sum].Changed + " | " + _perRule[T8][ri][Sum].AtTie + " |");
            sb.AppendLine();

            var impossible = Enumerable.Range(0, Family.Length).Where(a => clear["T4"][a] == 0 && clear["T6"][a] == 0 && clear["T9"][a] > 0).ToList();
            sb.AppendLine("### The impossibility, checked");
            sb.AppendLine();
            sb.AppendLine("No aggregator of anonymous contributions can be invariant to duplication (T4) and to proportional splitting (T6) and still respond to weight (T9). Aggregators here that show all three: **"
                          + (impossible.Count == 0 ? "none" : string.Join(", ", impossible.Select(a => Family[a].Name))) + "**.");
            sb.AppendLine();
            sb.AppendLine("| Aggregator | T4 duplicate | T6 split | T9 scale x 2 | Gives up |");
            sb.AppendLine("|---|---|---|---|---|");
            for (var a = 0; a < Family.Length; a++)
            {
                var gives = new List<string>();
                if (clear["T4"][a] > 0) gives.Add("duplication");
                if (clear["T6"][a] > 0) gives.Add("splitting");
                if (clear["T9"][a] == 0) gives.Add("**weight**");
                sb.AppendLine("| " + Family[a].Name + " | " + (clear["T4"][a] == 0 ? "P" : "V") + " | " + (clear["T6"][a] == 0 ? "P" : "V") + " | "
                              + (clear["T9"][a] == 0 ? "no response" : "responds") + " | " + string.Join(", ", gives) + " |");
            }
            Record("H", sb.ToString());

            Assert.IsEmpty(impossible, "the theorem: no aggregator of anonymous contributions keeps duplication and splitting and responds to weight");
            Assert.AreEqual(0, PerRuleTransforms.Indices().Sum(t => _perRule[t].Sum(r => r.Sum(x => x.Outside))),
                "locality: rewriting a rule can only change cells where it is compatible");
        }

        // ============================================================ Z

        [Test, Order(9)]
        public void Z_TheRuleFileIsUntouchedAfterEverything()
        {
            var sha = Sha(_rulePath);
            Record("Z", "## Z. The frozen file after the whole run\n\n**sha256: `" + sha + "` — "
                        + (sha == FrozenSha ? "unchanged.**" : "**CHANGED**.**") + " Every rewritten rule set above was built in memory.\n");
            Assert.AreEqual(FrozenSha, sha, "the rule file must still be byte-identical after the run");
        }
    }

    static class IndexExtensions
    {
        public static IEnumerable<int> Indices<T>(this IReadOnlyCollection<T> list) => Enumerable.Range(0, list.Count);
    }
}
