using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using Candidate = Fallow.Tests.Core.IntentionSelector.Candidate;
using Formed = Fallow.Tests.Core.IntentionSelector.Formed;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// Does the intention-formation mechanism encode reusable relationships
    /// between a want, a person and a situation, or is it a table fitted to four
    /// people?
    ///
    /// The ten candidate rules are **frozen**: the file is hashed at the start of
    /// the run and again at the end, and nothing is added for a held-out person.
    /// The holdout is four declared people placed outside the shipped cast's
    /// trait ranges by a stated principle, and a mechanical sweep of 2,187
    /// profiles that enumerates trait space and that nobody designed.
    ///
    /// The second question is kept separate from the first. A mechanism can
    /// generalize perfectly and still rank intentions for a bad reason, so the
    /// rule-count experiment (G6) is run and reported on its own.
    ///
    /// No production change of any kind. Writes
    /// `Docs/experiments/intention-generalization/measurements.md`.
    /// </summary>
    public class IntentionGeneralizationExperimentTests
    {
        const string FrozenSha = "61e6412e8a7cb77674f0c7685e4cb0e5f7dca5db3ad05f928a63f34dfb099d92";

        static Scenario001Content _content;
        static IReadOnlyList<Candidate> _rules;
        static string _rulePath;
        static HeldOut _heldOut;
        static RoomGraph _house;
        static string _kitchen;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static readonly string[] Cast = { "daniel", "elena", "leo", "mara" };
        static readonly string[] Wants =
            { "avoid_exposure", "find_out", "get_food", "guard_supplies", "keep_peace", "look_after", "restore_standing" };

        [OneTimeSetUp]
        public void Load()
        {
            _content = Baselines.Primary();
            _rulePath = Path.Combine(TestPaths.DataRoot, "Experiments", "intentions.json");
            _rules = IntentionSelector.Load(_rulePath);
            _heldOut = HeldOut.Load(Path.Combine(TestPaths.DataRoot, "Experiments", "held-out-people.json"));

            var run = Scenario001.Prepare(_content, _content.Morning.Variants[0].Id, 1);
            _house = run.World.House;
            _kitchen = _house.Rooms.First(r => r.HasTag(ActionCatalog.PantryTag)).Id;
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Intention formation, generalization: measurements");
            sb.AppendLine();
            sb.AppendLine("Generated by `IntentionGeneralizationExperimentTests` against the frozen candidate rules, whose hash is checked at the start and the end of the run. The held-out people were declared and committed before any of them was run. The selector has no randomness.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "intention-generalization");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "measurements.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string Or(string s) => string.IsNullOrEmpty(s) ? "none" : s;
        static string Pc(double part, double whole)
            => whole == 0 ? "n/a" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + " %";

        static string Sha(string path)
        {
            using (var sha = SHA256.Create())
                return string.Concat(sha.ComputeHash(File.ReadAllBytes(path)).Select(b => b.ToString("x2")));
        }

        // ============================================================ the held-out people

        sealed class Declared
        {
            public string Id;
            public string Principle;
            public int Age;
            public string Role;
            public Dictionary<string, double> Traits;
            public List<string> Values;
            public List<BeliefSeed> Beliefs;
        }

        sealed class HeldOut
        {
            public List<Declared> People = new List<Declared>();
            public List<string> SweepTraits = new List<string>();
            public List<double> Levels = new List<double>();
            public List<string> ValueRing = new List<string>();
            public List<List<BeliefSeed>> BeliefSets = new List<List<BeliefSeed>>();

            public static HeldOut Load(string path)
            {
                var root = JObject.Parse(File.ReadAllText(path));
                var h = new HeldOut();
                foreach (var d in (JArray)root["declared"])
                    h.People.Add(new Declared
                    {
                        Id = d["id"].Value<string>(),
                        Principle = d["principle"].Value<string>(),
                        Age = d["age"].Value<int>(),
                        Role = d["family_role"].Value<string>(),
                        Traits = ((JObject)d["traits"]).Properties().ToDictionary(x => x.Name, x => x.Value.Value<double>()),
                        Values = ((JArray)d["values"]).Select(x => x.Value<string>()).ToList(),
                        Beliefs = Seeds(d["beliefs"] as JArray, d["id"].Value<string>())
                    });

                var s = (JObject)root["sweep"];
                h.SweepTraits = ((JArray)s["traits"]).Select(x => x.Value<string>()).ToList();
                h.Levels = ((JArray)s["levels"]).Select(x => x.Value<double>()).ToList();
                h.ValueRing = ((JArray)s["value_ring"]).Select(x => x.Value<string>()).ToList();
                foreach (var set in (JArray)s["belief_sets"])
                    h.BeliefSets.Add(Seeds(set as JArray, null));
                return h;
            }

            static List<BeliefSeed> Seeds(JArray node, string self)
            {
                var list = new List<BeliefSeed>();
                if (node == null) return list;
                foreach (var b in node)
                    list.Add(new BeliefSeed(
                        b["predicate"].Value<string>(),
                        ((JArray)b["args"]).Select(a => a.Value<string>()).ToList(),
                        b["confidence"].Value<double>()));
                return list;
            }
        }

        /// <summary>A mind from a bare specification, with `$self` in a belief resolved to them.</summary>
        static Mind Person(string id, IReadOnlyDictionary<string, double> traits,
            IReadOnlyList<string> values, IReadOnlyList<BeliefSeed> beliefs,
            int age = 30, string role = "sibling")
        {
            var profile = new Profile(id, id, age, role, traits, values, 0.5,
                new Dictionary<string, double>(), new List<BeliefSeed>());
            var mind = new Mind(profile);
            foreach (var b in beliefs ?? new List<BeliefSeed>())
                mind.Beliefs.Seed(new BeliefSeed(
                    b.Predicate, b.Args.Select(a => a == "$self" ? id : a).ToList(), b.Confidence));
            return mind;
        }

        static Mind FromDeclared(Declared d) => Person(d.Id, d.Traits, d.Values, d.Beliefs, d.Age, d.Role);

        static Mind FromCast(string who)
        {
            var mind = new Mind(_content.Cast[who]);
            foreach (var b in _content.Cast[who].InitialBeliefs) mind.Beliefs.Seed(b);
            return mind;
        }

        /// <summary>
        /// The i-th profile of the sweep: the traits are the base-3 digits of i
        /// over the seven trait names, the values are the ring rotated by i, and
        /// the beliefs are set (i mod 4). Nobody chose any of it.
        /// </summary>
        static Mind Sweep(int i)
        {
            var traits = new Dictionary<string, double>(StringComparer.Ordinal);
            var n = i;
            foreach (var name in _heldOut.SweepTraits)
            {
                traits[name] = _heldOut.Levels[n % _heldOut.Levels.Count];
                n /= _heldOut.Levels.Count;
            }
            var shift = i % _heldOut.ValueRing.Count;
            var values = _heldOut.ValueRing.Skip(shift).Concat(_heldOut.ValueRing.Take(shift)).ToList();
            return Person("p" + i, traits, values, _heldOut.BeliefSets[i % _heldOut.BeliefSets.Count]);
        }

        static int SweepSize =>
            (int)Math.Pow(_heldOut.Levels.Count, _heldOut.SweepTraits.Count);

        // ============================================================ situations

        static Percept At(string who, IReadOnlyList<string> present, double hunger = 0.3, string roomId = null)
        {
            var room = _house.Get(roomId ?? _kitchen);
            var holdsFood = room.HasTag(ActionCatalog.PantryTag);
            return new Percept(who, 10, room, present, _house.Adjacent(room.Id), hunger,
                holdsFood, holdsFood ? (bool?)true : null, false, _house, false, null, null);
        }

        static readonly IReadOnlyList<string> Nobody = new List<string>();
        static readonly IReadOnlyList<string> Others = new List<string> { "a", "b", "c" };

        static Motive Want(string key, string target = null)
            => new Motive(key, target, 0.6, new List<string>(), new List<ScalerTerm>());

        static Formed Form(IReadOnlyList<Candidate> rules, Mind mind, Percept p, string want)
            => IntentionSelector.Form(rules, mind, p, Want(want, want == "look_after" ? "a" : null),
                _content.Morning.Day, _content.Rules.Deciding.RecallHalfLife);

        static Formed Form(Mind mind, Percept p, string want) => Form(_rules, mind, p, want);

        /// <summary>The intention this person forms for each want, in order: their signature.</summary>
        static string Signature(IReadOnlyList<Candidate> rules, Mind mind, Percept p)
            => string.Join("|", Wants.Select(w => Or(Form(rules, mind, p, w).Intent)));

        // ============================================================ G1

        [Test]
        public void WhatIsFrozenAndWhetherItNamesAnybody()
        {
            var sha = Sha(_rulePath);
            var sb = new StringBuilder();
            sb.AppendLine("## G1. The frozen rules, and whether they know anybody's name");
            sb.AppendLine();
            sb.AppendLine("| | |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| File | `Assets/_Project/Data/Experiments/intentions.json` |");
            sb.AppendLine("| sha256 at the start of this run | `" + sha + "` |");
            sb.AppendLine("| Expected | `" + FrozenSha + "` |");
            sb.AppendLine("| Match | " + (sha == FrozenSha ? "**yes**" : "**NO**") + " |");
            sb.AppendLine("| Rules | " + _rules.Count + " |");
            sb.AppendLine();

            var names = Cast.Concat(_heldOut.People.Select(p => p.Id)).ToList();
            var hits = new List<string>();
            foreach (var c in _rules)
            {
                var text = string.Join(" ", new[] { c.Id, c.Intent, string.Join(" ", c.Motives) }
                    .Concat(c.ScaledBy.Select(s => string.Join(" ", new[]
                    {
                        s.Kind, s.Name, s.Predicate, s.Entry, s.About, s.Topic, s.By, s.Target,
                        string.Join(" ", s.Args ?? new List<string>())
                    }.Where(x => x != null)))));
                foreach (var n in names)
                    if (text.IndexOf(n, StringComparison.OrdinalIgnoreCase) >= 0) hits.Add(c.Id + " mentions " + n);
            }
            sb.AppendLine("**Character names or ids anywhere in a rule's id, intent, wants, or any scaler's kind, name, predicate, entry, about, topic, by, target or arguments: " + hits.Count + ".** "
                          + (hits.Count == 0 ? "The only person-token any rule uses is `$self`, which is whoever is deciding."
                                             : string.Join("; ", hits)));
            sb.AppendLine();

            sb.AppendLine("### What generic state the rules actually read");
            sb.AppendLine();
            sb.AppendLine("| Kind | Names read | Names in the vocabulary that no rule reads |");
            sb.AppendLine("|---|---|---|");
            var traitsRead = _rules.SelectMany(c => c.ScaledBy).Where(s => s.Kind == ScalerKind.Trait)
                .Select(s => s.Name).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();
            var valuesRead = _rules.SelectMany(c => c.ScaledBy).Where(s => s.Kind == ScalerKind.Value)
                .Select(s => s.Name).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();
            var otherKinds = _rules.SelectMany(c => c.ScaledBy).Select(s => s.Kind).Distinct()
                .Where(k => k != ScalerKind.Trait && k != ScalerKind.Value)
                .OrderBy(s => s, StringComparer.Ordinal).ToList();
            sb.AppendLine("| trait | " + string.Join(", ", traitsRead) + " | **"
                          + string.Join(", ", _content.Vocabulary.Traits.Except(traitsRead).OrderBy(s => s, StringComparer.Ordinal)) + "** |");
            sb.AppendLine("| value | " + string.Join(", ", valuesRead) + " | **"
                          + string.Join(", ", _content.Vocabulary.Values.Except(valuesRead).OrderBy(s => s, StringComparer.Ordinal)) + "** |");
            sb.AppendLine("| other | " + string.Join(", ", otherKinds) + " | - |");
            sb.AppendLine();
            sb.AppendLine("Ten rules cannot read seven traits and six values evenly, and they do not. What they do not read at all is as much a fact about the mechanism as what they do.");
            Record("G1", sb.ToString());

            Assert.AreEqual(FrozenSha, sha, "the rule file must be byte-identical to the one the predictions were written against");
            Assert.AreEqual(0, hits.Count, "P6/P10: no rule may name a character");
        }

        // ============================================================ G2

        [Test]
        public void TheDeclaredFourAgainstTheCast()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## G2. Four held-out people, beside the four the rules were written knowing");
            sb.AppendLine();
            sb.AppendLine("Each held-out person is placed by a stated principle outside the region the shipped cast occupies. The cast is nowhere below 0.50 on empathetic or honest, nowhere above 0.70 on cautious, and never high on dominant and empathetic together.");
            sb.AppendLine();
            sb.AppendLine("| Person | Held out | Principle | Traits | Values | Beliefs |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var d in _heldOut.People)
                sb.AppendLine("| **" + d.Id + "** | yes | " + d.Principle + " | "
                              + string.Join(", ", d.Traits.OrderBy(t => t.Key, StringComparer.Ordinal).Select(t => t.Key + " " + F(t.Value)))
                              + " | " + string.Join(", ", d.Values)
                              + " | " + (d.Beliefs.Count == 0 ? "none" : string.Join(", ", d.Beliefs.Select(b => b.ToString()))) + " |");
            foreach (var who in Cast)
            {
                var p = _content.Cast[who];
                sb.AppendLine("| " + who + " | no | shipped | "
                              + string.Join(", ", _content.Vocabulary.Traits.OrderBy(s => s, StringComparer.Ordinal).Select(t => t + " " + F(p.Trait(t))))
                              + " | " + string.Join(", ", p.Values)
                              + " | " + (p.InitialBeliefs.Count == 0 ? "none" : string.Join(", ", p.InitialBeliefs.Select(b => b.ToString()))) + " |");
            }
            sb.AppendLine();

            foreach (var context in new[] { "with three others in the room", "alone" })
            {
                var present = context == "alone" ? Nobody : Others;
                sb.AppendLine("### " + context);
                sb.AppendLine();
                sb.AppendLine("| Want | " + string.Join(" | ", _heldOut.People.Select(d => "**" + d.Id + "**")) + " | "
                              + string.Join(" | ", Cast) + " |");
                sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", _heldOut.People.Count + Cast.Length)));
                foreach (var w in Wants)
                {
                    var cells = _heldOut.People.Select(d => Form(FromDeclared(d), At(d.Id, present), w).Line)
                        .Concat(Cast.Select(c => Form(FromCast(c), At(c, present), w).Line));
                    sb.AppendLine("| `" + w + "` | " + string.Join(" | ", cells) + " |");
                }
                sb.AppendLine();
            }

            var heldOutFormed = _heldOut.People.SelectMany(d => Wants.Select(w =>
                Form(FromDeclared(d), At(d.Id, Others), w).Intent)).Count(i => i != null);
            var heldOutDistinct = _heldOut.People.SelectMany(d => Wants.Select(w =>
                Form(FromDeclared(d), At(d.Id, Others), w).Intent)).Where(i => i != null).Distinct().Count();
            sb.AppendLine("**The frozen rules formed an intention in " + heldOutFormed + " of "
                          + (_heldOut.People.Count * Wants.Length) + " held-out (person, want) cells in company, using "
                          + heldOutDistinct + " distinct intentions.**");
            Record("G2", sb.ToString());

            Assert.Greater(heldOutFormed, 0, "P1: the rules must transfer at all");
            Assert.Greater(heldOutDistinct, 1, "P1: more than one intention must be reachable off the cast");
        }

        // ============================================================ G3

        [Test]
        [Timeout(600000)]
        public void TheSweep()
        {
            var n = SweepSize;
            var company = At("x", Others);
            var alone = At("x", Nobody);

            var byWant = Wants.ToDictionary(w => w, w => new Dictionary<string, int>(StringComparer.Ordinal), StringComparer.Ordinal);
            var signatures = new Dictionary<string, int>(StringComparer.Ordinal);
            var flippedOnAudience = 0;
            var lookAfterEscapes = new List<string>();
            var theftInnocent = 0;
            var theftTotal = 0;

            for (var i = 0; i < n; i++)
            {
                var mind = Sweep(i);
                var p = At(mind.Id, Others);
                var a = At(mind.Id, Nobody);

                var sig = new List<string>();
                var flipped = false;
                foreach (var w in Wants)
                {
                    var inCompany = Form(mind, p, w);
                    var byThemselves = Form(mind, a, w);
                    sig.Add(Or(inCompany.Intent));

                    var key = Or(inCompany.Intent);
                    byWant[w].TryGetValue(key, out var c);
                    byWant[w][key] = c + 1;

                    if (inCompany.Intent != byThemselves.Intent) flipped = true;

                    if (w == "look_after" && inCompany.Intent != "protect" && inCompany.Intent != null)
                        lookAfterEscapes.Add(mind.Id + " in company -> " + inCompany.Intent);
                    if (w == "look_after" && byThemselves.Intent != "protect" && byThemselves.Intent != null)
                        lookAfterEscapes.Add(mind.Id + " alone -> " + byThemselves.Intent);

                    if (w == "get_food" || w == "avoid_exposure")
                    {
                        if (inCompany.Intent == "took_what_was_not_mine")
                        {
                            theftTotal++;
                            if (mind.Beliefs.Confidence("answerable_for", new[] { mind.Id, "missing_can" }) <= 0.0) theftInnocent++;
                        }
                    }
                }
                if (flipped) flippedOnAudience++;
                var s = string.Join("|", sig);
                signatures.TryGetValue(s, out var sc);
                signatures[s] = sc + 1;
            }

            var sb = new StringBuilder();
            sb.AppendLine("## G3. The sweep: " + n + " profiles nobody designed");
            sb.AppendLine();
            sb.AppendLine("Every combination of the seven shipped traits at three levels, with values and beliefs rotating by index. The frozen rules have never seen any of them.");
            sb.AppendLine();
            sb.AppendLine("| Want | Distinct intentions across the sweep | Distribution, in company |");
            sb.AppendLine("|---|---|---|");
            foreach (var w in Wants)
            {
                var dist = byWant[w].Where(k => k.Key != "none").OrderByDescending(k => k.Value)
                    .ThenBy(k => k.Key, StringComparer.Ordinal).ToList();
                sb.AppendLine("| `" + w + "` | " + dist.Count + " | "
                              + string.Join(", ", dist.Select(k => "`" + k.Key + "` " + Pc(k.Value, n))) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("| | Value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Profiles | " + n + " |");
            sb.AppendLine("| **Distinct signatures** (the seven intentions a profile forms, in order) | **" + signatures.Count + "** |");
            sb.AppendLine("| Most common signature, share of profiles | " + Pc(signatures.Values.Max(), n) + " |");
            sb.AppendLine("| Profiles whose intention changed on the audience alone | " + flippedOnAudience + " | ");
            sb.AppendLine();
            sb.AppendLine("A mechanism that were a table keyed on the want would produce **one** signature. " + signatures.Count + " is what a function of the person produces.");
            sb.AppendLine();
            sb.AppendLine("The five most common signatures:");
            sb.AppendLine();
            sb.AppendLine("| Share | " + string.Join(" | ", Wants.Select(w => "`" + w + "`")) + " |");
            sb.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", Wants.Length)));
            foreach (var s in signatures.OrderByDescending(k => k.Value).Take(5))
                sb.AppendLine("| " + Pc(s.Value, n) + " | " + string.Join(" | ", s.Key.Split('|')) + " |");
            sb.AppendLine();

            sb.AppendLine("### How often the person cannot matter at all");
            sb.AppendLine();
            sb.AppendLine("An intention is chosen by comparing candidates. Where the circumstances leave only one intention with any candidate matching, there is nothing to compare and the person is irrelevant by construction, however elaborate their scalers.");
            sb.AppendLine();
            sb.AppendLine("| Want | In company | Alone |");
            sb.AppendLine("|---|---|---|");
            var uncontestedCells = 0;
            var allCells = 0;
            foreach (var w in Wants)
            {
                var cols = new List<string>();
                foreach (var present in new[] { Others, Nobody })
                {
                    var only = 0;
                    for (var i = 0; i < n; i++)
                    {
                        var mind = Sweep(i);
                        var f = Form(mind, At(mind.Id, present), w);
                        allCells++;
                        if (f.Considered.Count <= 1) { only++; uncontestedCells++; }
                    }
                    cols.Add(Pc(only, n) + " of profiles");
                }
                sb.AppendLine("| `" + w + "` | " + string.Join(" | ", cols) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**" + Pc(uncontestedCells, allCells) + " of all " + allCells
                          + " (profile, want, context) cells had only one intention in the running.** In those, every profile in the sweep forms the same intention, and no amount of psychology could change it.");
            sb.AppendLine();

            sb.AppendLine("### The known failure, off the cast");
            sb.AppendLine();
            sb.AppendLine("`look_after` collapsed to `protect` in 851 of 851 decisions on the shipped cast. Across " + n
                          + " held-out profiles in two contexts, the number of times anything else won: **" + lookAfterEscapes.Count + "**.");
            if (lookAfterEscapes.Count > 0)
                sb.AppendLine("Examples: " + string.Join("; ", lookAfterEscapes.Take(5)) + ".");
            sb.AppendLine();
            sb.AppendLine("### The innocent theft, off the cast");
            sb.AppendLine();
            sb.AppendLine("`took_what_was_not_mine` was formed " + theftTotal + " times in company across the sweep, of which **"
                          + theftInnocent + "** (" + Pc(theftInnocent, theftTotal) + ") were by a profile holding no belief that they are answerable for anything.");
            Record("G3", sb.ToString());

            Assert.Greater(signatures.Count, 1, "P1: a table would produce one signature");
        }

        // ============================================================ G4

        [Test]
        [Timeout(600000)]
        public void WhatMovesItAndWhatDoesNot()
        {
            var n = SweepSize;
            var sb = new StringBuilder();
            sb.AppendLine("## G4. Counterfactuals on held-out people");
            sb.AppendLine();
            sb.AppendLine("Each perturbation is applied to the whole sweep, one thing at a time, everything else held. A cell is one (profile, want) pair: " + (n * Wants.Length) + " of them.");
            sb.AppendLine();

            var cells = 0;
            var c1 = 0;   // relevant circumstance: company
            var c2a = 0;  // irrelevant: hunger
            var c2b = 0;  // irrelevant: food in the room
            var c3a = 0;  // belief: role_claim
            var c3b = 0;  // belief: answerable_for
            var c5 = 0;   // reachable set differs between wants

            for (var i = 0; i < n; i++)
            {
                var mind = Sweep(i);
                var basis = At(mind.Id, Nobody, hunger: 0.3);
                var withCompany = At(mind.Id, Others, hunger: 0.3);
                var hungry = At(mind.Id, Nobody, hunger: 0.95);
                var elsewhere = At(mind.Id, Nobody, hunger: 0.3,
                    roomId: _house.Rooms.First(r => !r.HasTag(ActionCatalog.PantryTag)).Id);

                var claiming = Person(mind.Id, TraitsOf(mind), mind.Profile.Values,
                    Seeds(mind).Concat(new[] { new BeliefSeed("role_claim", new[] { "$self", "leads_family" }, 0.95) }).ToList());
                var answerable = Person(mind.Id, TraitsOf(mind), mind.Profile.Values,
                    Seeds(mind).Concat(new[] { new BeliefSeed("answerable_for", new[] { "$self", "missing_can" }, 0.95) }).ToList());

                var reachable = new HashSet<string>(StringComparer.Ordinal);
                foreach (var w in Wants)
                {
                    var b = Form(mind, basis, w).Intent;
                    cells++;
                    if (b != Form(mind, withCompany, w).Intent) c1++;
                    if (b != Form(mind, hungry, w).Intent) c2a++;
                    if (b != Form(mind, elsewhere, w).Intent) c2b++;
                    if (b != Form(claiming, basis, w).Intent) c3a++;
                    if (b != Form(answerable, basis, w).Intent) c3b++;
                    reachable.Add(Or(b));
                }
                if (reachable.Count > 1) c5++;
            }

            sb.AppendLine("| Perturbation | Read by a rule | Cells whose intention changed | Share |");
            sb.AppendLine("|---|---|---|---|");
            sb.AppendLine("| C1 three others come into the room | **yes**, six rules gate on it | " + c1 + " | " + Pc(c1, cells) + " |");
            sb.AppendLine("| C3 they come to believe they lead the family (0 -> 0.95) | **yes**, two rules scale on it | " + c3a + " | " + Pc(c3a, cells) + " |");
            sb.AppendLine("| C3 they come to believe they are answerable for the can (0 -> 0.95) | **yes**, one rule scales on it | " + c3b + " | " + Pc(c3b, cells) + " |");
            sb.AppendLine("| C2 hunger 0.30 -> 0.95 | **no rule reads it** | **" + c2a + "** | " + Pc(c2a, cells) + " |");
            sb.AppendLine("| C2 moved to a room with no food | **no rule reads it** | **" + c2b + "** | " + Pc(c2b, cells) + " |");
            sb.AppendLine();
            sb.AppendLine("| C5 | the want itself | profiles for which changing the want changes the intention | " + c5 + " of " + n + ", " + Pc(c5, n) + " |");
            sb.AppendLine();

            // C4: one trait at a time, over the whole sweep.
            sb.AppendLine("### C4. One trait at a time");
            sb.AppendLine();
            sb.AppendLine("Every seventh profile in the sweep, in both contexts, with a single trait forced low and then high and nothing else touched. Both contexts matter: four of the ten rules are gated on being alone or on having company, so a trait only those rules read would look deaf if it were asked in one context only.");
            sb.AppendLine();
            sb.AppendLine("| Trait | Read by a rule | Cells changed by moving it 0.15 -> 0.85 | Share |");
            sb.AppendLine("|---|---|---|---|");
            var traitsRead = _rules.SelectMany(c => c.ScaledBy).Where(s => s.Kind == ScalerKind.Trait)
                .Select(s => s.Name).Distinct().ToList();
            var byTrait = new List<Tuple<string, int>>();
            foreach (var trait in _content.Vocabulary.Traits.OrderBy(s => s, StringComparer.Ordinal))
            {
                var moved = 0;
                var seen = 0;
                for (var i = 0; i < n; i += 7)   // every seventh profile, deterministic, for speed
                {
                    var baseMind = Sweep(i);
                    var lowTraits = TraitsOf(baseMind);
                    lowTraits[trait] = 0.15;
                    var highTraits = TraitsOf(baseMind);
                    highTraits[trait] = 0.85;
                    var low = Person(baseMind.Id, lowTraits, baseMind.Profile.Values, Seeds(baseMind));
                    var high = Person(baseMind.Id, highTraits, baseMind.Profile.Values, Seeds(baseMind));
                    foreach (var p in new[] { At(baseMind.Id, Others), At(baseMind.Id, Nobody) })
                    foreach (var w in Wants)
                    {
                        seen++;
                        if (Form(low, p, w).Intent != Form(high, p, w).Intent) moved++;
                    }
                }
                byTrait.Add(Tuple.Create(trait, moved));
                sb.AppendLine("| `" + trait + "` | " + (traitsRead.Contains(trait) ? "yes" : "**no**")
                              + " | " + moved + " | " + Pc(moved, seen) + " |");
            }
            sb.AppendLine();
            var deaf = byTrait.Where(t => t.Item2 == 0).Select(t => t.Item1).ToList();
            sb.AppendLine("**Traits that never changed an intention: " + (deaf.Count == 0 ? "none" : string.Join(", ", deaf.Select(d => "`" + d + "`"))) + ".**");
            Record("G4", sb.ToString());

            Assert.AreEqual(0, c2a, "P4: hunger is read by no rule and must never move an intention");
            Assert.AreEqual(0, c2b, "P4: a foodless room is read by no rule and must never move an intention");
            Assert.Greater(c1, 0, "P2: a circumstance the rules read must sometimes move it");
            Assert.Greater(c3a + c3b, 0, "P3: a belief the rules read must sometimes move it");
        }

        static Dictionary<string, double> TraitsOf(Mind m)
            => _content.Vocabulary.Traits.ToDictionary(t => t, t => m.Profile.Trait(t), StringComparer.Ordinal);

        static List<BeliefSeed> Seeds(Mind m)
            => m.Beliefs.All.Select(b => new BeliefSeed(b.Predicate, b.Args, b.Confidence)).ToList();

        // ============================================================ G5

        [Test]
        public void DeterministicOffTheCast()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## G5. Replay");
            sb.AppendLine();
            var first = new List<string>();
            var second = new List<string>();
            for (var i = 0; i < 300; i++)
            {
                var m = Sweep(i * 7 % SweepSize);
                first.Add(Signature(_rules, m, At(m.Id, Others)));
            }
            for (var i = 0; i < 300; i++)
            {
                var m = Sweep(i * 7 % SweepSize);
                second.Add(Signature(_rules, m, At(m.Id, Others)));
            }
            var same = first.Where((x, i) => x == second[i]).Count();
            sb.AppendLine("**" + same + " of " + first.Count + " held-out signatures identical on replay.** The selector draws no random number, so this is exact rather than probable.");
            Record("G5", sb.ToString());
            CollectionAssert.AreEqual(first, second, "P7");
        }

        // ============================================================ G6

        [Test]
        [Timeout(900000)]
        public void TheRuleCountExperiment()
        {
            var n = SweepSize;
            var step = 7;   // every seventh profile, deterministic
            var sb = new StringBuilder();
            sb.AppendLine("## G6. Does having more rules beat having more weight");
            sb.AppendLine();
            sb.AppendLine("This is the second question and it is not about generalization. Contributions for one intention are **summed**. So two things that look different on the page may be the same arithmetic, and the way to find out is to separate them.");
            sb.AppendLine();
            sb.AppendLine("Three conditions, same people, same wants, same circumstances, same beliefs, same traits, same values:");
            sb.AppendLine();
            sb.AppendLine("| | Rules | Total weight for that intention |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| **A** frozen | 10 | unchanged |");
            sb.AppendLine("| **B** plus an exact clone of one rule under a new id | 11 | **doubled** for that intention |");
            sb.AppendLine("| **C** with one rule split into two halves | 11 | **unchanged** |");
            sb.AppendLine();
            sb.AppendLine("Nothing on disk changes: B and C are built in memory from the frozen rules.");
            sb.AppendLine();
            sb.AppendLine("| Rule cloned or split | Intention | Cells changed by **cloning** it (B) | Cells changed by **splitting** it (C) |");
            sb.AppendLine("|---|---|---|---|");

            var cloneTotal = 0;
            var splitTotal = 0;
            var cells = 0;
            foreach (var rule in _rules)
            {
                var cloned = _rules.Concat(new[] { rule.CloneAs(rule.Id + "_again") }).ToList();
                var split = _rules.Where(r => r.Id != rule.Id)
                    .Concat(new[] { rule.CloneAs(rule.Id + "_a", 0.5), rule.CloneAs(rule.Id + "_b", 0.5) }).ToList();

                var clonedMoved = 0;
                var splitMoved = 0;
                var seen = 0;
                for (var i = 0; i < n; i += step)
                {
                    var mind = Sweep(i);
                    foreach (var p in new[] { At(mind.Id, Others), At(mind.Id, Nobody) })
                    foreach (var w in Wants)
                    {
                        var a = Form(_rules, mind, p, w).Intent;
                        seen++;
                        if (Form(cloned, mind, p, w).Intent != a) clonedMoved++;
                        if (Form(split, mind, p, w).Intent != a) splitMoved++;
                    }
                }
                cells = seen;
                cloneTotal += clonedMoved;
                splitTotal += splitMoved;
                sb.AppendLine("| `" + rule.Id + "` | `" + rule.Intent + "` | " + clonedMoved + " (" + Pc(clonedMoved, seen) + ") | "
                              + splitMoved + " (" + Pc(splitMoved, seen) + ") |");
            }
            sb.AppendLine();
            sb.AppendLine("**Over " + cells + " cells per rule and " + _rules.Count + " rules: cloning changed the intention "
                          + cloneTotal + " times; splitting changed it " + splitTotal + " times.**");
            sb.AppendLine();
            sb.AppendLine("Splitting a rule in two adds a rule and adds no weight. Cloning a rule adds a rule and doubles the weight. If the count mattered, both would move the answer. Only one does, which means **the rule count is not the bias; the sum is.** Writing a second rule for an intention and raising the first rule's numbers are the same operation as far as the mechanism can tell.");
            sb.AppendLine();

            // And the specific diagnosis for look_after, by removal rather than repair.
            sb.AppendLine("### `look_after`, diagnosed by removal");
            sb.AppendLine();
            sb.AppendLine("Not a fix. The frozen file is untouched; this asks what the collapse is made of by running the sweep with one rule withheld in memory.");
            sb.AppendLine();
            sb.AppendLine("| Rules used | Distinct intentions for `look_after` across the sweep | Distribution |");
            sb.AppendLine("|---|---|---|");
            foreach (var withheld in new[] { (string)null, "keeping_it_off_them", "standing_between_them_and_it" })
            {
                var rules = withheld == null ? _rules : _rules.Where(r => r.Id != withheld).ToList();
                var dist = new Dictionary<string, int>(StringComparer.Ordinal);
                for (var i = 0; i < n; i += step)
                {
                    var mind = Sweep(i);
                    foreach (var p in new[] { At(mind.Id, Others), At(mind.Id, Nobody) })
                    {
                        var key = Or(Form(rules, mind, p, "look_after").Intent);
                        dist.TryGetValue(key, out var c);
                        dist[key] = c + 1;
                    }
                }
                var total = dist.Values.Sum();
                sb.AppendLine("| " + (withheld == null ? "**all ten, as frozen**" : "without `" + withheld + "`") + " | "
                              + dist.Count(k => k.Key != "none") + " | "
                              + string.Join(", ", dist.OrderByDescending(k => k.Value).ThenBy(k => k.Key, StringComparer.Ordinal)
                                  .Select(k => "`" + k.Key + "` " + Pc(k.Value, total))) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("The frozen hash is checked again at the end of this test to show that none of this touched the file.");
            var shaAfter = Sha(_rulePath);
            sb.AppendLine();
            sb.AppendLine("**sha256 after the whole run: `" + shaAfter + "` — " + (shaAfter == FrozenSha ? "unchanged." : "**CHANGED**.") + "**");
            Record("G6", sb.ToString());

            Assert.AreEqual(FrozenSha, shaAfter, "the rule file must still be byte-identical after the run");
            Assert.AreEqual(0, splitTotal, "H2: splitting a rule adds no weight and must change nothing");
            Assert.Greater(cloneTotal, 0, "H2: cloning a rule doubles a weight and must change something");
        }
    }
}
