using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The intent-carrying experiment: if what a person took themselves to be
    /// doing survives onto the event their act becomes, does anything about them
    /// afterwards differ?
    ///
    /// One physical act (searching a room), one character, one morning, one
    /// seed, and the only difference between arms is the intent carried on the
    /// event. Everything else is identical by construction: the same content,
    /// the same seed, the same random streams (forked per person and minute), the
    /// same world, and the same act with the same physical outcome.
    ///
    /// The two meanings are the shipped ones, and both are defensible from the
    /// data as it stands (see the report). Nothing about wants, rules, numbers,
    /// appraisal or interpretation was changed; the only new code in
    /// `Fallow.Core` is the hook that carries the intent and the event field it
    /// fills, which is null unless an experiment sets it.
    ///
    /// Writes `Docs/experiments/intent-carrying/results.md`.
    /// </summary>
    public class IntentCarryingExperimentTests
    {
        const string TakeResponsibility = "take_responsibility";
        const string AssertAuthority = "assert_authority";
        const int Seeds = 10;

        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load() => _content = Baselines.Primary();

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Intent-carrying action: results");
            sb.AppendLine();
            sb.AppendLine("Generated by `IntentCarryingExperimentTests` on the primary baseline. Each arm is a whole morning run from the same content with the same seed; the only difference between arms is the intent carried onto the event that one act becomes (or, in part 3, that every search becomes). The random stream is forked per person and minute from the seed, so it cannot shift between arms.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "intent-carrying");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "results.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string Or(string s) => string.IsNullOrEmpty(s) ? "null" : s;

        // ------------------------------------------------------------------ watching a run

        /// <summary>One decision, and the state it was taken in.</summary>
        sealed class Snap
        {
            public int Minute;
            public string Who;
            public string Chosen;
            public string Leading;
            public double Margin;
            public bool Ambiguous;
            public string Options;
            public Dictionary<string, double> Wants = new Dictionary<string, double>(StringComparer.Ordinal);
            public string Feelings;
            public string World;

            public string Line => "m" + Minute + " " + Who + " " + Chosen + " for " + (Leading ?? "nothing");
        }

        sealed class Watch
        {
            public string Label;
            public string Intent;
            public List<Snap> Decisions = new List<Snap>();
            public IReadOnlyList<ActionRecord> Actions;
            public IReadOnlyList<WorldEvent> Events;
            public IReadOnlyDictionary<string, Mind> Minds;
            public TraceLog Trace;
            public string Fingerprint;

            public Snap After(string who, int minute)
                => Decisions.FirstOrDefault(d => d.Who == who && d.Minute >= minute);

            public WorldEvent ActEvent(string who, string action, int notBefore)
                => Events.FirstOrDefault(e => e.ActorId == who && e.Action == action && e.Minute >= notBefore);
        }

        static Watch Run(string label, string variant, ulong seed, Func<Scenario001Run, Func<string, ActionOption, Decision, string>> intends, string intentLabel = null)
        {
            var run = Scenario001.Prepare(_content, variant, seed);
            if (intends != null) run.Morning.IntentOfAct = intends(run);
            var w = new Watch { Label = label, Intent = intentLabel };
            run.Morning.Decided = m =>
            {
                var d = m.Decision;
                var s = new Snap
                {
                    Minute = m.Minute, Who = m.CharacterId, Chosen = d.Chosen.Key, Leading = d.Leading?.Key,
                    Margin = d.Margin, Ambiguous = d.Resolution == Resolution.Ambiguous,
                    Options = string.Join("; ", d.Considered.Take(4).Select(r => r.Option.Key + " " + r.Score.ToString("+0.000;-0.000", CultureInfo.InvariantCulture))),
                    Feelings = string.Join(", ", m.Mind.Emotions.Live.OrderBy(e => e.Type, StringComparer.Ordinal)
                        .Select(e => e.Type + (e.TargetId == null ? "" : ":" + e.TargetId) + " " + F(e.Intensity))),
                    World = "portions " + run.World.Portions + "; " + string.Join(", ", S16.People.Select(p => p + " in " + run.World.RoomOf(p) + " hunger " + F(run.World.HungerOf(p))))
                };
                foreach (var x in m.Motives) s.Wants[x.Key] = x.Urgency;
                w.Decisions.Add(s);
            };
            run.Morning.Run(_content.Morning.Minutes);
            w.Actions = run.Result.Actions;
            w.Events = run.Result.Events;
            w.Minds = run.Minds;
            w.Trace = run.Trace;
            w.Fingerprint = string.Join("\n", w.Actions.Select(a => a.ToString() + " | " + a.Resolution + " " + a.Margin.ToString("R", CultureInfo.InvariantCulture)));
            return w;
        }

        /// <summary>
        /// Carries one intent onto one person's search, the one that finishes at
        /// a given minute, and onto nothing else. The minute identifies the act
        /// exactly: an act makes its event when it finishes, and the arms run
        /// identically up to that point.
        /// </summary>
        static Func<Scenario001Run, Func<string, ActionOption, Decision, string>> OnTheSearchFinishingAt(string who, int minute, string intent)
            => run => (actor, action, decision) =>
                actor == who && action.Kind == ActionKind.SearchRoom && run.World.Minute == minute ? intent : null;

        /// <summary>A hook that carries nothing, to show the hook itself changes nothing.</summary>
        static readonly Func<Scenario001Run, Func<string, ActionOption, Decision, string>> CarriesNothing =
            run => (actor, action, decision) => null;

        // ------------------------------------------------------------------ the case

        /// <summary>A real search act, found by running the baseline.</summary>
        sealed class Case
        {
            public string Variant;
            public ulong Seed;
            public string Who;
            public int Minute;
            public int Finished;
            public string Leading;
            public double Urgency;
            public Watch Baseline;
        }

        /// <summary>The first search led by the given want, over the design conditions in order.</summary>
        static Case FindSearch(string leadingWant)
        {
            foreach (var v in _content.Morning.Variants.Select(x => x.Id))
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var w = Run("baseline", v, seed, null);
                foreach (var a in w.Actions.Where(a => a.Action.Kind == ActionKind.SearchRoom))
                {
                    if (a.LeadingMotive != leadingWant) continue;
                    // Only a search that ran its course and became an event, at
                    // the minute it was due to finish.
                    var finished = a.Minute + a.Action.Duration;
                    var e = w.Events.FirstOrDefault(x => x.ActorId == a.CharacterId && x.Action == "search_belongings" && x.Minute == finished);
                    if (e == null) continue;
                    return new Case
                    {
                        Variant = v, Seed = seed, Who = a.CharacterId, Minute = a.Minute, Finished = finished,
                        Leading = a.LeadingMotive, Urgency = a.LeadingUrgency, Baseline = w
                    };
                }
            }
            return null;
        }

        static string ReadingOf(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "no event";
            var x = w.Minds[who].Experiences.LastOrDefault(k => k.EventId == e.Id);
            if (x == null) return "nothing kept";
            return x.Meaning + (x.FromOwnIntent ? " (own intention)" : " (" + x.Access.ToString().ToLowerInvariant() + ")") +
                   ", salience " + F(x.Salience) + ", felt " + (x.DominantEmotion ?? "nothing");
        }

        static string StirredBy(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "-";
            var records = w.Trace.ForEvent(e.Id).Where(r => r.CharacterId == who).ToList();
            var appraisals = records.Where(r => r.Kind == TraceKind.Appraisal).Select(r => r.Summary).ToList();
            return appraisals.Count == 0 ? "nothing" : string.Join("; ", appraisals);
        }

        static string InterpretationOf(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "-";
            var r = w.Trace.ForEvent(e.Id).FirstOrDefault(x => x.CharacterId == who && x.Kind == TraceKind.Interpretation);
            if (r == null) return "-";
            var weight = r.Data.TryGetValue("weight", out var wt) ? wt : "1.00";
            var runner = r.Data.TryGetValue("runner_up", out var ru) ? ru : "none";
            return r.Summary + " (weight " + weight + ", runner-up " + runner + ")";
        }

        /// <summary>Whether what the act stirred became visible in the room afterwards, and to whom.</summary>
        static string Showed(Watch w, string who, int from)
        {
            var shown = w.Events.Where(e => e.Action == "show_distress" && e.TargetId == who && e.Minute >= from).ToList();
            if (shown.Count == 0) return "no";
            return string.Join("; ", shown.Take(3).Select(e => "m" + e.Minute + ", seen by " + string.Join(", ", e.Witnesses)))
                   + (shown.Count > 3 ? "; and " + (shown.Count - 3) + " more" : "");
        }

        /// <summary>Everything else the actor perceived between their act becoming an event and their next decision.</summary>
        static string Between(Watch w, string who, WorldEvent act, int until)
        {
            var others = w.Events
                .Where(e => e.Id != act.Id && e.Minute >= act.Minute && e.Minute <= until)
                .Where(e => e.Witnesses.Contains(who) || e.Overhearers.Contains(who) || e.ActorId == who || e.TargetId == who)
                .ToList();
            if (others.Count == 0) return "nothing";
            return string.Join("; ", others.Select(e =>
            {
                var x = w.Minds[who].Experiences.LastOrDefault(k => k.EventId == e.Id);
                var how = x == null ? "not perceived" : x.Meaning;
                return "m" + e.Minute + " " + e.Action + (e.ActorId == null ? "" : " by " + e.ActorId) + (e.TargetId == null ? "" : " to " + e.TargetId) + " -> " + how;
            }));
        }

        static string FirstDifference(Watch a, Watch b)
        {
            var x = a.Actions.Select(r => r.ToString()).ToList();
            var y = b.Actions.Select(r => r.ToString()).ToList();
            for (var i = 0; i < Math.Min(x.Count, y.Count); i++)
                if (x[i] != y[i]) return "act " + (i + 1) + ": " + x[i] + "  ->  " + y[i];
            return x.Count == y.Count ? "none" : "the runs differ in length only";
        }

        static int DecisionsDiffering(Watch a, Watch b)
        {
            var x = a.Decisions.Select(d => d.Line).ToList();
            var y = b.Decisions.Select(d => d.Line).ToList();
            var n = 0;
            for (var i = 0; i < Math.Min(x.Count, y.Count); i++) if (x[i] != y[i]) n++;
            return n + Math.Abs(x.Count - y.Count);
        }

        // ------------------------------------------------------------------ 1

        [Test, Timeout(1800000)]
        public void I1_TheCaseAndTheControls()
        {
            var found = FindSearch("find_out");
            Assert.IsNotNull(found, "some search is led by find_out");
            var other = FindSearch("restore_standing");

            var sb = new StringBuilder();
            sb.AppendLine("## 1. The act, and the controls");
            sb.AppendLine();
            sb.AppendLine("The act is a **room search**, chosen because it is the one act the shipped data already carries an intent for: `p02` of the backstory is `search_belongings` with intent `take_responsibility`. Two real searches were found by running the baseline and taking the first search led by each want, in condition and seed order:");
            sb.AppendLine();
            sb.AppendLine("| Case | Who | Condition, seed | Minute | Led by | Urgency |");
            sb.AppendLine("|---|---|---|---|---|---|");
            sb.AppendLine("| A | " + found.Who + " | " + found.Variant + ", seed " + found.Seed + " | " + found.Minute + " | " + found.Leading + " | " + F(found.Urgency) + " |");
            if (other != null)
                sb.AppendLine("| B | " + other.Who + " | " + other.Variant + ", seed " + other.Seed + " | " + other.Minute + " | " + other.Leading + " | " + F(other.Urgency) + " |");
            sb.AppendLine();

            // Control 1: the baseline reproduces itself.
            var again = Run("baseline again", found.Variant, found.Seed, null);
            Assert.AreEqual(found.Baseline.Fingerprint, again.Fingerprint);

            // Control 3: the hook, returning nothing, is the baseline.
            var removed = Run("intent removed", found.Variant, found.Seed, CarriesNothing);
            Assert.AreEqual(found.Baseline.Fingerprint, removed.Fingerprint);

            // Control 3b: an intent on an act, then taken away again.
            var carried = Run("take_responsibility", found.Variant, found.Seed, OnTheSearchFinishingAt(found.Who, found.Finished, TakeResponsibility));
            var takenAway = Run("removed again", found.Variant, found.Seed, OnTheSearchFinishingAt(found.Who, found.Finished, null));
            Assert.AreEqual(found.Baseline.Fingerprint, takenAway.Fingerprint);

            // Control 5: the world, at the actor's next decision, is the same.
            var e0 = found.Baseline.ActEvent(found.Who, "search_belongings", found.Finished);
            var e1 = carried.ActEvent(found.Who, "search_belongings", found.Finished);
            Assert.IsNotNull(e0);
            Assert.IsNotNull(e1);
            Assert.AreEqual(TakeResponsibility, e1.Intent, "the act carried the intent");
            Assert.IsNull(e0.Intent, "and the baseline act carried none");
            var after0 = found.Baseline.After(found.Who, e0.Minute);
            var after1 = carried.After(found.Who, e1.Minute);
            Assert.AreEqual(after0.World, after1.World, "the house is the same after the act");
            Assert.AreEqual(after0.Minute, after1.Minute, "the act took the same time");

            // Control 4: the same decisions, in the same order, up to any divergence.
            var sameOrder = found.Baseline.Decisions.Zip(carried.Decisions, (x, y) => x.Minute == y.Minute && x.Who == y.Who).All(ok => ok);
            Assert.IsTrue(sameOrder, "the same people decide at the same minutes");

            sb.AppendLine("| Control | What was checked | Result |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| 1. Repeat | the baseline run twice, same seed | **identical**, act for act (" + found.Baseline.Actions.Count + " acts) |");
            sb.AppendLine("| 3. Intent removed | the hook set, returning nothing | **identical to the baseline** |");
            sb.AppendLine("| 3b. Intent taken away again | the same hook shape, carrying null on the same act | **identical to the baseline** |");
            sb.AppendLine("| 4. Randomness | every decision in both arms at the same minute by the same person | **held**; the stream is forked from the seed by person and minute, so an arm cannot shift it |");
            sb.AppendLine("| 5. Physical outcome | the house at the actor's next decision: portions, everybody's room and hunger | **identical**: " + after0.World + " |");
            sb.AppendLine("| 5b. The act's own event | every field but the intent | " + (e0.Action == e1.Action && e0.Topic == e1.Topic && e0.Valence == e1.Valence && e0.TargetId == e1.TargetId && e0.Summary == e1.Summary && e0.Minute == e1.Minute ? "**identical**" : "DIFFERENT") + ": `" + e0.Action + "`, topic `" + Or(e0.Topic) + "`, valence `" + e0.Valence + "`, target `" + Or(e0.TargetId) + "`, minute " + e0.Minute + " |");
            sb.AppendLine("| 5c. The intent itself | the event's `intent` | baseline `" + Or(e0.Intent) + "`, carrying arm `" + Or(e1.Intent) + "` |");
            Record("1", sb.ToString());
        }

        // ------------------------------------------------------------------ 2

        [Test, Timeout(1800000)]
        public void I2_OneActThreeMeanings()
        {
            var cases = new List<Case>();
            var a = FindSearch("find_out");
            if (a != null) cases.Add(a);
            var b = FindSearch("restore_standing");
            if (b != null) cases.Add(b);

            var sb = new StringBuilder();
            sb.AppendLine("## 2. The same search, three meanings");
            sb.AppendLine();
            sb.AppendLine("For each case: the baseline (no intent), the same act carrying `take_responsibility`, and the same act carrying `assert_authority`. Nothing else differs.");
            sb.AppendLine();

            foreach (var c in cases)
            {
                var arms = new List<Watch> { c.Baseline };
                foreach (var intent in new[] { TakeResponsibility, AssertAuthority })
                    arms.Add(Run(intent, c.Variant, c.Seed, OnTheSearchFinishingAt(c.Who, c.Finished, intent), intent));

                sb.AppendLine("### " + c.Who + ", " + c.Variant + " seed " + c.Seed + ", searching from minute " + c.Minute + " to " + c.Finished + " (led by " + c.Leading + " " + F(c.Urgency) + ")");
                sb.AppendLine();
                sb.AppendLine("| | baseline (no intent) | `take_responsibility` | `assert_authority` |");
                sb.AppendLine("|---|---|---|---|");

                var events = arms.Select(w => w.ActEvent(c.Who, "search_belongings", c.Finished)).ToList();
                for (var i = 1; i < arms.Count; i++)
                    Assert.AreEqual(arms[i].Intent, events[i].Intent, "the act carried the intent meant for it");
                var afters = arms.Select((w, i) => w.After(c.Who, events[i].Minute)).ToList();
                var bases = afters[0];

                sb.AppendLine("| **Event** carried | " + string.Join(" | ", events.Select(e => "intent " + Or(e.Intent))) + " |");
                sb.AppendLine("| **Interpretation** by the actor | " + string.Join(" | ", arms.Select((w, i) => InterpretationOf(w, c.Who, events[i]))) + " |");
                sb.AppendLine("| **Appraisal** for the actor | " + string.Join(" | ", arms.Select((w, i) => StirredBy(w, c.Who, events[i]))) + " |");
                sb.AppendLine("| **Memory** kept | " + string.Join(" | ", arms.Select((w, i) => ReadingOf(w, c.Who, events[i]))) + " |");
                sb.AppendLine("| **Feelings** at the next decision (m" + bases.Minute + ") | " + string.Join(" | ", afters.Select(s => s.Feelings.Length == 0 ? "nothing" : s.Feelings)) + " |");
                sb.AppendLine("| **Wants** there | " + string.Join(" | ", afters.Select(s => string.Join(", ", s.Wants.OrderByDescending(x => x.Value).Select(x => x.Key + " " + F(x.Value))))) + " |");
                sb.AppendLine("| **Options** there | " + string.Join(" | ", afters.Select(s => s.Options)) + " |");
                sb.AppendLine("| **Chose** there | " + string.Join(" | ", afters.Select(s => s.Chosen + " for " + (s.Leading ?? "nothing") + (s.Ambiguous ? ", the seed settled it" : ", clear by " + F(s.Margin)))) + " |");
                sb.AppendLine("| **Did what it stirred become visible?** | " + string.Join(" | ", arms.Select((w, i) => Showed(w, c.Who, events[i].Minute))) + " |");
                sb.AppendLine("| **What else reached the actor in the same minute** | " + string.Join(" | ", arms.Select((w, i) => Between(w, c.Who, events[i], afters[i].Minute))) + " |");
                sb.AppendLine("| **What others made of the search** | " + string.Join(" | ", arms.Select((w, i) => string.Join("; ", events[i].Witnesses.Concat(events[i].Overhearers).Select(p => p + ": " + ReadingOf(w, p, events[i]).Split(',')[0])))) + " |");
                sb.AppendLine("| **The rest of the morning** | - | " + string.Join(" | ", arms.Skip(1).Select(w => FirstDifference(c.Baseline, w) == "none" ? "identical to the baseline" : DecisionsDiffering(c.Baseline, w) + " of " + c.Baseline.Decisions.Count + " decisions differ; first at " + FirstDifference(c.Baseline, w))) + " |");
                sb.AppendLine();

                // What the actor recovered must be what was carried.
                for (var i = 1; i < arms.Count; i++)
                {
                    var x = arms[i].Minds[c.Who].Experiences.Last(k => k.EventId == events[i].Id);
                    Assert.AreEqual(events[i].Intent, x.Meaning, "the actor recovers the carried meaning");
                    Assert.IsTrue(x.FromOwnIntent);
                }
                var baseline = c.Baseline.Minds[c.Who].Experiences.Last(k => k.EventId == events[0].Id);
                Assert.IsFalse(baseline.FromOwnIntent, "the baseline actor reads their own act as a witness would");
            }
            Record("2", sb.ToString());
        }

        // ------------------------------------------------------------------ 3

        [Test, Timeout(1800000)]
        public void I3_EverySearchInFiftyMornings()
        {
            // The same two meanings, carried on every search in fifty mornings,
            // by the want that led the search. This is a stipulation of the
            // experiment, not a rule of the simulation: it exists to count how
            // far the difference reaches, not to propose a mapping.
            string Map(Decision d)
            {
                var lead = d?.Leading?.Name;
                if (lead == "find_out") return TakeResponsibility;
                if (lead == "restore_standing") return AssertAuthority;
                return null;
            }

            int carried = 0, recovered = 0, meaningChanged = 0, salienceChanged = 0, feelingsChanged = 0,
                beliefsChanged = 0, wantsChanged = 0, actsChanged = 0, morningsChanged = 0, witnessChanged = 0;
            var byIntent = new SortedDictionary<string, int>(StringComparer.Ordinal);
            var firstChanges = new List<string>();
            var mornings = 0;

            foreach (var v in _content.Morning.Variants.Select(x => x.Id))
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var b = Run("baseline", v, seed, null);
                var i = Run("intent", v, seed, run => (who, act, d) => act.Kind == ActionKind.SearchRoom ? Map(d) : null);
                var removed = Run("removed", v, seed, CarriesNothing);
                Assert.AreEqual(b.Fingerprint, removed.Fingerprint, v + " seed " + seed + ": the hook alone changes nothing");
                mornings++;

                foreach (var e in i.Events.Where(e => e.Intent != null))
                {
                    carried++;
                    byIntent.TryGetValue(e.Intent, out var n);
                    byIntent[e.Intent] = n + 1;

                    var mine = i.Minds[e.ActorId].Experiences.LastOrDefault(x => x.EventId == e.Id);
                    var theirs = b.Minds[e.ActorId].Experiences.LastOrDefault(x => x.EventId == e.Id);
                    if (mine != null && mine.FromOwnIntent && mine.Meaning == e.Intent) recovered++;
                    if (mine != null && theirs != null)
                    {
                        if (mine.Meaning != theirs.Meaning) meaningChanged++;
                        if (Math.Abs(mine.Salience - theirs.Salience) > 1e-9) salienceChanged++;
                    }

                    // what everybody else made of the same search
                    foreach (var p in e.Witnesses.Concat(e.Overhearers))
                    {
                        var m1 = i.Minds[p].Experiences.LastOrDefault(x => x.EventId == e.Id);
                        var m0 = b.Minds[p].Experiences.LastOrDefault(x => x.EventId == e.Id);
                        if (m1?.Meaning != m0?.Meaning) witnessChanged++;
                    }

                    // the actor's next decision after that act
                    var after1 = i.Decisions.FirstOrDefault(d => d.Who == e.ActorId && d.Minute >= e.Minute);
                    var after0 = b.Decisions.FirstOrDefault(d => d.Who == e.ActorId && d.Minute >= e.Minute);
                    if (after1 != null && after0 != null)
                    {
                        if (after1.Feelings != after0.Feelings) feelingsChanged++;
                        if (string.Join(",", after1.Wants.Select(x => x.Key + "=" + F(x.Value))) !=
                            string.Join(",", after0.Wants.Select(x => x.Key + "=" + F(x.Value)))) wantsChanged++;
                        if (after1.Chosen != after0.Chosen) actsChanged++;
                    }

                    var beliefs1 = string.Join(",", i.Minds[e.ActorId].Beliefs.All.Select(x => x.Key + "=" + F(x.Confidence)));
                    var beliefs0 = string.Join(",", b.Minds[e.ActorId].Beliefs.All.Select(x => x.Key + "=" + F(x.Confidence)));
                    if (beliefs1 != beliefs0) beliefsChanged++;
                }

                if (b.Fingerprint != i.Fingerprint)
                {
                    morningsChanged++;
                    if (firstChanges.Count < 6) firstChanges.Add(v + " seed " + seed + ": " + FirstDifference(b, i));
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("## 3. Every search in fifty mornings");
            sb.AppendLine();
            sb.AppendLine("The five design conditions, seeds 1-" + Seeds + ". Every search carries the meaning of the want that led it: `find_out` -> `take_responsibility`, `restore_standing` -> `assert_authority`, nothing otherwise. **This mapping is a stipulation of the experiment**, made to count how far a carried meaning reaches; it is not proposed as a rule.");
            sb.AppendLine();
            sb.AppendLine("| | Count |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Mornings | " + mornings + " |");
            sb.AppendLine("| Searches carrying an intent | " + carried + " (" + string.Join(", ", byIntent.Select(x => x.Key + " " + x.Value)) + ") |");
            sb.AppendLine("| ... where the actor recovered it as their own intention | **" + recovered + "** |");
            sb.AppendLine("| ... where what the actor kept of the act changed | **" + meaningChanged + "** |");
            sb.AppendLine("| ... where how much the memory mattered (salience) changed | " + salienceChanged + " |");
            sb.AppendLine("| ... where what the actor was feeling at their next decision changed | " + feelingsChanged + " |");
            sb.AppendLine("| ... where the actor's beliefs changed by the end | " + beliefsChanged + " |");
            sb.AppendLine("| ... where the actor's wants at their next decision changed | " + wantsChanged + " |");
            sb.AppendLine("| ... where the act the actor then chose changed | **" + actsChanged + "** |");
            sb.AppendLine("| ... where any witness read the search differently | " + witnessChanged + " |");
            sb.AppendLine("| Mornings whose whole course changed | **" + morningsChanged + " of " + mornings + "** |");
            sb.AppendLine("| Mornings identical when the intent is removed again | " + mornings + " of " + mornings + " |");
            if (firstChanges.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("Where the mornings first parted:");
                sb.AppendLine();
                foreach (var f in firstChanges) sb.AppendLine("- " + f);
            }
            Record("3", sb.ToString());
        }

        // ------------------------------------------------------------------ 4

        [Test]
        public void I4_WhatCanReadAnIntentAtAll()
        {
            // Read from the rules: which self-meanings any rule downstream of
            // perception can consume. Nothing here runs a morning.
            var rules = _content.Rules;
            var selfMeanings = _content.Vocabulary.SelfMeanings.OrderBy(x => x, StringComparer.Ordinal).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("## 4. What can read an intent at all");
            sb.AppendLine();
            sb.AppendLine("The six meanings a person can hold about their own act, and every rule in the shipped data that reads one.");
            sb.AppendLine();
            sb.AppendLine("| Self-meaning | Appraisal rules | Belief nudges | Motivation rules that read a memory of it | Authored events carrying it |");
            sb.AppendLine("|---|---|---|---|---|");
            var authored = _content.Backstory.Events.Concat(new[] { _content.Morning.Opening })
                .Concat(_content.Morning.Variants.Concat(_content.Morning.HeldOutVariants).SelectMany(v => v.NightEvents))
                .Where(e => e?.Intent != null).ToList();
            foreach (var m in selfMeanings)
            {
                var appraisals = rules.Appraisal.Where(r => r.When?.Meanings != null && r.When.Meanings.Contains(m, StringComparer.Ordinal)).Select(r => r.Id).ToList();
                var nudges = rules.BeliefNudges.Where(r => r.When?.Meanings != null && r.When.Meanings.Contains(m, StringComparer.Ordinal)).Select(r => r.Id).ToList();
                var motives = rules.Motivation.Where(r => r.ScaledBy.Any(s => s.Kind == ScalerKind.Memory && s.Name == m)).Select(r => r.Id).ToList();
                sb.AppendLine("| `" + m + "` | " + (appraisals.Count == 0 ? "**none**" : string.Join(", ", appraisals)) + " | " + (nudges.Count == 0 ? "none" : string.Join(", ", nudges)) + " | " + (motives.Count == 0 ? "**none**" : string.Join(", ", motives)) + " | " + authored.Count(e => e.Intent == m) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("A memory carrying a self-meaning is read by **no motivation rule**: every memory term in `decisions.json` names `concern`, `threat` or `reassurance`. So a preserved intent can reach a later decision only by what it stirs at the moment of the act, never by being remembered.");
            Record("4", sb.ToString());

            Assert.IsNotEmpty(selfMeanings);
        }
    }
}
