using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.1, before anything is changed: where does the night go?
    ///
    /// Every overnight condition is run against a control with no night at all,
    /// on the same seed, and each stage of the pipeline is compared. The report
    /// this writes is the diagnosis the rest of the slice is built on. It asserts
    /// nothing about what should happen; it records what does.
    /// </summary>
    public class S11DiagnosisTests
    {
        static Scenario001Content _content;

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        static IReadOnlyList<string> Motives => _content.Vocabulary.Set("motives").ToList();

        [Test]
        public void HowOftenFeelingsFadeInAMorning()
        {
            // Feelings fade once for every event, anywhere in the house. This
            // measures how many that is per morning across the S1 batch, so any
            // change to fading can be checked against the rate it replaces.
            var counts = new List<int>();
            foreach (var variant in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 40; seed++)
                counts.Add(Scenario001.Run(_content, variant.Id, seed).Result.Events.Count);

            var mean = counts.Average();
            var line = "events per 90-minute morning across " + counts.Count + " mornings: mean " +
                       mean.ToString("0.00") + ", min " + counts.Min() + ", max " + counts.Max() +
                       "; one fade every " + (90.0 / mean).ToString("0.00") + " minutes on average";
            TestContext.WriteLine(line);

            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.1");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "fading-rate-current.md"),
                "# Fading rate" + Environment.NewLine + Environment.NewLine +
                "Measured by `S11DiagnosisTests.HowOftenFeelingsFadeInAMorning`." +
                Environment.NewLine + Environment.NewLine + line + Environment.NewLine);
        }

        [Test]
        public void WhereTheNightGoes()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.1 diagnosis: where the night goes");
            sb.AppendLine();
            sb.AppendLine("Each overnight condition against a control with no night events, same seed (1),");
            sb.AppendLine("same world, same people. Generated by `S11DiagnosisTests`.");
            sb.AppendLine();

            foreach (var variant in _content.Morning.Variants.Where(v => v.NightEvents.Count > 0))
            {
                var causes = variant.NightEvents.Select(e => e.Id).ToList();
                var pair = Counterfactual.Run(
                    _content, variant.Id, new List<WorldEvent>(), variant.NightEvents, causes, 1);

                sb.AppendLine("## " + variant.Id);
                sb.AppendLine();
                foreach (var e in variant.NightEvents)
                    sb.AppendLine("> " + e.Summary + " (witnessed by the actor" +
                                  (e.Witnesses.Count == 0 ? "" : " and " + string.Join(", ", e.Witnesses)) + ")");
                sb.AppendLine();

                foreach (var p in pair.People.Values)
                {
                    var treatment = pair.Treatment.Minds[p.CharacterId];
                    var nightMemory = treatment.Experiences.FirstOrDefault(x => causes.Contains(x.EventId));

                    sb.AppendLine("### " + p.CharacterId);
                    sb.AppendLine();
                    sb.AppendLine("- **Perceived the night:** " + (nightMemory == null
                        ? "no"
                        : "yes, as `" + nightMemory.Meaning + "`, day " + nightMemory.Day +
                          ", salience " + nightMemory.Salience.ToString("0.00") +
                          ", strongest feeling " + (nightMemory.DominantEmotion ?? "none")));

                    var nightBeliefs = treatment.Beliefs.All
                        .Where(b => b.Justifications.Any(j =>
                            pair.Treatment.Trace.Chain(j).Any(r => r.EventId != null && causes.Contains(r.EventId))))
                        .Select(b => b.ToString()).ToList();
                    sb.AppendLine("- **Beliefs moved by it:** " + (nightBeliefs.Count == 0 ? "none" : string.Join(", ", nightBeliefs)));

                    sb.AppendLine("- **Feelings after the night:** control `" + p.ControlFeelings[Scenario001.Stages.AfterNight] +
                                  "`; treatment `" + p.TreatmentFeelings[Scenario001.Stages.AfterNight] + "`");
                    sb.AppendLine("- **Feelings after the opening count:** control `" + p.ControlFeelings[Scenario001.Stages.AfterOpening] +
                                  "`; treatment `" + p.TreatmentFeelings[Scenario001.Stages.AfterOpening] + "`");

                    foreach (var minute in new[] { 0, 4, 9, 19, 44 })
                    {
                        if (minute >= p.TreatmentFeelTimeline.Count) continue;
                        var c = p.ControlFeelTimeline[minute];
                        var t = p.TreatmentFeelTimeline[minute];
                        var types = c.Keys.Union(t.Keys).OrderBy(k => k).ToList();
                        var diffs = types
                            .Select(k => new { k, d = (t.TryGetValue(k, out var tv) ? tv : 0) - (c.TryGetValue(k, out var cv) ? cv : 0) })
                            .Where(x => Math.Abs(x.d) > 0.01)
                            .Select(x => x.k + " " + x.d.ToString("+0.00;-0.00"))
                            .ToList();
                        sb.AppendLine("  - minute " + (minute + 1) + " feeling difference: " +
                                      (diffs.Count == 0 ? "none" : string.Join(", ", diffs)));
                    }

                    sb.AppendLine("- **Wants at the start, treatment minus control:**");
                    foreach (var m in Motives)
                    {
                        var shift = p.ShiftAtStart(m);
                        if (Math.Abs(shift) < 0.005 && p.ControlAtStart.Of(m) == 0 && p.TreatmentAtStart.Of(m) == 0) continue;
                        var rests = p.TreatmentAtStart.RestsOnCause.TryGetValue(m, out var yes) && yes;
                        sb.AppendLine("  - `" + m + "` " + p.ControlAtStart.Of(m).ToString("0.000") + " -> " +
                                      p.TreatmentAtStart.Of(m).ToString("0.000") +
                                      " (" + shift.ToString("+0.000;-0.000;0.000") + ")" +
                                      (rests ? ", traceable to the night" : ""));
                    }

                    sb.AppendLine("- **Mean shift across the morning:** " + string.Join(", ",
                        Motives.Select(m => new { m, s = p.ShiftOverMorning(m) })
                            .Where(x => Math.Abs(x.s) > 0.005)
                            .Select(x => x.m + " " + x.s.ToString("+0.000;-0.000"))
                            .DefaultIfEmpty("none")));
                    sb.AppendLine("- **Motivation sensitivity:** start " + p.SensitivityAtStart(Motives).ToString("0.000") +
                                  ", morning " + p.SensitivityOverMorning(Motives).ToString("0.000"));
                    sb.AppendLine("- **First decisions:** control `" + string.Join(" ", p.ControlActions.Take(3)) +
                                  "`; treatment `" + string.Join(" ", p.TreatmentActions.Take(3)) + "`");
                    sb.AppendLine("- **Behaviour difference over the morning:** " + p.BehaviourDifference.ToString("0.00"));
                    sb.AppendLine();
                }
            }

            sb.AppendLine("## Fading");
            sb.AppendLine();
            var counted = Scenario001.Run(_content, "daniel_ate_it", 1);
            sb.AppendLine("Events processed during one morning (`daniel_ate_it`, seed 1): " +
                          counted.Result.Events.Count + ". Every one fades every mind, whether or not that mind perceived it.");

            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.1");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "diagnosis-current.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());
        }
    }
}
