using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Data;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The S1.1 experiment: can something that happens to a person change what
    /// that person wants, through the pipeline, and not merely because they are a
    /// different person?
    ///
    /// Every comparison here is a counterfactual: two mornings on the same seed,
    /// same world, same people, differing in one cause. Only the design conditions
    /// are used. The held-out condition lives in its own file.
    ///
    /// Each test records what it measured into a report whether it passes or not.
    /// </summary>
    public class S11ExperimentTests
    {
        const double Changed = 0.02;
        const int Seeds = 10;

        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _findings = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static readonly (string Variant, string Who)[] Culprits =
        {
            ("daniel_ate_it", "daniel"),
            ("mara_ate_it", "mara"),
            ("daniel_hid_it", "daniel"),
            ("elena_fed_mara", "elena")
        };

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.1 experiment results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S11ExperimentTests`. Design conditions only; the held-out");
            sb.AppendLine("condition is reported separately. Every comparison is paired on the seed.");
            sb.AppendLine();
            foreach (var pair in _findings) sb.AppendLine("## " + pair.Key + Environment.NewLine + Environment.NewLine + pair.Value);

            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.1");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "experiment-results.md"), sb.ToString());
        }

        static IReadOnlyList<string> Motives => _content.Vocabulary.Set("motives").ToList();

        static IReadOnlyList<WorldEvent> Night(string variant) => _content.Morning.Variant(variant).NightEvents;
        static IReadOnlyList<string> Causes(string variant) => Night(variant).Select(e => e.Id).ToList();

        static Counterfactual.Pair Pair(string variant, ulong seed, int? minutes = null, Action<Simulation> intervene = null,
            IReadOnlyList<WorldEvent> treatment = null, Scenario001Content content = null)
            => Counterfactual.Run(content ?? _content, variant, new List<WorldEvent>(), treatment ?? Night(variant),
                Causes(variant), seed, minutes, intervene);

        static void Record(string key, string text)
        {
            _findings[key] = text;
            TestContext.WriteLine(text);
        }

        /// <summary>
        /// The scale to read a circumstance effect against: how far apart two
        /// different people's wants are at the same moment in the same world.
        /// </summary>
        static double PersonalityGapAtStart(Counterfactual.Pair pair)
        {
            var ids = pair.People.Keys.ToList();
            var gaps = new List<double>();
            for (var i = 0; i < ids.Count; i++)
            for (var j = i + 1; j < ids.Count; j++)
                gaps.Add(Motives.Average(m =>
                    Math.Abs(pair.People[ids[i]].ControlAtStart.Of(m) - pair.People[ids[j]].ControlAtStart.Of(m))));
            return gaps.Average();
        }

        // ---- A: a changed night changes the person it happened to ----

        [Test]
        public void A_AChangedNightChangesWhatThePersonItHappenedToWants()
        {
            var sb = new StringBuilder();
            sb.AppendLine("| Condition | Who | Start sensitivity | Morning sensitivity (mean of " + Seeds + " seeds) | Lasting share | `avoid_exposure` at start | `avoid_exposure` over morning | Attribution at start | Attribution over morning |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|");

            var best = 0.0;
            string bestCase = null;
            var gap = 0.0;

            foreach (var (variant, who) in Culprits)
            {
                var starts = new List<double>();
                var mornings = new List<double>();
                var avoidStart = 0.0;
                var avoidMorning = new List<double>();
                double? attrStart = null;
                var attrMorning = new List<double>();

                for (ulong seed = 1; seed <= Seeds; seed++)
                {
                    var pair = Pair(variant, seed);
                    var p = pair.People[who];
                    if (seed == 1) gap = PersonalityGapAtStart(pair);

                    starts.Add(p.SensitivityAtStart(Motives));
                    mornings.Add(p.SensitivityOverMorning(Motives));
                    avoidStart = p.ShiftAtStart("avoid_exposure");
                    avoidMorning.Add(p.ShiftOverMorning("avoid_exposure"));
                    attrStart = p.AttributionAtStart(Motives, Changed);
                    var am = p.AttributionOverMorning(Motives, Changed);
                    if (am.HasValue) attrMorning.Add(am.Value);
                }

                var start = starts.Average();
                var morning = mornings.Average();
                sb.AppendLine("| " + variant + " | " + who + " | " + start.ToString("0.000") + " | " + morning.ToString("0.000") +
                              " | " + (start < 0.01 ? "n/a (nothing at the start)" : (morning / start).ToString("P0")) +
                              " | " + avoidStart.ToString("+0.000;-0.000;0.000") + " | " + avoidMorning.Average().ToString("+0.000;-0.000;0.000") +
                              " | " + (attrStart.HasValue ? attrStart.Value.ToString("P0") : "nothing changed") +
                              " | " + (attrMorning.Count == 0 ? "nothing changed" : attrMorning.Average().ToString("P0")) + " |");

                if (morning > best) { best = morning; bestCase = variant + "/" + who; }
            }

            sb.AppendLine();
            sb.AppendLine("For scale: two different people in the same world differ at the start by a mean of **" +
                          gap.ToString("0.000") + "** per want.");
            sb.AppendLine("Strongest lasting effect: **" + bestCase + "**, " + best.ToString("0.000") +
                          " per want, " + (best / gap).ToString("P0") + " of the personality gap.");
            Record("A. A changed night, same person", sb.ToString());

            Assert.Greater(best, 0.0, "no condition changed its culprit's wants across the morning at all");
        }

        [Test]
        public void A_TheChangeAtTheStartCanAlwaysBeWalkedBackToTheNight()
        {
            var problems = new List<string>();
            foreach (var (variant, who) in Culprits)
            {
                var p = Pair(variant, 1, minutes: 0).People[who];
                foreach (var m in Motives.Where(m => Math.Abs(p.ShiftAtStart(m)) > Changed))
                    if (!(p.TreatmentAtStart.RestsOnCause.TryGetValue(m, out var yes) && yes))
                        problems.Add(variant + "/" + who + ": " + m + " moved " +
                                     p.ShiftAtStart(m).ToString("+0.000;-0.000") + " with no trace to the night");
            }

            Record("A. Attribution at the start", problems.Count == 0
                ? "Every want that moved by more than " + Changed + " at the start, in every design condition, has a reason that leads back to the night."
                : string.Join(Environment.NewLine, problems));

            Assert.IsEmpty(problems, string.Join("\n", problems));
        }

        [Test]
        public void A_ItSurvivesTheSeed()
        {
            // The main claim, on the condition with the largest lasting effect in
            // the sweep above, across twice as many seeds.
            const string variant = "mara_ate_it";
            const string who = "mara";
            const int seeds = 20;

            var shifts = new List<double>();
            for (ulong seed = 1; seed <= seeds; seed++)
                shifts.Add(Pair(variant, seed).People[who].ShiftOverMorning("avoid_exposure"));

            var positive = shifts.Count(s => s > 0);
            var mean = shifts.Average();
            var sd = Math.Sqrt(shifts.Sum(s => (s - mean) * (s - mean)) / (shifts.Count - 1));
            var se = sd / Math.Sqrt(shifts.Count);

            Record("A. Across seeds", "`" + variant + "`, " + who + ", `avoid_exposure` averaged over the morning, treatment minus control on the same seed, " + seeds + " seeds." +
                   Environment.NewLine + Environment.NewLine +
                   "- positive on " + positive + " of " + seeds + " seeds" + Environment.NewLine +
                   "- mean " + mean.ToString("+0.000;-0.000") + ", standard deviation " + sd.ToString("0.000") +
                   ", standard error " + se.ToString("0.000") + ", mean over standard error " + (mean / se).ToString("0.0") + Environment.NewLine +
                   "- per seed: " + string.Join(" ", shifts.Select(s => s.ToString("+0.00;-0.00"))));

            Assert.GreaterOrEqual(positive, 16, "the effect does not hold on most seeds");
            Assert.Greater(mean / se, 3.0, "the effect is not clearly distinguishable from zero across seeds");
        }

        // ---- B: remove the cause, and the effect goes with it ----

        [Test]
        public void B_RemovingTheNightRemovesEverythingItDid()
        {
            var problems = new List<string>();

            foreach (var (variant, _) in Culprits)
            for (ulong seed = 1; seed <= 3; seed++)
            {
                var removed = Pair(variant, seed, treatment: Counterfactual.Without(Night(variant), Causes(variant).ToArray()));

                foreach (var p in removed.People.Values)
                {
                    if (p.SensitivityOverMorning(Motives) != 0.0 || p.SensitivityAtStart(Motives) != 0.0)
                        problems.Add(variant + "/" + seed + "/" + p.CharacterId + " still differs from the control");
                    if (!p.ControlActions.SequenceEqual(p.TreatmentActions))
                        problems.Add(variant + "/" + seed + "/" + p.CharacterId + " still acts differently");
                }
            }

            Record("B. Removing the night", problems.Count == 0
                ? "With the originating event removed, every person in every design condition on seeds 1 to 3 has exactly the wants and exactly the actions of the control, every minute. There is no second path by which the night reaches anybody."
                : string.Join(Environment.NewLine, problems));

            Assert.IsEmpty(problems, string.Join("\n", problems));
        }

        [Test]
        public void B_TakingAwayTheBeliefTakesAwayMostOfWhatLasts()
        {
            // Mediation. Keep the night and everything it made the person feel;
            // take away only the belief it formed, right after the night. If the
            // belief is what carries the night into the morning, most of what
            // lasts should go, and what remains at the start should mostly stay.
            const string variant = "mara_ate_it";
            const string who = "mara";

            var withBelief = new List<double>();
            var withoutBelief = new List<double>();
            var startWith = 0.0;
            var startWithout = 0.0;

            for (ulong seed = 1; seed <= Seeds; seed++)
            {
                var full = Pair(variant, seed).People[who];
                var cut = Pair(variant, seed, intervene: sim =>
                {
                    var mind = sim.Minds[who];
                    var args = new[] { who, "missing_can" };
                    var id = sim.Trace.Add(Fallow.Core.Tracing.TraceKind.BeliefChange, who, null,
                        "EXPERIMENT: belief removed to test what it was carrying");
                    mind.Beliefs.Nudge("answerable_for", args, -1.0, id);
                }).People[who];

                withBelief.Add(full.ShiftOverMorning("avoid_exposure"));
                withoutBelief.Add(cut.ShiftOverMorning("avoid_exposure"));
                if (seed == 1)
                {
                    startWith = full.ShiftAtStart("avoid_exposure");
                    startWithout = cut.ShiftAtStart("avoid_exposure");
                }
            }

            var lasting = withBelief.Average();
            var lastingCut = withoutBelief.Average();
            var carried = lasting == 0 ? 0 : 1.0 - lastingCut / lasting;

            Record("B. Taking away the belief", "`" + variant + "`, " + who + ", `avoid_exposure` shift against the no-night control, " + Seeds + " seeds." +
                   Environment.NewLine + Environment.NewLine +
                   "| | At the start | Averaged over the morning |" + Environment.NewLine +
                   "|---|---|---|" + Environment.NewLine +
                   "| Night, with the belief it formed | " + startWith.ToString("+0.000;-0.000") + " | " + lasting.ToString("+0.000;-0.000") + " |" + Environment.NewLine +
                   "| Night, belief removed | " + startWithout.ToString("+0.000;-0.000") + " | " + lastingCut.ToString("+0.000;-0.000") + " |" + Environment.NewLine +
                   Environment.NewLine +
                   "Share of the lasting effect carried by the belief: **" + carried.ToString("P0") + "**.");

            Assert.Greater(carried, 0.5, "the belief is not what carries the night into the morning");
        }

        [Test]
        public void B_TakingSomebodyOutOfTheRoomTakesAwayOnlyTheirPart()
        {
            const string variant = "elena_fed_mara";

            var full = Pair(variant, 1, minutes: 0);
            var noWitness = Pair(variant, 1, minutes: 0, treatment: Counterfactual.WithoutWitness(Night(variant), "mara"));

            var maraBelief = noWitness.Treatment.Minds["mara"].Beliefs.Confidence("answerable_for", "elena", "missing_can");
            var maraSame = Motives.All(m => Math.Abs(noWitness.People["mara"].ShiftAtStart(m)) < 1e-12)
                           && noWitness.People["mara"].ControlFeelings[Scenario001.Stages.AfterOpening] ==
                              noWitness.People["mara"].TreatmentFeelings[Scenario001.Stages.AfterOpening];
            var elenaSame = Motives.All(m =>
                Math.Abs(noWitness.People["elena"].TreatmentAtStart.Of(m) - full.People["elena"].TreatmentAtStart.Of(m)) < 1e-12);

            Record("B. Taking one witness out of the room", "`" + variant + "` with Mara removed from the witnesses of the night: " +
                   "her belief about Elena " + maraBelief.ToString("0.00") + "; her feelings and wants identical to the control: " + maraSame +
                   "; Elena's wants identical to the full night: " + elenaSame + ".");

            Assert.AreEqual(0.0, maraBelief);
            Assert.IsTrue(maraSame, "Mara is still changed by a night she no longer saw");
            Assert.IsTrue(elenaSame, "taking Mara out of the room changed Elena, who was still there");
        }

        // ---- C: same night, different person ----

        [Test]
        public void C_TheSameNightStillLandsOnDifferentPeopleDifferently()
        {
            var sb = new StringBuilder();
            foreach (var (variant, _) in Culprits)
            {
                var pair = Pair(variant, 1, minutes: 0);
                sb.AppendLine("- `" + variant + "`: in the same world at the start, two different people's wants differ by a mean of " +
                              PersonalityGapAtStart(pair).ToString("0.000") + " per want.");
            }
            Record("C. Same night, different people", sb.ToString());

            var gap = PersonalityGapAtStart(Pair("mara_ate_it", 1, minutes: 0));
            Assert.Greater(gap, 0.1, "people have stopped being different from each other");
        }

        // ---- D: same night, one thing about the person changed ----

        static Scenario001Content WithTrait(string who, string trait, double level)
        {
            var cast = new Dictionary<string, Profile>(StringComparer.Ordinal);
            foreach (var pair in _content.Cast) cast[pair.Key] = pair.Value;

            var p = _content.Cast[who];
            var traits = p.Traits.ToDictionary(t => t.Key, t => t.Value, StringComparer.Ordinal);
            traits[trait] = level;
            cast[who] = new Profile(p.Id, p.DisplayName, p.Age, p.FamilyRole, traits, p.Values,
                p.Perceptiveness, p.AttentionWeights, p.InitialBeliefs, p.Expressiveness, p.HungerRate);

            return new Scenario001Content(_content.Vocabulary, cast, _content.Backstory, _content.Morning, _content.Rules);
        }

        [Test]
        public void D_ChangingOneTraitChangesHowTheSameNightLands()
        {
            const string variant = "mara_ate_it";
            const string who = "mara";

            (double start, double morning, string meaning, double fear) Measure(Scenario001Content content)
            {
                var starts = new List<double>();
                var mornings = new List<double>();
                for (ulong seed = 1; seed <= Seeds; seed++)
                {
                    var p = Pair(variant, seed, content: content).People[who];
                    starts.Add(p.ShiftAtStart("avoid_exposure"));
                    mornings.Add(p.ShiftOverMorning("avoid_exposure"));
                }

                var probe = Scenario001.Prepare(content, variant, 1);
                var search = new WorldEvent("probe-d", _content.Morning.Day, 5000, EventKind.Action, "leo", null,
                    null, "search_belongings", "missing_can", "neutral", "direct", "neutral", null, "Leo searches.",
                    new[] { who }, new string[0], new List<LedgerEffect>(), null, 10);
                var o = probe.Simulation.Apply(search).ByCharacter[who];
                var fear = o.Emotions.Where(e => e.Type == "fear").Select(e => e.Intensity).DefaultIfEmpty(0).Max();

                return (starts.Average(), mornings.Average(), o.Meaning, fear);
            }

            var asShe = Measure(_content);
            var calm = Measure(WithTrait(who, "anxious", 0.20));
            var shameless = Measure(WithTrait(who, "honest", 0.10));

            Record("D. Same night, one trait changed", "`" + variant + "`, " + who + ", " + Seeds + " seeds." +
                   Environment.NewLine + Environment.NewLine +
                   "| Mara | `avoid_exposure` at start | over the morning | Reads a search as | Fear it stirs |" + Environment.NewLine +
                   "|---|---|---|---|---|" + Environment.NewLine +
                   "| as written (anxious 0.80, honest 0.55) | " + asShe.start.ToString("+0.000;-0.000") + " | " + asShe.morning.ToString("+0.000;-0.000") + " | " + asShe.meaning + " | " + asShe.fear.ToString("0.00") + " |" + Environment.NewLine +
                   "| anxious 0.20 | " + calm.start.ToString("+0.000;-0.000") + " | " + calm.morning.ToString("+0.000;-0.000") + " | " + calm.meaning + " | " + calm.fear.ToString("0.00") + " |" + Environment.NewLine +
                   "| honest 0.10 | " + shameless.start.ToString("+0.000;-0.000") + " | " + shameless.morning.ToString("+0.000;-0.000") + " | " + shameless.meaning + " | " + shameless.fear.ToString("0.00") + " |" + Environment.NewLine +
                   Environment.NewLine +
                   "The reading of the search comes from the belief and is the same in all three. What it does to her comes from her.");

            Assert.AreEqual(asShe.meaning, calm.meaning, "temperament should not change what she believes the search is about");
            Assert.Less(calm.fear, asShe.fear, "a calmer Mara is not less frightened by the same threat");
            Assert.Less(shameless.start, asShe.start, "a less honest Mara is not less troubled at the start by what she did");
        }

        // ---- behaviour, measured against the noise it has to beat ----

        [Test]
        public void WhetherItReachesBehaviourAboveTheNoise()
        {
            // A behaviour difference means nothing without knowing how different
            // two sets of mornings are when nothing at all has changed. Each
            // comparison is between twenty-seed pools from disjoint seeds.
            var sb = new StringBuilder();
            sb.AppendLine("| Condition | Who | Night vs no night | No night vs no night | Night vs night | Above the noise |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var anyAbove = false;

            foreach (var (variant, who) in Culprits)
            {
                Dictionary<string, double> Pool(bool treatment, ulong from)
                {
                    var counts = new Dictionary<string, double>(StringComparer.Ordinal);
                    var total = 0;
                    for (var seed = from; seed < from + 20; seed++)
                    {
                        var run = Scenario001.PrepareWith(_content, variant, treatment ? Night(variant) : new List<WorldEvent>(), seed);
                        run.Morning.Run(_content.Morning.Minutes);
                        foreach (var a in run.Result.By(who))
                        {
                            counts.TryGetValue(a.Action.KindName, out var n);
                            counts[a.Action.KindName] = n + 1;
                            total++;
                        }
                    }
                    return counts.ToDictionary(c => c.Key, c => c.Value / Math.Max(1, total), StringComparer.Ordinal);
                }

                var t1 = Pool(true, 1); var t2 = Pool(true, 21);
                var c1 = Pool(false, 1); var c2 = Pool(false, 21);

                var effect = (BatchRunner.HowDifferent(t1, c2) + BatchRunner.HowDifferent(t2, c1)) / 2;
                var noiseC = BatchRunner.HowDifferent(c1, c2);
                var noiseT = BatchRunner.HowDifferent(t1, t2);
                var above = effect > Math.Max(noiseC, noiseT) * 1.5;
                anyAbove |= above;

                sb.AppendLine("| " + variant + " | " + who + " | " + effect.ToString("0.000") + " | " + noiseC.ToString("0.000") +
                              " | " + noiseT.ToString("0.000") + " | " + (above ? "yes" : "no") + " |");
            }

            sb.AppendLine();
            sb.AppendLine("Above the noise means the night-versus-no-night difference is more than one and a half times the larger of the two same-condition differences.");
            Record("E. Behaviour against the noise floor", sb.ToString());
            TestContext.WriteLine("any condition above the noise: " + anyAbove);
        }

        [Test]
        public void WhetherTheBehaviourEffectRepeatsOnSeedsNeverUsedBefore()
        {
            // Written after the test above was widened from ten-seed pools to
            // twenty, which it was because the ten-seed result was null. Widening
            // a sample after seeing a null is how a false positive gets made, so
            // the positive result is checked here on seeds 41 to 80, which no test
            // had used when this was written. The gate is unchanged, and was
            // stated before these seeds were run: Mara must clear it.
            var sb = new StringBuilder();
            sb.AppendLine("| Condition | Who | Night vs no night | No night vs no night | Night vs night | Above the noise |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var maraAbove = false;

            foreach (var (variant, who) in new[] { ("mara_ate_it", "mara"), ("elena_fed_mara", "elena") })
            {
                Dictionary<string, double> Pool(bool treatment, ulong from)
                {
                    var counts = new Dictionary<string, double>(StringComparer.Ordinal);
                    var total = 0;
                    for (var seed = from; seed < from + 20; seed++)
                    {
                        var run = Scenario001.PrepareWith(_content, variant, treatment ? Night(variant) : new List<WorldEvent>(), seed);
                        run.Morning.Run(_content.Morning.Minutes);
                        foreach (var a in run.Result.By(who))
                        {
                            counts.TryGetValue(a.Action.KindName, out var n);
                            counts[a.Action.KindName] = n + 1;
                            total++;
                        }
                    }
                    return counts.ToDictionary(c => c.Key, c => c.Value / Math.Max(1, total), StringComparer.Ordinal);
                }

                var t1 = Pool(true, 41); var t2 = Pool(true, 61);
                var c1 = Pool(false, 41); var c2 = Pool(false, 61);

                var effect = (BatchRunner.HowDifferent(t1, c2) + BatchRunner.HowDifferent(t2, c1)) / 2;
                var noiseC = BatchRunner.HowDifferent(c1, c2);
                var noiseT = BatchRunner.HowDifferent(t1, t2);
                var above = effect > Math.Max(noiseC, noiseT) * 1.5;
                if (who == "mara") maraAbove = above;

                sb.AppendLine("| " + variant + " | " + who + " | " + effect.ToString("0.000") + " | " + noiseC.ToString("0.000") +
                              " | " + noiseT.ToString("0.000") + " | " + (above ? "yes" : "no") + " |");
            }

            Record("E. Behaviour against the noise floor, fresh seeds 41 to 80", sb.ToString());
            Assert.IsTrue(maraAbove, "the behaviour effect did not repeat on seeds that were never used to find it");
        }

        // ---- nothing was fitted by naming anybody or anything ----

        [Test]
        public void NothingAddedInS11NamesAPersonACondition()
        {
            var problems = new List<string>();
            problems.AddRange(RuleSetValidator.ValidateNamesNobody(_content.Rules, _content.Cast.Keys));
            problems.AddRange(DecisionRuleValidator.ValidateNamesNobody(_content.Rules, _content.Cast.Keys));

            var forbidden = _content.Morning.Variants.Concat(_content.Morning.HeldOutVariants)
                .SelectMany(v => new[] { v.Id }.Concat(v.NightEvents.Select(e => e.Id)))
                .Concat(_content.Cast.Keys)
                .Distinct()
                .ToList();

            foreach (var file in Directory.GetFiles(TestPaths.CoreSources, "*.cs", SearchOption.AllDirectories))
            {
                var text = File.ReadAllText(file);
                foreach (var word in forbidden)
                    if (System.Text.RegularExpressions.Regex.IsMatch(text, "\"" + System.Text.RegularExpressions.Regex.Escape(word) + "\""))
                        problems.Add(Path.GetFileName(file) + " contains the string \"" + word + "\"");
            }

            foreach (var file in new[] { "rules.json", "decisions.json" })
            {
                var text = File.ReadAllText(Path.Combine(TestPaths.Rules, file));
                foreach (var v in _content.Morning.Variants.Concat(_content.Morning.HeldOutVariants))
                    if (text.Contains("\"" + v.Id + "\"")) problems.Add(file + " names the condition " + v.Id);
            }

            Assert.IsEmpty(problems, string.Join("\n", problems));
        }
    }
}
