using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.2: what is deciding the decisions?
    ///
    /// Written before anything in deliberation changed, and re-run after each
    /// change. It asserts nothing about what should happen; it records what does,
    /// into files that the report is built from.
    /// </summary>
    public class S12DiagnosisTests
    {
        const int Seeds = 20;
        static Scenario001Content _content;

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        static string Dir()
        {
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.2");
            Directory.CreateDirectory(dir);
            return dir;
        }

        [Test]
        public void WhatIsDecidingTheDecisions()
        {
            var variants = _content.Morning.Variants.Select(v => v.Id).ToList();
            var audit = DeliberationAudit.Run(_content, variants, Seeds);

            var sb = new StringBuilder();
            sb.AppendLine("# S1.2 diagnosis: what is deciding the decisions");
            sb.AppendLine();
            sb.AppendLine("Generated by `S12DiagnosisTests.WhatIsDecidingTheDecisions`. The five design conditions,");
            sb.AppendLine("seeds 1 to " + Seeds + ".");
            sb.AppendLine();
            sb.AppendLine(audit.ToMarkdown());

            File.WriteAllText(Path.Combine(Dir(), "audit-current.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());
        }

        /// <summary>One person's decisions in two mornings that differ only in the night.</summary>
        sealed class Paired
        {
            public List<DecisionMoment> Control = new List<DecisionMoment>();
            public List<DecisionMoment> Treatment = new List<DecisionMoment>();

            /// <summary>Whether taking avoid_exposure away would change each decision, weighed at the moment it was taken.</summary>
            public List<int> ControlAvoidDecisive = new List<int>();
            public List<int> TreatmentAvoidDecisive = new List<int>();
            public Scenario001Run ControlRun;
            public Scenario001Run TreatmentRun;
        }

        static Paired RunPaired(string variant, string who, ulong seed)
        {
            var night = _content.Morning.Variant(variant).NightEvents;
            var p = new Paired
            {
                ControlRun = Scenario001.PrepareWith(_content, variant + "/control", new List<WorldEvent>(), seed),
                TreatmentRun = Scenario001.PrepareWith(_content, variant + "/treatment", night, seed)
            };
            p.ControlRun.Morning.Decided = m => { if (m.CharacterId == who) { p.Control.Add(m); p.ControlAvoidDecisive.Add(Decisive(m, "avoid_exposure")); } };
            p.TreatmentRun.Morning.Decided = m => { if (m.CharacterId == who) { p.Treatment.Add(m); p.TreatmentAvoidDecisive.Add(Decisive(m, "avoid_exposure")); } };
            p.ControlRun.Morning.Run(_content.Morning.Minutes);
            p.TreatmentRun.Morning.Run(_content.Morning.Minutes);
            return p;
        }

        static string Ranked(Decision d, int n)
        {
            var sb = new StringBuilder();
            sb.AppendLine("| Option | Appeal | Cost | Score | Contributions |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var r in d.Ranked.Take(n))
                sb.AppendLine("| " + r.Option.Key + (r.Option.SameAs(d.Chosen) ? " **(chosen)**" : "") + " | " +
                              r.Appeal.ToString("0.000") + " | " + r.Cost.ToString("0.000") + " | " + r.Score.ToString("0.000") + " | " +
                              string.Join("; ", r.Contributions.Select(c => c.MotiveKey + " " + c.Amount.ToString("0.000"))) + " |");
            sb.AppendLine();
            sb.AppendLine("Resolution: " + d.Resolution + (d.Tied.Count > 0 ? ", tied " + string.Join(", ", d.Tied.Select(t => t.Key)) : "") + ".");
            return sb.ToString();
        }

        static int Decisive(DecisionMoment m, string motive)
        {
            var without = m.Motives.Where(x => x.Name != motive).ToList();
            var again = new Deliberator(_content.Rules).Decide(m.Mind, m.Percept, without, _content.Morning.Day, new Rng(1), new TraceLog(), 0, m.Decision.Holding);
            return again.Considered[0].Option.Key != m.Decision.Considered[0].Option.Key ? 1 : 0;
        }

        /// <summary>Share of one person's decisions spent on each kind of action.</summary>
        static Dictionary<string, double> ByDecision(IEnumerable<ActionRecord> mine, bool skipCarriedOn)
        {
            var list = mine.Where(a => !skipCarriedOn || a.Outcome != "thought again, and carried on").ToList();
            return list.GroupBy(a => a.Action.KindName).ToDictionary(g => g.Key, g => g.Count() / (double)Math.Max(1, list.Count), StringComparer.Ordinal);
        }

        /// <summary>Share of one person's morning, in minutes, spent on each kind of action.</summary>
        static Dictionary<string, double> ByMinute(IReadOnlyList<ActionRecord> mine, int minutes)
        {
            var d = new Dictionary<string, double>(StringComparer.Ordinal);
            for (var i = 0; i < mine.Count; i++)
            {
                var until = i + 1 < mine.Count ? mine[i + 1].Minute : minutes;
                d.TryGetValue(mine[i].Action.KindName, out var v);
                d[mine[i].Action.KindName] = v + (until - mine[i].Minute);
            }
            var total = d.Values.Sum();
            return d.ToDictionary(k => k.Key, k => k.Value / Math.Max(1, total), StringComparer.Ordinal);
        }

        static Dictionary<string, double> Merge(IEnumerable<Dictionary<string, double>> profiles)
        {
            var list = profiles.ToList();
            var keys = list.SelectMany(p => p.Keys).Distinct().ToList();
            return keys.ToDictionary(k => k, k => list.Average(p => p.TryGetValue(k, out var v) ? v : 0.0), StringComparer.Ordinal);
        }

        [Test]
        public void HowBigTheBehaviourEffectIsAgainstTheNoiseAndHowItIsCounted()
        {
            const string variant = "mara_ate_it";
            const string who = "mara";
            var night = _content.Morning.Variant(variant).NightEvents;
            var sb = new StringBuilder();
            sb.AppendLine("# S1.2 diagnosis: Mara's behaviour effect against the noise, three ways of counting");
            sb.AppendLine();
            sb.AppendLine("Generated by `S12DiagnosisTests`. Twenty-seed pools. Effect is night against no night across pools;");
            sb.AppendLine("noise is the larger same-condition difference between the two pools.");
            sb.AppendLine();
            sb.AppendLine("| Seeds | Counting | Night vs no night | Noise | Ratio |");
            sb.AppendLine("|---|---|---|---|---|");

            var perSeed = new StringBuilder();

            foreach (var from in new ulong[] { 1, 41 })
            {
                var runs = new Dictionary<string, List<Scenario001Run>>();
                foreach (var (label, withNight, start) in new[] { ("t1", true, from), ("t2", true, from + 20), ("c1", false, from), ("c2", false, from + 20) })
                {
                    runs[label] = new List<Scenario001Run>();
                    for (var s = start; s < start + 20; s++)
                    {
                        var run = Scenario001.PrepareWith(_content, variant, withNight ? night : new List<WorldEvent>(), s);
                        run.Morning.Run(_content.Morning.Minutes);
                        runs[label].Add(run);
                        if (from == 41)
                        {
                            var mine = run.Result.By(who);
                            perSeed.AppendLine("| " + s + " | " + (withNight ? "night" : "no night") + " | " + mine.Count + " | " +
                                               mine.Count(a => a.Outcome == "thought again, and carried on") + " | " +
                                               string.Join(", ", ByMinute(mine, _content.Morning.Minutes).OrderByDescending(k => k.Value).Take(3)
                                                   .Select(k => k.Key + " " + k.Value.ToString("P0"))) + " |");
                        }
                    }
                }

                foreach (var (counting, profile) in new (string, Func<Scenario001Run, Dictionary<string, double>>)[]
                         {
                             ("every decision (the S1.1 measure)", r => ByDecision(r.Result.By(who), false)),
                             ("decisions, not counting carrying on", r => ByDecision(r.Result.By(who), true)),
                             ("minutes spent", r => ByMinute(r.Result.By(who), _content.Morning.Minutes))
                         })
                {
                    // Pooled the way S1.1 pooled: every record in the pool counts once.
                    Dictionary<string, double> P(string k) => counting.StartsWith("minutes")
                        ? Merge(runs[k].Select(profile))
                        : ByDecision(runs[k].SelectMany(r => r.Result.By(who)), counting.StartsWith("decisions, not"));

                    var effect = (Fallow.Core.Testing.BatchRunner.HowDifferent(P("t1"), P("c2")) + Fallow.Core.Testing.BatchRunner.HowDifferent(P("t2"), P("c1"))) / 2;
                    var noise = Math.Max(Fallow.Core.Testing.BatchRunner.HowDifferent(P("c1"), P("c2")), Fallow.Core.Testing.BatchRunner.HowDifferent(P("t1"), P("t2")));
                    sb.AppendLine("| " + from + " to " + (from + 39) + " | " + counting + " | " + effect.ToString("0.000") + " | " + noise.ToString("0.000") + " | " + (effect / noise).ToString("0.0") + " |");
                }
            }

            sb.AppendLine();
            sb.AppendLine("## What the night does to how her morning runs, seeds 1 to 40");
            sb.AppendLine();
            sb.AppendLine("| Who | Night | Stopped per morning | ... by what they already felt | ... then carried on | Decisions | Minutes, by kind of action |");
            sb.AppendLine("|---|---|---|---|---|---|---|");
            foreach (var (v, person) in new[] { ("mara_ate_it", "mara"), ("elena_fed_mara", "elena") })
            foreach (var withNight in new[] { true, false })
            {
                var theNight = _content.Morning.Variant(v).NightEvents;
                double stopped = 0, byStanding = 0, carried = 0, decisions = 0;
                var minutes = new List<Dictionary<string, double>>();
                for (ulong s = 1; s <= 40; s++)
                {
                    var run = Scenario001.PrepareWith(_content, v, withNight ? theNight : new List<WorldEvent>(), s);
                    run.Morning.Run(_content.Morning.Minutes);
                    var mine = run.Morning.Interruptions.Where(x => x.CharacterId == person).ToList();
                    stopped += mine.Count;
                    byStanding += mine.Count(x => x.EventIntensity < _content.Rules.Deciding.InterruptIntensity);
                    carried += run.Result.By(person).Count(a => a.Outcome == "thought again, and carried on");
                    decisions += run.Result.By(person).Count;
                    minutes.Add(ByMinute(run.Result.By(person), _content.Morning.Minutes));
                }
                sb.AppendLine("| " + person + " | " + (withNight ? "yes" : "no") + " | " + (stopped / 40).ToString("0.0") + " | " + (byStanding / 40).ToString("0.0") +
                              " | " + (carried / 40).ToString("0.0") + " | " + (decisions / 40).ToString("0.0") + " | " +
                              string.Join(", ", Merge(minutes).OrderByDescending(k => k.Value).Select(k => k.Key + " " + k.Value.ToString("P0"))) + " |");
            }

            sb.AppendLine();
            sb.AppendLine("## Seeds 41 to 80, one morning each");
            sb.AppendLine();
            sb.AppendLine("| Seed | Night | Decisions | Of which carrying on | Most of her morning, by minutes |");
            sb.AppendLine("|---|---|---|---|---|");
            sb.Append(perSeed);

            File.WriteAllText(Path.Combine(Dir(), "behaviour-noise-current.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());
        }

        [Test]
        public void WhetherAChangedWantReachesTheChoice()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.2 diagnosis: whether a changed want reaches the choice");
            sb.AppendLine();
            sb.AppendLine("Generated by `S12DiagnosisTests.WhetherAChangedWantReachesTheChoice`. Each culprit against a");
            sb.AppendLine("no-night control on the same seed, seeds 1 to " + Seeds + ". Minute zero is the one moment");
            sb.AppendLine("where both worlds are identical apart from the person, so any difference there is the night.");
            sb.AppendLine();

            foreach (var (variant, who) in new[] { ("mara_ate_it", "mara"), ("elena_fed_mara", "elena"), ("daniel_ate_it", "daniel") })
            {
                var firstTopDiffers = 0;
                var firstChosenDiffers = 0;
                var avoidDecisiveT = 0;
                var avoidDecisiveC = 0;
                var decisionsT = 0;
                var decisionsC = 0;
                var sameMinuteBoth = 0;
                var sameMinuteDiffer = 0;
                var appealShift = new Dictionary<string, List<double>>(StringComparer.Ordinal);
                Paired first = null;

                for (ulong seed = 1; seed <= Seeds; seed++)
                {
                    var p = RunPaired(variant, who, seed);
                    if (seed == 1) first = p;

                    var c0 = p.Control[0].Decision;
                    var t0 = p.Treatment[0].Decision;
                    if (c0.Ranked[0].Option.Key != t0.Ranked[0].Option.Key) firstTopDiffers++;
                    if (!c0.Chosen.SameAs(t0.Chosen)) firstChosenDiffers++;

                    foreach (var r in t0.Ranked)
                    {
                        var c = c0.Ranked.FirstOrDefault(x => x.Option.SameAs(r.Option));
                        if (c == null) continue;
                        if (!appealShift.TryGetValue(r.Option.Key, out var list)) appealShift[r.Option.Key] = list = new List<double>();
                        list.Add(r.Score - c.Score);
                    }

                    decisionsT += p.Treatment.Count; avoidDecisiveT += p.TreatmentAvoidDecisive.Sum();
                    decisionsC += p.Control.Count; avoidDecisiveC += p.ControlAvoidDecisive.Sum();

                    foreach (var t in p.Treatment)
                    {
                        var c = p.Control.FirstOrDefault(x => x.Minute == t.Minute);
                        if (c == null) continue;
                        sameMinuteBoth++;
                        if (!c.Decision.Chosen.SameAs(t.Decision.Chosen)) sameMinuteDiffer++;
                    }
                }

                sb.AppendLine("## " + variant + ", " + who);
                sb.AppendLine();
                sb.AppendLine("| Measure | Value |");
                sb.AppendLine("|---|---|");
                sb.AppendLine("| First decision: best-scoring option differs from control | " + firstTopDiffers + " of " + Seeds + " seeds |");
                sb.AppendLine("| First decision: chosen option differs from control | " + firstChosenDiffers + " of " + Seeds + " seeds |");
                sb.AppendLine("| `avoid_exposure` decisive, with the night | " + avoidDecisiveT + " of " + decisionsT + " decisions |");
                sb.AppendLine("| `avoid_exposure` decisive, without it | " + avoidDecisiveC + " of " + decisionsC + " decisions |");
                sb.AppendLine("| Deciding at the same minute in both worlds, and choosing differently | " + sameMinuteDiffer + " of " + sameMinuteBoth + " |");
                sb.AppendLine();
                sb.AppendLine("Score change at minute zero, night minus no night, mean over seeds, largest moves:");
                sb.AppendLine();
                foreach (var kv in appealShift.OrderByDescending(k => Math.Abs(k.Value.Average())).Take(6))
                    sb.AppendLine("- `" + kv.Key + "` " + kv.Value.Average().ToString("+0.000;-0.000;0.000"));
                sb.AppendLine();
                sb.AppendLine("Seed 1, first decision, without the night:");
                sb.AppendLine();
                sb.AppendLine(Ranked(first.Control[0].Decision, 6));
                sb.AppendLine("Seed 1, first decision, with the night:");
                sb.AppendLine();
                sb.AppendLine(Ranked(first.Treatment[0].Decision, 6));
                sb.AppendLine("Seed 1, the first ten decisions: without `" +
                              string.Join(" ", first.Control.Take(10).Select(m => m.Minute + ":" + m.Decision.Chosen.Key)) + "`; with `" +
                              string.Join(" ", first.Treatment.Take(10).Select(m => m.Minute + ":" + m.Decision.Chosen.Key)) + "`.");
                sb.AppendLine();
            }

            File.WriteAllText(Path.Combine(Dir(), "reach-current.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());
        }
    }
}
