using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.2: what is deciding the decisions?
    ///
    /// Written before anything in deliberation changed, and re-run after each
    /// change. It asserts nothing about what should happen; it records what does,
    /// into files that the report is built from.
    /// </summary>
    public class S12DiagnosisTests
    {
        const int Seeds = 20;
        static Scenario001Content _content;

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        static string Dir()
        {
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.2");
            Directory.CreateDirectory(dir);
            return dir;
        }

        [Test]
        public void WhatIsDecidingTheDecisions()
        {
            var variants = _content.Morning.Variants.Select(v => v.Id).ToList();
            var audit = DeliberationAudit.Run(_content, variants, Seeds);

            var sb = new StringBuilder();
            sb.AppendLine("# S1.2 diagnosis: what is deciding the decisions");
            sb.AppendLine();
            sb.AppendLine("Generated by `S12DiagnosisTests.WhatIsDecidingTheDecisions`. The five design conditions,");
            sb.AppendLine("seeds 1 to " + Seeds + ".");
            sb.AppendLine();
            sb.AppendLine(audit.ToMarkdown());

            File.WriteAllText(Path.Combine(Dir(), "audit-current.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());
        }

        /// <summary>One person's decisions in two mornings that differ only in the night.</summary>
        sealed class Paired
        {
            public List<DecisionMoment> Control = new List<DecisionMoment>();
            public List<DecisionMoment> Treatment = new List<DecisionMoment>();
            public Scenario001Run ControlRun;
            public Scenario001Run TreatmentRun;
        }

        static Paired RunPaired(string variant, string who, ulong seed)
        {
            var night = _content.Morning.Variant(variant).NightEvents;
            var p = new Paired
            {
                ControlRun = Scenario001.PrepareWith(_content, variant + "/control", new List<WorldEvent>(), seed),
                TreatmentRun = Scenario001.PrepareWith(_content, variant + "/treatment", night, seed)
            };
            p.ControlRun.Morning.Decided = m => { if (m.CharacterId == who) p.Control.Add(m); };
            p.TreatmentRun.Morning.Decided = m => { if (m.CharacterId == who) p.Treatment.Add(m); };
            p.ControlRun.Morning.Run(_content.Morning.Minutes);
            p.TreatmentRun.Morning.Run(_content.Morning.Minutes);
            return p;
        }

        static string Ranked(Decision d, int n)
        {
            var sb = new StringBuilder();
            sb.AppendLine("| Option | Appeal | Cost | Score | Contributions |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var r in d.Ranked.Take(n))
                sb.AppendLine("| " + r.Option.Key + (r.Option.SameAs(d.Chosen) ? " **(chosen)**" : "") + " | " +
                              r.Appeal.ToString("0.000") + " | " + r.Cost.ToString("0.000") + " | " + r.Score.ToString("0.000") + " | " +
                              string.Join("; ", r.Contributions.Select(c => c.MotiveKey + " " + c.Amount.ToString("0.000"))) + " |");
            sb.AppendLine();
            sb.AppendLine("Resolution: " + d.Resolution + (d.Tied.Count > 0 ? ", tied " + string.Join(", ", d.Tied.Select(t => t.Key)) : "") + ".");
            return sb.ToString();
        }

        static int Decisive(DecisionMoment m, string motive)
        {
            var without = m.Motives.Where(x => x.Name != motive).ToList();
            var again = new Deliberator(_content.Rules).Decide(m.Mind, m.Percept, without, _content.Morning.Day, new Rng(1), new TraceLog(), 0);
            return again.Ranked[0].Option.Key != m.Decision.Ranked[0].Option.Key ? 1 : 0;
        }

        [Test]
        public void WhetherAChangedWantReachesTheChoice()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.2 diagnosis: whether a changed want reaches the choice");
            sb.AppendLine();
            sb.AppendLine("Generated by `S12DiagnosisTests.WhetherAChangedWantReachesTheChoice`. Each culprit against a");
            sb.AppendLine("no-night control on the same seed, seeds 1 to " + Seeds + ". Minute zero is the one moment");
            sb.AppendLine("where both worlds are identical apart from the person, so any difference there is the night.");
            sb.AppendLine();

            foreach (var (variant, who) in new[] { ("mara_ate_it", "mara"), ("elena_fed_mara", "elena"), ("daniel_ate_it", "daniel") })
            {
                var firstTopDiffers = 0;
                var firstChosenDiffers = 0;
                var avoidDecisiveT = 0;
                var avoidDecisiveC = 0;
                var decisionsT = 0;
                var decisionsC = 0;
                var sameMinuteBoth = 0;
                var sameMinuteDiffer = 0;
                var appealShift = new Dictionary<string, List<double>>(StringComparer.Ordinal);
                Paired first = null;

                for (ulong seed = 1; seed <= Seeds; seed++)
                {
                    var p = RunPaired(variant, who, seed);
                    if (seed == 1) first = p;

                    var c0 = p.Control[0].Decision;
                    var t0 = p.Treatment[0].Decision;
                    if (c0.Ranked[0].Option.Key != t0.Ranked[0].Option.Key) firstTopDiffers++;
                    if (!c0.Chosen.SameAs(t0.Chosen)) firstChosenDiffers++;

                    foreach (var r in t0.Ranked)
                    {
                        var c = c0.Ranked.FirstOrDefault(x => x.Option.SameAs(r.Option));
                        if (c == null) continue;
                        if (!appealShift.TryGetValue(r.Option.Key, out var list)) appealShift[r.Option.Key] = list = new List<double>();
                        list.Add(r.Score - c.Score);
                    }

                    foreach (var m in p.Treatment) { decisionsT++; avoidDecisiveT += Decisive(m, "avoid_exposure"); }
                    foreach (var m in p.Control) { decisionsC++; avoidDecisiveC += Decisive(m, "avoid_exposure"); }

                    foreach (var t in p.Treatment)
                    {
                        var c = p.Control.FirstOrDefault(x => x.Minute == t.Minute);
                        if (c == null) continue;
                        sameMinuteBoth++;
                        if (!c.Decision.Chosen.SameAs(t.Decision.Chosen)) sameMinuteDiffer++;
                    }
                }

                sb.AppendLine("## " + variant + ", " + who);
                sb.AppendLine();
                sb.AppendLine("| Measure | Value |");
                sb.AppendLine("|---|---|");
                sb.AppendLine("| First decision: best-scoring option differs from control | " + firstTopDiffers + " of " + Seeds + " seeds |");
                sb.AppendLine("| First decision: chosen option differs from control | " + firstChosenDiffers + " of " + Seeds + " seeds |");
                sb.AppendLine("| `avoid_exposure` decisive, with the night | " + avoidDecisiveT + " of " + decisionsT + " decisions |");
                sb.AppendLine("| `avoid_exposure` decisive, without it | " + avoidDecisiveC + " of " + decisionsC + " decisions |");
                sb.AppendLine("| Deciding at the same minute in both worlds, and choosing differently | " + sameMinuteDiffer + " of " + sameMinuteBoth + " |");
                sb.AppendLine();
                sb.AppendLine("Score change at minute zero, night minus no night, mean over seeds, largest moves:");
                sb.AppendLine();
                foreach (var kv in appealShift.OrderByDescending(k => Math.Abs(k.Value.Average())).Take(6))
                    sb.AppendLine("- `" + kv.Key + "` " + kv.Value.Average().ToString("+0.000;-0.000;0.000"));
                sb.AppendLine();
                sb.AppendLine("Seed 1, first decision, without the night:");
                sb.AppendLine();
                sb.AppendLine(Ranked(first.Control[0].Decision, 6));
                sb.AppendLine("Seed 1, first decision, with the night:");
                sb.AppendLine();
                sb.AppendLine(Ranked(first.Treatment[0].Decision, 6));
                sb.AppendLine("Seed 1, the first ten decisions: without `" +
                              string.Join(" ", first.Control.Take(10).Select(m => m.Minute + ":" + m.Decision.Chosen.Key)) + "`; with `" +
                              string.Join(" ", first.Treatment.Take(10).Select(m => m.Minute + ":" + m.Decision.Chosen.Key)) + "`.");
                sb.AppendLine();
            }

            File.WriteAllText(Path.Combine(Dir(), "reach-current.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());
        }
    }
}
