using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.3, before anything changes: what happens to wanting food, from the
    /// hunger that raises it to what eating does to it.
    ///
    /// Asserts nothing about what should happen. Records what does, including
    /// under circumstances the scenario never produces on its own and under one
    /// diagnostic rule set that is never shipped, each labelled as what it is.
    /// </summary>
    public class S13DiagnosisTests
    {
        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _sections = new SortedDictionary<string, string>(StringComparer.Ordinal);
        static readonly string[] People = { "daniel", "elena", "leo", "mara" };

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.3 diagnosis: wanting food");
            sb.AppendLine();
            sb.AppendLine("Generated by `S13DiagnosisTests`. Records, asserts nothing.");
            sb.AppendLine();
            foreach (var s in _sections.Values) sb.AppendLine(s);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.3");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "diagnosis-current.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _sections[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);

        // ---- circumstances and diagnostic rule sets ----

        /// <summary>DIAGNOSTIC ONLY, never shipped: the same rules with nothing priced against eating.</summary>
        internal static Scenario001Content PriceRemoved(Scenario001Content c)
        {
            var r = c.Rules;
            var rules = new RuleSet
            {
                Interpretation = r.Interpretation, BeliefNudges = r.BeliefNudges, Appraisal = r.Appraisal, Dynamics = r.Dynamics,
                Motivation = r.Motivation, Proposals = r.Proposals, Costs = r.Costs.Where(x => x.Action != "eat").ToList(), Deciding = r.Deciding
            };
            return new Scenario001Content(c.Vocabulary, c.Cast, c.Backstory, c.Morning, rules);
        }

        /// <summary>
        /// A circumstance, not a rule: more food in the pantry, and optionally an
        /// opening count that does not come up short, so nobody learns the
        /// shelf is short.
        /// </summary>
        internal static Scenario001Content Plenty(Scenario001Content c, int portions, bool countComesUpShort)
        {
            var m = c.Morning;
            var o = m.Opening;
            var opening = countComesUpShort
                ? o
                : new WorldEvent(o.Id, o.Day, o.Order, o.Kind, o.ActorId, o.TargetId, o.Act, o.Action, "supplies", o.Tone, o.Directness,
                    "neutral", o.Intent, "Elena counts the pantry with everyone standing there. There is enough.",
                    o.Witnesses, o.Overhearers, o.LedgerEffects, o.BeliefEffects, o.Minute);
            var morning = new MorningScenario(m.Id, m.Description, m.Day, m.Minutes, m.House, portions, m.StartRooms, m.StartHunger,
                opening, m.Variants, m.HeldOutVariants);
            return new Scenario001Content(c.Vocabulary, c.Cast, c.Backstory, morning, c.Rules);
        }

        /// <summary>Everyone else out of the kitchen, and this person as hungry as the scale allows.</summary>
        internal static void StarvingAlone(Scenario001Run run, string who, double hunger = 0.99)
        {
            run.World.Place(who, "kitchen");
            foreach (var id in run.World.Inhabitants.Where(i => i != who).ToList()) run.World.Place(id, "back_room");
            run.World.SetHunger(who, hunger);
        }

        static IReadOnlyList<Motive> Wants(Scenario001Run run, string who, TraceLog scratch = null)
            => new Motivator(_content.Rules).Raise(run.Minds[who], run.Morning.See(who), _content.Morning.Day, scratch ?? new TraceLog(), 0);

        // ---- 1. how hunger is raised and represented ----

        [Test]
        public void D1_HowHungerIsRaisedAndWhatTheWantRestsOn()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 1. How hunger is raised, and how it becomes a want");
            sb.AppendLine();
            sb.AppendLine("`mara_ate_it`, seed 1, shipped rules. Hunger is world state: a start level from the scenario, plus");
            sb.AppendLine("`hunger_per_minute` " + _content.Rules.Deciding.HungerPerMinute + " times the person's metabolism, every minute, clamped to 1.");
            sb.AppendLine("The want is raised by the rule `a_body_that_has_not_eaten`: `get_food` = hunger x 1.0, through the urgency knee at " + _content.Rules.Deciding.UrgencyKnee + ".");
            sb.AppendLine();
            sb.AppendLine("| Who | Metabolism | Hunger at 0 / 30 / 60 / 90 | `get_food` at 90 | Records the hunger term rests on |");
            sb.AppendLine("|---|---|---|---|---|");

            var run = Scenario001.Prepare(_content, "mara_ate_it", 1);
            var levels = People.ToDictionary(p => p, p => new List<double> { run.World.HungerOf(p) });
            for (var i = 1; i <= 90; i++)
            {
                run.Morning.Step();
                if (i % 30 == 0) foreach (var p in People) levels[p].Add(run.World.HungerOf(p));
            }

            foreach (var p in People)
            {
                var want = Wants(run, p).FirstOrDefault(m => m.Name == "get_food");
                var term = want?.Terms.FirstOrDefault(t => t.Description.StartsWith("hunger", StringComparison.Ordinal));
                sb.AppendLine("| " + p + " | " + run.Minds[p].Profile.HungerRate + " | " + string.Join(" / ", levels[p].Select(F)) + " | " +
                              (want == null ? "not raised" : F(want.Urgency)) + " | " + (term == null ? "n/a" : term.Drew.Count.ToString()) + " |");
            }

            sb.AppendLine();
            sb.AppendLine("Every other kind of term a want can rest on names the records it read (a feeling's causes, a memory, a belief's evidence). The hunger term names none: nothing in the trace can say why somebody is as hungry as they are.");
            Record("1", sb.ToString());
        }

        // ---- 2. the price of eating ----

        [Test]
        public void D2_WhatEatingCostsEachOfThemAndWhetherItCanEverBeWorthIt()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 2. What eating costs each of them, and whether it can ever be worth it");
            sb.AppendLine();
            sb.AppendLine("Shipped rules, `mara_ate_it`, seed 1, just after the opening count. Eating is worth exactly the urgency of `get_food`, which cannot exceed 1.");
            sb.AppendLine("The highest it can reach this morning is the knee applied to start hunger plus ninety minutes of that person's metabolism.");
            sb.AppendLine("Price alone is measured with everyone else moved out of the kitchen; watched, with the whole house there.");
            sb.AppendLine();
            sb.AppendLine("| Who | Price alone | ... of which | Price watched | Best `get_food` this morning | Best score alone | Best score watched | Standing still alone, same moment |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");

            foreach (var p in People)
            {
                var run = Scenario001.Prepare(_content, "mara_ate_it", 1);
                run.World.Place(p, "kitchen");
                var watched = Price(run, p);

                StarvingAlone(run, p, run.World.HungerOf(p));
                var alone = Price(run, p);
                var d = new Deliberator(_content.Rules).Decide(run.Minds[p], run.Morning.See(p), Wants(run, p), _content.Morning.Day, new Rng(1), new TraceLog(), 0);
                var wait = d.Ranked.First(r => r.Option.Kind == ActionKind.Wait);

                var start = _content.Morning.StartHunger[p];
                var reach = Accumulate.Knee(Math.Min(1.0, start + 90 * _content.Rules.Deciding.HungerPerMinute * run.Minds[p].Profile.HungerRate), _content.Rules.Deciding.UrgencyKnee);

                sb.AppendLine("| " + p + " | " + F(alone.cost) + " | " + string.Join("; ", alone.prices) + " | " + F(watched.cost) + " | " + F(reach) + " | " +
                              F(reach - alone.cost) + " | " + F(reach - watched.cost) + " | " + F(wait.Score) + " (" +
                              string.Join(", ", wait.Contributions.Select(c => c.ProposalId + " " + F(c.Amount))) + ") |");
            }

            sb.AppendLine();
            sb.AppendLine("The same, at the top of the hunger scale (1.0, worth " + F(Accumulate.Knee(1.0, _content.Rules.Deciding.UrgencyKnee)) + " after the knee), is the column of best scores shifted up by the difference.");
            sb.AppendLine();
            sb.AppendLine("The same price, alone, where the count did not come up short and there is plenty (nobody believes supplies are short), against the top of the hunger scale:");
            sb.AppendLine();
            sb.AppendLine("| Who | Price alone, nothing short | Best score alone at hunger 1.0 |");
            sb.AppendLine("|---|---|---|");
            foreach (var p in People)
            {
                var run = Scenario001.Prepare(Plenty(_content, 10, false), "mara_ate_it", 1);
                StarvingAlone(run, p, 1.0);
                var price = Price(run, p).cost;
                sb.AppendLine("| " + p + " | " + F(price) + " | " + F(Accumulate.Knee(1.0, _content.Rules.Deciding.UrgencyKnee) - price) + " |");
            }
            Record("2", sb.ToString());
        }

        static (double cost, List<string> prices) Price(Scenario001Run run, string who)
        {
            var d = new Deliberator(_content.Rules).Decide(run.Minds[who], run.Morning.See(who), new List<Motive>(), _content.Morning.Day, new Rng(1), new TraceLog(), 0);
            var eat = d.Ranked.First(r => r.Option.Kind == ActionKind.Eat);
            return (eat.Cost, eat.Prices.Select(x => x.Split('(')[0].Trim()).ToList());
        }

        // ---- 3. why eating loses, in the morning as it runs ----

        [Test]
        public void D3_EveryTimeEatingWasPossibleAndWhatBeatIt()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 3. Every time eating was possible, and what beat it");
            sb.AppendLine();
            sb.AppendLine("Shipped rules, five design conditions, seeds 1 to 20. Decisions where eating was an option.");
            sb.AppendLine();
            sb.AppendLine("| Who | Decisions with eating available | Eating scored above zero | Eating beat standing still | Eating beat everything except standing still | Eating came top | Mean score of eating | Mean score of what came top | What came top most |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|");

            var stats = People.ToDictionary(p => p, p => new List<(double eat, double top, double wait, double bestOther, string topKind)>());
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 20; seed++)
            {
                var run = Scenario001.Prepare(_content, v.Id, seed);
                run.Morning.Decided = m =>
                {
                    var eat = m.Decision.Ranked.FirstOrDefault(r => r.Option.Kind == ActionKind.Eat);
                    if (eat == null) return;
                    var wait = m.Decision.Ranked.First(r => r.Option.Kind == ActionKind.Wait);
                    var other = m.Decision.Ranked.Where(r => r.Option.Kind != ActionKind.Wait && r.Option.Kind != ActionKind.Eat).Select(r => r.Score).DefaultIfEmpty(double.MinValue).Max();
                    stats[m.CharacterId].Add((eat.Score, m.Decision.Considered[0].Score, wait.Score, other, m.Decision.Considered[0].Option.KindName));
                };
                run.Morning.Run(_content.Morning.Minutes);
            }

            foreach (var p in People)
            {
                var s = stats[p];
                if (s.Count == 0) { sb.AppendLine("| " + p + " | 0 | | | | | | | |"); continue; }
                sb.AppendLine("| " + p + " | " + s.Count + " | " + s.Count(x => x.eat > 0) + " | " + s.Count(x => x.eat > x.wait) + " | " +
                              s.Count(x => x.eat > x.bestOther) + " | " + s.Count(x => x.eat >= x.top) + " | " + F(s.Average(x => x.eat)) + " | " +
                              F(s.Average(x => x.top)) + " | " + s.GroupBy(x => x.topKind).OrderByDescending(g => g.Count()).First().Key + " |");
            }

            Record("3", sb.ToString());
        }

        // ---- 4. walking to the food ----

        [Test]
        public void D4_WalkingToTheFoodAndWhatHappensOnArrival()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 4. Walking to the food, and what happens on arrival");
            sb.AppendLine();
            var audit = DeliberationAudit.Run(_content, _content.Morning.Variants.Select(v => v.Id).ToList(), 20, weighWants: false);
            sb.AppendLine("Shipped rules, five conditions, seeds 1 to 20, from the S1.2 audit: intentions carried into a decision, by want and fate:");
            sb.AppendLine();
            foreach (var k in audit.CommitmentsByWant.OrderBy(k => k.Key, StringComparer.Ordinal)) sb.AppendLine("- `" + k.Key + "` " + k.Value);
            sb.AppendLine();

            // Who walks for food, how often, and whether wanting it changed afterwards.
            var walks = People.ToDictionary(p => p, p => 0);
            var sameWantAfter = new List<double>();
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 20; seed++)
            {
                var run = Scenario001.Prepare(_content, v.Id, seed);
                var lapsedAt = new Dictionary<string, double>();
                run.Morning.Decided = m =>
                {
                    var foodWant = m.Motives.FirstOrDefault(x => x.Name == "get_food")?.Urgency ?? 0;
                    if (m.Decision.Holding?.MotiveName == "get_food")
                    {
                        walks[m.CharacterId]++;
                        if (m.Decision.Commitment != Commitment.Held) lapsedAt[m.CharacterId] = foodWant;
                    }
                    else if (lapsedAt.TryGetValue(m.CharacterId, out var was))
                    {
                        sameWantAfter.Add(foodWant - was);
                        lapsedAt.Remove(m.CharacterId);
                    }
                };
                run.Morning.Run(_content.Morning.Minutes);
            }

            sb.AppendLine("Walks for food that arrived: " + string.Join(", ", walks.Select(w => w.Key + " " + w.Value)) + ".");
            sb.AppendLine("After a walk for food ended without eating, `get_food` at the person's next decision differed from what it was on arrival by a mean of " +
                          (sameWantAfter.Count == 0 ? "n/a" : F(sameWantAfter.Average())) + " (" + sameWantAfter.Count + " cases): the only change is the body getting hungrier. Nothing about having gone and not eaten is recorded anywhere a want can read.");
            Record("4", sb.ToString());
        }

        // ---- 5. what eating does when it does happen ----

        [Test]
        public void D5_WhatEatingDoesToTheWantWhenItHappens()
        {
            // Nobody eats under the shipped rules, so what eating does has to be
            // seen somewhere it happens. First under the diagnostic rule set with
            // nothing priced against eating, then under the shipped rules in the
            // most permissive circumstance the house allows.
            var sb = new StringBuilder();
            sb.AppendLine("## 5. What eating does to the want, when it happens");
            sb.AppendLine();
            sb.AppendLine("| Setting | Who, minute | Hunger before -> after | `get_food` the minute before -> the minute after | Eater's own reading of it | Beliefs it moved in the eater | Does `get_food` afterwards lead back to the eating? | Does anything the eater wants lead back to it? |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");

            foreach (var (label, content, circumstance) in new (string, Scenario001Content, Action<Scenario001Run>)[]
                     {
                         ("DIAGNOSTIC rules, eating unpriced, `mara_ate_it` seed 1", PriceRemoved(_content), null),
                         ("shipped rules, Mara starving alone, plenty and not short", Plenty(_content, 10, false), r => StarvingAlone(r, "mara"))
                     })
            {
                var run = Scenario001.Prepare(content, "mara_ate_it", 1);
                circumstance?.Invoke(run);
                var found = false;

                for (var i = 0; i < 90 && !found; i++)
                {
                    var hungerBefore = People.ToDictionary(p => p, p => run.World.HungerOf(p));
                    var wantBefore = People.ToDictionary(p => p, p => Wants(run, p).FirstOrDefault(m => m.Name == "get_food")?.Urgency ?? 0);
                    var seen = run.Result.Events.Count;
                    run.Morning.Step();

                    var eat = run.Result.Events.Skip(seen).FirstOrDefault(e => e.Action == "eat_portion");
                    if (eat == null) continue;
                    found = true;

                    var who = eat.ActorId;
                    var mind = run.Minds[who];
                    var reading = mind.Experiences.First(x => x.EventId == eat.Id);
                    var moved = run.Trace.All.Where(r => r.Kind == TraceKind.BeliefChange && r.CharacterId == who && r.EventId == eat.Id && r.Summary.Contains("moved"))
                        .Select(r => r.Summary).ToList();

                    var after = Wants(run, who);
                    var food = after.FirstOrDefault(m => m.Name == "get_food");
                    var causes = new[] { eat.Id };
                    var foodReaches = food != null && Counterfactual.ReachesCause(run.Trace, food, causes);
                    var anyReaches = after.Where(m => Counterfactual.ReachesCause(run.Trace, m, causes)).Select(m => m.Key).ToList();

                    sb.AppendLine("| " + label + " | " + who + ", " + eat.Minute + " | " + F(hungerBefore[who]) + " -> " + F(run.World.HungerOf(who)) + " | " +
                                  F(wantBefore[who]) + " -> " + (food == null ? "not raised" : F(food.Urgency)) + " | " + reading.Meaning + (reading.DominantEmotion == null ? "" : ", felt as " + reading.DominantEmotion) +
                                  " | " + (moved.Count == 0 ? "none" : string.Join("; ", moved)) + " | " + (foodReaches ? "yes" : "**no**") + " | " +
                                  (anyReaches.Count == 0 ? "no" : string.Join(", ", anyReaches)) + " |");
                }

                if (!found) sb.AppendLine("| " + label + " | nobody ate in 90 minutes | | | | | | |");
            }

            sb.AppendLine();
            sb.AppendLine("The body is relieved directly by the world (`SetHunger`), so the want falls. Nothing records that it fell because of the eating: the want cannot be walked back to the act that changed it.");
            Record("5", sb.ToString());
        }

        // ---- 6. reaching for food that is not there ----

        [Test]
        public void D6_ReachingForFoodThatIsGone()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 6. Reaching for food that is gone");
            sb.AppendLine();
            sb.AppendLine("Shipped rules, Mara starving alone with plenty and not short, every design condition, seeds 1 to 10, until ten attempts are found. As soon as she has started eating, the pantry is emptied from outside, as if somebody else had got there first.");
            sb.AppendLine();
            var tried = 0;
            var noted = 0;
            var eventsForIt = 0;
            var experiences = 0;
            var stoppedFirst = 0;
            double hungerChange = 0;

            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 10 && tried < 10; seed++)
            {
                var run = Scenario001.Prepare(Plenty(_content, 10, false), v.Id, seed);
                StarvingAlone(run, "mara");
                for (var i = 0; i < 60; i++)
                {
                    run.Morning.Step();
                    var doing = run.Morning.Doing("mara");
                    if (!doing.HasValue || doing.Value.Action.Kind != ActionKind.Eat) continue;

                    while (run.World.TakePortion()) { }
                    var before = run.World.HungerOf("mara");
                    var seen = run.Result.Events.Count;
                    var expSeen = run.Minds["mara"].Experiences.Count;
                    var stopsSeen = run.Morning.Interruptions.Count(x => x.CharacterId == "mara");
                    for (var j = 0; j < doing.Value.MinutesLeft; j++) run.Morning.Step();

                    tried++;
                    if (run.Result.By("mara").Any(a => a.Outcome != null && a.Outcome.Contains("nothing"))) noted++;
                    if (run.Morning.Interruptions.Count(x => x.CharacterId == "mara") > stopsSeen) stoppedFirst++;
                    eventsForIt += run.Result.Events.Skip(seen).Count(e => e.ActorId == "mara");
                    experiences += run.Minds["mara"].Experiences.Skip(expSeen).Count(x => x.ActorId == "mara");
                    hungerChange += run.World.HungerOf("mara") - before;
                    break;
                }
            }

            sb.AppendLine("- attempts that met an empty pantry: " + tried);
            sb.AppendLine("- noted on the action record as finding nothing: " + noted);
            sb.AppendLine("- stopped by something else before reaching the shelf: " + stoppedFirst);
            sb.AppendLine("- events anybody could perceive, made by her, from then until she would have finished: " + eventsForIt);
            sb.AppendLine("- memories she kept of her own act: " + experiences);
            sb.AppendLine("- mean change in her hunger over those minutes: " + F(tried == 0 ? 0 : hungerChange / tried) + " (the body alone)");
            sb.AppendLine();
            sb.AppendLine("A failed attempt is written on the action record and nowhere else. It is not an event, so nobody perceives it, including her.");
            Record("6", sb.ToString());
        }

        // ---- 7. can anybody eat when the circumstances allow it ----

        [Test]
        public void D7_WhetherAnybodyEatsWhenTheHouseLetsThem()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 7. Whether anybody eats when the house lets them");
            sb.AppendLine();
            sb.AppendLine("Shipped rules throughout; only the circumstances change.");
            sb.AppendLine();
            sb.AppendLine("| Circumstance | Mornings | Mornings each person ate: daniel / elena / leo / mara |");
            sb.AppendLine("|---|---|---|");

            string Row(string label, Scenario001Content content, Action<Scenario001Run> set, int seeds, int minutes)
            {
                var ate = People.ToDictionary(p => p, p => 0);
                var n = 0;
                foreach (var v in content.Morning.Variants)
                for (ulong seed = 1; seed <= (ulong)seeds; seed++)
                {
                    var run = Scenario001.Prepare(content, v.Id, seed);
                    set?.Invoke(run);
                    run.Morning.Run(minutes);
                    n++;
                    foreach (var p in People)
                        if (run.Result.By(p).Any(a => a.Action.Kind == ActionKind.Eat && a.Outcome != null && a.Outcome.StartsWith("ate", StringComparison.Ordinal))) ate[p]++;
                }
                return "| " + label + " | " + n + " | " + string.Join(" / ", People.Select(p => ate[p].ToString())) + " |";
            }

            sb.AppendLine(Row("the scenario as written", _content, null, 10, 90));
            sb.AppendLine(Row("plenty of food, count still comes up short", Plenty(_content, 10, true), null, 10, 90));
            sb.AppendLine(Row("plenty of food, count not short", Plenty(_content, 10, false), null, 10, 90));
            foreach (var p in People)
                sb.AppendLine(Row(p + " starving alone in the kitchen, plenty, not short", Plenty(_content, 10, false), r => StarvingAlone(r, p), 4, 60));
            foreach (var p in People)
                sb.AppendLine(Row(p + " starving alone in the kitchen, as written", _content, r => StarvingAlone(r, p), 4, 60));

            Record("7", sb.ToString());
        }
    }
}
