using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The S1.3 experiment: does acting on wanting food change the want according
    /// to what actually happened, traceably, and without anything that decays by
    /// itself?
    ///
    /// Nobody eats in the scenario as written (see the diagnosis), so eating is
    /// observed where the house lets people eat: plenty of food and a count that
    /// does not come up short. That is a circumstance, not a rule. The shipped
    /// rules are used throughout; one test removes what eating does to the body,
    /// and says so.
    /// </summary>
    public class S13ExperimentTests
    {
        static Scenario001Content _content;
        static Scenario001Content _plenty;
        static readonly SortedDictionary<string, string> _findings = new SortedDictionary<string, string>(StringComparer.Ordinal);
        static readonly string[] People = { "daniel", "elena", "leo", "mara" };

        [OneTimeSetUp]
        public void Load()
        {
            _content = Scenario001Content.Load(TestPaths.DataRoot);
            _plenty = S13DiagnosisTests.Plenty(_content, 10, false);
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.3 experiment results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S13ExperimentTests`. Shipped rules unless a section says otherwise.");
            sb.AppendLine("\"Plenty\" means ten portions and an opening count that does not come up short: a circumstance, not a rule.");
            sb.AppendLine();
            foreach (var f in _findings) sb.AppendLine("## " + f.Key + Environment.NewLine + Environment.NewLine + f.Value);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.3");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "experiment-results.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _findings[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);

        static string Shorten(string why)
            => string.Join(Environment.NewLine, why.Split('\n')
                .Select(l => l.TrimEnd('\r'))
                .Select(l => l.Length > 220 ? l.Substring(0, 217) + "..." : l));

        /// <summary>One act of eating and everything around it.</summary>
        sealed class Meal
        {
            public string Variant;
            public ulong Seed;
            public string Who;
            public DecisionMoment Chose;
            public DecisionMoment Next;
            public DecisionMoment NextWithFoodInReach;

            /// <summary>Every decision the eater took after the meal, in order.</summary>
            public List<DecisionMoment> After = new List<DecisionMoment>();
            public WorldEvent Event;
            public PursuitOutcome Outcome;
            public Scenario001Run Run;
        }

        /// <summary>
        /// Runs mornings and collects every completed act of eating, with the
        /// decision that chose it, the eater's next decision, the event and the
        /// outcome. Everything about a decision is read in the callback, while
        /// the mind is still in the state it decided in.
        /// </summary>
        static List<Meal> Meals(Scenario001Content content, IEnumerable<string> variants, int seeds, Action<Scenario001Run> set = null)
        {
            var meals = new List<Meal>();
            foreach (var v in variants)
            for (ulong seed = 1; seed <= (ulong)seeds; seed++)
            {
                var run = Scenario001.Prepare(content, v, seed);
                set?.Invoke(run);
                var chosen = new Dictionary<string, DecisionMoment>(StringComparer.Ordinal);
                var open = new List<Meal>();
                var seenEvents = run.Result.Events.Count;

                // A meal is resolved, and the eater may decide again, within the
                // same minute, so meals are gathered as soon as their event exists.
                void Gather()
                {
                    var events = run.Result.Events;
                    for (; seenEvents < events.Count; seenEvents++)
                    {
                        var e = events[seenEvents];
                        if (e.Action != "eat_portion" && e.Action != "find_nothing_left") continue;
                        var meal = new Meal
                        {
                            Variant = v, Seed = seed, Who = e.ActorId, Event = e, Run = run,
                            Outcome = run.Minds[e.ActorId].Outcomes.LastOrDefault(o => o.EventId == e.Id)
                        };
                        chosen.TryGetValue(e.ActorId, out var decided);
                        meal.Chose = decided;
                        meals.Add(meal);
                        open.Add(meal);
                    }
                }

                run.Morning.Decided = m =>
                {
                    Gather();
                    foreach (var meal in open.Where(x => x.Who == m.CharacterId))
                    {
                        if (meal.Next == null) meal.Next = m;
                        meal.After.Add(m);
                        if (meal.NextWithFoodInReach == null && m.Decision.Ranked.Any(r => r.Option.Kind == ActionKind.Eat)) meal.NextWithFoodInReach = m;
                    }
                    if (m.Decision.Chosen.Kind == ActionKind.Eat) chosen[m.CharacterId] = m;
                };

                for (var i = 0; i < content.Morning.Minutes; i++)
                {
                    run.Morning.Step();
                    Gather();
                }
            }
            return meals;
        }

        static Motive FoodWant(DecisionMoment m) => m?.Motives.FirstOrDefault(x => x.Name == "get_food");

        // ---- A: eating that works ----

        [Test]
        public void A1_EatingLowersTheWantByWhatTheBodyGotAndTheWantCanBeWalkedBackToTheEating()
        {
            var meals = Meals(_plenty, _content.Morning.Variants.Select(v => v.Id), 10).Where(m => m.Event.Action == "eat_portion").ToList();
            Assert.IsNotEmpty(meals, "nobody ate even with plenty of food");

            var problems = new List<string>();
            var checkedNext = 0;
            Meal shown = null;

            foreach (var meal in meals)
            {
                var o = meal.Outcome;
                if (o == null) { problems.Add(meal.Who + " ate at minute " + meal.Event.Minute + " and has no outcome for it"); continue; }
                if (o.MotiveName != "get_food") problems.Add("the outcome was judged against " + o.MotiveName);
                if (o.Kind != OutcomeKind.PartlySatisfied && o.Kind != OutcomeKind.Satisfied) problems.Add(meal.Who + ": eating judged " + o.Kind);
                if (Math.Abs(o.Before - o.After - Math.Min(o.Before, _content.Rules.Deciding.PortionRelief)) > 1e-9)
                    problems.Add(meal.Who + ": the outcome says " + F(o.Before) + " -> " + F(o.After) + ", which is not what one portion does");

                if (meal.Next == null) continue;
                var want = FoodWant(meal.Next);
                var hunger = meal.Next.Percept.Hunger;
                if (want == null) { if (hunger > 0) problems.Add(meal.Who + ": hungry and wanting nothing"); continue; }

                checkedNext++;
                if (Math.Abs(want.Urgency - Accumulate.Knee(hunger, _content.Rules.Deciding.UrgencyKnee)) > 1e-9)
                    problems.Add(meal.Who + ": the want is not what the body says");
                var term = want.Terms.First(t => t.Description.StartsWith("hunger", StringComparison.Ordinal));
                if (!term.Drew.Contains(o.TraceId)) problems.Add(meal.Who + ": the want afterwards does not rest on the eating");
                if (!Counterfactual.ReachesCause(meal.Run.Trace, want, new[] { meal.Event.Id }))
                    problems.Add(meal.Who + ": the want afterwards cannot be walked back to the eating");
                var chose = FoodWant(meal.Chose);
                if (chose != null && want.Urgency >= chose.Urgency) problems.Add(meal.Who + ": wanted food as much after eating as when choosing to");

                if (shown == null && meal.Chose != null) shown = meal;
            }

            var sb = new StringBuilder();
            sb.AppendLine("Plenty, five conditions, seeds 1 to 10. " + meals.Count + " meals; next decision checked on " + checkedNext + ".");
            sb.AppendLine();
            sb.AppendLine("| Who | Minute | Hunger before -> after | Outcome | `get_food` when choosing | `get_food` at the next decision |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var m in meals.Take(12))
                sb.AppendLine("| " + m.Who + " | " + m.Event.Minute + " | " + F(m.Outcome.Before) + " -> " + F(m.Outcome.After) + " | " + PursuitOutcome.Words(m.Outcome.Kind) +
                              " | " + (FoodWant(m.Chose) == null ? "n/a" : F(FoodWant(m.Chose).Urgency)) + " | " + (FoodWant(m.Next) == null ? "not raised" : F(FoodWant(m.Next).Urgency) + " (minute " + m.Next.Minute + ")") + " |");
            if (shown != null)
            {
                sb.AppendLine();
                sb.AppendLine("### The whole loop, " + shown.Variant + " seed " + shown.Seed + ", " + shown.Who);
                sb.AppendLine();
                sb.AppendLine("The decision to eat:");
                sb.AppendLine();
                sb.AppendLine("```");
                sb.AppendLine(DecisionTrace.Explain(shown.Chose.Decision, 3));
                sb.AppendLine("```");
                sb.AppendLine();
                sb.AppendLine("The want for food at the next decision, and everything it rests on:");
                sb.AppendLine();
                sb.AppendLine("```");
                sb.AppendLine(Shorten(shown.Run.Trace.Why(FoodWant(shown.Next).TraceId)));
                sb.AppendLine("```");
            }
            Record("A1. Eating that works", sb.ToString());
            Assert.IsEmpty(problems, string.Join("\n", problems));
            Assert.Greater(checkedNext, 0);
        }

        [Test]
        public void A2_EatingWhenLittleHungerIsLeftSatisfiesItAndTheWantIsGone()
        {
            // The body is made less hungry part way through eating, as an
            // intervention: nobody here chooses to eat when so little is left. One
            // portion then covers all of it.
            string found = null;
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 10 && found == null; seed++)
            {
                var run = Scenario001.Prepare(_plenty, v.Id, seed);
                for (var i = 0; i < 90 && found == null; i++)
                {
                    run.Morning.Step();
                    var who = People.FirstOrDefault(p => run.Morning.Doing(p)?.Action.Kind == ActionKind.Eat && run.Morning.Doing(p)?.MinutesLeft == 1);
                    if (who == null) continue;

                    run.World.SetHunger(who, 0.30);
                    DecisionMoment next = null;
                    run.Morning.Decided = m => { if (m.CharacterId == who && next == null) next = m; };
                    var outcomes = run.Minds[who].Outcomes.Count;
                    run.Morning.Step();
                    if (run.Minds[who].Outcomes.Count == outcomes) { run.Morning.Decided = null; continue; }

                    var o = run.Minds[who].Outcomes.Last();
                    for (var j = 0; j < 10 && next == null; j++) run.Morning.Step();

                    Assert.AreEqual(OutcomeKind.Satisfied, o.Kind);
                    Assert.AreEqual(0.0, o.After, 0.0);
                    Assert.IsNotNull(next);
                    var hungerNow = next.Percept.Hunger;
                    var want = FoodWant(next);
                    found = who + " at minute " + o.Minute + ": " + o + ". At the next decision, minute " + next.Minute + ", hunger " + F(hungerNow) +
                            " (the body since), and `get_food` " + (want == null ? "not raised" : F(want.Urgency) + " resting on: " + want.Terms.First().Description) + ".";
                    Assert.AreEqual(Accumulate.Knee(hungerNow, _content.Rules.Deciding.UrgencyKnee), want?.Urgency ?? 0.0, 1e-9);
                    Assert.IsTrue(want == null || want.Terms.First().Drew.Contains(o.TraceId));
                }
            }

            Record("A2. Eating that covers all of it", found ?? "No case found.");
            Assert.IsNotNull(found, "nobody reached the last minute of eating");
        }

        [Test]
        public void A4_TheWholeLoopIsInTheTraceLinkByLink()
        {
            // need -> want -> decision -> eating -> consequence -> experience ->
            // outcome -> the want at the next decision. Every arrow is checked as a
            // parent link between real records, for every meal, and the first loop
            // is written out record by record.
            var meals = Meals(_plenty, _content.Morning.Variants.Select(v => v.Id), 10)
                .Where(m => m.Event.Action == "eat_portion" && m.Chose != null && FoodWant(m.Next) != null).ToList();
            Assert.IsNotEmpty(meals);

            string shown = null;
            var heldIntention = 0;
            foreach (var m in meals)
            {
                var t = m.Run.Trace;
                var wantBefore = t.Get(FoodWant(m.Chose).TraceId);
                var decision = t.Get(m.Chose.Decision.TraceId);
                var eating = t.ForEvent(m.Event.Id).First(r => r.Kind == TraceKind.Event);
                var consequence = t.ForEvent(m.Event.Id).First(r => r.Kind == TraceKind.Consequence && r.CharacterId == m.Who);
                var experience = t.Get(m.Run.Minds[m.Who].Experiences.First(x => x.EventId == m.Event.Id).TraceId);
                var outcome = t.Get(m.Outcome.TraceId);
                var wantAfter = t.Get(FoodWant(m.Next).TraceId);

                void Link(TraceRecord child, TraceRecord parent, string what)
                    => Assert.IsTrue(child.ParentIds.Contains(parent.Id), m.Variant + "/" + m.Seed + " " + m.Who + ": " + what + " is not linked");

                StringAssert.StartsWith("hunger", FoodWant(m.Chose).Terms.First().Description, "the want at the decision is not raised by hunger");
                Link(decision, wantBefore, "the decision to the want");
                Link(consequence, decision, "the consequence to the decision");
                Assert.AreEqual(m.Event.Id, consequence.EventId, "the consequence is not the eating");
                Assert.IsTrue(t.Chain(experience.Id).Contains(eating), "the experience does not rest on the eating");
                Link(outcome, consequence, "the outcome to the consequence");
                Link(outcome, experience, "the outcome to the experience");
                Link(outcome, wantBefore, "the outcome to the want it was for");
                Link(wantAfter, outcome, "the next want to the outcome");

                if (m.Chose.Decision.Commitment == Commitment.Held) heldIntention++;

                if (shown == null)
                {
                    string Line(string stage, TraceRecord r) => "| " + stage + " | #" + r.Id + " " + r.Kind + " | " + r.Summary.Replace("|", "/") + " |";
                    shown = "### " + m.Variant + ", seed " + m.Seed + ", " + m.Who + Environment.NewLine + Environment.NewLine +
                            "| Stage | Record | What it says |" + Environment.NewLine + "|---|---|---|" + Environment.NewLine +
                            "| need | the body | hunger " + F(m.Chose.Percept.Hunger) + " at minute " + m.Chose.Minute + " |" + Environment.NewLine +
                            Line("want", wantBefore) + Environment.NewLine +
                            Line("decision", decision) + Environment.NewLine +
                            Line("eating", eating) + Environment.NewLine +
                            Line("consequence", consequence) + Environment.NewLine +
                            Line("experience", experience) + Environment.NewLine +
                            Line("outcome", outcome) + Environment.NewLine +
                            Line("want again", wantAfter) + Environment.NewLine + Environment.NewLine +
                            "Each record in the table is a parent of the one below it, checked. The want at the next decision, printed by the trace tool with the decision's own reasons cut:" +
                            Environment.NewLine + Environment.NewLine + "```" + Environment.NewLine +
                            string.Join(Environment.NewLine, Shorten(t.Why(wantAfter.Id)).Split('\n').Select(l => l.TrimEnd('\r')).TakeWhile(l => !l.Contains("Deliberation"))) +
                            Environment.NewLine + "```" + Environment.NewLine;
                }
            }

            Record("A4. The loop, link by link", meals.Count + " meals checked, every link present. " + heldIntention + " of them were chosen on arrival under an intention to get food carried from a walk (S1.2)." +
                   Environment.NewLine + Environment.NewLine + shown);
        }

        [Test]
        public void A3_HavingEatenMakesEatingAgainLessWanted()
        {
            var meals = Meals(_plenty, _content.Morning.Variants.Select(v => v.Id), 10)
                .Where(m => m.Event.Action == "eat_portion" && m.Chose != null).ToList();

            var pairs = meals.Where(m => m.NextWithFoodInReach != null).ToList();
            var drops = new List<double>();
            foreach (var m in pairs)
            {
                var before = m.Chose.Decision.Ranked.First(r => r.Option.Kind == ActionKind.Eat).Appeal;
                var after = m.NextWithFoodInReach.Decision.Ranked.First(r => r.Option.Kind == ActionKind.Eat).Appeal;
                drops.Add(before - after);
                Assert.Less(after, before, m.Who + " wanted to eat again as much as before eating");
            }

            var byPerson = meals.GroupBy(m => m.Variant + "/" + m.Seed + "/" + m.Who).ToList();
            var again = byPerson.Where(g => g.Count() > 1).ToList();
            var gaps = again.SelectMany(g => g.OrderBy(x => x.Event.Minute).Zip(g.OrderBy(x => x.Event.Minute).Skip(1), (a, b) => b.Event.Minute - a.Event.Minute)).ToList();

            Record("A3. Eating again", meals.Count + " meals in " + byPerson.Count + " person-mornings. " +
                   pairs.Count + " eaters had food in reach again later; eating was worth less to every one of them than when they chose to eat, by a mean of " +
                   (drops.Count == 0 ? "n/a" : F(drops.Average())) + " (one portion is " + _content.Rules.Deciding.PortionRelief + "). " +
                   again.Count + " person-mornings had a second meal, " +
                   (gaps.Count == 0 ? "" : "the soonest " + gaps.Min() + " and on average " + gaps.Average().ToString("0") + " minutes after the first") + ".");
            Assert.IsNotEmpty(pairs, "nobody was ever near food again after eating, so this measured nothing");
        }

        // ---- B: not enough ----

        [Test]
        public void B1_NotEnoughFoodLeavesAWantThatSaysHowMuchIsLeftAndWhy()
        {
            // One portion is not enough for anybody hungry enough to take it: every
            // meal in the house is partial. What remains has to be exactly what the
            // meal left plus what the body has added since, and has to say so.
            var meals = Meals(_plenty, _content.Morning.Variants.Select(v => v.Id), 10).Where(m => m.Event.Action == "eat_portion").ToList();
            Assert.IsNotEmpty(meals);

            var sb = new StringBuilder();
            var checkedLater = 0;
            foreach (var m in meals)
            {
                Assert.AreEqual(OutcomeKind.PartlySatisfied, m.Outcome.Kind);
                Assert.Greater(m.Outcome.After, 0.0);

                // The eater's want at a later decision, well after the meal.
                var later = LaterDecision(m, 10);
                if (later == null) continue;
                var want = FoodWant(later);
                Assert.IsNotNull(want, m.Who + " is still hungry and wants nothing");
                var elapsed = later.Minute - m.Outcome.Minute;
                var expected = Math.Min(1.0, m.Outcome.After + elapsed * _content.Rules.Deciding.HungerPerMinute * m.Run.Minds[m.Who].Profile.HungerRate);
                Assert.AreEqual(expected, later.Percept.Hunger, 1e-9, "what remains is not what the meal left plus the body since");
                Assert.AreEqual(Accumulate.Knee(expected, _content.Rules.Deciding.UrgencyKnee), want.Urgency, 1e-9);
                var term = want.Terms.First(t => t.Description.StartsWith("hunger", StringComparison.Ordinal));
                Assert.IsTrue(term.Drew.Contains(m.Outcome.TraceId), "what remains does not rest on the meal");
                checkedLater++;
                if (checkedLater <= 3)
                    sb.AppendLine("- " + m.Who + ", " + m.Variant + " seed " + m.Seed + ": ate at minute " + m.Outcome.Minute + " (" + F(m.Outcome.Before) + " -> " + F(m.Outcome.After) +
                                  "); at minute " + later.Minute + ", " + elapsed + " minutes on, `get_food` " + F(want.Urgency) + ", resting on: " + term);
            }

            sb.AppendLine();
            sb.AppendLine(meals.Count + " meals, all partly satisfied. On " + checkedLater + " of them the eater decided again at least ten minutes later; each time the want was exactly what the meal left plus the body since, and named the meal.");
            Record("B1. Not enough", sb.ToString());
            Assert.Greater(checkedLater, 0);
        }

        /// <summary>The eater's first decision at least this many minutes after the meal, read from the run's recorded decisions.</summary>
        static DecisionMoment LaterDecision(Meal m, int minutes)
        {
            var later = m.After.FirstOrDefault(x => x.Minute - m.Outcome.Minute >= minutes);
            if (later == null) return null;
            // Only if nothing else was done about the need in between.
            var between = m.Run.Minds[m.Who].Outcomes.Any(o => o.Need == m.Outcome.Need && o.Minute > m.Outcome.Minute && o.Minute <= later.Minute && o != m.Outcome);
            return between ? null : later;
        }

        [Test]
        public void B2_WhenThereIsOnlyOnePortionNobodyTakesIt()
        {
            // Recorded, not asserted as a success. With a single portion, the first
            // person to open the pantry counts one, which is a short count, and
            // everybody who sees it learns the shelf is short. That prices eating
            // out for everybody, so the one portion is never eaten and there is no
            // partial meal to observe. It is the price, not the lifecycle.
            var one = S13DiagnosisTests.Plenty(_content, 1, false);
            var meals = Meals(one, _content.Morning.Variants.Select(v => v.Id), 10).Where(m => m.Event.Action == "eat_portion").ToList();
            var counts = 0;
            var shortAfter = 0.0;
            foreach (var v in _content.Morning.Variants)
            {
                var run = Scenario001.Run(one, v.Id, 1);
                counts += run.Result.Events.Count(e => e.Action == "count_supplies" && e.Valence == "bad");
                shortAfter += People.Average(p => run.Minds[p].Beliefs.Confidence("supplies_short"));
            }
            Record("B2. One portion", "One portion, count not short at the opening, five conditions, seeds 1 to 10: " + meals.Count + " meals. On seed 1 the pantry was opened and found short " +
                   counts + " times across the five conditions, and by the end of the morning the four of them believed supplies were short at a mean of " + F(shortAfter / 5) + ".");
        }

        // ---- C: wanting food and not getting it ----

        [Test]
        public void C1_ReachingForFoodThatIsGoneIsBlockedFeltAndLeavesTheWantWhereItWas()
        {
            // An intervention: in the last minute of somebody eating, the pantry is
            // emptied, as if somebody else had got there first. The same moment
            // without the intervention is the control.
            string found = null;
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 10 && found == null; seed++)
            {
                var probe = Scenario001.Prepare(_plenty, v.Id, seed);
                var steps = 0;
                string who = null;
                for (; steps < 90 && who == null; steps++)
                {
                    probe.Morning.Step();
                    who = People.FirstOrDefault(p => probe.Morning.Doing(p)?.Action.Kind == ActionKind.Eat && probe.Morning.Doing(p)?.MinutesLeft == 1);
                }
                if (who == null) continue;

                (Scenario001Run run, PursuitOutcome outcome, WorldEvent e, DecisionMoment next) Finish(bool drain)
                {
                    var run = Scenario001.Prepare(_plenty, v.Id, seed);
                    for (var i = 0; i < steps; i++) run.Morning.Step();
                    if (drain) while (run.World.TakePortion()) { }
                    DecisionMoment next = null;
                    run.Morning.Decided = m => { if (m.CharacterId == who && next == null) next = m; };
                    var seen = run.Result.Events.Count;
                    run.Morning.Step();
                    var e = run.Result.Events.Skip(seen).FirstOrDefault(x => x.ActorId == who && (x.Action == "eat_portion" || x.Action == "find_nothing_left"));
                    for (var j = 0; j < 10 && next == null; j++) run.Morning.Step();
                    return (run, e == null ? null : run.Minds[who].Outcomes.LastOrDefault(o => o.EventId == e.Id), e, next);
                }

                var blocked = Finish(true);
                if (blocked.e == null) continue;
                var control = Finish(false);

                Assert.AreEqual("find_nothing_left", blocked.e.Action);
                Assert.AreEqual(OutcomeKind.Blocked, blocked.outcome.Kind);
                Assert.AreEqual(blocked.outcome.Before, blocked.outcome.After, 0.0, "nothing was eaten and the need moved");
                var felt = blocked.run.Minds[who].Experiences.FirstOrDefault(x => x.EventId == blocked.e.Id);
                Assert.IsNotNull(felt, "reaching for nothing was not perceived by the person who reached");

                Assert.IsNotNull(blocked.next);
                var want = FoodWant(blocked.next);
                Assert.IsNotNull(want, "the want disappeared when the food did");
                Assert.IsTrue(Counterfactual.ReachesCause(blocked.run.Trace, want, new[] { blocked.e.Id }), "the want cannot be walked back to finding nothing");

                var controlWant = FoodWant(control.next);
                Assert.AreEqual(OutcomeKind.PartlySatisfied, control.outcome.Kind);
                Assert.Greater(want.Urgency, controlWant?.Urgency ?? 0.0, "finding nothing left the want as low as eating did");

                var witnesses = blocked.e.Witnesses.Where(w => blocked.run.Minds[w].Experiences.Any(x => x.EventId == blocked.e.Id)).ToList();
                found = "### " + v.Id + ", seed " + seed + ", " + who + ", minute " + blocked.e.Minute + Environment.NewLine + Environment.NewLine +
                        "| | Pantry emptied first | Control |" + Environment.NewLine + "|---|---|---|" + Environment.NewLine +
                        "| What happened | " + blocked.e.Summary + " | " + control.e.Summary + " |" + Environment.NewLine +
                        "| Outcome | " + blocked.outcome + " | " + control.outcome + " |" + Environment.NewLine +
                        "| What " + who + " made of it | " + felt.Meaning + (felt.DominantEmotion == null ? "" : ", felt as " + felt.DominantEmotion) + " | " +
                        control.run.Minds[who].Experiences.First(x => x.EventId == control.e.Id).Meaning + " |" + Environment.NewLine +
                        "| Others who perceived it | " + (witnesses.Count == 0 ? "nobody" : string.Join(", ", witnesses)) + " | |" + Environment.NewLine +
                        "| `get_food` at the next decision | " + F(want.Urgency) + " (minute " + blocked.next.Minute + ") | " + (controlWant == null ? "not raised" : F(controlWant.Urgency)) + " (minute " + control.next.Minute + ") |" +
                        Environment.NewLine + Environment.NewLine + "The want after finding nothing, and what it rests on:" + Environment.NewLine + Environment.NewLine +
                        "```" + Environment.NewLine + Shorten(blocked.run.Trace.Why(want.TraceId)) + Environment.NewLine + "```" + Environment.NewLine;
            }

            Record("C1. Reaching for food that is gone", found ?? "No case found.");
            Assert.IsNotNull(found, "never managed to empty the pantry in somebody's last minute of eating");
        }

        [Test]
        public void C2_GoingForFoodAndNotEatingIsUnresolvedAndMovesNothing()
        {
            // The scenario as written. Every walk to the food ends in not eating.
            var lapses = 0;
            var outcomes = 0;
            var wrong = new List<string>();
            PursuitOutcome example = null;

            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 10; seed++)
            {
                var run = Scenario001.Prepare(_content, v.Id, seed);
                run.Morning.Decided = m =>
                {
                    if (m.Decision.Holding?.MotiveName != "get_food" || m.Decision.Commitment == Commitment.Held) return;
                    lapses++;
                    var o = m.Mind.Outcomes.LastOrDefault();
                    if (o == null || o.Minute != m.Minute || o.MotiveName != "get_food") { wrong.Add(m.CharacterId + " gave up at minute " + m.Minute + " with no outcome"); return; }
                    outcomes++;
                    if (o.Kind != Outcomes.OfLapse(m.Decision.Commitment)) wrong.Add("judged " + o.Kind + " for " + m.Decision.Commitment);
                    var want = FoodWant(m);
                    if (want != null && Math.Abs(want.Urgency - Accumulate.Knee(m.Percept.Hunger, _content.Rules.Deciding.UrgencyKnee)) > 1e-9) wrong.Add("the want moved");
                    example = example ?? o;
                };
                run.Morning.Run(_content.Morning.Minutes);
            }

            Record("C2. Going for food and not eating", "The scenario as written, five conditions, seeds 1 to 10: " + lapses + " walks to the food given up on arrival, " +
                   outcomes + " outcomes recorded. Example: `" + example + "`. The want is unchanged by it: still exactly what the body says, and it now says why.");
            Assert.IsEmpty(wrong, string.Join("\n", wrong));
            Assert.Greater(lapses, 0);
        }

        [Test]
        public void C3_WhenTheWantHasGoneByTheTimeYouArriveItIsNoLongerRelevant()
        {
            // An intervention: somebody walking to the food for hunger stops being
            // hungry on the way (the body is set to nothing). On arrival there is
            // nothing to serve. Metabolism would add a little back every minute
            // before they arrive, so for this test nobody's body burns anything;
            // that is a change to the circumstance, and the only one.
            var cast = _content.Cast.ToDictionary(k => k.Key, k =>
            {
                var p = k.Value;
                return new Profile(p.Id, p.DisplayName, p.Age, p.FamilyRole, p.Traits, p.Values, p.Perceptiveness, p.AttentionWeights,
                    p.InitialBeliefs, p.Expressiveness, 0.0);
            }, StringComparer.Ordinal);
            var still = new Scenario001Content(_content.Vocabulary, cast, _content.Backstory, _content.Morning, _content.Rules);

            string found = null;
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= 10 && found == null; seed++)
            {
                var run = Scenario001.Prepare(still, v.Id, seed);
                for (var i = 0; i < 90 && found == null; i++)
                {
                    run.Morning.Step();
                    var who = People.FirstOrDefault(p => run.Morning.Intends(p)?.MotiveName == "get_food" && run.Morning.Doing(p)?.Action.Kind == ActionKind.GoTo);
                    if (who == null) continue;

                    run.World.SetHunger(who, 0.0);
                    DecisionMoment arrival = null;
                    run.Morning.Decided = m => { if (m.CharacterId == who && arrival == null) arrival = m; };
                    for (var j = 0; j < 10 && arrival == null; j++) run.Morning.Step();
                    Assert.IsNotNull(arrival);
                    if (arrival.Decision.Holding == null) { run.Morning.Decided = null; continue; }

                    Assert.AreEqual(Commitment.NoLongerWanted, arrival.Decision.Commitment);
                    var o = run.Minds[who].Outcomes.Last();
                    Assert.AreEqual(OutcomeKind.NoLongerRelevant, o.Kind);
                    found = who + ", " + v.Id + " seed " + seed + ": `" + o + "`.";
                }
            }

            Record("C3. No longer relevant", found ?? "No case found.");
            Assert.IsNotNull(found, "nobody walked to the food for hunger and arrived");
        }

        // ---- D: causality ----

        static Scenario001Content WithoutRelief(Scenario001Content c)
        {
            var d = c.Rules.Deciding;
            var deciding = new DecisionDynamics
            {
                AmbiguityBand = d.AmbiguityBand, InterruptIntensity = d.InterruptIntensity, VisibleDistress = d.VisibleDistress,
                HungerPerMinute = d.HungerPerMinute, PortionRelief = 0.0, LowPortions = d.LowPortions, DistressShows = d.DistressShows,
                ComfortSettles = d.ComfortSettles, ComfortSettling = d.ComfortSettling, UrgencyKnee = d.UrgencyKnee,
                RecallHalfLife = d.RecallHalfLife, WatchingGoesStaleAfter = d.WatchingGoesStaleAfter, ActionMinutes = d.ActionMinutes
            };
            var r = c.Rules;
            var rules = new RuleSet
            {
                Interpretation = r.Interpretation, BeliefNudges = r.BeliefNudges, Appraisal = r.Appraisal, Dynamics = r.Dynamics,
                Motivation = r.Motivation, Proposals = r.Proposals, Costs = r.Costs, Deciding = deciding
            };
            return new Scenario001Content(c.Vocabulary, c.Cast, c.Backstory, c.Morning, rules);
        }

        [Test]
        public void D_WithoutWhatEatingDoesToTheBodyTheUpdateIsGoneAndNothingDiffersBeforeIt()
        {
            // Same seed, same house, same people. In one morning a portion relieves
            // hunger; in the other it relieves nothing. Everything else is the same,
            // including taking the portion and being seen to.
            var without = WithoutRelief(_plenty);
            var sb = new StringBuilder();
            sb.AppendLine("| Condition, seed | First meal | Outcome with relief / without | First difference of any kind | ... in whom, and what | First difference in anybody else |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var problems = new List<string>();
            var pairs = 0;

            foreach (var v in new[] { "mara_ate_it", "daniel_ate_it", "elena_fed_mara" })
            for (ulong seed = 1; seed <= 5; seed++)
            {
                var a = Scenario001.Prepare(_plenty, v, seed);
                var b = Scenario001.Prepare(without, v, seed);
                int? firstMeal = null;
                string eater = null;
                int? firstDiff = null;
                string diffWhat = null;
                int? othersDiff = null;
                PursuitOutcome oa = null, ob = null;

                for (var i = 0; i < 90; i++)
                {
                    var seen = a.Result.Events.Count;
                    a.Morning.Step();
                    b.Morning.Step();

                    var meal = a.Result.Events.Skip(seen).FirstOrDefault(e => e.Action == "eat_portion");
                    if (meal != null && firstMeal == null)
                    {
                        firstMeal = a.World.Minute;
                        eater = meal.ActorId;
                        oa = a.Minds[eater].Outcomes.Last();
                        ob = b.Minds[eater].Outcomes.LastOrDefault();
                    }

                    foreach (var p in People)
                    {
                        var hungerDiffers = Math.Abs(a.World.HungerOf(p) - b.World.HungerOf(p)) > 1e-12;
                        var wa = new Motivator(_plenty.Rules).Raise(a.Minds[p], a.Morning.See(p), _content.Morning.Day, new TraceLog(), 0);
                        var wb = new Motivator(without.Rules).Raise(b.Minds[p], b.Morning.See(p), _content.Morning.Day, new TraceLog(), 0);
                        var wantsDiffer = wa.Count != wb.Count || wa.Zip(wb, (x, y) => x.Key != y.Key || Math.Abs(x.Urgency - y.Urgency) > 1e-12).Any(d => d);
                        var actsDiffer = !a.Result.By(p).Select(x => x.Minute + x.Action.Key).SequenceEqual(b.Result.By(p).Select(x => x.Minute + x.Action.Key));
                        if (!hungerDiffers && !wantsDiffer && !actsDiffer) continue;

                        if (firstDiff == null)
                        {
                            firstDiff = a.World.Minute;
                            diffWhat = p + ": " + string.Join(", ", new[] { hungerDiffers ? "hunger" : null, wantsDiffer ? "wants" : null, actsDiffer ? "acts" : null }.Where(x => x != null));
                            if (firstMeal == null || firstDiff < firstMeal) problems.Add(v + "/" + seed + ": something differed at minute " + firstDiff + ", before anybody ate");
                            else if (p != eater) problems.Add(v + "/" + seed + ": the first difference was in " + p + ", not the eater " + eater);
                        }
                        if (p != eater && othersDiff == null) othersDiff = a.World.Minute;
                    }
                }

                if (firstMeal == null) continue;
                pairs++;
                if (ob == null || ob.Kind != OutcomeKind.Unresolved) problems.Add(v + "/" + seed + ": without relief the meal was judged " + (ob?.Kind.ToString() ?? "nothing"));
                if (oa.Kind != OutcomeKind.PartlySatisfied && oa.Kind != OutcomeKind.Satisfied) problems.Add(v + "/" + seed + ": with relief the meal was judged " + oa.Kind);

                sb.AppendLine("| " + v + ", " + seed + " | " + eater + " at " + firstMeal + " | " + PursuitOutcome.Words(oa.Kind) + " / " + (ob == null ? "none" : PursuitOutcome.Words(ob.Kind)) + " | minute " +
                              firstDiff + " | " + diffWhat + " | " + (othersDiff == null ? "never" : "minute " + othersDiff) + " |");
            }

            sb.AppendLine();
            sb.AppendLine("Nothing differs before the first meal. The first thing to differ is always the eater, at the minute the meal is resolved. Anybody else differs only later, through what the eater then does.");
            Record("D. With and without what eating does to the body", sb.ToString());
            Assert.IsEmpty(problems, string.Join("\n", problems));
            Assert.Greater(pairs, 0, "nobody ate in any pair");
        }

        // ---- E: who eats ----

        [Test]
        public void E_WhoEatsWhenTheHouseLetsThem()
        {
            var sb = new StringBuilder();
            sb.AppendLine("Shipped rules; only circumstances change. Every eating act and every reach for food that was gone, with how each was judged.");
            sb.AppendLine();
            sb.AppendLine("| Circumstance | Mornings | Mornings each ate: daniel / elena / leo / mara | Meals | ... chosen under an intention held from a walk | Second meals | Outcomes of meals | Reaches that found nothing |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            var problems = new List<string>();

            void Row(string label, Scenario001Content content, int seeds, Action<Scenario001Run> set = null)
            {
                var meals = Meals(content, content.Morning.Variants.Select(v => v.Id), seeds, set);
                var ate = meals.Where(m => m.Event.Action == "eat_portion").ToList();
                foreach (var m in meals.Where(m => m.Outcome == null)) problems.Add(label + ": " + m.Who + " " + m.Event.Action + " with no outcome");
                var mornings = content.Morning.Variants.Count * seeds;
                sb.AppendLine("| " + label + " | " + mornings + " | " +
                              string.Join(" / ", People.Select(p => ate.Where(m => m.Who == p).Select(m => m.Variant + m.Seed).Distinct().Count())) + " | " + ate.Count + " | " +
                              ate.Count(m => m.Chose?.Decision.Commitment == Commitment.Held) + " | " +
                              ate.GroupBy(m => m.Variant + m.Seed + m.Who).Sum(g => g.Count() - 1) + " | " +
                              string.Join(", ", ate.Where(m => m.Outcome != null).GroupBy(m => m.Outcome.Kind).Select(g => PursuitOutcome.Words(g.Key) + " " + g.Count())) + " | " +
                              meals.Count(m => m.Event.Action == "find_nothing_left") + " |");
            }

            Row("the scenario as written", _content, 20);
            Row("plenty of food, count still short", S13DiagnosisTests.Plenty(_content, 10, true), 20);
            Row("plenty of food, count not short", _plenty, 20);
            Row("two portions, count not short", S13DiagnosisTests.Plenty(_content, 2, false), 20);
            foreach (var p in People) Row(p + " starving alone, plenty, not short", _plenty, 4, r => S13DiagnosisTests.StarvingAlone(r, p));
            foreach (var p in People) Row(p + " starving alone, as written", _content, 4, r => S13DiagnosisTests.StarvingAlone(r, p));

            Record("E. Who eats", sb.ToString());
            Assert.IsEmpty(problems, string.Join("\n", problems));
        }

        [Test]
        public void TheSameSeedGivesTheSameMealsAndTheSameOutcomes()
        {
            string Morning()
            {
                var run = Scenario001.Run(_plenty, "daniel_ate_it", 3);
                return string.Join("|", run.Result.Actions.Select(x => x.ToString())) + "#" +
                       string.Join("|", People.SelectMany(p => run.Minds[p].Outcomes.Select(o => p + ":" + o)));
            }
            Assert.AreEqual(Morning(), Morning());
        }
    }
}
