using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// Where the S1.4 change in behaviour comes from. S1.4 changed three things at
    /// once: help that cannot reach its person no longer happens, distress stopping
    /// can be seen, and the want reads that sight. The S1 batch is run twice on the
    /// same seeds, once as shipped and once with nothing reading the sight, so the
    /// first two can be told apart from the third. Written to its own file so that
    /// running it alone does not overwrite the experiment results.
    /// </summary>
    public class S14AttributionTests
    {
        const int Seeds = 40;

        sealed class Measures
        {
            public int Mornings;
            public int Decisions;
            public double SittingShare;
            public int SatWithSomebodyWhoHadGone;
            public double MeanGap;
            public double WorstConditionMean;
            public double ClosestPair;
            public string ClosestWho;
            public int WorstPacing;
            public string WorstPacingWho;
            public double RealTies;
        }

        static Measures Measure(Scenario001Content content, IReadOnlyList<string> variants, IReadOnlyList<string> people)
        {
            var batch = BatchRunner.Run(content, new BatchRunner.Options { Variants = variants, Seeds = Seeds, FirstSeed = 1 });
            var m = new Measures
            {
                Mornings = batch.Summary.Runs,
                Decisions = batch.Rows.Count,
                SittingShare = batch.Rows.Count(r => r.Action == "comfort") / (double)batch.Rows.Count,
                SatWithSomebodyWhoHadGone = batch.Rows.Count(r => r.Action == "comfort" && r.Outcome != null && r.Outcome.Contains("had gone")),
                RealTies = batch.Summary.AmbiguousShare * (1.0 - batch.Summary.InterchangeableShare),
                WorstConditionMean = 1.0,
                ClosestPair = 1.0
            };

            // The S1 measures, exactly as S1ExperimentTests takes them.
            var all = new List<double>();
            foreach (var v in variants)
            {
                var gaps = new List<double>();
                for (var i = 0; i < people.Count; i++)
                for (var j = i + 1; j < people.Count; j++)
                {
                    var gap = BatchRunner.HowDifferent(BatchRunner.ActionProfile(batch.Rows, v, people[i]), BatchRunner.ActionProfile(batch.Rows, v, people[j]));
                    gaps.Add(gap);
                    if (gap < m.ClosestPair) { m.ClosestPair = gap; m.ClosestWho = v + ": " + people[i] + "/" + people[j]; }
                }
                all.AddRange(gaps);
                m.WorstConditionMean = Math.Min(m.WorstConditionMean, gaps.Average());
            }
            m.MeanGap = all.Average();

            foreach (var group in batch.Rows.Where(r => r.Action == "go_to").GroupBy(r => r.Variant + "/" + r.Seed + "/" + r.Character))
            {
                var moves = group.OrderBy(r => r.Minute).Select(r => r.Target).ToList();
                var backAndForth = 0;
                for (var i = 2; i < moves.Count; i++)
                    if (moves[i] == moves[i - 2] && moves[i] != moves[i - 1]) backAndForth++;
                if (backAndForth > m.WorstPacing) { m.WorstPacing = backAndForth; m.WorstPacingWho = group.Key; }
            }

            return m;
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string P(double v) => (v * 100).ToString("0.0", CultureInfo.InvariantCulture) + " %";

        [Test, Timeout(1800000)]
        public void WhereTheChangeInBehaviourComesFrom()
        {
            var content = Scenario001Content.Load(TestPaths.DataRoot);
            var variants = content.Morning.Variants.Select(v => v.Id).ToList();
            var people = content.Cast.Keys.OrderBy(k => k, StringComparer.Ordinal).ToList();

            var shipped = Measure(content, variants, people);
            var unread = Measure(new Scenario001Content(content.Vocabulary, content.Cast, content.Backstory, content.Morning,
                S14ExperimentTests.NothingIsAnswered(content.Rules)), variants, people);

            var sb = new StringBuilder();
            sb.AppendLine("# S1.4 attribution: where the change in behaviour comes from");
            sb.AppendLine();
            sb.AppendLine("Generated by `S14AttributionTests`. The S1 batch: five design conditions, seeds 1 to " + Seeds + ", " + shipped.Mornings + " mornings, measured the way `S1ExperimentTests` measures it.");
            sb.AppendLine();
            sb.AppendLine("- **As shipped:** help that cannot reach its person does not happen; distress stopping can be seen; the want reads that sight (`until reassurance`).");
            sb.AppendLine("- **Nothing reads the sight:** the same code and rules with `until` removed from both memory terms. Help still cannot reach somebody who has gone, and distress stopping is still seen and remembered; no want reads it.");
            sb.AppendLine();
            sb.AppendLine("| | As shipped | Nothing reads the sight |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Decisions | " + shipped.Decisions + " | " + unread.Decisions + " |");
            sb.AppendLine("| Share of choices that are sitting with somebody | " + P(shipped.SittingShare) + " | " + P(unread.SittingShare) + " |");
            sb.AppendLine("| Sittings that found the person gone | " + shipped.SatWithSomebodyWhoHadGone + " | " + unread.SatWithSomebodyWhoHadGone + " |");
            sb.AppendLine("| Different people, mean gap | " + F(shipped.MeanGap) + " | " + F(unread.MeanGap) + " |");
            sb.AppendLine("| Weakest condition, mean gap | " + F(shipped.WorstConditionMean) + " | " + F(unread.WorstConditionMean) + " |");
            sb.AppendLine("| Closest pair | " + F(shipped.ClosestPair) + " (" + shipped.ClosestWho + ") | " + F(unread.ClosestPair) + " (" + unread.ClosestWho + ") |");
            sb.AppendLine("| Worst back-and-forth pacing | " + shipped.WorstPacing + " (" + shipped.WorstPacingWho + ") | " + unread.WorstPacing + " (" + unread.WorstPacingWho + ") |");
            sb.AppendLine("| Ties between genuinely different actions | " + P(shipped.RealTies) + " | " + P(unread.RealTies) + " |");
            sb.AppendLine();
            sb.AppendLine("For comparison, the same batch on the S1.3 code is committed at `56c6c7e` as `Docs/slices/S1/batch/decisions.csv`; `Docs/slices/S1.4/report.md` gives its figures.");

            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.4");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "attribution.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());

            // As first measured: without the reading, the S1.2 pacing gate holds and
            // people are further apart than with it. If either turns round, the
            // attribution in the S1.4 report no longer stands.
            Assert.Less(unread.WorstPacing, 4, "pacing without anything reading the sight");
            Assert.Greater(unread.MeanGap, shipped.MeanGap, "reading the sight is what brings people closer together");
        }
    }
}
