using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.4, before anything changes: wanting to look after somebody. How the
    /// want is raised, what it reads, what serves it, what sitting with somebody
    /// actually does, and whether anything that happens because of it can reach
    /// the want. Records, asserts nothing.
    /// </summary>
    public class S14DiagnosisTests
    {
        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _sections = new SortedDictionary<string, string>(StringComparer.Ordinal);
        static readonly string[] People = { "daniel", "elena", "leo", "mara" };
        const int Seeds = 10;

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.4 diagnosis: looking after somebody");
            sb.AppendLine();
            sb.AppendLine("Generated by `S14DiagnosisTests`. Shipped rules, the scenario as written, five design conditions, seeds 1 to " + Seeds + ", unless a section says otherwise. Records, asserts nothing.");
            sb.AppendLine();
            foreach (var s in _sections.Values) sb.AppendLine(s);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.4");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "diagnosis-current.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _sections[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string P(double part, double whole) => whole == 0 ? "n/a" : (part / whole).ToString("P0", CultureInfo.InvariantCulture);

        /// <summary>Whether a person's distress is showing, by the same test the morning uses to announce it.</summary>
        internal static bool Showing(Mind mind, Scenario001Content content)
        {
            var d = mind.Emotions.Dominant;
            return d != null && content.Rules.Deciding.DistressShows.Contains(d.Type) &&
                   d.Intensity * mind.Profile.Expressiveness >= content.Rules.Deciding.VisibleDistress;
        }

        static string Kind(string description)
        {
            if (description.StartsWith("memory", StringComparison.Ordinal)) return "memory";
            if (description.StartsWith("remembers", StringComparison.Ordinal)) return "ledger";
            return "trait or value";
        }

        /// <summary>One completed act of sitting with somebody, and what was around it.</summary>
        sealed class Sitting
        {
            public string Variant;
            public ulong Seed;
            public int Minute;
            public string Who;
            public string Whom;
            public WorldEvent Event;
            public DecisionMoment Chose;
            public DecisionMoment NextWithThemThere;
            public bool ShowingBefore;
            public bool ShowingAfter;
            public bool TargetWasInTheRoom;
            public int ReshownWithin15;
            public Scenario001Run Run;
        }

        static List<Sitting> Sittings(Scenario001Content content, int seeds)
        {
            var all = new List<Sitting>();
            foreach (var v in content.Morning.Variants)
            for (ulong seed = 1; seed <= (ulong)seeds; seed++)
            {
                var run = Scenario001.Prepare(content, v.Id, seed);
                var chosen = new Dictionary<string, DecisionMoment>(StringComparer.Ordinal);
                var open = new List<Sitting>();
                var seen = run.Result.Events.Count;
                var before = People.ToDictionary(p => p, p => Showing(run.Minds[p], content));

                // A sitting is resolved, and the one who sat may decide again, in
                // the same minute, so sittings are gathered as soon as they exist.
                void Gather()
                {
                    var events = run.Result.Events;
                    for (; seen < events.Count; seen++)
                    {
                        var e = events[seen];
                        if (e.Action == "show_distress")
                            foreach (var s in all.Where(x => x.Run == run && x.Whom == e.TargetId && e.Minute - x.Minute <= 15 && e.Minute > x.Minute)) s.ReshownWithin15++;
                        if (e.Action != "comfort") continue;
                        chosen.TryGetValue(e.ActorId, out var c);
                        var s2 = new Sitting
                        {
                            Variant = v.Id, Seed = seed, Minute = e.Minute, Who = e.ActorId, Whom = e.TargetId, Event = e, Chose = c,
                            ShowingBefore = before[e.TargetId], ShowingAfter = Showing(run.Minds[e.TargetId], content),
                            TargetWasInTheRoom = run.World.RoomOf(e.TargetId) == run.World.RoomOf(e.ActorId), Run = run
                        };
                        all.Add(s2);
                        open.Add(s2);
                    }
                }

                run.Morning.Decided = m =>
                {
                    Gather();
                    foreach (var s in open.Where(x => x.Who == m.CharacterId && x.NextWithThemThere == null))
                        if (m.Motives.Any(x => x.Key == "look_after:" + s.Whom)) s.NextWithThemThere = m;
                    if (m.Decision.Chosen.Kind == ActionKind.Comfort) chosen[m.CharacterId] = m;
                };

                for (var i = 0; i < content.Morning.Minutes; i++)
                {
                    before = People.ToDictionary(p => p, p => Showing(run.Minds[p], content));
                    run.Morning.Step();
                    Gather();
                }
            }
            return all;
        }

        // ---- 1. how the want is raised and what it reads ----

        [Test]
        public void D1_WhatTheWantReads()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 1. How the want is raised, and what it reads");
            sb.AppendLine();
            sb.AppendLine("One rule, `somebody_in_front_of_you_is_not_all_right`, raised once for each person in the room:");
            sb.AppendLine();
            foreach (var r in _content.Rules.Motivation.Where(m => m.Motive == "look_after"))
            foreach (var s in r.ScaledBy) sb.AppendLine("- " + s.Describe() + " x " + s.Factor);
            sb.AppendLine();
            sb.AppendLine("A memory term is the strongest experience today with that reading and that person as its target, its salience times a freshness of 20 / (20 + minutes since). Nothing else changes a memory term.");
            sb.AppendLine();

            var parts = new Dictionary<string, double>(StringComparer.Ordinal);
            var pairs = new Dictionary<string, List<double>>(StringComparer.Ordinal);
            var raised = 0;
            var withoutAnyMemory = 0;
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var run = Scenario001.Prepare(_content, v.Id, seed);
                run.Morning.Decided = m =>
                {
                    foreach (var w in m.Motives.Where(x => x.Name == "look_after"))
                    {
                        raised++;
                        var positive = w.Terms.Where(t => t.Amount > 0).ToList();
                        if (!positive.Any(t => Kind(t.Description) == "memory")) withoutAnyMemory++;
                        var total = positive.Sum(t => t.Amount);
                        foreach (var t in positive)
                        {
                            parts.TryGetValue(Kind(t.Description), out var x);
                            parts[Kind(t.Description)] = x + w.Urgency * t.Amount / total;
                        }
                        var key = m.CharacterId + " -> " + w.TargetId;
                        if (!pairs.TryGetValue(key, out var l)) pairs[key] = l = new List<double>();
                        l.Add(w.Urgency);
                    }
                };
                run.Morning.Run(_content.Morning.Minutes);
            }

            var sum = parts.Values.Sum();
            sb.AppendLine("Across every decision it was raised in (" + raised + " times), where its urgency came from: " +
                          string.Join(", ", parts.OrderByDescending(k => k.Value).Select(k => k.Key + " " + P(k.Value, sum))) + ".");
            sb.AppendLine("Raised with no memory behind it at all, on traits, values and the backstory ledger alone: " + P(withoutAnyMemory, raised) + ".");
            sb.AppendLine();
            sb.AppendLine("| Who, about whom | Mean urgency | Range |");
            sb.AppendLine("|---|---|---|");
            foreach (var k in pairs.OrderByDescending(k => k.Value.Average()))
                sb.AppendLine("| " + k.Key + " | " + F(k.Value.Average()) + " | " + F(k.Value.Min()) + " to " + F(k.Value.Max()) + " |");
            Record("1", sb.ToString());
        }

        // ---- 2 and 3. what serves it, and what sitting with somebody does ----

        [Test]
        public void D2_WhatSittingWithSomebodyDoes()
        {
            var sittings = Sittings(_content, Seeds);
            var sb = new StringBuilder();
            sb.AppendLine("## 2. What serves it, and what sitting with somebody does");
            sb.AppendLine();
            sb.AppendLine("Proposals serving it: " + string.Join(", ", _content.Rules.Proposals.Where(p => p.Motive == "look_after").Select(p => "`" + p.Id + "` " + p.Action + " " + p.Fit)) +
                          ". Also credited to sitting with somebody: `settle_them_down` (keeping the peace) " + _content.Rules.Proposals.First(p => p.Id == "settle_them_down").Fit + ".");
            sb.AppendLine();

            var chosen = sittings.Where(s => s.Chose != null).ToList();
            double fromLook = 0, fromPeace = 0;
            foreach (var s in chosen)
            {
                var opt = s.Chose.Decision.ChosenScored;
                fromLook += opt.Contributions.Where(c => c.MotiveName == "look_after").Sum(c => c.Amount);
                fromPeace += opt.Contributions.Where(c => c.MotiveName == "keep_peace").Sum(c => c.Amount);
            }
            sb.AppendLine("Completed sittings: " + sittings.Count + " in " + (_content.Morning.Variants.Count * Seeds) + " mornings. Their appeal came from looking after " +
                          P(fromLook, fromLook + fromPeace) + " and keeping the peace " + P(fromPeace, fromLook + fromPeace) + ".");
            sb.AppendLine();
            sb.AppendLine("**When it finishes, the world does two things.** It makes a `comfort` event (valence good) that people in the room see and people in audible rooms hear, and it softens the other person's fear and anxiety to " +
                          _content.Rules.Deciding.ComfortSettling + " of what they were, directly, without that person perceiving or appraising anything (`Soothe`, marked as technical debt since S1.1).");
            sb.AppendLine();

            // How it was read.
            var readings = new Dictionary<string, Dictionary<string, int>>(StringComparer.Ordinal)
            {
                { "the person who sat", new Dictionary<string, int>() },
                { "the person sat with", new Dictionary<string, int>() },
                { "others who saw it", new Dictionary<string, int>() },
                { "others who only heard it", new Dictionary<string, int>() }
            };
            var nobodyElse = 0;
            foreach (var s in sittings)
            foreach (var p in People)
            {
                var x = s.Run.Minds[p].Experiences.FirstOrDefault(e => e.EventId == s.Event.Id);
                string role = p == s.Who ? "the person who sat" : p == s.Whom ? "the person sat with" :
                    s.Event.Witnesses.Contains(p) ? "others who saw it" : s.Event.Overhearers.Contains(p) ? "others who only heard it" : null;
                if (role == null) { if (x != null) nobodyElse++; continue; }
                if (x == null) continue;
                readings[role].TryGetValue(x.Meaning, out var n);
                readings[role][x.Meaning] = n + 1;
            }
            sb.AppendLine("| Who | What they made of it |");
            sb.AppendLine("|---|---|");
            foreach (var r in readings) sb.AppendLine("| " + r.Key + " | " + string.Join(", ", r.Value.OrderByDescending(k => k.Value).Select(k => k.Key + " " + k.Value)) + " |");
            sb.AppendLine();
            sb.AppendLine("Memories of it held by anybody neither in the room nor within earshot: " + nobodyElse + ".");
            sb.AppendLine();
            sb.AppendLine("A memory of **concern** about the person sat with feeds everybody's wish to look after them. Overhearing it is read as concern (`what_you_only_hear_worries_you`).");
            Record("2", sb.ToString());
        }

        [Test]
        public void D3_WhetherWhatHappenedReachesTheWant()
        {
            var sittings = Sittings(_content, Seeds);
            var sb = new StringBuilder();
            sb.AppendLine("## 3. Whether what happened reaches the want");
            sb.AppendLine();

            var withNext = sittings.Where(s => s.Chose != null && s.NextWithThemThere != null).ToList();
            var changes = new List<double>();
            var memoryChanges = new List<double>();
            var standingChanges = new List<double>();
            var restsOnIt = 0;
            foreach (var s in withNext)
            {
                var before = s.Chose.Motives.FirstOrDefault(m => m.Key == "look_after:" + s.Whom);
                var after = s.NextWithThemThere.Motives.First(m => m.Key == "look_after:" + s.Whom);
                if (before == null) continue;
                changes.Add(after.Urgency - before.Urgency);
                double Part(Motive m, bool memory) => m.Terms.Where(t => (Kind(t.Description) == "memory") == memory).Sum(t => t.Amount);
                memoryChanges.Add(Part(after, true) - Part(before, true));
                standingChanges.Add(Part(after, false) - Part(before, false));
                if (Counterfactual.ReachesCause(s.Run.Trace, after, new[] { s.Event.Id })) restsOnIt++;
            }

            sb.AppendLine("Sittings where the one who sat decided again with the other still in the room: " + withNext.Count + ".");
            sb.AppendLine();
            sb.AppendLine("| | Mean change from choosing to sit to the next decision |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Wanting to look after them | " + (changes.Count == 0 ? "n/a" : F(changes.Average())) + " |");
            sb.AppendLine("| ... of which memory terms | " + (memoryChanges.Count == 0 ? "n/a" : F(memoryChanges.Average())) + " |");
            sb.AppendLine("| ... of which traits, values and ledger | " + (standingChanges.Count == 0 ? "n/a" : F(standingChanges.Average())) + " |");
            sb.AppendLine();
            sb.AppendLine("The want afterwards could be walked back to the sitting in " + restsOnIt + " of " + changes.Count + " cases.");
            sb.AppendLine();

            var showingBefore = sittings.Count(s => s.ShowingBefore);
            var stopped = sittings.Count(s => s.ShowingBefore && !s.ShowingAfter);
            sb.AppendLine("**What happened to the other person.** Their distress was showing when the sitting finished in " + showingBefore + " of " + sittings.Count +
                          " cases; over that minute it stopped showing in " + stopped + ". The morning announces distress only when it starts to show. When it stops showing, nothing happens that anybody can perceive, so the person who sat cannot see that it worked.");
            sb.AppendLine();
            sb.AppendLine("Distress shown again, as a fresh event, within fifteen minutes of being sat with: " + sittings.Sum(s => s.ReshownWithin15) + " times after " + sittings.Count +
                          " sittings. Each is a new `show_distress` event and so a new memory of concern for everybody who sees it.");
            sb.AppendLine();
            var outcomes = sittings.Select(s => s.Run).Distinct().Sum(r => People.Sum(p => r.Minds[p].Outcomes.Count(o => o.MotiveName == "look_after")));
            sb.AppendLine("**The S1.3 outcome mechanism, as built.** Outcomes recorded for wanting to look after somebody, across these mornings: " + outcomes +
                          ". It judges an act only against wants that read a need the act touched, and this want reads no need.");
            sb.AppendLine();
            var absent = sittings.Count(s => !s.TargetWasInTheRoom);
            sb.AppendLine("**Can help be refused or prevented?** There is no way to refuse being sat with. Sittings that finished with the other person no longer in the room: " + absent +
                          " of " + sittings.Count + "; the world still soothed them wherever they were.");
            Record("3", sb.ToString());
        }

        [Test]
        public void D5_WhatAnybodyCanSeeOfDistressStartingAndStopping()
        {
            var starts = 0;
            var startsSeen = 0;
            var stops = 0;
            var stopsInFrontOfSomebody = 0;
            var stopsJustAfterBeingSatWith = 0;
            var mornings = 0;
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var run = Scenario001.Prepare(_content, v.Id, seed);
                mornings++;
                var was = People.ToDictionary(p => p, p => Showing(run.Minds[p], _content));
                for (var i = 0; i < _content.Morning.Minutes; i++)
                {
                    var seen = run.Result.Events.Count;
                    run.Morning.Step();
                    var now = People.ToDictionary(p => p, p => Showing(run.Minds[p], _content));
                    var fresh = run.Result.Events.Skip(seen).ToList();
                    foreach (var p in People)
                    {
                        if (!was[p] && now[p]) { starts++; if (fresh.Any(e => e.Action == "show_distress" && e.TargetId == p)) startsSeen++; }
                        if (was[p] && !now[p])
                        {
                            stops++;
                            if (run.World.WithMe(p).Count > 0) stopsInFrontOfSomebody++;
                            if (fresh.Any(e => e.Action == "comfort" && e.TargetId == p)) stopsJustAfterBeingSatWith++;
                        }
                    }
                    was = now;
                }
            }

            Record("5", "## 5. What anybody can see of distress starting and stopping" + Environment.NewLine + Environment.NewLine +
                        "Per morning: distress started showing " + (starts / (double)mornings).ToString("0.0") + " times, announced as an event " + (startsSeen / (double)mornings).ToString("0.0") +
                        " times; it stopped showing " + (stops / (double)mornings).ToString("0.0") + " times, " + (stopsInFrontOfSomebody / (double)mornings).ToString("0.0") +
                        " of them with somebody else in the room, " + (stopsJustAfterBeingSatWith / (double)mornings).ToString("0.0") +
                        " of them in the minute somebody finished sitting with that person. Stopping is never announced, so none of it can be perceived." + Environment.NewLine);
        }

        [Test]
        public void D4_TheOneMemoryTheWantRestsOnNeverLearnsHowItEnded()
        {
            // A concrete case: a person sees somebody go to pieces, sits with them,
            // and the want to look after them is measured before and after.
            var sittings = Sittings(_content, Seeds).Where(s => s.Chose != null && s.NextWithThemThere != null && s.ShowingBefore).ToList();
            var sb = new StringBuilder();
            sb.AppendLine("## 4. One case");
            sb.AppendLine();
            if (sittings.Count == 0) { sb.AppendLine("No sitting with somebody whose distress was showing, followed by another decision with them there."); Record("4", sb.ToString()); return; }

            var s = sittings.First();
            var before = s.Chose.Motives.First(m => m.Key == "look_after:" + s.Whom);
            var after = s.NextWithThemThere.Motives.First(m => m.Key == "look_after:" + s.Whom);
            sb.AppendLine(s.Variant + ", seed " + s.Seed + ": " + s.Who + " sits with " + s.Whom + ", finishing at minute " + s.Minute + ". " + s.Whom + "'s distress showing before: " + s.ShowingBefore + ", after: " + s.ShowingAfter + ".");
            sb.AppendLine();
            sb.AppendLine("- When choosing, minute " + s.Chose.Minute + ": `look_after:" + s.Whom + "` " + F(before.Urgency) + " because " + before.Because);
            sb.AppendLine("- Next decision, minute " + s.NextWithThemThere.Minute + ": `look_after:" + s.Whom + "` " + F(after.Urgency) + " because " + after.Because);
            sb.AppendLine();
            sb.AppendLine("The memory term reads the strongest concern about them, fading by the minute. Whether they were helped does not enter it.");
            Record("4", sb.ToString());
        }
    }
}
