using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The S1.4 experiment: does what actually happens when somebody sits with
    /// another person reach the helper's wish to look after them, through what
    /// the helper perceives, and only through that?
    ///
    /// Shipped rules and the five design conditions, seeds 1 to 10, unless a test
    /// says otherwise. The held-out condition is in its own file.
    /// </summary>
    public class S14ExperimentTests
    {
        const int Seeds = 10;
        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _findings = new SortedDictionary<string, string>(StringComparer.Ordinal);
        internal static readonly string[] People = { "daniel", "elena", "leo", "mara" };

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.4 experiment results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S14ExperimentTests`. Shipped rules, five design conditions, seeds 1 to " + Seeds + ", unless a section says otherwise.");
            sb.AppendLine();
            foreach (var f in _findings) sb.AppendLine("## " + f.Key + Environment.NewLine + Environment.NewLine + f.Value);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.4");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "experiment-results.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _findings[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);

        static string Shorten(string why)
            => string.Join(Environment.NewLine, why.Split('\n').Select(l => l.TrimEnd('\r')).Select(l => l.Length > 220 ? l.Substring(0, 217) + "..." : l));

        // ---- what happened at the end of each sitting ----

        internal enum Ending { CameRight, StillNotAllRight, NothingShowing, TheyHadGone }

        internal sealed class Sitting
        {
            public string Variant;
            public ulong Seed;
            public int Minute;
            public string Who;
            public string Whom;
            public Ending Ending;
            public WorldEvent Comfort;
            public WorldEvent Steady;
            public DecisionMoment Chose;
            public DecisionMoment Next;
            public Scenario001Run Run;
            public int SittingsWithThemWithin20;
        }

        internal static List<Sitting> Sittings(Scenario001Content content, IEnumerable<string> variants, int seeds, ulong firstSeed = 1)
        {
            var all = new List<Sitting>();
            foreach (var v in variants)
            for (var seed = firstSeed; seed < firstSeed + (ulong)seeds; seed++)
            {
                var run = Scenario001.Prepare(content, v, seed);
                var chosen = new Dictionary<string, DecisionMoment>(StringComparer.Ordinal);
                var open = new List<Sitting>();
                var finishing = new Dictionary<string, string>(StringComparer.Ordinal);
                var showingBefore = new Dictionary<string, bool>(StringComparer.Ordinal);
                var seenTrace = run.Trace.Count;
                var gathered = false;

                void Gather()
                {
                    if (gathered) return;
                    gathered = true;
                    var fresh = run.Trace.All.Skip(seenTrace).ToList();
                    foreach (var pair in finishing)
                    {
                        var who = pair.Key;
                        var whom = pair.Value;
                        var comfort = run.Result.Events.LastOrDefault(e => e.Action == "comfort" && e.ActorId == who && e.TargetId == whom && e.Minute == run.World.Minute);
                        var gone = fresh.Any(r => r.Kind == TraceKind.Consequence && r.CharacterId == who && r.Summary.StartsWith("could not sit with " + whom, StringComparison.Ordinal));
                        if (comfort == null && !gone) continue;

                        var steady = run.Result.Events.LastOrDefault(e => e.Action == "steady" && e.TargetId == whom && e.Minute == run.World.Minute);
                        var s = new Sitting
                        {
                            Variant = v, Seed = seed, Minute = run.World.Minute, Who = who, Whom = whom, Comfort = comfort, Steady = steady, Run = run,
                            Chose = chosen.TryGetValue(who, out var c) ? c : null,
                            Ending = gone ? Ending.TheyHadGone
                                : !showingBefore[whom] ? Ending.NothingShowing
                                : steady != null && steady.Witnesses.Contains(who) ? Ending.CameRight
                                : Ending.StillNotAllRight
                        };
                        foreach (var earlier in all.Where(x => x.Run == run && x.Who == who && x.Whom == whom && s.Minute - x.Minute <= 20 && s.Minute > x.Minute))
                            earlier.SittingsWithThemWithin20++;
                        all.Add(s);
                        open.Add(s);
                    }
                }

                run.Morning.Decided = m =>
                {
                    Gather();
                    foreach (var s in open.Where(x => x.Who == m.CharacterId && x.Next == null))
                        if (m.Motives.Any(x => x.Key == "look_after:" + s.Whom)) s.Next = m;
                    if (m.Decision.Chosen.Kind == ActionKind.Comfort) chosen[m.CharacterId] = m;
                };

                for (var i = 0; i < content.Morning.Minutes; i++)
                {
                    finishing.Clear();
                    foreach (var p in People)
                    {
                        var d = run.Morning.Doing(p);
                        if (d.HasValue && d.Value.Action.Kind == ActionKind.Comfort && d.Value.MinutesLeft == 1) finishing[p] = d.Value.Action.TargetId;
                        showingBefore[p] = S14DiagnosisTests.Showing(run.Minds[p], content);
                    }
                    seenTrace = run.Trace.Count;
                    gathered = false;
                    run.Morning.Step();
                    Gather();
                }
            }
            return all;
        }

        static Motive Want(DecisionMoment m, string whom) => m?.Motives.FirstOrDefault(x => x.Key == "look_after:" + whom);

        static IEnumerable<ScalerTerm> MemoryTerms(Motive w) => w.Terms.Where(t => t.Description.StartsWith("memory", StringComparison.Ordinal));

        static double MemoryPart(Motive w) => MemoryTerms(w).Sum(t => t.Amount);

        // ---- A, B and C side by side ----

        [Test]
        public void Natural_HowSittingsEndedAndWhatThatDidToTheConcern()
        {
            var sittings = Sittings(_content, _content.Morning.Variants.Select(x => x.Id), Seeds);
            var problems = new List<string>();
            var sb = new StringBuilder();
            sb.AppendLine(sittings.Count + " sittings finished.");
            sb.AppendLine();
            sb.AppendLine("| How it ended | Sittings | ... helper decided again with them there | Memory terms answered at that decision | Mean change in wanting to look after them (memory part) | Mean further sittings with them within 20 minutes |");
            sb.AppendLine("|---|---|---|---|---|---|");

            foreach (var ending in new[] { Ending.CameRight, Ending.StillNotAllRight, Ending.TheyHadGone, Ending.NothingShowing })
            {
                var group = sittings.Where(s => s.Ending == ending).ToList();
                var decided = group.Where(s => s.Chose != null && s.Next != null && Want(s.Chose, s.Whom) != null).ToList();
                var answered = 0;
                var changes = new List<double>();
                foreach (var s in decided)
                {
                    var before = Want(s.Chose, s.Whom);
                    var after = Want(s.Next, s.Whom);
                    changes.Add(MemoryPart(after) - MemoryPart(before));
                    var wasAnswered = MemoryTerms(after).Any(t => t.Answered);
                    if (wasAnswered) answered++;

                    // No sight of them coming right means no answer, however it ended.
                    var sawThemComeRight = s.Run.Minds[s.Who].Experiences.Any(x => x.Meaning == "reassurance" && x.TargetId == s.Whom && x.Minute <= s.Next.Minute);
                    if (wasAnswered && !sawThemComeRight) problems.Add(s.Who + " had concern about " + s.Whom + " answered without ever seeing them come right");
                    if (ending == Ending.TheyHadGone && s.Comfort != null) problems.Add("a sitting with somebody who had gone still made a comfort event");
                }
                if (ending == Ending.CameRight)
                    foreach (var s in decided)
                    {
                        var after = Want(s.Next, s.Whom);
                        var freshDistressSince = s.Run.Result.Events.Any(e => e.Action == "show_distress" && e.TargetId == s.Whom && e.Minute >= s.Minute && e.Minute <= s.Next.Minute && e.Witnesses.Contains(s.Who));
                        if (!freshDistressSince && MemoryPart(after) != 0.0) problems.Add(s.Variant + "/" + s.Seed + " " + s.Who + ": saw " + s.Whom + " come right and the concern still presses");
                    }

                sb.AppendLine("| " + ending + " | " + group.Count + " | " + decided.Count + " | " + answered + " | " + (changes.Count == 0 ? "n/a" : F(changes.Average())) + " | " +
                              (group.Count == 0 ? "n/a" : group.Average(s => s.SittingsWithThemWithin20).ToString("0.00")) + " |");
            }

            var example = sittings.FirstOrDefault(s => s.Ending == Ending.CameRight && s.Chose != null && s.Next != null && Want(s.Next, s.Whom) != null && MemoryTerms(Want(s.Next, s.Whom)).Any(t => t.Answered));
            if (example != null)
            {
                sb.AppendLine();
                sb.AppendLine("### Came right: " + example.Variant + ", seed " + example.Seed + ", " + example.Who + " with " + example.Whom + ", minute " + example.Minute);
                sb.AppendLine();
                sb.AppendLine("- When choosing to sit, minute " + example.Chose.Minute + ": `look_after:" + example.Whom + "` " + F(Want(example.Chose, example.Whom).Urgency) + " because " + Want(example.Chose, example.Whom).Because);
                sb.AppendLine("- Next decision, minute " + example.Next.Minute + ": `look_after:" + example.Whom + "` " + F(Want(example.Next, example.Whom).Urgency) + " because " + Want(example.Next, example.Whom).Because);
                sb.AppendLine("- Memory terms at the next decision: " + string.Join("; ", MemoryTerms(Want(example.Next, example.Whom)).Select(t => t.ToString())));
            }

            var still = sittings.FirstOrDefault(s => s.Ending == Ending.StillNotAllRight && s.Chose != null && s.Next != null && Want(s.Next, s.Whom) != null);
            if (still != null)
            {
                sb.AppendLine();
                sb.AppendLine("### Still not all right: " + still.Variant + ", seed " + still.Seed + ", " + still.Who + " with " + still.Whom + ", minute " + still.Minute);
                sb.AppendLine();
                sb.AppendLine("- Next decision, minute " + still.Next.Minute + ": `look_after:" + still.Whom + "` " + F(Want(still.Next, still.Whom).Urgency) + " because " + Want(still.Next, still.Whom).Because);
            }

            sb.AppendLine();
            sb.AppendLine("\"Memory terms answered\" counts any sight of the person coming right up to that decision, not only at the end of this sitting.");
            sb.AppendLine("No sitting in these mornings ended with the other person still visibly not all right. Being sat with is perceived by them as support and felt as gratitude, which in every case became a stronger feeling than whatever distress was showing. So partial help does not occur on its own here, and is built by intervention in the next test.");
            Record("A B C D (natural). How sittings ended, and what that did to the concern", sb.ToString());
            Assert.IsEmpty(problems, string.Join("\n", problems));
            Assert.IsTrue(sittings.Any(s => s.Ending == Ending.CameRight), "nobody ever saw somebody they sat with come right");
        }

        [Test]
        public void ABCD_TheSameMomentEndedFourWays()
        {
            // Real moments: somebody in the last minute of sitting with a person
            // whose distress is showing, having seen that person go to pieces. From
            // the identical state, four endings, three of them interventions:
            //   A as it happens
            //   B the person also carries shame, which being sat with does not settle
            //   C the person has left the room
            //   D the helper has left the room, so there is no interaction
            var moments = new List<(string v, ulong seed, int steps, string who, string whom)>();
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= (ulong)Seeds && moments.Count < 12; seed++)
            {
                var run = Scenario001.Prepare(_content, v.Id, seed);
                for (var i = 1; i <= 90 && moments.Count(m => m.v == v.Id && m.seed == seed) == 0; i++)
                {
                    run.Morning.Step();
                    foreach (var p in People)
                    {
                        var d = run.Morning.Doing(p);
                        if (!d.HasValue || d.Value.Action.Kind != ActionKind.Comfort || d.Value.MinutesLeft != 1) continue;
                        var whom = d.Value.Action.TargetId;
                        if (!S14DiagnosisTests.Showing(run.Minds[whom], _content)) continue;
                        if (!run.Minds[p].Experiences.Any(x => x.Meaning == "concern" && x.TargetId == whom)) continue;
                        moments.Add((v.Id, seed, i, p, whom));
                        break;
                    }
                }
            }
            Assert.IsNotEmpty(moments, "never found somebody finishing sitting with a person whose distress was showing");

            var table = new Dictionary<string, List<(double memory, bool answered, bool rests, int minutes, bool satAgain20, bool steadyAtEnd)>>
            {
                { "A as it happens", new List<(double, bool, bool, int, bool, bool)>() },
                { "B shame being sat with does not settle", new List<(double, bool, bool, int, bool, bool)>() },
                { "C they had left", new List<(double, bool, bool, int, bool, bool)>() },
                { "D the helper had left", new List<(double, bool, bool, int, bool, bool)>() }
            };
            var problems = new List<string>();

            foreach (var (v, seed, steps, who, whom) in moments)
            foreach (var ending in table.Keys.ToList())
            {
                var run = Scenario001.Prepare(_content, v, seed);
                for (var i = 0; i < steps; i++) run.Morning.Step();
                var end = run.World.Minute + 1;
                var elsewhere = run.World.RoomOf(who) == "hallway" ? "bathroom" : "hallway";
                if (ending.StartsWith("B")) run.Minds[whom].Emotions.Add("shame", null, "respect", 0.95, 0, "experiment");
                if (ending.StartsWith("C")) run.World.Place(whom, elsewhere);
                if (ending.StartsWith("D")) run.World.Place(who, elsewhere);

                DecisionMoment next = null;
                var satAgain = false;
                run.Morning.Decided = m =>
                {
                    if (m.CharacterId != who) return;
                    if (next == null && m.Minute >= end && m.Motives.Any(x => x.Key == "look_after:" + whom)) next = m;
                    if (m.Minute > end && m.Minute <= end + 20 && m.Decision.Chosen.Kind == ActionKind.Comfort && m.Decision.Chosen.TargetId == whom) satAgain = true;
                };
                run.Morning.Step();
                var steadyAtEnd = run.Result.Events.Any(e => e.Action == "steady" && e.TargetId == whom && e.Minute == end && e.Witnesses.Contains(who));
                var satThrough = run.Result.Events.Any(e => e.Action == "comfort" && e.ActorId == who && e.TargetId == whom && e.Minute == end);
                if ((ending.StartsWith("A") || ending.StartsWith("B")) && !satThrough) continue;
                for (var i = 0; i < 40 && (next == null || run.World.Minute < end + 20); i++) run.Morning.Step();
                if (next == null) continue;

                if (ending.StartsWith("B") && steadyAtEnd) { problems.Add(v + "/" + seed + ": the shame did not keep " + whom + " showing, so B was not built"); continue; }

                var want = Want(next, whom);
                var memory = MemoryPart(want);
                var answered = MemoryTerms(want).Any(t => t.Answered);
                var sawComeRight = run.Minds[who].Experiences.Where(x => x.Meaning == "reassurance" && x.TargetId == whom && x.Minute <= next.Minute).ToList();
                var rests = sawComeRight.Any(x => run.Trace.Get(want.TraceId).ParentIds.Contains(x.TraceId));
                table[ending].Add((memory, answered, rests, next.Minute - end, satAgain, steadyAtEnd));

                if (answered && sawComeRight.Count == 0) problems.Add(ending + " " + v + "/" + seed + ": answered without seeing them come right");
                if (!ending.StartsWith("A") && steadyAtEnd) problems.Add(ending + " " + v + "/" + seed + ": " + who + " saw " + whom + " come right at the end");
            }

            var sb = new StringBuilder();
            sb.AppendLine(moments.Count + " moments, each ended four ways from the same state.");
            sb.AppendLine();
            sb.AppendLine("| Ending | Cases | Helper saw them come right at the end | Concern answered at the helper's next decision with them | Want rests on that sight | Mean memory part of the want then | Mean minutes to that decision | Sat with them again within 20 minutes |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            foreach (var k in table)
            {
                var r = k.Value;
                if (r.Count == 0) { sb.AppendLine("| " + k.Key + " | 0 | | | | | | |"); continue; }
                sb.AppendLine("| " + k.Key + " | " + r.Count + " | " + r.Count(x => x.steadyAtEnd) + " | " + r.Count(x => x.answered) + " | " + r.Count(x => x.rests) + " | " +
                              F(r.Average(x => x.memory)) + " | " + r.Average(x => x.minutes).ToString("0.0") + " | " + r.Count(x => x.satAgain20) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("B, C and D are interventions. B adds shame 0.95 to the person being sat with in the last minute; C and D move one of the two into another room in the last minute.");
            Record("A B C D (controlled). The same moment ended four ways", sb.ToString());

            Assert.IsEmpty(problems, string.Join("\n", problems));
            var a = table["A as it happens"];
            Assert.IsNotEmpty(a);
            Assert.AreEqual(a.Count, a.Count(x => x.steadyAtEnd), "as it happens, the helper did not always see them come right");
            foreach (var k in table.Keys.Where(k => !k.StartsWith("A")))
                Assert.Greater(table[k].Count(x => !x.answered), 0, k + " never left the concern unanswered");
        }

        [Test]
        public void A_TheWholeChainIsInTheTraceLinkByLink()
        {
            // circumstance -> perception -> reading -> want -> decision -> sitting
            // -> what it did to them -> what the helper saw -> memory -> answered
            // want. Each arrow is a parent link between real records.
            var sittings = Sittings(_content, _content.Morning.Variants.Select(x => x.Id), Seeds)
                .Where(s => s.Ending == Ending.CameRight && s.Chose != null && s.Next != null && Want(s.Next, s.Whom) != null && MemoryTerms(Want(s.Next, s.Whom)).Any(t => t.Answered))
                .ToList();
            Assert.IsNotEmpty(sittings, "no sitting ended with the helper seeing them come right and still caring enough to want to look after them");

            string shown = null;
            foreach (var s in sittings)
            {
                var t = s.Run.Trace;
                var before = Want(s.Chose, s.Whom);
                var concernTerm = MemoryTerms(before).First(x => x.Amount > 0 || x.Answered);
                var concernMemory = t.Get(concernTerm.Drew.First());
                var distressEvent = t.Chain(concernMemory.Id).FirstOrDefault(r => r.Kind == TraceKind.Event);
                var wantBefore = t.Get(before.TraceId);
                var decision = t.Get(s.Chose.Decision.TraceId);
                var sitting = t.ForEvent(s.Comfort.Id).First(r => r.Kind == TraceKind.Event);
                var settled = t.All.First(r => r.Kind == TraceKind.Consequence && r.CharacterId == s.Whom && r.ParentIds.Contains(decision.Id));
                var steady = t.ForEvent(s.Steady.Id).First(r => r.Kind == TraceKind.Event);
                var seen = t.Get(s.Run.Minds[s.Who].Experiences.First(x => x.EventId == s.Steady.Id).TraceId);
                var after = Want(s.Next, s.Whom);
                var wantAfter = t.Get(after.TraceId);

                void Link(TraceRecord child, TraceRecord parent, string what)
                    => Assert.IsTrue(child.ParentIds.Contains(parent.Id), s.Variant + "/" + s.Seed + " " + s.Who + ": " + what + " is not linked");

                Assert.IsNotNull(distressEvent, "the concern does not rest on anything that happened");
                Assert.IsTrue(wantBefore.ParentIds.Contains(concernMemory.Id), "the want does not rest on the concern");
                Link(decision, wantBefore, "the decision to the want");
                Link(settled, decision, "what the sitting did to them, to the decision");
                Link(steady, settled, "what could be seen, to what the sitting did");
                var theirReading = t.Get(s.Run.Minds[s.Whom].Experiences.First(x => x.EventId == s.Comfort.Id).TraceId);
                Link(steady, theirReading, "what could be seen, to what the person made of being sat with");
                Assert.IsTrue(t.Chain(seen.Id).Contains(steady), "what the helper made of it does not rest on what could be seen");
                Link(wantAfter, seen, "the want afterwards, to what the helper saw");
                Assert.AreEqual(s.Comfort.Minute, s.Steady.Minute);
                Assert.IsNotNull(sitting);

                if (shown == null)
                {
                    string Line(string stage, TraceRecord r) => "| " + stage + " | #" + r.Id + " " + r.Kind + (r.CharacterId == null ? "" : " [" + r.CharacterId + "]") + " | " + r.Summary.Replace("|", "/") + " |";
                    shown = "### " + s.Variant + ", seed " + s.Seed + ", " + s.Who + " and " + s.Whom + Environment.NewLine + Environment.NewLine +
                            "| Stage | Record | What it says |" + Environment.NewLine + "|---|---|---|" + Environment.NewLine +
                            Line("social circumstance", distressEvent) + Environment.NewLine +
                            Line("perception, reading, memory", concernMemory) + Environment.NewLine +
                            Line("want", wantBefore) + Environment.NewLine +
                            Line("decision", decision) + Environment.NewLine +
                            Line("action", sitting) + Environment.NewLine +
                            Line("social consequence (their reading)", theirReading) + Environment.NewLine +
                            Line("social consequence (the settling)", settled) + Environment.NewLine +
                            Line("what could be seen", steady) + Environment.NewLine +
                            Line("experience, memory", seen) + Environment.NewLine +
                            Line("changed want", wantAfter) + Environment.NewLine + Environment.NewLine +
                            "The want afterwards, printed by the trace tool down to what the helper saw:" + Environment.NewLine + Environment.NewLine +
                            "```" + Environment.NewLine + string.Join(Environment.NewLine, Shorten(t.Why(wantAfter.Id)).Split('\n').Select(l => l.TrimEnd('\r')).Take(12)) + Environment.NewLine + "```" + Environment.NewLine;
                }
            }

            Record("A. The chain, link by link", sittings.Count + " sittings checked, every link present." + Environment.NewLine + Environment.NewLine + shown);
        }

        // ---- C: help that cannot reach them ----

        [Test]
        public void C_WhenTheyLeaveBeforeItFinishesTheyAreNotSoothedAndNothingIsTreatedAsHelp()
        {
            // An intervention: the person being sat with is moved out of the room in
            // the last minute. The control is the same moment without the move.
            string found = null;
            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= (ulong)Seeds && found == null; seed++)
            {
                var probe = Scenario001.Prepare(_content, v.Id, seed);
                var steps = 0;
                string who = null, whom = null;
                for (; steps < 90 && who == null; steps++)
                {
                    probe.Morning.Step();
                    foreach (var p in People)
                    {
                        var d = probe.Morning.Doing(p);
                        if (d.HasValue && d.Value.Action.Kind == ActionKind.Comfort && d.Value.MinutesLeft == 1 &&
                            probe.Minds[d.Value.Action.TargetId].Emotions.IntensityAny("fear") > 0.1) { who = p; whom = d.Value.Action.TargetId; break; }
                    }
                }
                if (who == null) continue;

                (Scenario001Run run, double fearBefore, double fearAfter, bool comforted, bool couldNot) Finish(bool move)
                {
                    var run = Scenario001.Prepare(_content, v.Id, seed);
                    for (var i = 0; i < steps; i++) run.Morning.Step();
                    if (move) run.World.Place(whom, run.World.RoomOf(who) == "hallway" ? "bathroom" : "hallway");
                    var fear = run.Minds[whom].Emotions.IntensityAny("fear");
                    var seen = run.Trace.Count;
                    var events = run.Result.Events.Count;
                    run.Morning.Step();
                    return (run, fear, run.Minds[whom].Emotions.IntensityAny("fear"),
                        run.Result.Events.Skip(events).Any(e => e.Action == "comfort" && e.ActorId == who),
                        run.Trace.All.Skip(seen).Any(r => r.Kind == TraceKind.Consequence && r.CharacterId == who && r.Summary.StartsWith("could not sit with", StringComparison.Ordinal)));
                }

                var gone = Finish(true);
                var stayed = Finish(false);
                if (!stayed.comforted) continue;

                Assert.IsTrue(gone.couldNot, "the world did not notice they had gone");
                Assert.IsFalse(gone.comforted, "sitting with somebody who had gone still happened");
                Assert.Greater(gone.fearAfter, stayed.fearAfter, "they were soothed from another room");
                Assert.IsFalse(gone.run.Minds[who].Outcomes.Any(o => o.Kind == OutcomeKind.Satisfied || o.Kind == OutcomeKind.PartlySatisfied), "it was treated as help");
                Assert.IsFalse(gone.run.Minds[who].Experiences.Any(x => x.Meaning == "reassurance" && x.TargetId == whom && x.Minute == gone.run.World.Minute));

                found = v.Id + ", seed " + seed + ": " + who + " sitting with " + whom + ". Moved out in the last minute: no sitting happened, `" + whom + "` fear " + F(gone.fearBefore) + " -> " + F(gone.fearAfter) +
                        ". Left where they were: sat with, fear " + F(stayed.fearBefore) + " -> " + F(stayed.fearAfter) + ".";
            }

            Record("C. They had gone", found ?? "No case found.");
            Assert.IsNotNull(found);
        }

        // ---- D: no interaction ----

        [Test]
        public void D_WithoutTheSittingThereIsNoAnswerUnlessTheyAreSeenToComeRightAnyway()
        {
            // The same moment twice. In one, the helper sits with them as chosen. In
            // the other, the helper is taken out of the room before the sitting can
            // finish, so they do not interact and do not see how it ends.
            var sb = new StringBuilder();
            sb.AppendLine("| Condition, seed | Helper, person | Sat, and saw them come right | Did not interact: concern at the helper's next decision with them | ... answered |");
            sb.AppendLine("|---|---|---|---|---|");
            var cases = 0;
            var fabricated = new List<string>();

            foreach (var s in Sittings(_content, _content.Morning.Variants.Select(x => x.Id), Seeds).Where(x => x.Ending == Ending.CameRight).Take(12))
            {
                var run = Scenario001.Prepare(_content, s.Variant, s.Seed);
                while (run.World.Minute < s.Minute - 1) run.Morning.Step();
                var elsewhere = run.World.RoomOf(s.Who) == "hallway" ? "bathroom" : "hallway";
                run.World.Place(s.Who, elsewhere);

                DecisionMoment next = null;
                run.Morning.Decided = m => { if (m.CharacterId == s.Who && next == null && m.Motives.Any(x => x.Key == "look_after:" + s.Whom)) next = m; };
                for (var i = 0; i < 40 && next == null; i++) run.Morning.Step();
                if (next == null) continue;

                cases++;
                var want = Want(next, s.Whom);
                var answered = MemoryTerms(want).Any(t => t.Answered);
                var saw = run.Minds[s.Who].Experiences.Any(x => x.Meaning == "reassurance" && x.TargetId == s.Whom && x.Minute <= next.Minute);
                if (answered && !saw) fabricated.Add(s.Variant + "/" + s.Seed + ": answered without being seen");
                sb.AppendLine("| " + s.Variant + ", " + s.Seed + " | " + s.Who + ", " + s.Whom + " | yes | " + F(MemoryPart(want)) + " (minute " + next.Minute + ") | " +
                              (answered ? "yes, having seen them come right later" : "no") + " |");
            }

            Record("D. No interaction", sb.ToString());
            Assert.IsEmpty(fabricated, string.Join("\n", fabricated));
            Assert.Greater(cases, 0);
        }

        // ---- E: causality ----

        static Scenario001Content With(Scenario001Content c, Func<RuleSet, RuleSet> change)
            => new Scenario001Content(c.Vocabulary, c.Cast, c.Backstory, c.Morning, change(c.Rules));

        static RuleSet SittingSoothesNothing(RuleSet r)
        {
            var d = r.Deciding;
            return new RuleSet
            {
                Interpretation = r.Interpretation, BeliefNudges = r.BeliefNudges, Appraisal = r.Appraisal, Dynamics = r.Dynamics,
                Motivation = r.Motivation, Proposals = r.Proposals, Costs = r.Costs,
                Deciding = new DecisionDynamics
                {
                    AmbiguityBand = d.AmbiguityBand, InterruptIntensity = d.InterruptIntensity, VisibleDistress = d.VisibleDistress,
                    HungerPerMinute = d.HungerPerMinute, PortionRelief = d.PortionRelief, LowPortions = d.LowPortions, DistressShows = d.DistressShows,
                    ComfortSettles = d.ComfortSettles, ComfortSettling = 1.0, UrgencyKnee = d.UrgencyKnee,
                    RecallHalfLife = d.RecallHalfLife, WatchingGoesStaleAfter = d.WatchingGoesStaleAfter, ActionMinutes = d.ActionMinutes
                }
            };
        }

        internal static RuleSet NothingIsAnswered(RuleSet r)
            => new RuleSet
            {
                Interpretation = r.Interpretation, BeliefNudges = r.BeliefNudges, Appraisal = r.Appraisal, Dynamics = r.Dynamics,
                Proposals = r.Proposals, Costs = r.Costs, Deciding = r.Deciding,
                Motivation = r.Motivation.Select(m => new MotivationRule
                {
                    Id = m.Id, Note = m.Note, When = m.When, Motive = m.Motive, Scope = m.Scope, BaseUrgency = m.BaseUrgency,
                    ScaledBy = m.ScaledBy.Select(s => new Scaler
                    {
                        Kind = s.Kind, Name = s.Name, Predicate = s.Predicate, Args = s.Args, Entry = s.Entry, About = s.About,
                        Topic = s.Topic, By = s.By, Target = s.Target, Factor = s.Factor, Until = new List<string>()
                    }).ToList()
                }).ToList()
            };

        [Test]
        public void E_RemovingTheConsequenceOrWhatReadsItChangesNothingUntilItCouldMatter()
        {
            var sb = new StringBuilder();
            sb.AppendLine("| Counterfactual | Condition, seed | First sitting that did something / first answered concern | First difference in anybody's wants | In whom | Why it is them |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var problems = new List<string>();

            foreach (var (label, other) in new (string, Scenario001Content)[]
                     {
                         ("sitting soothes nothing", With(_content, SittingSoothesNothing)),
                         ("nothing reads seeing them come right", With(_content, NothingIsAnswered))
                     })
            foreach (var v in new[] { "mara_ate_it", "elena_fed_mara", "daniel_ate_it" })
            for (ulong seed = 1; seed <= 4; seed++)
            {
                var a = Scenario001.Prepare(_content, v, seed);
                var b = Scenario001.Prepare(other, v, seed);
                int? firstMatters = null;
                int? firstDiff = null;
                string whoDiff = null, why = null;

                for (var i = 0; i < 90 && firstDiff == null; i++)
                {
                    var seenA = a.Result.Events.Count;
                    a.Morning.Step();
                    b.Morning.Step();

                    // When the consequence could first matter in the shipped morning.
                    if (firstMatters == null)
                    {
                        if (label.StartsWith("sitting") && a.Result.Events.Skip(seenA).Any(e => e.Action == "comfort")) firstMatters = a.World.Minute;
                        if (label.StartsWith("nothing") && People.Any(p => new Motivator(_content.Rules).Raise(a.Minds[p], a.Morning.See(p), _content.Morning.Day, new TraceLog(), 0)
                                .Any(w => w.Name == "look_after" && w.Terms.Any(t => t.Answered)))) firstMatters = a.World.Minute;
                    }

                    foreach (var p in People)
                    {
                        var wa = new Motivator(_content.Rules).Raise(a.Minds[p], a.Morning.See(p), _content.Morning.Day, new TraceLog(), 0);
                        var wb = new Motivator(other.Rules).Raise(b.Minds[p], b.Morning.See(p), _content.Morning.Day, new TraceLog(), 0);
                        var differ = wa.Count != wb.Count || wa.Zip(wb, (x, y) => x.Key != y.Key || Math.Abs(x.Urgency - y.Urgency) > 1e-12).Any(d => d);
                        if (!differ) continue;
                        firstDiff = a.World.Minute;
                        whoDiff = p;
                        var satWith = a.Result.Events.Any(e => e.Action == "comfort" && e.TargetId == p);
                        var sawSteady = a.Minds[p].Experiences.Any(x => x.Meaning == "reassurance");
                        why = satWith ? "was sat with" : sawSteady ? "saw somebody come right" : "neither";
                        if (firstMatters == null || firstDiff < firstMatters) problems.Add(label + " " + v + "/" + seed + ": wants differed at minute " + firstDiff + " before the consequence could matter");
                        if (why == "neither") problems.Add(label + " " + v + "/" + seed + ": " + p + " differed without being sat with or seeing anybody come right");
                        break;
                    }
                }

                sb.AppendLine("| " + label + " | " + v + ", " + seed + " | " + (firstMatters?.ToString() ?? "never") + " | " + (firstDiff?.ToString() ?? "never") + " | " + (whoDiff ?? "") + " | " + (why ?? "") + " |");
            }

            Record("E. Causality", sb.ToString());
            Assert.IsEmpty(problems, string.Join("\n", problems));
        }

        // ---- F: knowledge locality ----

        [Test]
        public void F_OnlyThoseInTheRoomSeeSomebodyComeRightAndOnlyTheyHaveTheirConcernAnswered()
        {
            var steadies = 0;
            var holders = 0;
            var problems = new List<string>();
            var answeredTerms = 0;

            foreach (var v in _content.Morning.Variants)
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var run = Scenario001.Prepare(_content, v.Id, seed);
                run.Morning.Decided = m =>
                {
                    foreach (var w in m.Motives.Where(x => x.Name == "look_after"))
                    foreach (var t in w.Terms.Where(t => t.Answered))
                    {
                        answeredTerms++;
                        var answer = run.Trace.Get(t.Drew.Single());
                        var experience = m.Mind.Experiences.FirstOrDefault(x => x.TraceId == answer.Id);
                        if (experience == null || experience.Meaning != "reassurance" || experience.TargetId != w.TargetId)
                            problems.Add(m.CharacterId + ": a concern about " + w.TargetId + " was answered by something that is not their own sight of them coming right");
                    }
                };
                run.Morning.Run(_content.Morning.Minutes);

                foreach (var e in run.Result.Events.Where(e => e.Action == "steady"))
                {
                    steadies++;
                    if (e.Overhearers.Count > 0) problems.Add(e.Id + " was heard through a wall");
                    foreach (var p in People)
                    {
                        var holds = run.Minds[p].Experiences.Any(x => x.EventId == e.Id);
                        if (holds) holders++;
                        if (holds && !e.Witnesses.Contains(p)) problems.Add(p + " holds " + e.Id + " without being in the room");
                        if (!holds && e.Witnesses.Contains(p)) problems.Add(p + " was in the room for " + e.Id + " and kept nothing");
                        if (p == e.TargetId && holds) problems.Add(p + " saw their own face come right");
                    }
                }
            }

            Record("F. Knowledge locality", steadies + " moments of somebody coming right in front of others, " + holders + " memories of them, every one held by somebody in the room and nobody else; " +
                   answeredTerms + " answered concerns, every one resting on the holder's own sight of that person coming right.");
            Assert.IsEmpty(problems, string.Join("\n", problems.Take(20)));
            Assert.Greater(steadies, 0);
        }

        // ---- behaviour ----

        [Test]
        public void Behaviour_HowMuchSittingWithSomebodyThereIsNow()
        {
            var sittings = Sittings(_content, _content.Morning.Variants.Select(x => x.Id), Seeds);
            var mornings = _content.Morning.Variants.Count * Seeds;
            var by = People.ToDictionary(p => p, p => sittings.Count(s => s.Who == p));
            var noSoothing = Sittings(With(_content, SittingSoothesNothing), _content.Morning.Variants.Select(x => x.Id), Seeds);
            Record("Behaviour", sittings.Count + " sittings finished in " + mornings + " mornings (S1.3: 492 in the same 50, from `diagnosis-before.md`). By who sat: " +
                   string.Join(", ", by.Select(k => k.Key + " " + k.Value)) + ". Ended: " + string.Join(", ", sittings.GroupBy(s => s.Ending).Select(g => g.Key + " " + g.Count())) + "." +
                   Environment.NewLine + Environment.NewLine +
                   "What makes somebody come right when sat with: with the settling removed (sitting softens nothing, the same seeds), " + noSoothing.Count + " sittings, ended: " +
                   string.Join(", ", noSoothing.GroupBy(s => s.Ending).Select(g => g.Key + " " + g.Count())) + ". Anybody still coming right there came right from what they made of being sat with alone.");
        }
    }
}
