using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The S1.4 held-out predictions, committed in
    /// Docs/slices/S1.4/held-out-predictions.md before any S1.4 simulation code
    /// existed, checked here exactly as written. The held-out condition is
    /// `leo_ate_it`, which no other S1.4 test uses.
    /// </summary>
    public class S14HeldOutTests
    {
        const string HeldOut = "leo_ate_it";
        const int Seeds = 10;
        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);
        static readonly string[] People = S14ExperimentTests.People;

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.4 held-out results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S14HeldOutTests`. Predictions in `held-out-predictions.md`, committed first (`56c6c7e`). Condition `" + HeldOut + "`, seeds 1 to " + Seeds + ".");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine("- " + r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.4");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "held-out-results.md"), sb.ToString());
        }

        static bool Record(string id, bool held, string detail)
        {
            _results[id] = "**" + id + "** " + (held ? "held" : "MISSED") + ". " + detail;
            TestContext.WriteLine(_results[id]);
            return held;
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);

        /// <summary>Every decision of every held-out morning, read at the moment it was taken.</summary>
        sealed class Morning
        {
            public ulong Seed;
            public Scenario001Run Run;
            public List<DecisionMoment> Decisions = new List<DecisionMoment>();
        }

        static List<Morning> _mornings;

        static List<Morning> Mornings()
        {
            if (_mornings != null) return _mornings;
            _mornings = new List<Morning>();
            for (ulong seed = 1; seed <= Seeds; seed++)
            {
                var m = new Morning { Seed = seed, Run = Scenario001.Prepare(_content, HeldOut, seed) };
                m.Run.Morning.Decided = d => m.Decisions.Add(d);
                m.Run.Morning.Run(_content.Morning.Minutes);
                _mornings.Add(m);
            }
            return _mornings;
        }

        [Test]
        public void P1_OnlyThoseInTheRoomHoldTheSightOfSomebodyComingRight()
        {
            var memories = 0;
            var outside = 0;
            foreach (var m in Mornings())
            foreach (var p in People)
            foreach (var x in m.Run.Minds[p].Experiences.Where(x => x.Meaning == "reassurance"))
            {
                memories++;
                var e = m.Run.Result.Events.First(ev => ev.Id == x.EventId);
                if (!e.Witnesses.Contains(p)) outside++;
            }
            var held = Record("P1", memories > 0 && outside == 0, memories + " memories of seeing somebody come right; held by somebody not in the room: " + outside + ".");
            Assert.Greater(memories, 0, "nothing to check");
            Assert.IsTrue(held, "P1 held when first run");
        }

        [Test]
        public void P2_EveryWitnessWhoStillCaresHasTheirConcernAnsweredAndCanSayWhy()
        {
            var checkedCount = 0;
            var misses = new List<string>();
            foreach (var m in Mornings())
            foreach (var e in m.Run.Result.Events.Where(ev => ev.Action == "steady"))
            foreach (var w in e.Witnesses)
            {
                var next = m.Decisions.FirstOrDefault(d => d.CharacterId == w && d.Minute >= e.Minute && d.Motives.Any(x => x.Key == "look_after:" + e.TargetId));
                if (next == null) continue;
                checkedCount++;
                var want = next.Motives.First(x => x.Key == "look_after:" + e.TargetId);
                var memoryTerms = want.Terms.Where(t => t.Description.StartsWith("memory", StringComparison.Ordinal)).ToList();
                var zero = memoryTerms.All(t => t.Amount == 0.0);
                var seen = m.Run.Minds[w].Experiences.First(x => x.EventId == e.Id);
                var walksBack = m.Run.Trace.Chain(want.TraceId).Any(r => r.Id == seen.TraceId);
                if (zero && walksBack) continue;

                var freshDistress = m.Run.Result.Events.Any(ev => ev.Action == "show_distress" && ev.TargetId == e.TargetId && ev.Minute >= e.Minute && ev.Minute <= next.Minute && ev.Witnesses.Contains(w));
                misses.Add("seed " + m.Seed + ", " + w + " about " + e.TargetId + " at minute " + next.Minute + " (seen at " + e.Minute + "): memory terms " +
                           string.Join(", ", memoryTerms.Select(t => F(t.Amount))) + ", walks back " + walksBack +
                           (freshDistress ? "; they had seen " + e.TargetId + " go to pieces again in between" : ""));
            }

            var held2 = Record("P2", checkedCount > 0 && misses.Count == 0, checkedCount + " witnesses decided again while still wanting to look after the person they saw come right. Not answered: " + misses.Count +
                                                               (misses.Count == 0 ? "." : ": " + string.Join("; ", misses.Take(6)) + (misses.Count > 6 ? "; and " + (misses.Count - 6) + " more." : ".")));
            Assert.Greater(checkedCount, 0, "nothing to check");
            Assert.IsTrue(held2, "P2 held when first run");
        }

        [Test]
        public void P3_NobodyOutOfTheRoomHasTheirConcernAnsweredByIt()
        {
            var checkedCount = 0;
            var answeredWithoutSeeing = 0;
            foreach (var m in Mornings())
            foreach (var e in m.Run.Result.Events.Where(ev => ev.Action == "steady"))
            foreach (var p in People.Where(p => p != e.TargetId && !e.Witnesses.Contains(p)))
            {
                var mind = m.Run.Minds[p];
                if (!mind.Experiences.Any(x => x.Meaning == "concern" && x.TargetId == e.TargetId && x.Minute <= e.Minute)) continue;
                var next = m.Decisions.FirstOrDefault(d => d.CharacterId == p && d.Minute >= e.Minute && d.Motives.Any(x => x.Key == "look_after:" + e.TargetId));
                if (next == null) continue;
                var sawLater = mind.Experiences.Any(x => x.Meaning == "reassurance" && x.TargetId == e.TargetId && x.Minute >= e.Minute && x.Minute <= next.Minute);
                if (sawLater) continue;
                checkedCount++;
                var want = next.Motives.First(x => x.Key == "look_after:" + e.TargetId);
                if (want.Terms.Any(t => t.Answered)) answeredWithoutSeeing++;
            }
            var held3 = Record("P3", checkedCount > 0 && answeredWithoutSeeing == 0, checkedCount + " people out of the room, holding concern about the person, who decided again with them without seeing them come right themselves. Answered anyway: " + answeredWithoutSeeing + ".");
            Assert.Greater(checkedCount, 0, "nothing to check");
            Assert.IsTrue(held3, "P3 held when first run");
        }

        [Test]
        public void P4_SeeingThemComeRightIsFollowedByNoMoreSittingsThanSeeingThemStillNotAllRight()
        {
            var sittings = S14ExperimentTests.Sittings(_content, new[] { HeldOut }, Seeds);
            var right = sittings.Where(s => s.Ending == S14ExperimentTests.Ending.CameRight).ToList();
            var still = sittings.Where(s => s.Ending == S14ExperimentTests.Ending.StillNotAllRight).ToList();
            if (right.Count == 0 || still.Count == 0)
            {
                Record("P4", false, "Not measurable: " + right.Count + " sittings ended with them coming right and " + still.Count + " with them still not all right.");
                // RECORDED MISS, first run. The prediction assumed sittings would
                // sometimes end with the person still visibly not all right. They
                // never do: being sat with is read as support and felt as gratitude,
                // which outweighs whatever distress was showing. If this starts
                // failing, such endings have appeared and P4 can be judged.
                Assert.AreEqual(0, still.Count, "RECORDED MISS: turn round when sittings can end with the person still not all right");
                return;
            }
            var a = right.Average(s => s.SittingsWithThemWithin20);
            var b = still.Average(s => s.SittingsWithThemWithin20);
            Record("P4", a <= b, "Further sittings with the same person within 20 minutes: " + a.ToString("0.00") + " after " + right.Count + " that ended with them coming right, " +
                                 b.ToString("0.00") + " after " + still.Count + " that ended with them still not all right.");
        }

        [Test]
        public void P5_PeopleStayDifferent()
        {
            var profiles = People.ToDictionary(p => p, p =>
            {
                var mine = Mornings().SelectMany(m => m.Run.Result.By(p)).ToList();
                return (IReadOnlyDictionary<string, double>)mine.GroupBy(x => x.Action.KindName).ToDictionary(g => g.Key, g => g.Count() / (double)mine.Count);
            });
            var gaps = new List<double>();
            for (var i = 0; i < People.Length; i++)
            for (var j = i + 1; j < People.Length; j++)
                gaps.Add(BatchRunner.HowDifferent(profiles[People[i]], profiles[People[j]]));
            var held5 = Record("P5", gaps.Average() > 0.50, "Mean gap between different people's mornings: " + gaps.Average().ToString("0.00") + "; closest pair " + gaps.Min().ToString("0.00") + ".");
            Assert.IsTrue(held5, "P5 held when first run");
        }

        [Test]
        public void P6_ThereIsLessSittingWithSomebodyThanBefore()
        {
            var sittings = S14ExperimentTests.Sittings(_content, _content.Morning.Variants.Select(v => v.Id), 10);
            var held6 = Record("P6", sittings.Count < 492, sittings.Count + " sittings finished in the 50 design mornings, against 492 on the S1.3 code (`diagnosis-before.md`).");
            Assert.IsTrue(held6, "P6 held when first run");
        }
    }
}
