using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.5 diagnosis: where the wants people act on come from, on the shipped
    /// rules, before anything about how wants are raised is changed. Writes
    /// Docs/slices/S1.5/diagnosis-current.md.
    /// </summary>
    public class S15DiagnosisTests
    {
        const int AuditSeeds = 10;
        const int BatchSeeds = 40;

        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _sections = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.5 diagnosis: where wants come from");
            sb.AppendLine();
            sb.AppendLine("Generated by `S15DiagnosisTests`. Shipped rules, the five design conditions; decisions from seeds 1 to " + AuditSeeds + ", behaviour from the S1 batch, seeds 1 to " + BatchSeeds + ".");
            sb.AppendLine();
            sb.AppendLine("Each term of a want is sorted by what it read. **Circumstance:** the body, a memory of today, a live feeling. **History:** a belief with evidence behind it, a ledger entry. **Authored:** a belief written into the person with no evidence. **Disposition:** a trait, a value. A want is **FromCircumstance** when circumstance and history carry at least half of it, **MostlyDisposition** when they carry something but less than half, and **Unsupported** when nothing that happened is behind it at all.");
            sb.AppendLine();
            foreach (var s in _sections.Values) sb.AppendLine(s);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.5");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "diagnosis-current.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _sections[key] = text;
            TestContext.WriteLine(text);
        }

        [Test, Timeout(1800000)]
        public void D1_WhereTheWantsPeopleActOnComeFrom()
        {
            var variants = _content.Morning.Variants.Select(v => v.Id).ToList();
            var m = S15.Measure(_content, "shipped", variants, AuditSeeds, BatchSeeds);

            var sb = new StringBuilder();
            sb.AppendLine("## 1. Where wants come from");
            sb.AppendLine();
            sb.AppendLine(m.Sources.ToMarkdown());
            sb.AppendLine("## 2. How much of what people do depends on it");
            sb.AppendLine();
            sb.AppendLine("Each decision weighed again, at the moment it was taken:");
            sb.AppendLine();
            sb.AppendLine("| Taken out | Decisions whose top option changes |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| every Unsupported want | " + MotivationSources.P(m.DecidedByUnsupportedWants, m.Audit.Decisions) + " |");
            sb.AppendLine("| the trait and value part of every want (the rest raised as before) | " + MotivationSources.P(m.DecidedByTraitsAndValuesInWants, m.Audit.Decisions) + " |");
            sb.AppendLine();
            sb.AppendLine("A static re-weighing: it shows what the moment turned on, not what the morning would have become.");
            sb.AppendLine();
            sb.AppendLine("## 3. Behaviour");
            sb.AppendLine();
            sb.AppendLine(m.BatchMornings + " mornings, " + m.BatchDecisions + " decisions. What each person did, across every condition:");
            sb.AppendLine();
            sb.AppendLine(S15.Profiles(m));
            sb.AppendLine("| Measure | Value |");
            sb.AppendLine("|---|---|");
            sb.AppendLine("| Standing still, share of choices | " + S15.P(m.WaitShare) + " |");
            sb.AppendLine("| Sitting with somebody, share of choices | " + S15.P(m.SittingShare) + " |");
            sb.AppendLine("| Different people, mean gap | " + S15.F(m.MeanGap) + " |");
            sb.AppendLine("| Weakest condition, mean gap | " + S15.F(m.WorstConditionMean) + " |");
            sb.AppendLine("| Closest pair | " + S15.F(m.ClosestPair) + " (" + m.ClosestWho + ") |");
            sb.AppendLine("| Worst back-and-forth pacing | " + m.WorstPacing + " (" + m.WorstPacingWho + ") |");
            sb.AppendLine("| Ties between genuinely different actions | " + S15.P(m.RealTies) + " |");
            sb.AppendLine();
            sb.AppendLine("## 4. The decisions, by the S1.2 audit");
            sb.AppendLine();
            sb.AppendLine(m.Audit.ToMarkdown());
            Record("1", sb.ToString());

            Assert.AreEqual(m.Sources.Decisions, m.Audit.Decisions, "both instruments saw the same decisions");
        }

        [Test]
        public void D2_WhatEachPersonWantsWithNothingHappening()
        {
            // The same people, as they are written, in a room with the others and
            // nothing having happened: no night, no morning, no feelings, no
            // memories, not hungry. Whatever they want here, they want for who
            // they are.
            var sb = new StringBuilder();
            sb.AppendLine("## 5. What each person wants with nothing happening");
            sb.AppendLine();
            sb.AppendLine("Each person as written (traits, values, authored beliefs), in a kitchen with the other three, nothing having happened to them, not hungry.");
            sb.AppendLine();
            sb.AppendLine("| Who | Wants raised | Top choice | Unsupported wants |");
            sb.AppendLine("|---|---|---|---|");

            foreach (var id in S15.People)
            {
                var mind = new Mind(_content.Cast[id]);
                var others = S15.People.Where(p => p != id).ToList();
                var percept = Bench.Standing(id, present: others, hunger: 0.0);
                var wants = new Motivator(_content.Rules).Raise(mind, percept, _content.Morning.Day, new TraceLog(), 0);
                var decision = new Deliberator(_content.Rules).Decide(mind, percept, wants, _content.Morning.Day, new Rng(1), new TraceLog(), 0);
                var unsupported = wants.Count(w => MotivationSources.Of(w).Class == Support.Unsupported);
                sb.AppendLine("| " + id + " | " + string.Join("; ", wants.Select(w => w.Key + " " + w.Urgency.ToString("0.00"))) + " | " +
                              decision.ChosenScored + " | " + unsupported + " of " + wants.Count + " |");
            }
            Record("5", sb.ToString());
        }
    }
}
