using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.5: traits and values as standing wants (A, as shipped) against traits and
    /// values as dispositions that scale a response (B), with the gate (B0) as an
    /// ablation for attribution. Design conditions only. Everything is recorded
    /// whichever way it comes out; the assertions check the mechanism, never a
    /// behavioural number. Writes Docs/slices/S1.5/experiment-results.md.
    /// </summary>
    public class S15ExperimentTests
    {
        const int AuditSeeds = 10;
        const int BatchSeeds = 40;

        static Scenario001Content _content;
        static IReadOnlyList<string> _variants;
        static Dictionary<string, S15Measured> _measured;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static readonly (string Label, string Mode)[] Modes =
        {
            ("A standing", DispositionMode.Standing),
            ("B respond", DispositionMode.Respond),
            ("B0 gated", DispositionMode.Gated)
        };

        [OneTimeSetUp]
        public void Load()
        {
            _content = Scenario001Content.Load(TestPaths.DataRoot);
            _variants = _content.Morning.Variants.Select(v => v.Id).ToList();
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.5 experiment results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S15ExperimentTests`. The five design conditions. **A** is the shipped rules (`standing`). **B** is traits and values as dispositions (`respond`): `urgency = C x (1 + D)`. **B0** is the gate, an ablation for attribution only (`gated`). Nothing else differs between them.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.5");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "experiment-results.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static Dictionary<string, S15Measured> Measured()
        {
            if (_measured != null) return _measured;
            _measured = new Dictionary<string, S15Measured>(StringComparer.Ordinal);
            foreach (var (label, mode) in Modes)
                _measured[label] = S15.Measure(S15.Mode(_content, mode), label, _variants, AuditSeeds, BatchSeeds);
            return _measured;
        }

        static string Row(string name, Func<S15Measured, string> value)
            => "| " + name + " | " + string.Join(" | ", Modes.Select(m => value(Measured()[m.Label]))) + " |";

        static string Header(string first) => "| " + first + " | " + string.Join(" | ", Modes.Select(m => m.Label)) + " |" + Environment.NewLine +
                                             "|---|" + string.Join("|", Modes.Select(_ => "---")) + "|";

        // ---- 1 ----

        [Test, Timeout(3600000)]
        public void E1_WhereWantsComeFrom()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 1. Where wants come from");
            sb.AppendLine();
            sb.AppendLine("Decisions from seeds 1 to " + AuditSeeds + ".");
            sb.AppendLine();
            sb.AppendLine(Header("Measure"));
            sb.AppendLine(Row("Decisions", m => m.Audit.Decisions.ToString()));
            sb.AppendLine(Row("Wants raised", m => m.Sources.Raised.ToString()));
            sb.AppendLine(Row("... from circumstance", m => S15.P(m.Sources.Share(Support.FromCircumstance))));
            sb.AppendLine(Row("... mostly disposition", m => S15.P(m.Sources.Share(Support.MostlyDisposition))));
            sb.AppendLine(Row("... unsupported", m => S15.P(m.Sources.Share(Support.Unsupported))));
            sb.AppendLine(Row("... raised on traits and values alone", m => MotivationSources.P(m.Sources.OnTraitsAndValuesAlone, m.Sources.Raised)));
            sb.AppendLine(Row("... standing on history alone (evidence, ledger)", m => MotivationSources.P(m.Sources.StandingWithReasons, m.Sources.Raised)));
            foreach (Source s in Enum.GetValues(typeof(Source)))
                sb.AppendLine(Row("Urgency from " + s, m => S15.P(m.Sources.ShareOfUrgency(s))));
            sb.AppendLine(Row("Wants resting on something that happened (trace)", m => MotivationSources.P(m.Sources.WantsTraced, m.Sources.Raised)));
            sb.AppendLine(Row("Urgency resting on something that happened (trace)", m => MotivationSources.P(m.Sources.UrgencyTraced, m.Sources.UrgencyTraced + m.Sources.UrgencyUntraced)));
            sb.AppendLine(Row("Decisions with nothing wanted at all", m => MotivationSources.P(m.Sources.NothingWanted, m.Sources.Decisions)));
            sb.AppendLine(Row("Decisions changed by taking out unsupported wants", m => MotivationSources.P(m.DecidedByUnsupportedWants, m.Audit.Decisions)));
            sb.AppendLine(Row("Decisions changed by taking out the trait and value part of wants", m => MotivationSources.P(m.DecidedByTraitsAndValuesInWants, m.Audit.Decisions)));
            sb.AppendLine();
            foreach (var (label, _) in Modes)
            {
                sb.AppendLine("### " + label);
                sb.AppendLine();
                sb.AppendLine(Measured()[label].Sources.ToMarkdown());
            }
            Record("1", sb.ToString());

            var b = Measured()["B respond"];
            Assert.AreEqual(0, b.Sources.OnTraitsAndValuesAlone, "under B nothing may be raised on traits and values alone");
            Assert.Greater(Measured()["A standing"].Sources.OnTraitsAndValuesAlone, 0, "the instrument sees standing wants where they exist");
        }

        // ---- 2 ----

        [Test, Timeout(3600000)]
        public void E2_WhatPeopleDo()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 2. What people do");
            sb.AppendLine();
            sb.AppendLine("Behaviour from the S1 batch (seeds 1 to " + BatchSeeds + ", 200 mornings); decisions, walks and decisive rates from the S1.2 audit (seeds 1 to " + AuditSeeds + ").");
            sb.AppendLine();
            sb.AppendLine(Header("Measure"));
            sb.AppendLine(Row("Standing still, share of choices (batch)", m => S15.P(m.WaitShare)));
            sb.AppendLine(Row("Standing still on top (audit)", m => S15.P(m.WaitOnTopShare)));
            sb.AppendLine(Row("Sitting with somebody, share of choices", m => S15.P(m.SittingShare)));
            foreach (var want in new[] { "look_after", "keep_peace", "guard_supplies", "find_out", "get_food", "restore_standing", "avoid_exposure" })
                sb.AppendLine(Row("`" + want + "` decisive", m => S15.P(m.Decisive(want))));
            sb.AppendLine(Row("Walks completed and followed by a decision", m => m.Audit.WalksWithAPurpose.ToString()));
            sb.AppendLine(Row("... followed by something the walk's want did not serve", m => S15.P(m.AbandonedWalks)));
            sb.AppendLine(Row("Pacing, mean per person per morning (audit)", m => m.MeanPacing.ToString("0.00")));
            sb.AppendLine(Row("Worst pacing (batch)", m => m.WorstPacing + " (" + m.WorstPacingWho + ")"));
            sb.AppendLine(Row("Different people, mean gap", m => S15.F(m.MeanGap)));
            sb.AppendLine(Row("Weakest condition, mean gap", m => S15.F(m.WorstConditionMean)));
            sb.AppendLine(Row("Closest pair", m => S15.F(m.ClosestPair) + " (" + m.ClosestWho + ")"));
            sb.AppendLine(Row("Ties between genuinely different actions (batch)", m => S15.P(m.RealTies)));
            sb.AppendLine(Row("Settled by the seed, between different kinds (audit)", m => S15.P(m.GenuineTies)));
            sb.AppendLine(Row("Interruptions per morning", m => (m.Audit.Interruptions / (double)Math.Max(1, m.Audit.Mornings)).ToString("0.0")));
            sb.AppendLine(Row("Meals (batch)", m => m.Meals.ToString()));
            sb.AppendLine(Row("Walks to the food given up on arrival (audit)", m => m.Audit.CommitmentsByWant.TryGetValue("get_food: " + Commitment.NotWorthIt, out var n) ? n.ToString() : "0"));
            sb.AppendLine();
            foreach (var (label, _) in Modes)
            {
                var m = Measured()[label];
                sb.AppendLine("**" + label + "**, what each person did across every condition:");
                sb.AppendLine();
                sb.AppendLine(S15.Profiles(m));
                sb.AppendLine("What was chosen, by the support of the want that added most: " +
                              string.Join(", ", m.Sources.ChosenBy.OrderBy(k => k.Key, StringComparer.Ordinal).Select(k => k.Key + " " + MotivationSources.P(k.Value, m.Sources.Decisions))) + ". Standing still chosen, by the same: " +
                              string.Join(", ", m.Sources.WaitChosenBy.OrderBy(k => k.Key, StringComparer.Ordinal).Select(k => k.Key + " " + MotivationSources.P(k.Value, m.Sources.WaitChosenBy.Values.Sum()))) + ".");
                sb.AppendLine();
            }
            Record("2", sb.ToString());

            // Personal gaps between modes, for the report: how far each person moved.
            var moved = new StringBuilder();
            moved.AppendLine("How far each person's morning moved from A (the total difference between action profiles):");
            moved.AppendLine();
            moved.AppendLine("| Who | A to B | A to B0 |");
            moved.AppendLine("|---|---|---|");
            foreach (var p in S15.People)
                moved.AppendLine("| " + p + " | " + S15.F(BatchRunner.HowDifferent(Measured()["A standing"].ProfileByPerson[p], Measured()["B respond"].ProfileByPerson[p])) +
                                 " | " + S15.F(BatchRunner.HowDifferent(Measured()["A standing"].ProfileByPerson[p], Measured()["B0 gated"].ProfileByPerson[p])) + " |");
            Record("2b", moved.ToString());

            Assert.AreEqual(16060, Measured()["A standing"].BatchDecisions, "A is the shipped morning, unchanged by S1.5");
        }

        // ---- 3 ----

        [Test, Timeout(3600000)]
        public void E3_TheSamePersonWithAndWithoutTheNight()
        {
            var culprits = new[] { ("daniel_ate_it", "daniel"), ("mara_ate_it", "mara"), ("daniel_hid_it", "daniel"), ("elena_fed_mara", "elena") };
            var sb = new StringBuilder();
            sb.AppendLine("## 3. The same person, with and without the night");
            sb.AppendLine();
            sb.AppendLine("The S1.1 measure: behaviour with the night against without it, against two same-condition pools (seeds 1 to 20 and 21 to 40). Above the noise means more than 1.5 times the larger noise.");
            sb.AppendLine();
            sb.AppendLine("| Condition | Who | Mode | Night vs no night | No night vs no night | Night vs night | Effect / noise | Above |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            foreach (var (variant, who) in culprits)
            foreach (var (label, mode) in Modes.Where(m => m.Mode != DispositionMode.Gated))
            {
                var (effect, c, t) = S15.NightEffect(S15.Mode(_content, mode), variant, who, 1);
                var noise = Math.Max(c, t);
                sb.AppendLine("| " + variant + " | " + who + " | " + label + " | " + S15.F(effect) + " | " + S15.F(c) + " | " + S15.F(t) + " | " +
                              (noise == 0 ? "n/a" : (effect / noise).ToString("0.0")) + " | " + (effect > noise * 1.5 ? "yes" : "no") + " |");
            }
            Record("3", sb.ToString());
        }

        // ---- 4 ----

        [Test, Timeout(3600000)]
        public void E4_RemovingACircumstance_NobodysDistressCanBeSeen()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 4. Removing a circumstance: nobody's distress can be seen");
            sb.AppendLine();
            sb.AppendLine("Seeds 1 to 10. `visible_distress` set out of reach, so nobody ever sees anybody go to pieces or come right.");
            sb.AppendLine();
            sb.AppendLine("| Mode | World | Mornings | Distress seen | `look_after` raised | ... per decision | ... unsupported | ... with no history behind it | ... on history alone | Sittings | ... for `look_after` |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|");
            var counts = new Dictionary<string, S15.WorldCounts>();
            foreach (var (label, mode) in Modes.Where(m => m.Mode != DispositionMode.Gated))
            foreach (var (world, content) in new[] { ("as written", S15.Mode(_content, mode)), ("distress never seen", S15.DistressNeverShows(S15.Mode(_content, mode))) })
            {
                var w = S15.Count(content, _variants, 1, AuditSeeds);
                counts[label + "/" + world] = w;
                sb.AppendLine("| " + label + " | " + world + " | " + w.Mornings + " | " + w.ShowDistress + " | " + w.LookAfterRaised + " | " +
                              (w.LookAfterRaised / (double)Math.Max(1, w.Decisions)).ToString("0.00") + " | " + w.LookAfterUnsupported + " | " +
                              w.LookAfterWithoutHistory + " | " + w.LookAfterOnHistoryOnly + " | " + w.Comfort + " | " + w.ComfortForLookAfter + " |");
            }
            sb.AppendLine();
            var aw = counts["A standing/as written"]; var ar = counts["A standing/distress never seen"];
            var bw = counts["B respond/as written"]; var br = counts["B respond/distress never seen"];
            sb.AppendLine("Sittings left when distress cannot be seen: A " + ar.Comfort + " of " + aw.Comfort + " (" + S15.P(ar.Comfort / (double)Math.Max(1, aw.Comfort)) +
                          "), B " + br.Comfort + " of " + bw.Comfort + " (" + S15.P(br.Comfort / (double)Math.Max(1, bw.Comfort)) + ").");
            Record("4", sb.ToString());

            Assert.AreEqual(0, ar.ShowDistress + br.ShowDistress, "the circumstance was removed");
            Assert.AreEqual(0, br.LookAfterUnsupported, "under B, looking after somebody always stands on something that happened");
            Assert.AreEqual(ar.PeoplePresentAtDecisions, ar.LookAfterRaised, "under A it is raised about everybody present at every decision, whatever happens");
        }

        // ---- 5 ----

        [Test, Timeout(3600000)]
        public void E5_RemovingACircumstance_NothingIsMissing()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 5. Removing a circumstance: nothing is missing");
            sb.AppendLine();
            sb.AppendLine("Seeds 1 to 10. The opening count finds enough, so nobody has any reason this morning to wonder what happened to the food. The night is unchanged.");
            sb.AppendLine();
            sb.AppendLine("| Mode | World | `find_out` raised | Mean urgency | ... unsupported | ... with nothing about now behind it | ... with nothing but traits and values | Choices led by `find_out` | Rooms searched |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|");
            var counts = new Dictionary<string, S15.WorldCounts>();
            foreach (var (label, mode) in Modes.Where(m => m.Mode != DispositionMode.Gated))
            foreach (var (world, content) in new[] { ("as written", S15.Mode(_content, mode)), ("nothing missing", S15.NothingMissing(S15.Mode(_content, mode))) })
            {
                var w = S15.Count(content, _variants, 1, AuditSeeds);
                counts[label + "/" + world] = w;
                sb.AppendLine("| " + label + " | " + world + " | " + w.FindOutRaised + " | " + (w.FindOutUrgency / Math.Max(1, w.FindOutRaised)).ToString("0.00") + " | " +
                              w.FindOutUnsupported + " | " + w.FindOutWithNothingNowBehindIt + " | " + w.FindOutWithNeitherCircumstanceNorAuthored + " | " + w.ForFindOut + " | " + w.Searches + " |");
            }
            Record("5", sb.ToString());

            Assert.AreEqual(0, counts["B respond/nothing missing"].FindOutWithNeitherCircumstanceNorAuthored, "under B, wanting to find out needs something behind it other than who you are");
        }

        // ---- 6 ----

        [Test, Timeout(3600000)]
        public void E6_Food()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 6. Food");
            sb.AppendLine();
            sb.AppendLine("| Mode | Circumstance | Mornings | Meals | By person |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var (label, mode) in Modes.Where(m => m.Mode != DispositionMode.Gated))
            foreach (var (world, content) in new[]
                     {
                         ("as written", S15.Mode(_content, mode)),
                         ("plenty, count not short", S13DiagnosisTests.Plenty(S15.Mode(_content, mode), 10, countComesUpShort: false))
                     })
            {
                var w = S15.Count(content, _variants, 1, AuditSeeds);
                sb.AppendLine("| " + label + " | " + world + " | " + w.Mornings + " | " + w.Meals + " | " +
                              string.Join(", ", S15.People.Select(p => p + " " + (w.MealsBy.TryGetValue(p, out var n) ? n : 0))) + " |");
            }
            Record("6", sb.ToString());
        }

        // ---- 7 ----

        [Test]
        public void E7_WithNothingHappening()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 7. With nothing happening");
            sb.AppendLine();
            sb.AppendLine("Each person as written, in a kitchen with the other three, nothing having happened, not hungry.");
            sb.AppendLine();
            sb.AppendLine("| Mode | Who | Wants raised | Does |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var (label, mode) in Modes)
            foreach (var (who, wants, choice) in S15.NothingHappening(S15.Mode(_content, mode)))
                sb.AppendLine("| " + label + " | " + who + " | " + (wants.Count == 0 ? "nothing" : string.Join("; ", wants.Select(w => w.Key + " " + w.Urgency.ToString("0.00")))) + " | " + choice + " |");
            Record("7", sb.ToString());

            foreach (var (who, wants, _) in S15.NothingHappening(S15.Mode(_content, DispositionMode.Respond)))
                Assert.IsTrue(wants.All(w => MotivationSources.Of(w).Authored > 0.0 || MotivationSources.Of(w).Grounded > 0.0),
                    who + " wants something under B on traits and values alone");
        }

        // ---- 8 ----

        [Test]
        public void E8_OneWantUnderBTracedBackToWhatHappened()
        {
            var content = S15.Mode(_content, DispositionMode.Respond);
            var run = Scenario001.Prepare(content, "daniel_ate_it", 1);
            string found = null;
            run.Morning.Decided = m =>
            {
                if (found != null || m.CharacterId != "elena") return;
                var want = m.Motives.FirstOrDefault(x => x.Name == "keep_peace" && x.Terms.Any(t => t.Description.Contains("in response to")));
                if (want == null) return;
                found = "Minute " + m.Minute + ", Elena, chose " + m.Decision.Chosen + ":" + Environment.NewLine + Environment.NewLine +
                        "```" + Environment.NewLine + run.Trace.Why(want.TraceId) + Environment.NewLine + "```";
            };
            run.Morning.Run(content.Morning.Minutes);
            Record("8", "## 8. One want under B, traced" + Environment.NewLine + Environment.NewLine + (found ?? "none found") + Environment.NewLine);
            Assert.IsNotNull(found);
            StringAssert.Contains("Event", found);
        }
    }
}
