using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The S1.5 held-out predictions, committed in
    /// Docs/slices/S1.5/held-out-predictions.md (c8f788e) before any code for the
    /// alternative existed, checked here exactly as written. The held-out case is
    /// `leo_ate_it` on seeds 101 to 140, which no other test runs.
    /// </summary>
    public class S15HeldOutTests
    {
        const string HeldOut = "leo_ate_it";
        const ulong First = 101;

        static Scenario001Content _content;
        static S15Measured _a, _b;
        static readonly Dictionary<string, S15.WorldCounts> _worlds = new Dictionary<string, S15.WorldCounts>(StringComparer.Ordinal);
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.5 held-out results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S15HeldOutTests`. Predictions in `held-out-predictions.md`, committed first (`c8f788e`). `" + HeldOut + "`, decisions from seeds 101 to 120, behaviour and circumstance removal from seeds 101 to 140. **A** shipped, **B** `respond`.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine("- " + r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.5");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "held-out-results.md"), sb.ToString());
        }

        static bool Record(string id, bool held, string detail)
        {
            _results[id] = "**" + id + "** " + (held ? "held" : "MISSED") + ". " + detail;
            TestContext.WriteLine(_results[id]);
            return held;
        }

        static S15Measured A => _a ?? (_a = S15.Measure(S15.Mode(_content, DispositionMode.Standing), "A", new[] { HeldOut }, 20, 40, First));
        static S15Measured B => _b ?? (_b = S15.Measure(S15.Mode(_content, DispositionMode.Respond), "B", new[] { HeldOut }, 20, 40, First));

        static S15.WorldCounts World(string mode, bool distressSeen)
        {
            var key = mode + "/" + distressSeen;
            if (_worlds.TryGetValue(key, out var w)) return w;
            var content = S15.Mode(_content, mode);
            if (!distressSeen) content = S15.DistressNeverShows(content);
            return _worlds[key] = S15.Count(content, new[] { HeldOut }, First, 40);
        }

        [Test, Timeout(3600000)]
        public void P1_UnderBNothingIsWantedOnTraitsAndValuesAlone()
        {
            var held = B.Sources.OnTraitsAndValuesAlone == 0 && A.Sources.Share(Support.Unsupported) >= 0.30;
            Record("P1", held, "Under B, wants raised on traits and values alone: " + B.Sources.OnTraitsAndValuesAlone + " of " + B.Sources.Raised +
                               "; unsupported (all carried by an authored belief): " + S15.P(B.Sources.Share(Support.Unsupported)) +
                               ". Under A, unsupported: " + S15.P(A.Sources.Share(Support.Unsupported)) + ".");
            Assert.IsTrue(held, "P1 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P2_UnderBWantsRestOnWhatHappened()
        {
            double Traced(S15Measured m) => m.Sources.WantsTraced / (double)Math.Max(1, m.Sources.Raised);
            var held = Traced(B) >= 0.90 && Traced(A) <= 0.70;
            Record("P2", held, "Wants resting on at least one term that leads back to something that happened, or the body: B " + S15.P(Traced(B)) + ", A " + S15.P(Traced(A)) + ".");
            Assert.IsTrue(held, "P2 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P3_WithNoDistressToSeeLookingAfterSomebodyStandsOnHistoryUnderB()
        {
            var b = World(DispositionMode.Respond, false);
            var a = World(DispositionMode.Standing, false);
            var held = b.LookAfterWithoutHistory == 0 && a.LookAfterRaised == a.PeoplePresentAtDecisions;
            Record("P3", held, "Distress never seen. Under B, `look_after` raised " + b.LookAfterRaised + " times, " + b.LookAfterWithoutHistory +
                               " with no ledger history about that person (" + b.LookAfterUnsupported + " unsupported). Under A, raised " + a.LookAfterRaised +
                               " times against " + a.PeoplePresentAtDecisions + " people present at decisions.");
            Assert.AreEqual(0, a.ShowDistress + b.ShowDistress, "the circumstance was removed");
            // RECORDED MISS, first run. The prediction took seeing somebody go to
            // pieces to be the only thing today that could make a person concerned
            // about another. It is not: a few concerns come from other things seen
            // or heard. None is unsupported, which is the part that is structural.
            Assert.AreEqual(0, b.LookAfterUnsupported, "under B nothing about looking after somebody is unsupported");
            Assert.Greater(b.LookAfterWithoutHistory, 0, "RECORDED MISS: turn round if every such want comes to stand on history");
        }

        [Test, Timeout(3600000)]
        public void P4_WithNoDistressToSeeSittingsFallFurtherUnderB()
        {
            var bSeen = World(DispositionMode.Respond, true); var bNot = World(DispositionMode.Respond, false);
            var aSeen = World(DispositionMode.Standing, true); var aNot = World(DispositionMode.Standing, false);
            var held = bNot.Comfort <= 0.5 * bSeen.Comfort && aNot.Comfort > 0.5 * aSeen.Comfort;
            Record("P4", held, "Sittings with distress seen and never seen: B " + bSeen.Comfort + " and " + bNot.Comfort + "; A " + aSeen.Comfort + " and " + aNot.Comfort + ".");
            // RECORDED MISS, first run, on A's side. B's sittings fell as predicted;
            // A's fell below half as well, so the standing part of wanting to look
            // after somebody was carrying fewer sittings than predicted.
            Assert.LessOrEqual(bNot.Comfort, 0.5 * bSeen.Comfort, "the half of P4 that held");
            Assert.LessOrEqual(aNot.Comfort, 0.5 * aSeen.Comfort, "RECORDED MISS: turn round if A keeps more than half its sittings without distress to see");
        }

        [Test, Timeout(3600000)]
        public void P5_LessStandingStillUnderB()
        {
            var held = Record("P5", B.WaitShare < A.WaitShare, "Standing still, share of choices: B " + S15.P(B.WaitShare) + ", A " + S15.P(A.WaitShare) + ".");
            Assert.IsTrue(held, "P5 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P6_MoreTiesUnderB()
        {
            var held = Record("P6", B.RealTies > A.RealTies, "Ties between genuinely different actions: B " + S15.P(B.RealTies) + ", A " + S15.P(A.RealTies) + ".");
            // RECORDED MISS, first run. Nobody was ever left wanting nothing (hunger
            // and the supplies are always there), so options did not tie at zero.
            Assert.IsFalse(held, "RECORDED MISS: turn round if ties become more frequent under B");
        }

        [Test, Timeout(3600000)]
        public void P7_PeopleDoNotCollapseTogetherUnderB()
        {
            var held = B.ClosestPair > A.ClosestPair && B.MeanGap >= A.MeanGap - 0.05;
            Record("P7", held, "Closest pair: B " + S15.F(B.ClosestPair) + " (" + B.ClosestWho + "), A " + S15.F(A.ClosestPair) + " (" + A.ClosestWho +
                               "). Mean different-person gap: B " + S15.F(B.MeanGap) + ", A " + S15.F(A.MeanGap) + ".");
            // RECORDED MISS, first run. The closest pair did move apart; the mean
            // gap fell by more than the 0.05 allowed.
            Assert.Greater(B.ClosestPair, A.ClosestPair, "the half of P7 that held");
            Assert.Less(B.MeanGap, A.MeanGap - 0.05, "RECORDED MISS: turn round if people under B stay within 0.05 of A");
        }

        [Test, Timeout(3600000)]
        public void P8_NobodyEatsAndTheWalksToTheFoodDoNotGoAway()
        {
            int GivenUp(S15Measured m) => m.Audit.CommitmentsByWant.TryGetValue("get_food: " + Commitment.NotWorthIt, out var n) ? n : 0;
            var held = A.Meals == 0 && B.Meals == 0 && GivenUp(B) >= GivenUp(A);
            Record("P8", held, "Meals: A " + A.Meals + ", B " + B.Meals + ". Walks to the food given up on arrival (seeds 101 to 120): A " + GivenUp(A) + ", B " + GivenUp(B) + ".");
            // RECORDED MISS, first run. Under B somebody does eat: with less standing
            // in its way, eating sometimes comes out ahead of its price.
            Assert.GreaterOrEqual(GivenUp(B), GivenUp(A), "the half of P8 that held");
            Assert.Greater(B.Meals, 0, "RECORDED MISS: turn round if nobody eats under B");
        }

        [Test, Timeout(3600000)]
        public void P9_LeosNightStandsOutMoreUnderB()
        {
            var (ea, ca, ta) = S15.NightEffect(S15.Mode(_content, DispositionMode.Standing), HeldOut, "leo", First);
            var (eb, cb, tb) = S15.NightEffect(S15.Mode(_content, DispositionMode.Respond), HeldOut, "leo", First);
            var ra = ea / Math.Max(1e-9, Math.Max(ca, ta));
            var rb = eb / Math.Max(1e-9, Math.Max(cb, tb));
            Record("P9", rb > ra, "Leo, night against no night, over the larger noise: B " + S15.F(eb) + " / " + S15.F(Math.Max(cb, tb)) + " = " + rb.ToString("0.0") +
                                  "; A " + S15.F(ea) + " / " + S15.F(Math.Max(ca, ta)) + " = " + ra.ToString("0.0") + ".");
            Assert.Greater(rb, ra, "P9 held when first run");
        }
    }
}
