using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// Written after the first S1.5 run, to explain a result rather than to test a
    /// prediction: under B people walk far more and pace. This takes the walks
    /// apart. Writes Docs/slices/S1.5/walks.md; nothing here is asserted about B.
    /// </summary>
    public class S15PacingTests
    {
        static string Lead(Decision d)
        {
            var l = d.Leading;
            return l == null ? "nothing" : l.Name;
        }

        [Test, Timeout(3600000)]
        public void WhatTheWalksAreForAndWhatTheyTurnInto()
        {
            var content = Scenario001Content.Load(TestPaths.DataRoot);
            var variants = content.Morning.Variants.Select(v => v.Id).ToList();
            var sb = new StringBuilder();
            sb.AppendLine("# S1.5: what the walks are for, and what they turn into");
            sb.AppendLine();
            sb.AppendLine("Generated by `S15PacingTests`, written after the first experiment run to explain why people walk and pace far more under B. Design conditions, seeds 1 to 10.");
            sb.AppendLine();

            foreach (var (label, mode) in new[] { ("A standing", DispositionMode.Standing), ("B respond", DispositionMode.Respond), ("B0 gated", DispositionMode.Gated) })
            {
                var c = S15.Mode(content, mode);
                var pairs = new Dictionary<string, int>(StringComparer.Ordinal);
                var walksBy = new Dictionary<string, int>(StringComparer.Ordinal);
                var walks = 0;
                var ledByUnaffordableFood = 0;
                foreach (var v in variants)
                for (ulong seed = 1; seed <= 10; seed++)
                {
                    var run = Scenario001.Prepare(c, v, seed);
                    var mine = new Dictionary<string, List<DecisionMoment>>(StringComparer.Ordinal);
                    run.Morning.Decided = m =>
                    {
                        if (!mine.TryGetValue(m.CharacterId, out var list)) mine[m.CharacterId] = list = new List<DecisionMoment>();
                        list.Add(m);
                    };
                    run.Morning.Run(c.Morning.Minutes);

                    foreach (var list in mine.Values)
                    for (var i = 0; i < list.Count; i++)
                    {
                        var d = list[i].Decision;
                        if (d.Chosen.Kind != ActionKind.GoTo) continue;
                        walks++;
                        var key = Lead(d);
                        walksBy.TryGetValue(key, out var w);
                        walksBy[key] = w + 1;

                        if (i + 1 >= list.Count || list[i + 1].Why != "finished") continue;
                        var next = list[i + 1].Decision;
                        var outcome = key + " -> " + (next.Holding == null ? "no intention" : next.Commitment) + " -> " + next.Chosen.KindName + " for " + Lead(next);
                        pairs.TryGetValue(outcome, out var n);
                        pairs[outcome] = n + 1;
                        if (key == "get_food" && next.Commitment == Commitment.NotWorthIt) ledByUnaffordableFood++;
                    }
                }

                sb.AppendLine("## " + label);
                sb.AppendLine();
                sb.AppendLine(walks + " walks. What each was for: " + string.Join(", ", walksBy.OrderByDescending(k => k.Value).Select(k => k.Key + " " + k.Value)) + ".");
                sb.AppendLine();
                sb.AppendLine("Walks for food that ended with eating priced out on arrival: " + ledByUnaffordableFood + ".");
                sb.AppendLine();
                sb.AppendLine("| Walk for -> what became of the intention on arrival -> next act, for | Count |");
                sb.AppendLine("|---|---|");
                foreach (var p in pairs.OrderByDescending(k => k.Value).Take(12))
                    sb.AppendLine("| " + p.Key + " | " + p.Value + " |");
                sb.AppendLine();
            }

            // The worst pacing under B, as it happened.
            var worst = Scenario001.Prepare(S15.Mode(content, DispositionMode.Respond), "daniel_ate_it", 9);
            var lines = new List<string>();
            worst.Morning.Decided = m =>
            {
                if (m.CharacterId != "leo") return;
                var d = m.Decision;
                lines.Add("| " + m.Minute + " | " + m.Percept.Room.Id + " | " + d.Chosen + " | " + Lead(d) + " | " +
                          (d.Holding == null ? "" : d.Holding.MotiveName + ": " + d.Commitment) + " | " +
                          string.Join("; ", m.Motives.Where(x => x.Urgency >= 0.1).Select(x => x.Key + " " + x.Urgency.ToString("0.00"))) + " |");
            };
            worst.Morning.Run(content.Morning.Minutes);
            sb.AppendLine("## Leo under B, `daniel_ate_it` seed 9 (the worst pacing in the batch)");
            sb.AppendLine();
            sb.AppendLine("| Minute | Room | Chose | For | Intention brought in | Wants at 0.10 or more |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var l in lines) sb.AppendLine(l);

            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.5");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "walks.md"), sb.ToString());
            TestContext.WriteLine(sb.ToString());
        }
    }
}
