using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.6 diagnosis: why people under B walk to ends they then find not worth
    /// pursuing, taken apart before anything about deciding or memory is changed.
    /// Everything here is measured on `respond` (B), where the loop is plain; the
    /// shipped rules are untouched. Writes Docs/slices/S1.6/diagnosis-current.md.
    /// </summary>
    public class S16DiagnosisTests
    {
        const int Seeds = 10;

        static Scenario001Content _content;
        static Scenario001Content _b;
        static IReadOnlyList<string> _variants;
        static List<S16.WalkRecord> _walks;
        static readonly SortedDictionary<string, string> _sections = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load()
        {
            _content = Scenario001Content.Load(TestPaths.DataRoot);
            _b = S15.Mode(_content, DispositionMode.Respond);
            _variants = _content.Morning.Variants.Select(v => v.Id).ToList();
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.6 diagnosis: walking to an end already found not worth it");
            sb.AppendLine();
            sb.AppendLine("Generated by `S16DiagnosisTests`. Traits and values as dispositions (`respond`, B), where the loop S1.5 found is plain; the shipped rules are not touched. The five design conditions, seeds 1 to " + Seeds + ".");
            sb.AppendLine();
            sb.AppendLine("**Foreseen** means: at the moment somebody set out, the best thing they could have done for the walk's want at the destination, weighed exactly as the deliberator weighs it on arrival, on the destination as they could imagine it from what they knew. Nobody is imagined there unless the want is about somebody; food kept there is imagined within reach. That is the destination at its most favourable for the want, so an end that is not worth it even then could not have been worth walking to.");
            sb.AppendLine();
            foreach (var s in _sections.Values) sb.AppendLine(s);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.6");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "diagnosis-current.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _sections[key] = text;
            TestContext.WriteLine(text);
        }

        static List<S16.WalkRecord> Walks() => _walks ?? (_walks = S16.Walks(_b, _variants, 1, Seeds));

        // ---- 1 ----

        [Test, Timeout(1800000)]
        public void D1_TheMemoryOfTheOpeningCountNeverFades()
        {
            var opening = _content.Morning.Opening;
            var sb = new StringBuilder();
            sb.AppendLine("## 1. The memory of the opening count");
            sb.AppendLine();
            sb.AppendLine("`find_out` is carried by the memory of the count coming up short (concern and threat about `missing_can`). A memory presses at salience x freshness, and freshness halves over the recall half life (" + _content.Rules.Deciding.RecallHalfLife + " minutes) from the minute the event happened. The opening event `" + opening.Id + "` is scripted and carries minute " + opening.Minute + ".");
            sb.AppendLine();

            // Mean find_out per person per ten minutes.
            sb.AppendLine("Mean `find_out` urgency per person, by ten minutes of the morning (B, seeds 1 to " + Seeds + "):");
            sb.AppendLine();
            sb.AppendLine(S16.Timeline(_b, _variants, 1, Seeds, "find_out"));

            // Every memory of today that carries no minute, and what the strongest
            // memory term behind find_out drew on, with its freshness at the end.
            var timeless = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal);
            var freshness = new Dictionary<string, List<double>>(StringComparer.Ordinal);
            var restsOnTimeless = new Dictionary<string, int>(StringComparer.Ordinal);
            var restsOnTimed = new Dictionary<string, int>(StringComparer.Ordinal);
            var drewOn = new Dictionary<string, int>(StringComparer.Ordinal);
            var wantsSeen = 0;
            foreach (var p in S16.People) { freshness[p] = new List<double>(); timeless[p] = new Dictionary<string, string>(StringComparer.Ordinal); restsOnTimeless[p] = 0; restsOnTimed[p] = 0; }

            foreach (var v in _variants)
            for (ulong seed = 1; seed <= Seeds; seed++)
            {
                var run = Scenario001.Prepare(_b, v, seed);
                run.Morning.Decided = m =>
                {
                    foreach (var x in m.Mind.Experiences.Where(x => x.Day == _content.Morning.Day && x.Minute < 0))
                        timeless[m.CharacterId][x.EventId] = x.Meaning + " (salience " + x.Salience.ToString("0.00") + ")";

                    var want = m.Motives.FirstOrDefault(x => x.Name == "find_out");
                    if (want == null) return;
                    wantsSeen++;
                    var memoryTerms = want.Terms.Where(t => t.Kind == ScalerKind.Memory && t.Amount > 0.0).ToList();
                    if (memoryTerms.Count == 0) return;
                    var strongest = memoryTerms.OrderByDescending(t => t.Amount).First();
                    var kept = strongest.Drew.Select(id => m.Mind.Experiences.FirstOrDefault(x => x.TraceId == id)).FirstOrDefault(x => x != null);
                    if (kept == null) return;

                    var e = run.Result.Events.FirstOrDefault(x => x.Id == kept.EventId);
                    var key = (e == null ? kept.EventId + " (scripted, minute " + kept.Minute + ")" : e.Action + " (this morning)") + ", read as " + kept.Meaning;
                    drewOn.TryGetValue(key, out var n); drewOn[key] = n + 1;
                    if (kept.Minute < 0) restsOnTimeless[m.CharacterId]++; else restsOnTimed[m.CharacterId]++;

                    if (m.Minute < _content.Morning.Minutes - 10 || kept.Minute >= 0 || kept.Salience <= 0.0) return;
                    freshness[m.CharacterId].Add(strongest.Level / kept.Salience);
                };
                run.Morning.Run(_content.Morning.Minutes);
            }

            sb.AppendLine("Memories of today that carry no minute, by person (every one is scripted: the three day-4 events of the backstory and the opening):");
            sb.AppendLine();
            sb.AppendLine("| Who | Event: what it was kept as |");
            sb.AppendLine("|---|---|");
            foreach (var p in S16.People)
                sb.AppendLine("| " + p + " | " + (timeless[p].Count == 0 ? "none" : string.Join("; ", timeless[p].OrderBy(k => k.Key, StringComparer.Ordinal).Select(k => "`" + k.Key + "` " + k.Value))) + " |");
            sb.AppendLine();
            sb.AppendLine("What the strongest memory term behind `find_out` drew on, over " + wantsSeen + " wants raised: " +
                          string.Join("; ", drewOn.OrderByDescending(k => k.Value).Select(k => k.Key + " " + k.Value)) + ".");
            sb.AppendLine();
            sb.AppendLine("| Who | `find_out` resting on a memory with no minute | ... on a memory of this morning | Freshness of the no-minute memory in the last ten minutes (level / salience) |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var p in S16.People)
                sb.AppendLine("| " + p + " | " + restsOnTimeless[p] + " | " + restsOnTimed[p] + " | " +
                              (freshness[p].Count == 0 ? "-" : freshness[p].Min().ToString("0.000") + " to " + freshness[p].Max().ToString("0.000") + " over " + freshness[p].Count + " decisions") + " |");
            sb.AppendLine();

            // Leo's find_out at the end of the worst morning, walked back.
            var worst = Scenario001.Prepare(_b, "daniel_ate_it", 9);
            string why = null;
            worst.Morning.Decided = m =>
            {
                if (m.CharacterId != "leo" || m.Minute < 85) return;
                var want = m.Motives.FirstOrDefault(x => x.Name == "find_out");
                if (want != null && why == null) why = "Leo, minute " + m.Minute + ":" + Environment.NewLine + Environment.NewLine + "```" + Environment.NewLine + worst.Trace.Why(want.TraceId) + "```";
            };
            worst.Morning.Run(_content.Morning.Minutes);
            sb.AppendLine("Leo's `find_out` at the end of `daniel_ate_it` seed 9, walked back:");
            sb.AppendLine();
            sb.AppendLine(why ?? "not raised");
            Record("1", sb.ToString());

            Assert.AreEqual(-1, opening.Minute, "the opening event carries no minute");
            foreach (var p in S16.People)
            {
                Assert.IsTrue(timeless[p].ContainsKey(opening.Id), p + " remembers the opening with no minute");
                Assert.IsTrue(freshness[p].All(f => Math.Abs(f - 1.0) < 1e-9), p + ": a memory with no minute is still fully fresh at the end of the morning");
            }
            Assert.Greater(S16.People.Sum(p => freshness[p].Count), 0, "somebody's find_out rests on a memory with no minute at the end of the morning");
        }

        // ---- 2 ----

        [Test, Timeout(1800000)]
        public void D2_WhetherTheWalkerCouldHaveForeseenTheLapse()
        {
            var walks = Walks();
            var arrived = walks.Where(w => w.Arrived).ToList();
            var lapsedNotWorthIt = arrived.Where(w => w.Commitment == Commitment.NotWorthIt).ToList();
            var held = arrived.Where(w => w.Held).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("## 2. Could the walker have foreseen the lapse?");
            sb.AppendLine();
            sb.AppendLine(walks.Count + " walks set out on for a want. " + arrived.Count + " arrived and decided with the intention carried in (the rest were stopped on the way or the morning ended). What became of the intention on arrival, against what the walker could have foreseen when they set out:");
            sb.AppendLine();
            sb.AppendLine("| On arrival | Walks | Foreseen worth doing | Foreseen not worth doing | Foreseen: nothing there serves it |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var group in arrived.GroupBy(w => w.Commitment).OrderBy(g => g.Key, StringComparer.Ordinal))
                sb.AppendLine("| " + group.Key + " | " + group.Count() + " | " + group.Count(w => w.Foreseen.WorthIt) + " | " +
                              group.Count(w => w.Foreseen.Possible && !w.Foreseen.WorthIt) + " | " + group.Count(w => !w.Foreseen.Possible) + " |");
            sb.AppendLine();

            var foreseeable = lapsedNotWorthIt.Where(w => !w.Foreseen.WorthIt).ToList();
            var surprises = lapsedNotWorthIt.Where(w => w.Foreseen.WorthIt).ToList();
            sb.AppendLine("**Given up as not worth what it costs there: " + lapsedNotWorthIt.Count + ".** Foreseeable at departure: " + foreseeable.Count + " (" + S16.P(foreseeable.Count, lapsedNotWorthIt.Count) + "). " +
                          "Not foreseeable: " + surprises.Count + ", of which somebody was in the room on arrival in " + surprises.Count(w => w.PresentOnArrival > 0) +
                          ", and the want was lower on arrival than at departure in " + surprises.Count(w => w.WantUrgencyOnArrival < w.WantUrgencyAtDeparture - 1e-9) + ".");
            sb.AppendLine();
            sb.AppendLine("**Held: " + held.Count + ".** Foreseen worth doing: " + held.Count(w => w.Foreseen.WorthIt) + " (" + S16.P(held.Count(w => w.Foreseen.WorthIt), held.Count) + "). " +
                          "Foreseen not worth doing but held anyway: " + held.Count(w => !w.Foreseen.WorthIt) + ", of which somebody was in the room on arrival in " + held.Count(w => !w.Foreseen.WorthIt && w.PresentOnArrival > 0) + ".");
            sb.AppendLine();

            sb.AppendLine("By want, walks that arrived:");
            sb.AppendLine();
            sb.AppendLine("| Want | Walks | Held | Given up | ... foreseeable | Mean worth of the walk to the want | Mean foreseen worth of the end |");
            sb.AppendLine("|---|---|---|---|---|---|---|");
            foreach (var group in arrived.GroupBy(w => w.Want.Split(':')[0]).OrderByDescending(g => g.Count()))
            {
                var lapsed = group.Where(w => w.Lapsed).ToList();
                var possible = group.Where(w => w.Foreseen.Possible).ToList();
                sb.AppendLine("| `" + group.Key + "` | " + group.Count() + " | " + group.Count(w => w.Held) + " | " + lapsed.Count + " | " +
                              lapsed.Count(w => !w.Foreseen.WorthIt) + " | " + S16.F(group.Average(w => w.WalkWorth)) + " | " +
                              (possible.Count == 0 ? "-" : S16.F(possible.Average(w => w.Foreseen.Score))) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("Walks whose end was foreseeably not worth doing, as a share of every walk set out on: " + S16.P(walks.Count(w => !w.Foreseen.WorthIt), walks.Count) + " (" + walks.Count(w => !w.Foreseen.WorthIt) + " of " + walks.Count + ").");
            sb.AppendLine();
            sb.AppendLine("Where the foreseeably pointless walks went, by want and destination:");
            sb.AppendLine();
            sb.AppendLine("| Want | To | Walks | Foreseen best there |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var group in walks.Where(w => !w.Foreseen.WorthIt).GroupBy(w => w.Want.Split(':')[0] + " -> " + w.To).OrderByDescending(g => g.Count()).Take(10))
            {
                var sample = group.First();
                sb.AppendLine("| `" + group.Key.Split(' ')[0] + "` | " + sample.To + " | " + group.Count() + " | " + string.Join("; ", group.Select(w => w.Foreseen.Best?.Option.Key ?? "nothing").Distinct().Take(3)) + " |");
            }
            Record("2", sb.ToString());

            Assert.Greater(lapsedNotWorthIt.Count, 0, "the instrument saw the walks S1.5 counted");
        }

        // ---- 3 ----

        [Test]
        public void D3_LeoSettingOutAndArriving()
        {
            var run = Scenario001.Prepare(_b, "daniel_ate_it", 9);
            var sb = new StringBuilder();
            sb.AppendLine("## 3. Leo, `daniel_ate_it` seed 9: setting out at minute 25, arriving at minute 29");
            sb.AppendLine();
            string foresight = null;
            run.Morning.Decided = m =>
            {
                if (m.CharacterId != "leo") return;
                if (m.Minute == 25)
                {
                    sb.AppendLine("**Minute 25, in the " + m.Percept.Room.Id + ", with " + (m.Percept.Present.Count == 0 ? "nobody" : string.Join(", ", m.Percept.Present)) + ":**");
                    sb.AppendLine();
                    sb.AppendLine("```");
                    sb.Append(DecisionTrace.Explain(m.Decision));
                    sb.AppendLine("```");
                    sb.AppendLine();
                    if (m.Decision.Chosen.Kind == ActionKind.GoTo && m.Decision.Forms != null)
                    {
                        var want = m.Motives.First(x => x.Key == m.Decision.Forms.MotiveKey);
                        var f = S16.Foresee(_b, m, want, m.Decision.Chosen.DestinationRoomId);
                        foresight = "What he could have foreseen doing for `" + want.Key + "` in the " + f.Destination + ", from what he knew at minute 25: **" + f + "**" +
                                    (f.Best == null ? "" : ". Against it: " + string.Join("; ", f.Best.Prices)) + ".";
                        sb.AppendLine(foresight);
                        sb.AppendLine();
                    }
                }
                if (m.Minute == 29)
                {
                    sb.AppendLine("**Minute 29, in the " + m.Percept.Room.Id + ", with " + (m.Percept.Present.Count == 0 ? "nobody" : string.Join(", ", m.Percept.Present)) + ":**");
                    sb.AppendLine();
                    sb.AppendLine("```");
                    sb.Append(DecisionTrace.Explain(m.Decision));
                    sb.AppendLine("```");
                    sb.AppendLine();
                }
            };
            run.Morning.Run(40);
            sb.AppendLine("Every term in the price of going through the back room is a trait or value of Leo's own, or the fact that the room is somebody else's, which the house tells him. Nothing in it needed the walk to be known.");
            Record("3", sb.ToString());
            Assert.IsNotNull(foresight, "Leo set out from the kitchen at minute 25 on this seed, as walks.md recorded");
        }

        // ---- 4 ----

        [Test, Timeout(1800000)]
        public void D4_WhatAWalkGivenUpLeavesBehind()
        {
            var lapsed = Walks().Where(w => w.Commitment == Commitment.NotWorthIt).ToList();
            var meanings = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (var w in lapsed)
            foreach (var m in (w.ExperienceMeanings ?? "").Split(new[] { ", " }, StringSplitOptions.RemoveEmptyEntries))
            {
                meanings.TryGetValue(m, out var n); meanings[m] = n + 1;
            }

            var sb = new StringBuilder();
            sb.AppendLine("## 4. What a walk given up leaves behind");
            sb.AppendLine();
            sb.AppendLine("For the " + lapsed.Count + " walks given up on arrival as not worth what it costs there, what the walker had by the time they decided that they did not have when they set out:");
            sb.AppendLine();
            sb.AppendLine("| Left behind | Total | Walks with any |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Experiences (things perceived on the way or on arrival) | " + lapsed.Sum(w => w.ExperiencesGained) + " | " + lapsed.Count(w => w.ExperiencesGained > 0) + " |");
            sb.AppendLine("| Beliefs moved | " + lapsed.Sum(w => w.BeliefsMoved) + " | " + lapsed.Count(w => w.BeliefsMoved > 0) + " |");
            sb.AppendLine("| Outcomes recorded (S1.3: only for wants that read a need) | " + lapsed.Sum(w => w.OutcomesRecorded) + " | " + lapsed.Count(w => w.OutcomesRecorded > 0) + " |");
            sb.AppendLine();
            sb.AppendLine("What the experiences meant to them: " + (meanings.Count == 0 ? "nothing" : string.Join(", ", meanings.OrderByDescending(k => k.Value).Select(k => k.Key + " " + k.Value))) + ".");
            sb.AppendLine();
            sb.AppendLine("The want the walk was for, on arrival against departure: mean change " + S16.F(lapsed.Average(w => w.WantUrgencyOnArrival - w.WantUrgencyAtDeparture)) +
                          ", higher on arrival in " + lapsed.Count(w => w.WantUrgencyOnArrival > w.WantUrgencyAtDeparture + 1e-9) + ", lower in " + lapsed.Count(w => w.WantUrgencyOnArrival < w.WantUrgencyAtDeparture - 1e-9) + ", the same in " + lapsed.Count(w => Math.Abs(w.WantUrgencyOnArrival - w.WantUrgencyAtDeparture) <= 1e-9) + ".");
            sb.AppendLine();
            sb.AppendLine("Nothing that could make the same walk less worth proposing next time is written anywhere the next deliberation reads: the want is raised again from the same state, and the walk is worth what the want is worth.");
            Record("4", sb.ToString());
        }

        // ---- 5 ----

        [Test, Timeout(1800000)]
        public void D5_WhenNothingIsWanted()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 5. When nothing is wanted");
            sb.AppendLine();
            sb.AppendLine("| World | Decisions | With no want at all | ... chose | Led by no want (\"nothing pressing\") | ... chose | ... settled by the seed | ... between |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            foreach (var (label, content) in new[] { ("as written", _b), ("nothing missing", S15.NothingMissing(_b)) })
            {
                var decisions = 0; var none = 0; var unled = 0; var unledAmbiguous = 0;
                var noneChose = new Dictionary<string, int>(StringComparer.Ordinal);
                var unledChose = new Dictionary<string, int>(StringComparer.Ordinal);
                var unledTied = new Dictionary<string, int>(StringComparer.Ordinal);
                foreach (var v in _variants)
                for (ulong seed = 1; seed <= Seeds; seed++)
                {
                    var run = Scenario001.Prepare(content, v, seed);
                    run.Morning.Decided = m =>
                    {
                        decisions++;
                        var kind = m.Decision.Chosen.KindName;
                        if (m.Motives.Count == 0)
                        {
                            none++;
                            noneChose.TryGetValue(kind, out var n); noneChose[kind] = n + 1;
                        }
                        if (m.Decision.Leading == null)
                        {
                            unled++;
                            unledChose.TryGetValue(kind, out var n); unledChose[kind] = n + 1;
                            if (m.Decision.Resolution == Resolution.Ambiguous)
                            {
                                unledAmbiguous++;
                                var tied = string.Join(", ", m.Decision.Tied.Select(t => t.KindName).Distinct().OrderBy(k => k, StringComparer.Ordinal));
                                unledTied.TryGetValue(tied, out var t); unledTied[tied] = t + 1;
                            }
                        }
                    };
                    run.Morning.Run(content.Morning.Minutes);
                }
                sb.AppendLine("| " + label + " | " + decisions + " | " + none + " | " + Kinds(noneChose) + " | " + unled + " | " + Kinds(unledChose) + " | " + unledAmbiguous + " | " + Kinds(unledTied) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("A decision led by no want is one where nothing added to what was chosen: every option was worth nothing or less, and the cheapest won. With every appeal at zero, any act whose price is inside the ambiguity band of standing still ties with it, and the seed decides.");
            Record("5", sb.ToString());
        }

        static string Kinds(Dictionary<string, int> d)
            => d.Count == 0 ? "-" : string.Join(", ", d.OrderByDescending(k => k.Value).Select(k => k.Key + " " + k.Value));
    }
}
