using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.6: the two mechanisms, alone and together, on B, with A and A-with-M1
    /// for reference. Design conditions only. Everything is recorded whichever
    /// way it comes out; the assertions check the mechanisms, never a behavioural
    /// number. Writes Docs/slices/S1.6/experiment-results.md.
    /// </summary>
    public class S16ExperimentTests
    {
        const int AuditSeeds = 10;
        const int BatchSeeds = 40;

        static Scenario001Content _content;
        static IReadOnlyList<string> _variants;
        static Dictionary<string, Scenario001Content> _conditions;
        static Dictionary<string, S15Measured> _measured;
        static Dictionary<string, List<S16.WalkRecord>> _walks;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static IEnumerable<string> Labels => S16.Conditions.Select(c => c.Label);

        [OneTimeSetUp]
        public void Load()
        {
            _content = Scenario001Content.Load(TestPaths.DataRoot);
            _variants = _content.Morning.Variants.Select(v => v.Id).ToList();
            _conditions = S16.Conditions.ToDictionary(c => c.Label, c => c.Make(_content), StringComparer.Ordinal);
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.6 experiment results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S16ExperimentTests`. The five design conditions. **A** is the shipped rules (`standing`). **B** is traits and values as dispositions (`respond`, S1.5). **timed** is M1: the four scripted events of the lived day carry minute 0. **end** is M2: a walk is credited to a want only if something could be done for that want on arrival that would be worth doing (`means: end`). Nothing else differs between conditions.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.6");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "experiment-results.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static Dictionary<string, S15Measured> Measured()
        {
            if (_measured != null) return _measured;
            _measured = new Dictionary<string, S15Measured>(StringComparer.Ordinal);
            foreach (var label in Labels)
                _measured[label] = S15.Measure(_conditions[label], label, _variants, AuditSeeds, BatchSeeds);
            return _measured;
        }

        static Dictionary<string, List<S16.WalkRecord>> Walks()
        {
            if (_walks != null) return _walks;
            _walks = new Dictionary<string, List<S16.WalkRecord>>(StringComparer.Ordinal);
            foreach (var label in Labels) _walks[label] = S16.Walks(_conditions[label], _variants, 1, AuditSeeds);
            return _walks;
        }

        static string Header(string first) => "| " + first + " | " + string.Join(" | ", Labels) + " |" + Environment.NewLine + "|---|" + string.Join("|", Labels.Select(_ => "---")) + "|";
        static string Row(string name, Func<string, string> value) => "| " + name + " | " + string.Join(" | ", Labels.Select(value)) + " |";
        static string RowM(string name, Func<S15Measured, string> value) => Row(name, l => value(Measured()[l]));

        // ---- 1 ----

        [Test, Timeout(3600000)]
        public void E1_WhatPeopleDo()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 1. What people do, and where wants come from");
            sb.AppendLine();
            sb.AppendLine("Behaviour from the S1 batch (seeds 1 to " + BatchSeeds + ", 200 mornings); decisions, walks and decisive rates from the S1.2 audit (seeds 1 to " + AuditSeeds + "); sources from the S1.5 instrument on the same decisions.");
            sb.AppendLine();
            sb.AppendLine(Header("Measure"));
            sb.AppendLine(RowM("Walks completed and followed by a decision (audit)", m => m.Audit.WalksWithAPurpose.ToString()));
            sb.AppendLine(RowM("... followed by something the walk's want did not serve", m => S15.P(m.AbandonedWalks)));
            sb.AppendLine(RowM("Pacing, mean per person per morning (audit)", m => m.MeanPacing.ToString("0.00")));
            sb.AppendLine(RowM("Worst pacing (batch)", m => m.WorstPacing + " (" + m.WorstPacingWho + ")"));
            sb.AppendLine(RowM("Walks to the food given up on arrival (audit)", m => m.Audit.CommitmentsByWant.TryGetValue("get_food: " + Commitment.NotWorthIt, out var n) ? n.ToString() : "0"));
            sb.AppendLine(RowM("Standing still, share of choices (batch)", m => S15.P(m.WaitShare)));
            sb.AppendLine(RowM("Standing still on top (audit)", m => S15.P(m.WaitOnTopShare)));
            sb.AppendLine(RowM("Sitting with somebody, share of choices", m => S15.P(m.SittingShare)));
            foreach (var want in new[] { "look_after", "keep_peace", "guard_supplies", "find_out", "get_food", "restore_standing", "avoid_exposure" })
                sb.AppendLine(RowM("`" + want + "` decisive", m => S15.P(m.Decisive(want))));
            sb.AppendLine(RowM("Different people, mean gap", m => S15.F(m.MeanGap)));
            sb.AppendLine(RowM("Weakest condition, mean gap", m => S15.F(m.WorstConditionMean)));
            sb.AppendLine(RowM("Closest pair", m => S15.F(m.ClosestPair) + " (" + m.ClosestWho + ")"));
            sb.AppendLine(RowM("Ties between genuinely different actions (batch)", m => S15.P(m.RealTies)));
            sb.AppendLine(RowM("Interruptions per morning", m => (m.Audit.Interruptions / (double)Math.Max(1, m.Audit.Mornings)).ToString("0.0")));
            sb.AppendLine(RowM("Meals (batch)", m => m.Meals.ToString()));
            sb.AppendLine(RowM("Wants raised (audit)", m => m.Sources.Raised.ToString()));
            sb.AppendLine(RowM("... unsupported", m => S15.P(m.Sources.Share(Support.Unsupported))));
            sb.AppendLine(RowM("... raised on traits and values alone", m => MotivationSources.P(m.Sources.OnTraitsAndValuesAlone, m.Sources.Raised)));
            sb.AppendLine(RowM("Wants resting on something that happened (trace)", m => MotivationSources.P(m.Sources.WantsTraced, m.Sources.Raised)));
            sb.AppendLine(RowM("Urgency from traits and values", m => S15.P(m.Sources.ShareOfUrgency(Source.Disposition))));
            sb.AppendLine();
            foreach (var label in Labels)
            {
                sb.AppendLine("**" + label + "**, what each person did across every condition:");
                sb.AppendLine();
                sb.AppendLine(S15.Profiles(Measured()[label]));
            }
            sb.AppendLine("How far each person's morning moved (the total difference between action profiles):");
            sb.AppendLine();
            sb.AppendLine("| Who | A to B | B to B timed | B to B end | B to B timed end | A to B timed end |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var p in S16.People)
            {
                string Gap(string x, string y) => S15.F(BatchRunner.HowDifferent(Measured()[x].ProfileByPerson[p], Measured()[y].ProfileByPerson[p]));
                sb.AppendLine("| " + p + " | " + Gap("A", "B") + " | " + Gap("B", "B timed") + " | " + Gap("B", "B end") + " | " + Gap("B", "B timed end") + " | " + Gap("A", "B timed end") + " |");
            }
            Record("1", sb.ToString());

            Assert.AreEqual(16060, Measured()["A"].BatchDecisions, "A is the shipped morning, unchanged by S1.6");
            foreach (var label in new[] { "B end", "B timed end" })
                Assert.AreEqual(0, Measured()[label].Sources.OnTraitsAndValuesAlone, label + ": B's property that nothing is raised on traits and values alone survives");
        }

        // ---- 2 ----

        [Test, Timeout(3600000)]
        public void E2_TheWalksAndWhatCouldBeForeseen()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 2. The walks, and what could be foreseen");
            sb.AppendLine();
            sb.AppendLine("Seeds 1 to " + AuditSeeds + ", the S1.6 diagnosis instrument: at the moment somebody set out, the best thing they could have done for the walk's want on arrival, as they could imagine it.");
            sb.AppendLine();
            sb.AppendLine(Header("Measure"));
            sb.AppendLine(Row("Walks set out on", l => Walks()[l].Count.ToString()));
            sb.AppendLine(Row("... whose end was foreseeably not worth doing", l => Walks()[l].Count(w => !w.Foreseen.WorthIt) + " (" + S16.P(Walks()[l].Count(w => !w.Foreseen.WorthIt), Walks()[l].Count) + ")"));
            sb.AppendLine(Row("Walks that arrived and decided with the intention", l => Walks()[l].Count(w => w.Arrived).ToString()));
            sb.AppendLine(Row("... held", l => Walks()[l].Count(w => w.Held).ToString()));
            sb.AppendLine(Row("... given up as not worth what it costs there", l => Walks()[l].Count(w => w.Commitment == Commitment.NotWorthIt).ToString()));
            sb.AppendLine(Row("...... with somebody in the room on arrival", l => Walks()[l].Count(w => w.Commitment == Commitment.NotWorthIt && w.PresentOnArrival > 0).ToString()));
            sb.AppendLine(Row("...... foreseeable at departure", l => Walks()[l].Count(w => w.Commitment == Commitment.NotWorthIt && !w.Foreseen.WorthIt).ToString()));
            sb.AppendLine(Row("... given up: nothing there serves it", l => Walks()[l].Count(w => w.Commitment == Commitment.Impossible).ToString()));
            sb.AppendLine(Row("... given up: no longer wanted", l => Walks()[l].Count(w => w.Commitment == Commitment.NoLongerWanted).ToString()));
            foreach (var want in new[] { "find_out", "get_food", "avoid_exposure", "keep_peace", "look_after", "guard_supplies" })
                sb.AppendLine(Row("Walks for `" + want + "`: set out / given up", l => Walks()[l].Count(w => w.Want.StartsWith(want, StringComparison.Ordinal)) + " / " + Walks()[l].Count(w => w.Want.StartsWith(want, StringComparison.Ordinal) && w.Lapsed)));
            sb.AppendLine();
            foreach (var label in new[] { "B end", "B timed end" })
            {
                var lapsed = Walks()[label].Where(w => w.Lapsed).ToList();
                sb.AppendLine("**" + label + "**, every walk given up on arrival, by want, destination and who was there: " +
                              (lapsed.Count == 0 ? "none." : string.Join("; ", lapsed.GroupBy(w => w.Want.Split(':')[0] + " -> " + w.To + (w.PresentOnArrival > 0 ? ", somebody there" : ", nobody there") + ", " + w.Commitment)
                                  .OrderByDescending(g => g.Count()).Select(g => g.Key + " " + g.Count())) + "."));
                sb.AppendLine();
            }
            Record("2", sb.ToString());

            foreach (var label in new[] { "B end", "B timed end" })
                Assert.AreEqual(0, Walks()[label].Count(w => !w.Foreseen.WorthIt), label + ": no walk is set out on whose end was foreseeably not worth doing");
            foreach (var label in new[] { "B", "B timed" })
                Assert.Greater(Walks()[label].Count(w => !w.Foreseen.WorthIt), 0, label + ": the instrument still sees pointless walks where nothing stops them");
        }

        // ---- 3 ----

        [Test, Timeout(3600000)]
        public void E3_FindOutOverTheMorning()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 3. `find_out` over the morning");
            sb.AppendLine();
            sb.AppendLine("Mean urgency per person by ten minutes, seeds 1 to " + AuditSeeds + ".");
            sb.AppendLine();
            foreach (var label in new[] { "B", "B timed", "B end", "B timed end" })
            {
                sb.AppendLine("**" + label + "**");
                sb.AppendLine();
                sb.AppendLine(S16.Timeline(_conditions[label], _variants, 1, AuditSeeds, "find_out"));
            }
            Record("3", sb.ToString());
        }

        // ---- 4 ----

        [Test, Timeout(3600000)]
        public void E4_LeoOnTheWorstMorning()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 4. Leo, `daniel_ate_it` seed 9, under each condition");
            sb.AppendLine();
            sb.AppendLine("The morning S1.5 printed as the worst pacing in the batch (15 under B).");
            sb.AppendLine();
            foreach (var label in new[] { "B", "B timed", "B end", "B timed end" })
            {
                sb.AppendLine("**" + label + "**");
                sb.AppendLine();
                sb.AppendLine(S16.Table(_conditions[label], "daniel_ate_it", 9, "leo"));
            }
            Record("4", sb.ToString());
        }

        // ---- 5 ----

        [Test, Timeout(3600000)]
        public void E5_TheSamePersonWithAndWithoutTheNight()
        {
            var culprits = new[] { ("daniel_ate_it", "daniel"), ("mara_ate_it", "mara"), ("daniel_hid_it", "daniel"), ("elena_fed_mara", "elena") };
            var sb = new StringBuilder();
            sb.AppendLine("## 5. The same person, with and without the night");
            sb.AppendLine();
            sb.AppendLine("The S1.1 measure: behaviour with the night against without it, against two same-condition pools (seeds 1 to 20 and 21 to 40). Above the noise means more than 1.5 times the larger noise.");
            sb.AppendLine();
            sb.AppendLine("| Condition | Who | Mode | Night vs no night | No night vs no night | Night vs night | Effect / noise | Above |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            foreach (var (variant, who) in culprits)
            foreach (var label in new[] { "A", "B", "B timed end" })
            {
                var (effect, c, t) = S15.NightEffect(_conditions[label], variant, who, 1);
                var noise = Math.Max(c, t);
                sb.AppendLine("| " + variant + " | " + who + " | " + label + " | " + S15.F(effect) + " | " + S15.F(c) + " | " + S15.F(t) + " | " +
                              (noise == 0 ? "n/a" : (effect / noise).ToString("0.0")) + " | " + (effect > noise * 1.5 ? "yes" : "no") + " |");
            }
            Record("5", sb.ToString());
        }

        // ---- 6 ----

        [Test, Timeout(3600000)]
        public void E6_WhenNothingPresses()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 6. When nothing presses");
            sb.AppendLine();
            sb.AppendLine("Decisions where no want added to what was chosen, seeds 1 to " + AuditSeeds + ", as written and with nothing missing.");
            sb.AppendLine();
            sb.AppendLine("| Condition | World | Decisions | Led by no want | ... chose | ... settled by the seed |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var label in new[] { "B", "B timed end" })
            foreach (var (world, content) in new[] { ("as written", _conditions[label]), ("nothing missing", S15.NothingMissing(_conditions[label])) })
            {
                var (decisions, unled, chose, ambiguous) = S16.NothingPressing(content, _variants, 1, AuditSeeds);
                sb.AppendLine("| " + label + " | " + world + " | " + decisions + " | " + unled + " | " +
                              (chose.Count == 0 ? "-" : string.Join(", ", chose.OrderByDescending(k => k.Value).Select(k => k.Key + " " + k.Value))) + " | " + ambiguous + " |");
            }
            Record("6", sb.ToString());
        }

        // ---- 7 ----

        [Test]
        public void E7_OneWalkUnderEndTraced()
        {
            var content = _conditions["B timed end"];
            var run = Scenario001.Prepare(content, "daniel_ate_it", 9);
            string declined = null, taken = null;
            run.Morning.Decided = m =>
            {
                var record = run.Trace.Get(m.Decision.TraceId);
                if (!record.Data.TryGetValue("foresaw", out var foresaw)) return;
                if (declined == null && foresaw.Contains("not worth walking for") && m.CharacterId == "leo")
                    declined = "Minute " + m.Minute + ", Leo in the " + m.Percept.Room.Id + ", chose " + m.Decision.Chosen + ". Foresaw: " + foresaw + ".";
                if (taken == null && m.Decision.Chosen.Kind == ActionKind.GoTo)
                    taken = "Minute " + m.Minute + ", " + m.CharacterId + " in the " + m.Percept.Room.Id + ", chose " + m.Decision.Chosen + " for " + (m.Decision.Leading?.Key ?? "nothing") + ". Foresaw: " + foresaw + "." +
                            Environment.NewLine + Environment.NewLine + "```" + Environment.NewLine + DecisionTrace.Explain(m.Decision) + "```";
            };
            run.Morning.Run(content.Morning.Minutes);
            Record("7", "## 7. Walks under `end`, traced" + Environment.NewLine + Environment.NewLine +
                        "A walk not credited, because its end would not be worth doing:" + Environment.NewLine + Environment.NewLine + (declined ?? "none found") + Environment.NewLine + Environment.NewLine +
                        "A walk taken, because its end could be:" + Environment.NewLine + Environment.NewLine + (taken ?? "none found") + Environment.NewLine);
            Assert.IsNotNull(declined, "Leo declines a walk he would have taken under B");
            Assert.IsNotNull(taken, "somebody still walks somewhere, for an end that could be worth it");
        }

        // ---- 8 ----

        [Test, Timeout(3600000)]
        public void E8_Food()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 8. Food");
            sb.AppendLine();
            sb.AppendLine("| Condition | Circumstance | Mornings | Meals | By person |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var label in new[] { "A", "B", "B timed", "B end", "B timed end" })
            foreach (var (world, content) in new[]
                     {
                         ("as written", _conditions[label]),
                         ("plenty, count not short", S13DiagnosisTests.Plenty(_conditions[label], 10, countComesUpShort: false))
                     })
            {
                var w = S15.Count(content, _variants, 1, AuditSeeds);
                sb.AppendLine("| " + label + " | " + world + " | " + w.Mornings + " | " + w.Meals + " | " +
                              string.Join(", ", S15.People.Select(p => p + " " + (w.MealsBy.TryGetValue(p, out var n) ? n : 0))) + " |");
            }
            Record("8", sb.ToString());
        }
    }
}
