using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The S1.6 held-out predictions, committed in
    /// Docs/slices/S1.6/held-out-predictions.md before any code for either
    /// mechanism existed, checked here exactly as written. The held-out case is
    /// `leo_ate_it` on seeds 141 to 180, which no other test runs.
    /// </summary>
    public class S16HeldOutTests
    {
        const string HeldOut = "leo_ate_it";
        const ulong First = 141;
        const int WalkSeeds = 20;

        static Scenario001Content _content;
        static readonly Dictionary<string, Scenario001Content> _conditions = new Dictionary<string, Scenario001Content>(StringComparer.Ordinal);
        static readonly Dictionary<string, S15Measured> _measured = new Dictionary<string, S15Measured>(StringComparer.Ordinal);
        static readonly Dictionary<string, List<S16.WalkRecord>> _walks = new Dictionary<string, List<S16.WalkRecord>>(StringComparer.Ordinal);
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load()
        {
            _content = Scenario001Content.Load(TestPaths.DataRoot);
            foreach (var (label, make) in S16.Conditions) _conditions[label] = make(_content);
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.6 held-out results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S16HeldOutTests`. Predictions in `held-out-predictions.md`, committed first. `" + HeldOut + "`, walks and `find_out` from seeds " + First + " to " + (First + WalkSeeds - 1) + ", decisions from seeds " + First + " to " + (First + 19) + ", behaviour from seeds " + First + " to " + (First + 39) + ".");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine("- " + r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.6");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "held-out-results.md"), sb.ToString());
        }

        static bool Record(string id, bool held, string detail)
        {
            _results[id] = "**" + id + "** " + (held ? "held" : "MISSED") + ". " + detail;
            TestContext.WriteLine(_results[id]);
            return held;
        }

        static S15Measured M(string label)
            => _measured.TryGetValue(label, out var m) ? m : _measured[label] = S15.Measure(_conditions[label], label, new[] { HeldOut }, 20, 40, First);

        static List<S16.WalkRecord> W(string label)
            => _walks.TryGetValue(label, out var w) ? w : _walks[label] = S16.Walks(_conditions[label], new[] { HeldOut }, First, WalkSeeds);

        static double Pointless(string label) => W(label).Count == 0 ? 0.0 : W(label).Count(w => !w.Foreseen.WorthIt) / (double)W(label).Count;

        [Test, Timeout(3600000)]
        public void P1_UnderEndNoWalkIsSetOutOnWhoseEndWasForeseeablyNotWorthDoing()
        {
            var held = W("B end").Count(w => !w.Foreseen.WorthIt) == 0 && Pointless("B") >= 0.5;
            Record("P1", held, "Walks whose end was foreseeably not worth doing: B end " + W("B end").Count(w => !w.Foreseen.WorthIt) + " of " + W("B end").Count +
                               "; B " + W("B").Count(w => !w.Foreseen.WorthIt) + " of " + W("B").Count + " (" + S16.P(W("B").Count(w => !w.Foreseen.WorthIt), W("B").Count) + ").");
            Assert.IsTrue(held, "P1 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P2_UnderEndEveryWalkGivenUpHadSomebodyInTheRoom()
        {
            var lapsed = W("B end").Where(w => w.Commitment == Commitment.NotWorthIt).ToList();
            var held = lapsed.All(w => w.PresentOnArrival > 0);
            Record("P2", held, "Under B end, walks given up on arrival as not worth it: " + lapsed.Count + ", with somebody in the room in " + lapsed.Count(w => w.PresentOnArrival > 0) + ".");
            Assert.IsTrue(held, "P2 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P3_UnderTimedLeosFindOutFallsOverTheMorning()
        {
            (double First, double Last) Ends(string label)
            {
                var first = new List<double>(); var last = new List<double>();
                for (var seed = First; seed < First + WalkSeeds; seed++)
                {
                    var run = Scenario001.Prepare(_conditions[label], HeldOut, seed);
                    run.Morning.Decided = m =>
                    {
                        if (m.CharacterId != "leo") return;
                        var u = m.Motives.FirstOrDefault(x => x.Name == "find_out")?.Urgency ?? 0.0;
                        if (m.Minute <= 10) first.Add(u);
                        else if (m.Minute > _content.Morning.Minutes - 10) last.Add(u);
                    };
                    run.Morning.Run(_content.Morning.Minutes);
                }
                return (first.Count == 0 ? 0 : first.Average(), last.Count == 0 ? 0 : last.Average());
            }
            var timed = Ends("B timed");
            var untimed = Ends("B");
            var held = timed.Last < 0.5 * timed.First && Math.Abs(untimed.Last - untimed.First) < 0.01;
            Record("P3", held, "Leo's mean `find_out`, first ten minutes against last ten: B timed " + S15.F(timed.First) + " -> " + S15.F(timed.Last) + "; B " + S15.F(untimed.First) + " -> " + S15.F(untimed.Last) + ".");
            Assert.IsTrue(held, "P3 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P4_UnderBothBsCausalPropertiesSurvive()
        {
            var m = M("B timed end");
            var traced = m.Sources.WantsTraced / (double)Math.Max(1, m.Sources.Raised);
            var held = m.Sources.OnTraitsAndValuesAlone == 0 && traced >= 0.90;
            Record("P4", held, "Under B timed end: wants raised on traits and values alone " + m.Sources.OnTraitsAndValuesAlone + " of " + m.Sources.Raised + "; resting on something that happened or the body " + S15.P(traced) + ".");
            Assert.IsTrue(held, "P4 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P5_UnderTimedAloneTheWalksToTheFoodStay()
        {
            int Food(string label) => W(label).Count(w => w.Want == "get_food" && w.Commitment == Commitment.NotWorthIt);
            var held = Food("B timed") >= 0.8 * Food("B");
            Record("P5", held, "Walks to the food given up on arrival: B timed " + Food("B timed") + ", B " + Food("B") + ".");
            // RECORDED MISS, first run, as on the design seeds. With find_out fading,
            // people stop leaving the kitchen to look for something, so they are no
            // longer elsewhere with a reason to walk back to the food: most walks to
            // the food were the return legs of the loop.
            Assert.Less(Food("B timed"), 0.8 * Food("B"), "RECORDED MISS: turn round if M1 alone leaves the walks to the food where they were");
        }

        [Test, Timeout(3600000)]
        public void P6_UnderBothPacingIsBelowAsAndTheWorstIsSmall()
        {
            var both = M("B timed end"); var a = M("A");
            var held = both.MeanPacing < a.MeanPacing && both.WorstPacing <= 3;
            Record("P6", held, "Pacing, mean and worst: B timed end " + both.MeanPacing.ToString("0.00") + " and " + both.WorstPacing + " (" + both.WorstPacingWho + "); A " + a.MeanPacing.ToString("0.00") + " and " + a.WorstPacing + "; B " + M("B").MeanPacing.ToString("0.00") + " and " + M("B").WorstPacing + ".");
            Assert.IsTrue(held, "P6 held when first run");
        }

        [Test, Timeout(3600000)]
        public void P7_UnderBothLessStandingStillThanA()
        {
            var held = Record("P7", M("B timed end").WaitShare < M("A").WaitShare, "Standing still, share of choices: B timed end " + S15.P(M("B timed end").WaitShare) + ", A " + S15.P(M("A").WaitShare) + ", B " + S15.P(M("B").WaitShare) + ".");
            // RECORDED MISS, first run, as on the design seeds. B's standing still was
            // low because people were walking; with the walks gone, standing still is
            // what is left once nothing else is worth doing, and it is led by a want
            // carried by a belief, not by a standing want.
            Assert.Greater(M("B timed end").WaitShare, M("A").WaitShare, "RECORDED MISS: turn round if standing still under both falls below A's");
        }

        [Test, Timeout(3600000)]
        public void P8_UnderBothLeosNightStandsOutMoreThanUnderA()
        {
            var (ea, ca, ta) = S15.NightEffect(_conditions["A"], HeldOut, "leo", First);
            var (eb, cb, tb) = S15.NightEffect(_conditions["B timed end"], HeldOut, "leo", First);
            var ra = ea / Math.Max(1e-9, Math.Max(ca, ta));
            var rb = eb / Math.Max(1e-9, Math.Max(cb, tb));
            Record("P8", rb > ra, "Leo, night against no night, over the larger noise: B timed end " + S15.F(eb) + " / " + S15.F(Math.Max(cb, tb)) + " = " + rb.ToString("0.0") +
                                  "; A " + S15.F(ea) + " / " + S15.F(Math.Max(ca, ta)) + " = " + ra.ToString("0.0") + ".");
            // RECORDED MISS, first run. On the four design culprits the night stood out
            // more under both fixes than under A; for Leo on this case it stands out
            // less, though still above the noise. The half that holds is pinned.
            Assert.Greater(rb, 1.5, "Leo's night is above the noise under both fixes");
            Assert.Greater(ra, rb, "RECORDED MISS: turn round if Leo's night comes to stand out more under both fixes than under A");
        }

        [Test, Timeout(3600000)]
        public void P9_UnderBothSomebodyStillEatsAndFoodWalksAreNotGivenUpForNothing()
        {
            var meals = M("B timed end").Meals;
            var food = W("B timed end").Where(w => w.Want == "get_food" && w.Commitment == Commitment.NotWorthIt).ToList();
            var held = meals > 0 && food.Count <= meals + food.Count(w => w.PresentOnArrival > 0);
            Record("P9", held, "Under B timed end: meals " + meals + " (B " + M("B").Meals + ", A " + M("A").Meals + "); walks to the food given up on arrival " + food.Count + ", with somebody there in " + food.Count(w => w.PresentOnArrival > 0) + ".");
            // RECORDED MISS on the first half, first run. B's meals were a by-product
            // of the loop emptying the kitchen; with people standing still where they
            // are, eating in front of others stays priced out. The second half held:
            // every walk to the food given up had somebody there.
            Assert.IsTrue(food.All(w => w.PresentOnArrival > 0), "the half of P9 that held");
            Assert.AreEqual(0, meals, "RECORDED MISS: turn round if somebody eats as written under both fixes");
        }

        [Test, Timeout(3600000)]
        public void P10_UnderBothPeopleAreNoLessDifferentThanUnderB()
        {
            var both = M("B timed end"); var b = M("B");
            var held = both.MeanGap >= b.MeanGap - 0.02 && both.ClosestPair >= b.ClosestPair;
            Record("P10", held, "Mean different-person gap: B timed end " + S15.F(both.MeanGap) + ", B " + S15.F(b.MeanGap) + ", A " + S15.F(M("A").MeanGap) +
                                ". Closest pair: B timed end " + S15.F(both.ClosestPair) + " (" + both.ClosestWho + "), B " + S15.F(b.ClosestPair) + " (" + b.ClosestWho + ").");
            // RECORDED MISS, first run, as on the design seeds. Part of what told
            // people apart under B was the loop; with it gone, people with the same
            // circumstances do the same things. See the report, section 5.
            Assert.Less(both.MeanGap, b.MeanGap - 0.02, "RECORDED MISS: turn round if people under both fixes stay within 0.02 of B");
            Assert.Less(both.ClosestPair, b.ClosestPair, "RECORDED MISS: turn round if the closest pair is no closer than under B");
        }
    }
}
