using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.7 diagnosis: what can carry a past event into a later decision at all,
    /// measured on the shipped rules before anything is changed. Writes
    /// Docs/slices/S1.7/diagnosis-current.md. Nothing here changes any behaviour.
    /// </summary>
    public class S17DiagnosisTests
    {
        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _sections = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load() => _content = Scenario001Content.Load(TestPaths.DataRoot);

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.7 diagnosis: what carries a past event into a later decision");
            sb.AppendLine();
            sb.AppendLine("Generated by `S17DiagnosisTests` on the shipped rules, with nothing changed. Measured rather than read off the code: each section runs the thing it describes.");
            sb.AppendLine();
            foreach (var s in _sections.Values) sb.AppendLine(s);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.7");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "diagnosis-current.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _sections[key] = text;
            TestContext.WriteLine(text);
        }

        // ---- 1 ----

        [Test]
        public void D1_WhatSurvivesADayBoundary()
        {
            // One person, one earlier event they read as something, then days pass.
            // What of it is still readable by the machinery that raises wants?
            var sb = new StringBuilder();
            sb.AppendLine("## 1. What survives a day boundary");
            sb.AppendLine();
            sb.AppendLine("One person is shown one event on day 1 that they read as a slight. Then days pass with nothing happening. At each later day their wants are raised exactly as a morning would raise them, and the three things that could carry the event are read off: the memory, the belief it moved, and the feeling it stirred.");
            sb.AppendLine();
            sb.AppendLine("| Day the wants are raised | Memory of it recalled (`find_out` memory term) | Belief `treats_me_like_a_child` | Strongest feeling left |");
            sb.AppendLine("|---|---|---|---|");

            for (var day = 1; day <= 4; day++)
            {
                var trace = new TraceLog();
                var sim = new Simulation(_content.Cast, _content.Rules, trace) { FadeOnEachEvent = false };
                sim.Apply(S17.WentThroughTheirThings("daniel", "elena", 1, new List<string> { "elena" }));
                for (var d = 1; d < day; d++) sim.PassTime(1.0);

                var mind = sim.Minds["elena"];
                var percept = Bench.Standing("elena", present: new List<string> { "daniel" });
                var motives = new Motivator(_content.Rules).Raise(mind, percept, day, trace, 0);
                var findOut = motives.FirstOrDefault(m => m.Name == "find_out");
                var memoryTerm = findOut?.Terms
                    .Where(t => t.Kind == ScalerKind.Memory)
                    .Sum(t => t.Amount) ?? 0.0;
                var strongest = mind.Emotions.Live.OrderByDescending(e => e.Intensity).FirstOrDefault();

                sb.AppendLine("| " + day + (day == 1 ? " (the same day)" : "") + " | " + S17.F(memoryTerm) + " | " +
                              S17.F(mind.Beliefs.Confidence("tendency", new[] { "daniel", "treats_me_like_a_child" })) + " | " +
                              (strongest == null ? "nothing" : strongest.Type + " " + S17.F(strongest.Intensity)) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("A memory scaler only ever looks at the day being lived (`ScalerEval.Recall` filters on `x.Day == ctx.Today`), so a memory of an earlier day is kept and is never read by anything that raises a want. Feelings fade. **A belief is the only thing that crosses midnight with its strength intact**, and nothing anywhere decays one.");
            Record("1", sb.ToString());
        }

        // ---- 2 ----

        [Test]
        public void D2_TheLedgerIsAlmostEntirelyWriteOnly()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 2. The ledger is almost entirely write-only");
            sb.AppendLine();

            var written = new Dictionary<string, int>(StringComparer.Ordinal);
            var events = _content.Backstory.Events.ToList();
            if (_content.Morning.Opening != null) events.Add(_content.Morning.Opening);
            foreach (var v in _content.Morning.Variants.Concat(_content.Morning.HeldOutVariants)) events.AddRange(v.NightEvents);
            foreach (var e in events)
            foreach (var f in e.LedgerEffects)
            {
                written.TryGetValue(f.Entry, out var n);
                written[f.Entry] = n + 1;
            }

            var read = new HashSet<string>(StringComparer.Ordinal);
            foreach (var s in _content.Rules.Interpretation.SelectMany(r => r.ScaledBy)
                         .Concat(_content.Rules.Appraisal.SelectMany(r => r.ScaledBy))
                         .Concat(_content.Rules.BeliefNudges.SelectMany(r => r.ScaledBy))
                         .Concat(_content.Rules.Motivation.SelectMany(r => r.ScaledBy ?? new List<Scaler>()))
                         .Concat(_content.Rules.Costs.SelectMany(r => r.ScaledBy ?? new List<Scaler>())))
                if (s.Kind == ScalerKind.Ledger && s.Entry != null) read.Add(s.Entry);

            sb.AppendLine("| Ledger entry | Written by the scenario data | Read by any rule |");
            sb.AppendLine("|---|---|---|");
            foreach (var entry in _content.Vocabulary.LedgerEntries.OrderBy(e => e, StringComparer.Ordinal))
            {
                written.TryGetValue(entry, out var n);
                sb.AppendLine("| `" + entry + "` | " + (n == 0 ? "never" : n + " times") + " | " + (read.Contains(entry) ? "yes" : "**no**") + " |");
            }
            sb.AppendLine();
            sb.AppendLine("Every one of those writes is an authored `ledger_effects` block on a hand-written event. **No rule anywhere produces a ledger entry from what an event meant**, so the record of what somebody did to somebody else is authored rather than simulated. " +
                          read.Count + " of " + _content.Vocabulary.LedgerEntries.Count + " entry kinds are read by anything at all.");
            Record("2", sb.ToString());

            Assert.IsFalse(read.Contains("searched_my_things"),
                "if this starts failing, going through somebody's things has become readable and the S1.7 argument should be revisited");
        }

        // ---- 3 ----

        [Test]
        public void D3_WhichBeliefsAreLearnableAndWhatReadsThemBack()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 3. Which beliefs are learnable, and what reads them back");
            sb.AppendLine();
            sb.AppendLine("A belief matters longitudinally only if something can write it from experience and something else reads it later. The two columns are what make a loop.");
            sb.AppendLine();
            sb.AppendLine("| Belief | Written from experience by | Read by interpretation | Read by motivation |");
            sb.AppendLine("|---|---|---|---|");

            var predicates = new SortedSet<string>(StringComparer.Ordinal);
            foreach (var r in _content.Rules.BeliefNudges) predicates.Add(r.Predicate);
            foreach (var s in _content.Rules.Interpretation.SelectMany(r => r.ScaledBy).Where(s => s.Kind == ScalerKind.Belief)) predicates.Add(s.Predicate);
            foreach (var s in _content.Rules.Motivation.SelectMany(r => r.ScaledBy ?? new List<Scaler>()).Where(s => s.Kind == ScalerKind.Belief)) predicates.Add(s.Predicate);

            foreach (var p in predicates)
            {
                var writes = _content.Rules.BeliefNudges.Where(r => r.Predicate == p).Select(r => "`" + r.Id + "`").ToList();
                var interp = _content.Rules.Interpretation
                    .Where(r => r.ScaledBy.Any(s => s.Kind == ScalerKind.Belief && s.Predicate == p))
                    .Select(r => "`" + r.Id + "` -> " + r.Label).ToList();
                var motiv = _content.Rules.Motivation
                    .Where(r => (r.ScaledBy ?? new List<Scaler>()).Any(s => s.Kind == ScalerKind.Belief && s.Predicate == p))
                    .Select(r => "`" + r.Motive + "`").ToList();
                sb.AppendLine("| `" + p + "` | " + (writes.Count == 0 ? "**nothing**" : string.Join(", ", writes)) + " | " +
                              (interp.Count == 0 ? "-" : string.Join("; ", interp)) + " | " +
                              (motiv.Count == 0 ? "-" : string.Join(", ", motiv)) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("Two shapes, and they behave nothing like each other. A belief read by a **motivation** rule moves a want directly, by any amount, at once. A belief read only by **interpretation** rules can only change what a later event comes to mean, and section 4 shows what that costs.");
            Record("3", sb.ToString());
        }

        // ---- 4 ----

        [Test]
        public void D4_NothingDownstreamOfTheReadingCanSeeHistory()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 4. Nothing downstream of the reading can see history");
            sb.AppendLine();

            var appraisalKinds = _content.Rules.Appraisal
                .SelectMany(r => r.ScaledBy)
                .Select(s => s.Kind)
                .Distinct()
                .OrderBy(k => k, StringComparer.Ordinal)
                .ToList();
            var historyInAppraisal = _content.Rules.Appraisal
                .Where(r => r.ScaledBy.Any(s => s.Kind == ScalerKind.Belief || s.Kind == ScalerKind.Ledger || s.Kind == ScalerKind.Memory))
                .Select(r => r.Id).ToList();

            sb.AppendLine("Of the " + _content.Rules.Appraisal.Count + " appraisal rules, the kinds of thing they are weighed by are: " +
                          string.Join(", ", appraisalKinds.Select(k => "`" + k + "`")) + ". Rules weighed by a belief, a ledger entry or a memory: **" +
                          (historyInAppraisal.Count == 0 ? "none" : string.Join(", ", historyInAppraisal)) + "**.");
            sb.AppendLine();
            sb.AppendLine("So what an event feels like is decided by the reading it got, this person's temperament and values, and who was watching. History reaches a feeling only by changing the reading.");
            sb.AppendLine();
            sb.AppendLine("And a reading carries no strength with it. `Simulation.Perceive` hands appraisal and the belief nudges the winning **meaning** and nothing else; the weight that reading won by is written to the trace and read by nothing. The measurement below is the consequence: the same person, the same later event, two different histories that both end in the same reading.");
            sb.AppendLine();

            // Two histories of different strength. The lag is long enough that
            // whatever the earlier events made this person feel has faded away,
            // so the only thing left of them is the belief.
            var settled = new S17Arm { PriorSlights = 1, Answerable = false, LagFades = 40 };
            var weak = S17.Run(_content, settled.With(a => { a.Label = "one earlier time"; a.PriorSlights = 1; }));
            var strong = S17.Run(_content, settled.With(a => { a.Label = "six earlier times"; a.PriorSlights = 6; }));

            sb.AppendLine(S17.ChainTable(new[] { weak, strong }));
            sb.AppendLine("The belief differs, and so does the weight the reading won by. Everything after the reading is identical, to every decimal the simulation holds.");
            sb.AppendLine();

            // And the same pair while the earlier events are still being felt.
            var fresh = new S17Arm { PriorSlights = 1, Answerable = false, LagFades = 1 };
            var weakFresh = S17.Run(_content, fresh.With(a => { a.Label = "one, still felt"; a.PriorSlights = 1; }));
            var strongFresh = S17.Run(_content, fresh.With(a => { a.Label = "six, still felt"; a.PriorSlights = 6; }));

            sb.AppendLine("The same two histories, measured while what the earlier events stirred has not yet faded:");
            sb.AppendLine();
            sb.AppendLine(S17.ChainTable(new[] { weakFresh, strongFresh }));
            sb.AppendLine("Here the two do differ, and the difference is in what the person is **carrying**, not in what this event stirred: the row `5 it stirred` is identical in both, and only `carrying` moves. That is left-over feeling from the earlier events themselves, decaying on the ordinary schedule. It is not the belief reaching the present. Note also that both of those choices were too close to call, so the difference such left-over feeling makes here sits inside the ambiguity band.");
            sb.AppendLine();

            // How long the mood lasts, so the two channels can be told apart.
            sb.AppendLine("How long the earlier events go on being felt, after six of them:");
            sb.AppendLine();
            sb.AppendLine("| Fades since the last one | Strongest feeling carried | Belief `treats_me_like_a_child` |");
            sb.AppendLine("|---|---|---|");
            foreach (var fades in new[] { 0.0, 1.0, 2.0, 4.0, 8.0, 16.0, 40.0 })
            {
                var c = S17.Run(_content, new S17Arm { Label = "lag " + fades, PriorSlights = 6, Answerable = false, LagFades = fades });
                var carried = c.Emotions.Where(e => e.Value > 0.0).OrderByDescending(e => e.Value).FirstOrDefault();
                sb.AppendLine("| " + fades + " | " + (carried.Key == null ? "nothing" : carried.Key + " " + S17.F(carried.Value)) + " | " +
                              S17.F(c.Belief("tendency(daniel,treats_me_like_a_child)")) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("The carried feeling falls back to exactly what this event itself stirred (hurt 0.565) and stops there: by about sixteen fades nothing is left of the six earlier events but the belief. So an earlier event leaves two residues with completely different lifetimes: a feeling that is gone within the hour, and a belief that never goes at all. Only the second is longitudinal, and section 4 has just shown that the second cannot reach a feeling except by changing a reading.");
            Record("4", sb.ToString());

            Assert.AreEqual(0, historyInAppraisal.Count, "no appraisal rule reads history");
            Assert.AreEqual(weak.Meaning, strong.Meaning, "both still read it the same way");
            Assert.Greater(strong.Belief("tendency(daniel,treats_me_like_a_child)"), weak.Belief("tendency(daniel,treats_me_like_a_child)"), "the belief did move");
            Assert.Greater(strong.Weight, weak.Weight, "and the reading was won by more");
            Assert.AreEqual(weakFresh.Stirring, strongFresh.Stirring, "appraisal is blind to history: the event stirs the same thing either way");
            Assert.AreEqual(weak.Downstream, strong.Downstream, "once the feeling has faded, nothing downstream of the reading differs at all");
        }
    }
}
