using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Sim;
using Fallow.Core.Testing;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// S1.7: can a past event change a later decision, when the later situation is
    /// otherwise the same? The subject, the later event and every circumstance are
    /// held fixed; only the history varies. Nothing in the simulation is changed by
    /// this slice. Writes Docs/slices/S1.7/experiment-results.md.
    /// </summary>
    public class S17ExperimentTests
    {
        /// <summary>Long enough that nothing the earlier events stirred is still felt (diagnosis section 4).</summary>
        const double Settled = 40.0;

        static Scenario001Content _content;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load() => _content = Baselines.ModelA();

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# S1.7 experiment results");
            sb.AppendLine();
            sb.AppendLine("Generated by `S17ExperimentTests` on the shipped rules, unchanged. One person, one later event, and nothing different between arms but what happened to them before. The lag is always long enough that nothing the earlier events stirred is still being felt, so the only thing they have left behind is a belief.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "slices", "S1.7");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "experiment-results.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static S17Arm Base(string label) => new S17Arm
        {
            Label = label,
            Subject = "elena",
            Other = "daniel",
            Answerable = true,
            LagFades = Settled,
            ProbeKind = S17.Search
        };

        /// <summary>Enough earlier times to carry the belief past where the reading changes. Found by E2, not chosen.</summary>
        const int Many = 12;

        // ---- 1 ----

        [Test]
        public void E1_TheFourArms()
        {
            var control = S17.Run(_content, Base("C: it never happened").With(a => a.PriorSlights = 0));
            var treatment = S17.Run(_content, Base("T: it happened, she saw it").With(a => a.PriorSlights = Many));
            var unseen = S17.Run(_content, Base("U: it happened, she did not see it").With(a => { a.PriorSlights = Many; a.SubjectSeesPriors = false; }));
            var other = S17.Run(_content, Base("P: it happened, but somebody else does it now").With(a => { a.PriorSlights = Many; a.ProbeActor = "leo"; }));

            var sb = new StringBuilder();
            sb.AppendLine("## 1. The four arms");
            sb.AppendLine();
            sb.AppendLine("Elena is the subject. The history is Daniel going through her things, " + Many + " times, on " + Many + " separate earlier days. In between she does the thing that makes her answerable for what is missing, so that two readings of the later event are live at once. The later event is always the same: somebody goes through her things while she stands there, on a later day, with the feeling of the earlier times long gone.");
            sb.AppendLine();
            sb.AppendLine(S17.ChainTable(new[] { control, treatment, unseen, other }));
            sb.AppendLine("**C against T** is the experiment. **U** is the same world with the subject out of the room for it, and is how we know the effect travels through her perceiving it rather than through it having happened. **P** is the same history with a different person doing the later thing, and is how we know the effect is about Daniel rather than about her mood.");
            sb.AppendLine();
            sb.AppendLine("What each arm read the later event as, rule by rule:");
            sb.AppendLine();
            foreach (var c in new[] { control, treatment, unseen, other })
            {
                sb.AppendLine("- **" + c.Label + "**: `" + c.Meaning + "` " + S17.F(c.Weight));
                sb.AppendLine("  - " + (c.RulesDetail ?? "no rule spoke").Replace(" | ", "\n  - "));
            }
            Record("1", sb.ToString());

            Assert.AreNotEqual(control.Meaning, treatment.Meaning, "the history changed what the later event meant");
            Assert.AreEqual(control.Meaning, unseen.Meaning, "an event she did not perceive changed nothing");
            Assert.AreEqual(0.0, unseen.Belief("tendency(daniel,treats_me_like_a_child)"), 1e-9, "and left no belief behind");
            Assert.AreEqual(control.Meaning, other.Meaning, "the history is about one person, not about everybody");
            Assert.AreNotEqual(control.Downstream, treatment.Downstream, "and the difference reached what she wants");
        }

        // ---- 2 ----

        [Test]
        public void E2_TheResponseCurve()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 2. The response curve: how much history it takes");
            sb.AppendLine();
            sb.AppendLine("The same arm, run again for every number of earlier times from none to fourteen. A hidden modifier would move behaviour a little at every step. The architecture predicts a flat stretch and then a step, because the only way a belief about a person can reach a feeling is by changing which reading wins.");
            sb.AppendLine();
            sb.AppendLine("| Earlier times | Belief `treats_me_like_a_child` | `disrespect` would score | Read it as | Stirred | `restore_standing` | `keep_peace` | Chose |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");

            var rows = new List<S17Chain>();
            for (var n = 0; n <= 14; n++)
            {
                var c = S17.Run(_content, Base(n + " earlier times").With(a => a.PriorSlights = n));
                rows.Add(c);
                var disrespectScore = Weight(c, "your_things_gone_through");
                sb.AppendLine("| " + n + " | " + S17.F(c.Belief("tendency(daniel,treats_me_like_a_child)")) + " | " + S17.F(disrespectScore) + " | " +
                              c.Meaning + " " + S17.F(c.Weight) + " | " +
                              string.Join(", ", c.ProbeEmotions.OrderByDescending(e => e.Value).Take(2).Select(e => e.Key + " " + S17.F(e.Value))) + " | " +
                              S17.F(c.Want("restore_standing")) + " | " + S17.F(c.Want("keep_peace")) + " | " + c.Chosen + " |");
            }

            var flip = rows.FindIndex(r => r.Meaning != rows[0].Meaning);
            sb.AppendLine();
            sb.AppendLine("**The reading changes at " + flip + " earlier times.** Below that the belief climbs at every step and *nothing else moves at all*: the same reading, the same feelings to nine decimal places, the same wants, the same choice. At " + flip + " the reading flips and everything downstream changes together.");
            sb.AppendLine();
            sb.AppendLine("Every number below the flip is identical to the one before it, downstream of the reading: " +
                          (rows.Take(flip).Select(r => r.Downstream).Distinct().Count() == 1 ? "**one distinct downstream state across all " + flip + " of them**." : "they are not all identical, which contradicts the prediction."));
            Record("2", sb.ToString());

            Assert.Greater(flip, 0, "there is a stretch where history does nothing");
            Assert.AreEqual(1, rows.Take(flip).Select(r => r.Downstream).Distinct().Count(),
                "below the flip, every downstream number is identical however much history there is");
            Assert.Greater(rows.Take(flip).Select(r => r.Belief("tendency(daniel,treats_me_like_a_child)")).Distinct().Count(), 1,
                "while the belief itself moved at every step");
            Assert.AreEqual(Many >= flip, true, "the arm used in E1 is above the flip");
        }

        static double Weight(S17Chain c, string ruleId)
        {
            if (c.RulesDetail == null) return 0.0;
            foreach (var part in c.RulesDetail.Split('|'))
            {
                var bit = part.Trim();
                if (!bit.StartsWith(ruleId + " ", StringComparison.Ordinal)) continue;
                var after = bit.Substring(bit.IndexOf("-> ", StringComparison.Ordinal) + 3);
                var number = after.Split(' ')[1];
                if (double.TryParse(number, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var v)) return v;
            }
            return 0.0;
        }

        // ---- 3 ----

        [Test]
        public void E3_TheOtherKindOfBeliefMovesBehaviourContinuously()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 3. The other kind of belief, on the same instrument");
            sb.AppendLine();
            sb.AppendLine("`supplies_short` is learned the same way, from what an event meant, and it is read by a **motivation** rule rather than only by interpretation. The same subject, the same later event, the belief set to each level in turn. If the flat stretch in section 2 were an artefact of the instrument, it would show here too.");
            sb.AppendLine();
            sb.AppendLine("| `supplies_short` | `guard_supplies` want | Chose | | `treats_me_like_a_child` | `restore_standing` want | Chose |");
            sb.AppendLine("|---|---|---|---|---|---|---|");

            var world = new List<S17Chain>();
            var person = new List<S17Chain>();
            for (var i = 0; i <= 8; i++)
            {
                var level = i / 10.0;
                world.Add(S17.Run(_content, Base("supplies " + level).With(a =>
                {
                    a.PriorSlights = 0;
                    a.ForceBeliefs = new Dictionary<string, double>(StringComparer.Ordinal) { { "supplies_short()", level } };
                })));
                person.Add(S17.Run(_content, Base("child " + level).With(a =>
                {
                    a.PriorSlights = 0;
                    a.ForceBeliefs = new Dictionary<string, double>(StringComparer.Ordinal) { { "tendency(daniel,treats_me_like_a_child)", level } };
                })));
            }

            for (var i = 0; i <= 8; i++)
            {
                var level = i / 10.0;
                sb.AppendLine("| " + S17.F(level) + " | " + S17.F(world[i].Want("guard_supplies")) + " | " + world[i].Chosen + " | | " +
                              S17.F(level) + " | " + S17.F(person[i].Want("restore_standing")) + " | " + person[i].Chosen + " |");
            }
            sb.AppendLine();
            sb.AppendLine("The left-hand belief moves the want it feeds at every step, continuously, because a motivation rule reads it directly. The right-hand belief moves nothing until the reading flips. **Two beliefs, learned by the same machinery from the same kind of event, with completely different causal reach.** That is the finding of this slice.");
            Record("3", sb.ToString());

            Assert.Greater(world.Select(c => S17.F(c.Want("guard_supplies"))).Distinct().Count(), 5,
                "a belief a motivation rule reads moves the want continuously");
        }

        // ---- 4 ----

        [Test]
        public void E4_TimeDoesNotWearItOff()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 4. Time does not wear it off");
            sb.AppendLine();
            sb.AppendLine("The same history, with more and more time between it and the later event. Nothing in the code decays a belief, so the prediction is that the effect is the same however long ago it was. This is the mirror image of the memory that never faded in S1.6, and it is worth stating as a defect of the same family rather than as a success.");
            sb.AppendLine();
            sb.AppendLine("| Days between | Fades between | Belief | Read it as | Chose |");
            sb.AppendLine("|---|---|---|---|---|");
            var seen = new List<string>();
            foreach (var (days, fades) in new[] { (1, 1.0), (1, Settled), (2, Settled), (3, Settled), (30, Settled * 4) })
            {
                var c = S17.Run(_content, Base("lag").With(a => { a.PriorSlights = Many; a.LagDays = days; a.LagFades = fades; }));
                seen.Add(c.Meaning + "/" + c.Chosen);
                sb.AppendLine("| " + days + " | " + fades + " | " + S17.F(c.Belief("tendency(daniel,treats_me_like_a_child)")) + " | " +
                              c.Meaning + " " + S17.F(c.Weight) + " | " + c.Chosen + " |");
            }
            sb.AppendLine();
            sb.AppendLine("A month later it lands exactly as it did the next morning.");
            Record("4", sb.ToString());

            Assert.AreEqual(1, seen.Distinct().Count(), "the effect is the same at every lag, because no belief decays");
        }

        // ---- 5 ----

        [Test]
        public void E5_WhichLaterSituationsAreSensitiveToHistoryAtAll()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 5. Which later situations are sensitive to history at all");
            sb.AppendLine();
            sb.AppendLine("The same history against four different later events, to find out whether this is one situation fitted or a class of them. Each is aimed at the subject, on a later day, with one other person in the room, so that a rule needing an audience can fire at all.");
            sb.AppendLine();
            sb.AppendLine("| Later event | Without the history | With it | Reading changed | Anything downstream changed |");
            sb.AppendLine("|---|---|---|---|---|");

            var sensitive = new List<string>();
            foreach (var kind in new[] { S17.Search, S17.Observe, S17.Demand, S17.Refuse })
            {
                var audience = new List<string> { "daniel", "mara" };
                var c = S17.Run(_content, Base("C").With(a => { a.PriorSlights = 0; a.ProbeKind = kind; a.Present = audience; }));
                var t = S17.Run(_content, Base("T").With(a => { a.PriorSlights = Many; a.ProbeKind = kind; a.Present = audience; }));
                var flipped = c.Meaning != t.Meaning;
                var moved = c.Downstream != t.Downstream;
                if (moved) sensitive.Add(kind);
                sb.AppendLine("| `" + kind + "` | " + c.Meaning + " " + S17.F(c.Weight) + " | " + t.Meaning + " " + S17.F(t.Weight) + " | " +
                              (flipped ? "**yes**" : "no") + " | " + (moved ? "**yes**" : "no") + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**History moved the weight in three of the four, and moved the outcome in one.** The one it moved is the only one where the reading it strengthens was not already winning. Going through somebody's things is history-sensitive because two readings compete on it and history carries one of them, and which of the two wins is what decides how it feels. Being watched is read nearly two and a half times as darkly and nothing follows, because only one rule ever fires on it, so the extra weight has nothing to beat. A demand is read more darkly too, and nothing follows, because `disrespect` was already winning without any history. A refusal in front of others is read as support by this person either way; the slighted reading of it rises with history and stays second.");
            sb.AppendLine();
            sb.AppendLine("Being read *more strongly* is therefore not the same as being read *differently*, and only the second has any consequence. A later situation is sensitive to history exactly when history can change which reading wins, which needs two readings that are close and at least one of them carried by a belief that experience can write.");
            Record("5", sb.ToString());

            Assert.Contains(S17.Search, sensitive, "at least one class of later situation is sensitive to history");
        }

        // ---- 6 ----

        [Test]
        public void E6_WhetherTheChangedWantEverChangesTheAction()
        {
            // Every measurement so far ended in the same act. This asks whether
            // that is a fact about the architecture or about the one room she was
            // standing in, by running the same pair of arms in every ordinary
            // circumstance the slice can put her in.
            var sb = new StringBuilder();
            sb.AppendLine("## 6. Whether the changed want ever changes the action");
            sb.AppendLine();
            sb.AppendLine("The same two arms, in twenty-seven different immediate circumstances: three rooms, three sets of people to be with, three levels of hunger. Nothing about the history or the later event changes between them.");
            sb.AppendLine();
            sb.AppendLine("| Room | With her | Hunger | Without the history | With it | Changed | Both clear |");
            sb.AppendLine("|---|---|---|---|---|---|---|");

            var changed = 0;
            var total = 0;
            var differentReason = 0;
            var clearlyMoved = 0;
            foreach (var room in new[] { "back_room", "kitchen", "living_room" })
            foreach (var present in new[] { new List<string> { "daniel" }, new List<string> { "daniel", "mara" }, new List<string>() })
            foreach (var hunger in new[] { 0.10, 0.60, 0.95 })
            {
                var c = S17.Run(_content, Base("C").With(a => { a.PriorSlights = 0; a.Room = room; a.Present = present; a.Hunger = hunger; }));
                var t2 = S17.Run(_content, Base("T").With(a => { a.PriorSlights = Many; a.Room = room; a.Present = present; a.Hunger = hunger; }));
                total++;
                var moved = c.Chosen != t2.Chosen;
                if (moved) changed++;
                if (c.LeadingWant != t2.LeadingWant) differentReason++;
                var bothClear = c.Resolution == "clear" && t2.Resolution == "clear";
                if (moved && bothClear) clearlyMoved++;
                sb.AppendLine("| " + room + " | " + (present.Count == 0 ? "nobody" : string.Join(", ", present)) + " | " + hunger.ToString("0.00") + " | " +
                              c.Chosen + " (" + c.LeadingWant + ") | " + t2.Chosen + " (" + t2.LeadingWant + ") | " + (moved ? "**yes**" : "no") + " | " + (bothClear ? "yes" : "no") + " |");
            }
            sb.AppendLine();
            sb.AppendLine("**The act she chose differed in " + changed + " of " + total + " circumstances**, and in " + clearlyMoved +
                          " of those both sides were clear rather than settled by the seed. The reason behind the act differed in " + differentReason + " of " + total + ".");
            Record("6", sb.ToString());

            TestContext.WriteLine("changed act in " + changed + " of " + total + ", changed reason in " + differentReason);
            Assert.Greater(differentReason, 0, "the history reaches the reason for what she does");
        }

        // ---- 7 ----

        [Test, Timeout(1800000)]
        public void E7_OverAWholeMorning()
        {
            // The bench holds everything still. A morning does not: she decides
            // twenty times, and what she does changes the house, which changes
            // what everybody else does. This is the only measurement here that
            // asks whether any of it survives that.
            var sb = new StringBuilder();
            sb.AppendLine("## 7. Over a whole morning");
            sb.AppendLine();
            sb.AppendLine("The history is written into the backstory, on day 3, and the ordinary morning is run with it and without it on the same seeds. The condition is `elena_fed_mara`, so the subject is answerable for what is missing and both readings of being searched are live, exactly as on the bench. Compared against the S1.1 noise floor: two pools of twenty seeds of the *same* world, to see how much of any difference is just the dice.");
            sb.AppendLine();

            IReadOnlyDictionary<string, double> Pool(Scenario001Content content, ulong from, string who)
            {
                var counts = new Dictionary<string, double>(StringComparer.Ordinal);
                var total = 0;
                for (var seed = from; seed < from + 20; seed++)
                {
                    var run = Scenario001.Run(content, "elena_fed_mara", seed);
                    foreach (var a in run.Result.By(who))
                    {
                        counts.TryGetValue(a.Action.KindName, out var n);
                        counts[a.Action.KindName] = n + 1;
                        total++;
                    }
                }
                return counts.ToDictionary(k => k.Key, k => k.Value / Math.Max(1, total), StringComparer.Ordinal);
            }

            var withIt = S17.WithHistory(_content, Many, "daniel", "elena");
            sb.AppendLine("| Who | Effect of the history | Noise, no history | Noise, with history | Effect / noise | Above the noise |");
            sb.AppendLine("|---|---|---|---|---|---|");
            var anyAbove = false;
            foreach (var who in S17.People)
            {
                var c1 = Pool(_content, 201, who); var c2 = Pool(_content, 221, who);
                var t1 = Pool(withIt, 201, who); var t2 = Pool(withIt, 221, who);
                var effect = (BatchRunner.HowDifferent(t1, c2) + BatchRunner.HowDifferent(t2, c1)) / 2;
                var nc = BatchRunner.HowDifferent(c1, c2);
                var nt = BatchRunner.HowDifferent(t1, t2);
                var noise = Math.Max(nc, nt);
                var above = effect > noise * 1.5;
                if (above) anyAbove = true;
                sb.AppendLine("| " + who + " | " + S17.F(effect) + " | " + S17.F(nc) + " | " + S17.F(nt) + " | " +
                              (noise == 0 ? "n/a" : (effect / noise).ToString("0.0")) + " | " + (above ? "**yes**" : "no") + " |");
            }
            sb.AppendLine();
            sb.AppendLine("Seeds 201 to 240, which no test has used before.");
            sb.AppendLine();

            // The prediction as it was written: one earlier time, one shared seed.
            var once = S17.WithHistory(_content, 1, "daniel", "elena");
            var same = 0;
            for (ulong seed = 241; seed <= 250; seed++)
            {
                var a = Scenario001.Run(_content, "elena_fed_mara", seed).Result.By("elena").Select(x => x.Minute + ":" + x.Action.Key);
                var b = Scenario001.Run(once, "elena_fed_mara", seed).Result.By("elena").Select(x => x.Minute + ":" + x.Action.Key);
                if (a.SequenceEqual(b)) same++;
            }
            sb.AppendLine("With **one** earlier time rather than " + Many + ", on ten shared seeds, the subject's morning was identical in " + same + " of 10.");
            Record("7", sb.ToString());

            TestContext.WriteLine("any above the noise: " + anyAbove);
        }

        // ---- 8 ----

        [Test]
        public void E8_TheWholePathReconstructsFromTheTraceAlone()
        {
            var t = S17.Run(_content, Base("T").With(a => a.PriorSlights = Many));

            // Everything the decision rests on, walked back. The question is
            // whether the earliest thing that happened to her is in there.
            var chain = t.Trace.Chain(t.DecisionTraceId).ToList();
            var reached = chain.Where(r => r.EventId != null && t.HistoryEventIds.Contains(r.EventId)).ToList();
            var earliest = t.HistoryEventIds.First();

            var sb = new StringBuilder();
            sb.AppendLine("## 8. The whole path, from the trace alone");
            sb.AppendLine();
            sb.AppendLine("Everything the final decision rests on is walked back through its parents. The decision record has " + chain.Count +
                          " records behind it, of which " + reached.Count + " belong to one of the " + t.HistoryEventIds.Count + " earlier times.");
            sb.AppendLine();
            sb.AppendLine("The reading of the later event, written out as the trace holds it. Every `because` below is a real parent link, not a reconstruction:");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.Append(t.Trace.Why(t.InterpretationTraceId));
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("Reading it from the bottom up: she went through that this morning because of what she believes about him, and she believes it because of what he did on each of those earlier days, each of which she was there for and made something of at the time. Nothing in that path is a stored conclusion; every step is the record of a stage that ran.");
            sb.AppendLine();

            var kinds = chain.GroupBy(r => r.Kind).OrderBy(g => g.Key.ToString(), StringComparer.Ordinal);
            sb.AppendLine("What the decision rests on, by kind of record: " +
                          string.Join(", ", kinds.Select(g => g.Key + " " + g.Count())) + ".");
            Record("8", sb.ToString());

            Assert.IsTrue(chain.Any(r => r.EventId == earliest),
                "the decision walks back to the first thing he ever did to her");
            Assert.IsTrue(chain.Any(r => r.Kind == TraceKind.Motive), "and through a want");
            Assert.IsTrue(chain.Any(r => r.Kind == TraceKind.Appraisal), "and through a feeling");
            Assert.IsTrue(chain.Any(r => r.Kind == TraceKind.BeliefChange), "and through a belief that moved");
            Assert.IsTrue(chain.Any(r => r.Kind == TraceKind.Interpretation), "and through a reading");
        }
    }
}
