using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The same-act experiment: several wants reach for the same physical act.
    /// When one of them does, can the simulation keep hold of *which* one, and
    /// does anything read it?
    ///
    /// Three questions, kept apart: whether the distinction can be represented,
    /// whether it survives act -> event -> perception -> appraisal, and whether
    /// it ever reaches behaviour. A failure at the third is not a failure at the
    /// first.
    ///
    /// The act is `check_pantry`, which four wants propose. It is held fixed:
    /// the arms run identically up to the minute the act finishes, and the only
    /// difference between them is the intention carried onto the event it
    /// becomes, through the `IntentOfAct` hook the intent-carrying experiment
    /// added. The hook stays unset everywhere else, and nothing about wants,
    /// rules, numbers, appraisal, interpretation or the action model was
    /// changed for this. There is no new code in `Fallow.Core` at all.
    ///
    /// Writes `Docs/experiments/same-act-different-reason/measurements.md`.
    /// </summary>
    public class SameActExperimentTests
    {
        const int Seeds = 10;

        /// <summary>The wants that propose `check_pantry`, in the order the file lists them.</summary>
        static readonly string[] ReachForIt = { "get_food", "guard_supplies", "find_out", "restore_standing" };

        static Scenario001Content _content;
        static IReadOnlyList<string> _intentions;

        /// <summary>Baseline mornings, kept so that four tests do not each run fifty of them.</summary>
        static readonly Dictionary<string, Watch> _cache = new Dictionary<string, Watch>(StringComparer.Ordinal);
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        [OneTimeSetUp]
        public void Load()
        {
            _content = Baselines.Primary();
            _intentions = _content.Vocabulary.SelfMeanings.OrderBy(s => s, StringComparer.Ordinal).ToList();
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Same act, different reason: measurements");
            sb.AppendLine();
            sb.AppendLine("Generated by `SameActExperimentTests` on the primary baseline. One physical act is held fixed and only the intention carried onto the event it becomes is varied, through the `IntentOfAct` hook, which is unset in every baseline arm. The random stream is forked per person and minute from the seed, so it cannot shift between arms.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "same-act-different-reason");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "measurements.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => v.ToString("0.000", CultureInfo.InvariantCulture);
        static string Or(string s) => string.IsNullOrEmpty(s) ? "none" : s;

        static string Pc(double part, double whole)
            => whole == 0 ? "n/a" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + " %";

        // ------------------------------------------------------------------ watching a run

        sealed class Snap
        {
            public int Minute;
            public string Who;
            public string Chosen;
            public string Leading;
            public double Urgency;
            public double Margin;
            public string Commitment;
            public Resolution Resolution;
            public string Options;
            public Dictionary<string, double> Wants = new Dictionary<string, double>(StringComparer.Ordinal);

            public string Line => "m" + Minute + " " + Who + " " + Chosen + " for " + Or(Leading);
        }

        sealed class Watch
        {
            public string Label;
            public string Intent;
            public List<Snap> Decisions = new List<Snap>();
            public IReadOnlyList<ActionRecord> Actions;
            public IReadOnlyList<WorldEvent> Events;
            public IReadOnlyDictionary<string, Mind> Minds;
            public TraceLog Trace;
            public string Fingerprint;

            public Snap NextAfter(string who, int minute)
                => Decisions.FirstOrDefault(d => d.Who == who && d.Minute >= minute);

            public WorldEvent ActEvent(string who, string action, int minute)
                => Events.FirstOrDefault(e => e.ActorId == who && e.Action == action && e.Minute == minute);
        }

        static Watch Run(string label, string variant, ulong seed,
            Func<Scenario001Run, Func<string, ActionOption, Decision, string>> intends, string intentLabel = null)
        {
            var run = Scenario001.Prepare(_content, variant, seed);
            if (intends != null) run.Morning.IntentOfAct = intends(run);
            var w = new Watch { Label = label, Intent = intentLabel };
            run.Morning.Decided = m =>
            {
                var d = m.Decision;
                var s = new Snap
                {
                    Minute = m.Minute,
                    Who = m.CharacterId,
                    Chosen = d.Chosen.Key,
                    Leading = d.Leading?.Key,
                    Urgency = d.Leading?.Urgency ?? 0.0,
                    Margin = d.Margin,
                    Commitment = d.Commitment,
                    Resolution = d.Resolution,
                    Options = string.Join("; ", d.Considered.Take(4).Select(r =>
                        r.Option.Key + " " + r.Score.ToString("+0.000;-0.000", CultureInfo.InvariantCulture)))
                };
                foreach (var x in m.Motives) s.Wants[x.Key] = x.Urgency;
                w.Decisions.Add(s);
            };
            run.Morning.Run(_content.Morning.Minutes);
            w.Actions = run.Result.Actions;
            w.Events = run.Result.Events;
            w.Minds = run.Minds;
            w.Trace = run.Trace;
            w.Fingerprint = string.Join("\n", w.Actions.Select(a =>
                a.ToString() + " | " + a.Resolution + " " + a.Margin.ToString("R", CultureInfo.InvariantCulture)));
            return w;
        }

        /// <summary>
        /// Carries one intention onto one person's pantry-check, the one that
        /// finishes at a given minute, and onto nothing else. The minute
        /// identifies the act exactly: an act makes its event when it finishes,
        /// and the arms run identically up to that point.
        /// </summary>
        static Func<Scenario001Run, Func<string, ActionOption, Decision, string>> OnTheCheckFinishingAt(
            string who, int minute, string intent)
            => run => (actor, action, decision) =>
                actor == who && action.Kind == ActionKind.CheckPantry && run.World.Minute == minute ? intent : null;

        /// <summary>A hook that carries nothing, to show the hook itself changes nothing.</summary>
        static readonly Func<Scenario001Run, Func<string, ActionOption, Decision, string>> CarriesNothing =
            run => (actor, action, decision) => null;

        // ------------------------------------------------------------------ the case

        sealed class Case
        {
            public string Variant;
            public ulong Seed;
            public string Who;
            public int Started;
            public int Finished;
            public string Leading;
            public double Urgency;
            public ActionRecord Record;
            public Watch Baseline;
            public WorldEvent Event;
            public IReadOnlyList<string> Witnesses;
        }

        static Case At(Watch w, string variant, ulong seed, ActionRecord a)
        {
            var finished = a.Minute + a.Action.Duration;
            var e = w.ActEvent(a.CharacterId, "count_supplies", finished);
            if (e == null) return null;
            return new Case
            {
                Variant = variant,
                Seed = seed,
                Who = a.CharacterId,
                Started = a.Minute,
                Finished = finished,
                Leading = a.LeadingMotive,
                Urgency = a.LeadingUrgency,
                Record = a,
                Baseline = w,
                Event = e,
                Witnesses = e.Witnesses.Where(x => x != a.CharacterId).OrderBy(x => x, StringComparer.Ordinal).ToList()
            };
        }

        /// <summary>Every pantry-check in the design conditions that ran its course and became an event.</summary>
        static List<Case> AllChecks()
        {
            var found = new List<Case>();
            foreach (var v in _content.Morning.Variants.Select(x => x.Id))
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var key = v + "#" + seed;
                if (!_cache.TryGetValue(key, out var w)) _cache[key] = w = Run("baseline", v, seed, null);
                foreach (var a in w.Actions.Where(x => x.Action.Kind == ActionKind.CheckPantry))
                {
                    var c = At(w, v, seed, a);
                    if (c != null) found.Add(c);
                }
            }
            return found;
        }

        /// <summary>
        /// The case the rest of the experiment holds fixed: a real pantry-check,
        /// led by one of the wants the brief names, and seen by somebody, so that
        /// the witness question can be asked of the same act.
        /// </summary>
        static Case Fixed()
        {
            var all = AllChecks();
            foreach (var want in new[] { "find_out", "restore_standing", "get_food", "guard_supplies" })
            {
                var c = all.FirstOrDefault(x => x.Leading == want && x.Witnesses.Count > 0);
                if (c != null) return c;
            }
            foreach (var want in new[] { "find_out", "restore_standing", "get_food", "guard_supplies" })
            {
                var c = all.FirstOrDefault(x => x.Leading == want);
                if (c != null) return c;
            }
            return all.FirstOrDefault();
        }

        // ------------------------------------------------------------------ reading one arm

        static string ReadingOf(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "no event";
            var x = w.Minds[who].Experiences.LastOrDefault(k => k.EventId == e.Id);
            if (x == null) return "nothing kept";
            return x.Meaning + (x.FromOwnIntent ? " (own intention)" : " (" + x.Access.ToString().ToLowerInvariant() + ")");
        }

        static string KeptAs(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "-";
            var x = w.Minds[who].Experiences.LastOrDefault(k => k.EventId == e.Id);
            return x == null ? "nothing kept" : x.Meaning + ", salience " + F(x.Salience) + ", felt " + Or(x.DominantEmotion);
        }

        static string InterpretationOf(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "-";
            var r = w.Trace.ForEvent(e.Id).FirstOrDefault(x => x.CharacterId == who && x.Kind == TraceKind.Interpretation);
            if (r == null) return "-";
            var weight = r.Data.TryGetValue("weight", out var wt) ? wt : "1.00";
            var runner = r.Data.TryGetValue("runner_up", out var ru) ? ru : "none";
            return r.Summary + " (weight " + weight + ", runner-up " + runner + ")";
        }

        static string AccessOf(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "-";
            var r = w.Trace.ForEvent(e.Id).FirstOrDefault(x => x.CharacterId == who && x.Kind == TraceKind.Access);
            return r == null ? "-" : r.Summary;
        }

        static string StirredBy(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "-";
            var appraisals = w.Trace.ForEvent(e.Id)
                .Where(r => r.CharacterId == who && r.Kind == TraceKind.Appraisal)
                .Select(r => r.Data.TryGetValue("rules", out var rules)
                    ? r.Data["emotion"] + " " + r.Data["intensity"] + " [" + rules.Split(' ')[0] + "]"
                    : r.Summary)
                .ToList();
            return appraisals.Count == 0 ? "nothing" : string.Join("; ", appraisals);
        }

        static string FeelingsAt(Watch w, string who)
            => string.Join(", ", w.Minds[who].Emotions.Live.OrderBy(e => e.Type, StringComparer.Ordinal)
                   .Select(e => e.Type + (e.TargetId == null ? "" : ":" + e.TargetId) + " " + F(e.Intensity)));

        static string BeliefsOf(Watch w, string who)
            => string.Join(", ", w.Minds[who].Beliefs.All.Where(b => b.Confidence > 0.0)
                   .Select(b => b.Key + " " + F(b.Confidence)));

        static string NudgesFrom(Watch w, string who, WorldEvent e)
        {
            if (e == null) return "-";
            var nudges = w.Trace.ForEvent(e.Id)
                .Where(r => r.CharacterId == who && r.Kind == TraceKind.BeliefChange)
                .Select(r => r.Summary).ToList();
            return nudges.Count == 0 ? "none" : string.Join("; ", nudges);
        }

        static string WantsLine(Snap s)
            => s == null ? "-" : string.Join(", ", s.Wants.OrderByDescending(k => k.Value)
                   .ThenBy(k => k.Key, StringComparer.Ordinal).Select(k => k.Key + " " + F(k.Value)));

        /// <summary>The first decision anywhere in the morning that differs from the baseline.</summary>
        static string FirstDivergence(Watch baseline, Watch arm)
        {
            var n = Math.Min(baseline.Decisions.Count, arm.Decisions.Count);
            for (var i = 0; i < n; i++)
            {
                var b = baseline.Decisions[i];
                var a = arm.Decisions[i];
                if (b.Minute == a.Minute && b.Who == a.Who && b.Chosen == a.Chosen && b.Leading == a.Leading) continue;
                return "m" + a.Minute + " " + a.Who + ": " + b.Chosen + " for " + Or(b.Leading)
                     + " -> " + a.Chosen + " for " + Or(a.Leading);
            }
            if (baseline.Decisions.Count != arm.Decisions.Count)
                return "same decisions, different count (" + baseline.Decisions.Count + " -> " + arm.Decisions.Count + ")";
            return "none";
        }

        // ================================================================== M1

        [Test]
        public void FourWantsReachForTheSamePhysicalAct()
        {
            var all = AllChecks();

            var sb = new StringBuilder();
            sb.AppendLine("## M1. Four wants, one physical act");
            sb.AppendLine();
            sb.AppendLine("Every proposal in the shipped file that asks for `check_pantry`, and then the first real act in a live morning led by each of those wants.");
            sb.AppendLine();
            sb.AppendLine("| Proposal | Want | Fit |");
            sb.AppendLine("|---|---|---|");
            foreach (var p in _content.Rules.Proposals.Where(p => p.Action == "check_pantry"))
                sb.AppendLine("| `" + p.Id + "` | `" + p.Motive + "` | " + F(p.Fit) + " |");
            sb.AppendLine();

            sb.AppendLine("| Want | Found | Who | Minute | Urgency | Chosen | Margin | Resolution | Commitment | Target | Destination | What was considered |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|---|");
            var found = 0;
            foreach (var want in ReachForIt)
            {
                var c = all.FirstOrDefault(x => x.Leading == want);
                if (c == null)
                {
                    sb.AppendLine("| `" + want + "` | **no** | - | - | - | - | - | - | - | - | - | led no pantry-check in "
                                  + (_content.Morning.Variants.Count * Seeds) + " mornings |");
                    continue;
                }
                found++;
                var snap = c.Baseline.Decisions.FirstOrDefault(d => d.Who == c.Who && d.Minute == c.Started);
                sb.AppendLine("| `" + want + "` | yes | " + c.Who + " | m" + c.Started + " | " + F(c.Urgency)
                              + " | " + c.Record.Action.Key + " | " + F(c.Record.Margin) + " | " + c.Record.Resolution
                              + " | " + Or(snap?.Commitment) + " | " + Or(c.Record.Action.TargetId)
                              + " | " + Or(c.Record.Action.DestinationRoomId) + " | " + Or(snap?.Options) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("And the event each act became:");
            sb.AppendLine();
            sb.AppendLine("| Want | Event action | Actor | Target | Topic | Valence | Intent | Witnesses | Summary |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|");
            foreach (var want in ReachForIt)
            {
                var c = all.FirstOrDefault(x => x.Leading == want);
                if (c == null) continue;
                sb.AppendLine("| `" + c.Leading + "` | `" + c.Event.Action + "` | " + c.Event.ActorId + " | "
                              + Or(c.Event.TargetId) + " | " + Or(c.Event.Topic) + " | " + c.Event.Valence + " | **"
                              + Or(c.Event.Intent) + "** | " + (c.Witnesses.Count == 0 ? "nobody" : string.Join(", ", c.Witnesses))
                              + " | " + c.Event.Summary + " |");
            }
            sb.AppendLine();

            var shapes = all.Select(c => c.Event.Action + "|" + Or(c.Event.TargetId) + "|" + Or(c.Event.Topic) + "|" + Or(c.Event.Intent))
                .Distinct().Count();
            sb.AppendLine("**" + all.Count + " real pantry-checks across " + (_content.Morning.Variants.Count * Seeds)
                          + " mornings, led by " + all.Select(c => c.Leading).Distinct().Count()
                          + " different wants. Distinct event shapes, ignoring valence and the sentence: " + shapes + ".**");
            sb.AppendLine();
            sb.AppendLine("Valence is `bad` when the count is low and `neutral` otherwise, so it reports the state of the shelf and not the reason for looking. The sentence is about the shelf for the same reason. Nothing on the event says which want sent him.");
            Record("M1", sb.ToString());

            Assert.GreaterOrEqual(found, 3, "at least three wants must really lead this act for the experiment to mean anything");
            foreach (var c in all)
            {
                Assert.AreEqual("count_supplies", c.Event.Action);
                Assert.IsNull(c.Event.Intent, "no act carries an intent on the baseline");
            }
            Assert.AreEqual(1, shapes, "every pantry-check makes the same shape of event");
        }

        // ================================================================== M2

        [Test]
        public void OneActUnderEveryShippedIntention()
        {
            var c = Fixed();
            Assert.IsNotNull(c, "no pantry-check to hold fixed");

            var arms = new List<Watch>
            {
                Run("baseline: no hook", c.Variant, c.Seed, null),
                Run("control: hook set, carries nothing", c.Variant, c.Seed, CarriesNothing)
            };
            foreach (var intent in _intentions)
                arms.Add(Run("intent `" + intent + "`", c.Variant, c.Seed,
                    OnTheCheckFinishingAt(c.Who, c.Finished, intent), intent));

            var sb = new StringBuilder();
            sb.AppendLine("## M2. One act, every intention the vocabulary has");
            sb.AppendLine();
            sb.AppendLine("**The act.** " + c.Who + " checks the pantry, decided at m" + c.Started + " and finishing at m"
                          + c.Finished + ", led by `" + c.Leading + "` at urgency " + F(c.Urgency)
                          + ". Condition `" + c.Variant + "`, seed " + c.Seed + ". Witnessed by "
                          + (c.Witnesses.Count == 0 ? "nobody" : string.Join(", ", c.Witnesses)) + ".");
            sb.AppendLine();
            sb.AppendLine("Every arm is the same morning with the same seed, and the arms are identical up to m" + c.Finished
                          + " by construction: the intention is attached at the moment the act becomes an event, and nothing before that can see it.");
            sb.AppendLine();

            sb.AppendLine("### The event");
            sb.AppendLine();
            sb.AppendLine("| Arm | Event | Action | Target | Topic | Valence | **Intent on the event** | Same sentence |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");
            foreach (var w in arms)
            {
                var e = w.ActEvent(c.Who, "count_supplies", c.Finished);
                sb.AppendLine("| " + w.Label + " | " + (e == null ? "**missing**" : "yes") + " | " + (e == null ? "-" : e.Action)
                              + " | " + (e == null ? "-" : Or(e.TargetId)) + " | " + (e == null ? "-" : Or(e.Topic))
                              + " | " + (e == null ? "-" : e.Valence) + " | " + (e == null ? "-" : "`" + Or(e.Intent) + "`")
                              + " | " + (e == null ? "-" : (e.Summary == c.Event.Summary ? "yes" : "**no**")) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### What the actor made of his own act");
            sb.AppendLine();
            sb.AppendLine("| Arm | Access | Interpretation | Kept as | Appraisal rules that fired | Belief nudges |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var w in arms)
            {
                var e = w.ActEvent(c.Who, "count_supplies", c.Finished);
                sb.AppendLine("| " + w.Label + " | " + AccessOf(w, c.Who, e) + " | " + InterpretationOf(w, c.Who, e)
                              + " | " + KeptAs(w, c.Who, e) + " | " + StirredBy(w, c.Who, e) + " | " + NudgesFrom(w, c.Who, e) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### And what came of it");
            sb.AppendLine();
            sb.AppendLine("| Arm | Feelings at the end of the morning | Next decision after the act | Wants at that decision |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var w in arms)
            {
                var next = w.NextAfter(c.Who, c.Finished);
                sb.AppendLine("| " + w.Label + " | " + Or(FeelingsAt(w, c.Who)) + " | " + (next == null ? "none" : next.Line)
                              + " | " + WantsLine(next) + " |");
            }
            sb.AppendLine();
            sb.AppendLine("Beliefs at the end of the morning, for the same person:");
            sb.AppendLine();
            sb.AppendLine("| Arm | Beliefs |");
            sb.AppendLine("|---|---|");
            foreach (var w in arms)
                sb.AppendLine("| " + w.Label + " | " + Or(BeliefsOf(w, c.Who)) + " |");
            sb.AppendLine();

            var carried = _intentions.Count(i => arms.First(x => x.Intent == i)
                .ActEvent(c.Who, "count_supplies", c.Finished)?.Intent == i);
            sb.AppendLine("**The intention survived execution onto the event in " + carried + " of " + _intentions.Count
                          + " arms.** The two control arms carry none, as they should.");
            Record("M2", sb.ToString());

            foreach (var intent in _intentions)
            {
                var w = arms.First(x => x.Intent == intent);
                var e = w.ActEvent(c.Who, "count_supplies", c.Finished);
                Assert.IsNotNull(e, intent + ": the act must still become an event");
                Assert.AreEqual(intent, e.Intent, intent + ": the intention must reach the event");
                Assert.AreEqual(c.Event.Summary, e.Summary, intent + ": the physical act must be unchanged");
                Assert.AreEqual(c.Event.Action, e.Action);
                Assert.AreEqual(c.Event.Valence, e.Valence);
                Assert.AreEqual(c.Event.TargetId, e.TargetId);
            }
        }

        // ================================================================== M3

        [Test]
        public void RemovingTheIntentionRestoresTheBaselineExactly()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## M3. Taking the intention away");
            sb.AppendLine();
            sb.AppendLine("The null condition has to reproduce the existing behaviour exactly, or nothing else here means anything. Two ways of having no intention, over every condition and every seed, against the morning with no hook at all.");
            sb.AppendLine();
            sb.AppendLine("| Condition | Seed | Hook set, carries nothing | Hook set, then removed |");
            sb.AppendLine("|---|---|---|---|");

            var same = 0;
            var total = 0;
            foreach (var v in _content.Morning.Variants.Select(x => x.Id))
            for (ulong seed = 1; seed <= (ulong)Seeds; seed++)
            {
                var a = Run("no hook", v, seed, null);
                var b = Run("inert hook", v, seed, CarriesNothing);

                var run = Scenario001.Prepare(_content, v, seed);
                run.Morning.IntentOfAct = (actor, action, decision) => "assert_authority";
                run.Morning.IntentOfAct = null;
                run.Morning.Run(_content.Morning.Minutes);
                var removed = string.Join("\n", run.Result.Actions.Select(x =>
                    x.ToString() + " | " + x.Resolution + " " + x.Margin.ToString("R", CultureInfo.InvariantCulture)));

                var ok1 = a.Fingerprint == b.Fingerprint;
                var ok2 = a.Fingerprint == removed;
                total++;
                if (ok1 && ok2) same++;
                if (!ok1 || !ok2 || seed == 1)
                    sb.AppendLine("| `" + v + "` | " + seed + " | " + (ok1 ? "identical" : "**differs**")
                                  + " | " + (ok2 ? "identical" : "**differs**") + " |");

                Assert.AreEqual(a.Fingerprint, b.Fingerprint, v + " seed " + seed + ": an inert hook must change nothing");
                Assert.AreEqual(a.Fingerprint, removed, v + " seed " + seed + ": removing the hook must restore the baseline");
                Assert.IsTrue(a.Events.All(e => e.Intent == null || e.Minute < 0),
                    v + " seed " + seed + ": no morning event carries an intent on the baseline");
            }
            sb.AppendLine();
            sb.AppendLine("**" + same + " of " + total + " mornings identical on both.** Every act, every margin to full precision, every resolution. Only the first seed of each condition is listed; a difference anywhere would have been listed and would have failed the test.");
            Record("M3", sb.ToString());
        }

        // ================================================================== M4

        [Test]
        public void WhatTheWitnessGets()
        {
            var c = Fixed();
            Assert.IsNotNull(c);

            var sb = new StringBuilder();
            sb.AppendLine("## M4. The witness");
            sb.AppendLine();

            var witness = c.Witnesses.FirstOrDefault();
            if (witness == null)
            {
                sb.AppendLine("Nobody was in the room for the fixed act, so there is no witness to ask.");
                Record("M4", sb.ToString());
                Assert.Ignore("no witness to the fixed act");
                return;
            }

            sb.AppendLine("The actor is " + c.Who + "; the witness is " + witness
                          + ". Neither is told anything by the experiment. The witness responds only to what the existing perception system hands them.");
            sb.AppendLine();
            sb.AppendLine("| Arm | Witness access | Witness interpretation | Kept as | Appraisal | Belief nudges | Their next decision |");
            sb.AppendLine("|---|---|---|---|---|---|---|");

            var rows = new List<Watch> { Run("baseline", c.Variant, c.Seed, null) };
            foreach (var intent in _intentions)
                rows.Add(Run("intent `" + intent + "`", c.Variant, c.Seed,
                    OnTheCheckFinishingAt(c.Who, c.Finished, intent), intent));

            var readings = new List<string>();
            foreach (var w in rows)
            {
                var e = w.ActEvent(c.Who, "count_supplies", c.Finished);
                var next = w.NextAfter(witness, c.Finished);
                var line = AccessOf(w, witness, e) + " | " + InterpretationOf(w, witness, e) + " | " + KeptAs(w, witness, e)
                           + " | " + StirredBy(w, witness, e) + " | " + NudgesFrom(w, witness, e);
                readings.Add(line);
                sb.AppendLine("| " + w.Label + " | " + line + " | " + (next == null ? "none" : next.Line) + " |");
            }
            sb.AppendLine();
            var distinct = readings.Distinct().Count();
            sb.AppendLine("**Distinct witness readings across " + rows.Count + " arms: " + distinct + ".**");
            sb.AppendLine();
            sb.AppendLine("The witness sees the act. What the actor took himself to be doing is carried on the event, and the interpreter hands somebody their own intention only when the event's actor is the perceiver themselves. So the witness reads the act by rule, as they would anybody else's. That is knowledge locality working, not a defect. Whether they are given any evidence from which to infer more is a separate question, taken up in the report.");
            Record("M4", sb.ToString());

            Assert.AreEqual(1, distinct, "the witness must get the same thing in every arm: the intention is private");
        }

        // ================================================================== M5

        [Test]
        public void WhichReadersExistForAnIntention()
        {
            var rules = _content.Rules;
            var sb = new StringBuilder();
            sb.AppendLine("## M5. Who reads an intention");
            sb.AppendLine();
            sb.AppendLine("Counted from the loaded rules, not from memory. A rule *reads* a label if it is keyed on it (`when.meanings`) or scales on a memory of it (`kind: memory`, `name: <label>`).");
            sb.AppendLine();
            sb.AppendLine("| Intention | Interpretation rules | Belief nudges | Appraisal rules | Memory scalers anywhere | Total readers |");
            sb.AppendLine("|---|---|---|---|---|---|");

            var scalers = new List<Scaler>();
            foreach (var r in rules.Interpretation) scalers.AddRange(r.ScaledBy ?? new List<Scaler>());
            foreach (var r in rules.BeliefNudges) scalers.AddRange(r.ScaledBy ?? new List<Scaler>());
            foreach (var r in rules.Appraisal) scalers.AddRange(r.ScaledBy ?? new List<Scaler>());
            foreach (var r in rules.Motivation) scalers.AddRange(r.ScaledBy ?? new List<Scaler>());
            foreach (var r in rules.Costs) scalers.AddRange(r.ScaledBy ?? new List<Scaler>());

            Func<Condition, string, bool> keyed = (w, label) =>
                w != null && w.Meanings != null && w.Meanings.Contains(label, StringComparer.Ordinal);

            var readerCount = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (var label in _intentions)
            {
                var interp = rules.Interpretation.Count(r => keyed(r.When, label));
                var nudge = rules.BeliefNudges.Count(r => keyed(r.When, label));
                var appr = rules.Appraisal.Where(r => keyed(r.When, label)).ToList();
                var mem = scalers.Count(s => s.Kind == ScalerKind.Memory && string.Equals(s.Name, label, StringComparison.Ordinal));
                var total = interp + nudge + appr.Count + mem;
                readerCount[label] = total;
                sb.AppendLine("| `" + label + "` | " + interp + " | " + nudge + " | " + appr.Count
                              + (appr.Count == 0 ? "" : " (" + string.Join(", ", appr.Select(r => "`" + r.Id + "` -> " + r.Emotion)) + ")")
                              + " | " + mem + " | **" + total + "** |");
            }
            sb.AppendLine();
            sb.AppendLine("For comparison, the same count for the meanings a person can read in somebody *else*:");
            sb.AppendLine();
            sb.AppendLine("| Meaning | Interpretation | Belief nudges | Appraisal | Memory scalers | Total |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var label in _content.Vocabulary.Meanings.OrderBy(s => s, StringComparer.Ordinal))
            {
                var interp = rules.Interpretation.Count(r => string.Equals(r.Label, label, StringComparison.Ordinal));
                var nudge = rules.BeliefNudges.Count(r => keyed(r.When, label));
                var appr = rules.Appraisal.Count(r => keyed(r.When, label));
                var mem = scalers.Count(s => s.Kind == ScalerKind.Memory && string.Equals(s.Name, label, StringComparison.Ordinal));
                sb.AppendLine("| `" + label + "` | " + interp + " | " + nudge + " | " + appr + " | " + mem
                              + " | **" + (nudge + appr + mem) + "** |");
            }
            sb.AppendLine();
            sb.AppendLine("(The interpretation column means something different in the two tables: for a meaning it is the number of rules that can *produce* it, since no rule is keyed on a meaning to produce another. For an intention it is the number keyed on it, which is what a reader is.)");
            sb.AppendLine();

            var memoryNames = scalers.Where(s => s.Kind == ScalerKind.Memory && s.Name != null)
                .Select(s => s.Name).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();
            sb.AppendLine("Every meaning any memory scaler names, anywhere in the rules: "
                          + string.Join(", ", memoryNames.Select(m => "`" + m + "`"))
                          + ". None is an intention, so a stored intention is invisible to every memory scaler there is.");
            sb.AppendLine();

            sb.AppendLine("### Attention");
            sb.AppendLine();
            sb.AppendLine("Perception scales the feeling by how readily this person notices that kind of meaning. Here is what the cast carries:");
            sb.AppendLine();
            sb.AppendLine("| Person | Attention weights | Any weight on an intention |");
            sb.AppendLine("|---|---|---|");
            foreach (var p in _content.Cast.Values.OrderBy(p => p.Id, StringComparer.Ordinal))
            {
                var onIntentions = p.AttentionWeights.Keys.Where(k => _intentions.Contains(k)).ToList();
                sb.AppendLine("| " + p.Id + " | " + (p.AttentionWeights.Count == 0 ? "none" :
                        string.Join(", ", p.AttentionWeights.OrderBy(k => k.Key, StringComparer.Ordinal)
                            .Select(k => k.Key + " " + F(k.Value))))
                    + " | " + (onIntentions.Count == 0 ? "no" : string.Join(", ", onIntentions)) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### Can the three wants the brief names say what they intend");
            sb.AppendLine();
            sb.AppendLine("The vocabulary has " + _intentions.Count + " intentions: "
                          + string.Join(", ", _intentions.Select(i => "`" + i + "`")) + ". It has "
                          + _content.Vocabulary.Set("motives").Count + " wants: "
                          + string.Join(", ", _content.Vocabulary.Set("motives").OrderBy(s => s, StringComparer.Ordinal).Select(i => "`" + i + "`"))
                          + ". They are separate sets and nothing maps between them.");
            sb.AppendLine();
            sb.AppendLine("| Want | An intention that says what it intends | Readers that intention has |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| `find_out` | none exact; `take_responsibility` is the shipped precedent (backstory p02 is a search carried out under it) but means something else | " + readerCount["take_responsibility"] + " |");
            sb.AppendLine("| `restore_standing` | `assert_authority`, paired with it in the shipped backstory (b06) | " + readerCount["assert_authority"] + " |");
            sb.AppendLine("| `get_food` | **none**; no label in the vocabulary says wanting to eat | n/a |");
            sb.AppendLine();
            sb.AppendLine("**Of the three motivations the brief names, one is expressible, one is approximable, and one cannot be said at all.**");
            Record("M5", sb.ToString());

            Assert.AreEqual(0, rules.Interpretation.Count(r => _intentions.Any(l => keyed(r.When, l))),
                "no interpretation rule reads an intention");
            Assert.AreEqual(0, rules.BeliefNudges.Count(r => _intentions.Any(l => keyed(r.When, l))),
                "no belief nudge reads an intention");
            Assert.AreEqual(0, scalers.Count(s => s.Kind == ScalerKind.Memory && _intentions.Contains(s.Name ?? "")),
                "no memory scaler reads an intention");
        }

        // ================================================================== M6

        /// <summary>
        /// One case, every intention, against what the person would have made of
        /// the act with no intention at all. Returns how many arms left him with
        /// less than the baseline and how many gave him something it did not.
        /// </summary>
        static void Displacement(Case c, StringBuilder sb, out int lost, out int gained)
        {
            var baseline = Run("baseline", c.Variant, c.Seed, null);
            var e0 = baseline.ActEvent(c.Who, "count_supplies", c.Finished);
            var x0 = baseline.Minds[c.Who].Experiences.LastOrDefault(k => k.EventId == e0.Id);
            var baseStirred = StirredBy(baseline, c.Who, e0);

            sb.AppendLine("| Arm | Actor's reading | Rules consulted | Feelings from this act | Meaning kept in memory | Against baseline |");
            sb.AppendLine("|---|---|---|---|---|---|");
            sb.AppendLine("| baseline, no intention | " + ReadingOf(baseline, c.Who, e0) + " | yes | " + baseStirred
                          + " | `" + (x0 == null ? "-" : x0.Meaning) + "` | - |");

            lost = 0;
            gained = 0;
            foreach (var intent in _intentions)
            {
                var w = Run(intent, c.Variant, c.Seed, OnTheCheckFinishingAt(c.Who, c.Finished, intent), intent);
                var e = w.ActEvent(c.Who, "count_supplies", c.Finished);
                var x = w.Minds[c.Who].Experiences.LastOrDefault(k => k.EventId == e.Id);
                var stirred = StirredBy(w, c.Who, e);
                string verdict;
                if (stirred == baseStirred) verdict = "same";
                else if (stirred == "nothing") { verdict = "**less**: the reading the rules gave, and what it stirred, are gone"; lost++; }
                else if (baseStirred == "nothing") { verdict = "**more**"; gained++; }
                else { verdict = "**different**"; gained++; }
                sb.AppendLine("| `" + intent + "` | " + ReadingOf(w, c.Who, e) + " | no | " + stirred
                              + " | `" + (x == null ? "-" : x.Meaning) + "` | " + verdict + " |");
            }
        }

        [Test]
        public void AnIntentionReplacesTheReadingTheRulesWouldHaveGiven()
        {
            var all = AllChecks();
            var c = Fixed();
            Assert.IsNotNull(c);

            var sb = new StringBuilder();
            sb.AppendLine("## M6. An intention does not only add");
            sb.AppendLine();
            sb.AppendLine("The interpreter hands an actor their own intention *instead of* running the rules, not as well as. So carrying an intention can leave a person with **less** than carrying none: whatever reading the rules would have given is gone, and so is the memory of it. Whether that costs anything depends on whether the rules had anything to say about the act, which for a pantry-check depends on how much food is left.");
            sb.AppendLine();
            sb.AppendLine("### A count that found enough");
            sb.AppendLine();
            sb.AppendLine("The fixed act: " + c.Who + " at m" + c.Finished + " in `" + c.Variant + "` seed " + c.Seed
                          + ", event valence `" + c.Event.Valence + "`.");
            sb.AppendLine();
            int lostA, gainedA;
            Displacement(c, sb, out lostA, out gainedA);
            sb.AppendLine();
            sb.AppendLine("**Arms that left him with less than no intention at all: " + lostA + " of " + _intentions.Count
                          + ". Arms that gave him something the baseline did not: " + gainedA + ".**");
            sb.AppendLine();

            var bad = all.FirstOrDefault(x => x.Event.Valence == "bad");
            sb.AppendLine("### A count that found the shelf nearly empty");
            sb.AppendLine();
            if (bad == null)
            {
                var ate = _cache.Values.Sum(w => w.Events.Count(e => e.Action == "eat_portion" && e.Minute >= 0));
                var mornings = _cache.Values.Count(w => w.Events.Any(e => e.Action == "eat_portion" && e.Minute >= 0));
                sb.AppendLine("No pantry-check in " + (_content.Morning.Variants.Count * Seeds)
                              + " mornings found the shelf low enough for the event to carry a bad valence, so the displacing case does not arise here. The morning starts with "
                              + _content.Morning.Portions + " portions and the rule that would have been displaced (`bad_news_reads_as_a_problem`) needs the count to fall to "
                              + _content.Rules.Deciding.LowPortions + " or below, which takes somebody eating: " + ate
                              + " portions were eaten in the whole set, across " + mornings + " of "
                              + (_content.Morning.Variants.Count * Seeds) + " mornings, and no check followed one.");
                sb.AppendLine();
                sb.AppendLine("So the displacement is real in the code and costs nothing here, because for this act the rules had nothing to say in the first place. **On the baseline a man counting the family's food reads it as `neutral` at weight 0.00: no interpretation rule matches `count_supplies` at all unless the shelf is nearly bare.** Carrying an intention is the only way this act means anything to anybody.");
            }
            else
            {
                sb.AppendLine("Here the event carries valence `bad`, so `bad_news_reads_as_a_problem` matches and the baseline reading is not empty. The act: " + bad.Who
                              + " at m" + bad.Finished + " in `" + bad.Variant + "` seed " + bad.Seed + ", led by `" + bad.Leading + "`.");
                sb.AppendLine();
                int lostB, gainedB;
                Displacement(bad, sb, out lostB, out gainedB);
                sb.AppendLine();
                sb.AppendLine("**Arms that left him with less than no intention at all: " + lostB + " of " + _intentions.Count
                              + ". Arms that gave him something the baseline did not: " + gainedB + ".**");
            }
            sb.AppendLine();
            sb.AppendLine("The meaning kept in memory is the intention in every intention arm, which is the representation working. Whether that memory is ever read again is M5's question, and the answer there is no.");
            Record("M6", sb.ToString());
        }

        // ================================================================== M7

        [Test]
        [Timeout(900000)]
        public void DoesAnythingLaterMove()
        {
            var cases = AllChecks();

            var sb = new StringBuilder();
            sb.AppendLine("## M7. Whether it ever reaches behaviour");
            sb.AppendLine();
            sb.AppendLine("Every real pantry-check in the design conditions, under every intention, against its own baseline. A divergence is the first decision anywhere in the house that differs.");
            sb.AppendLine();
            sb.AppendLine("| Condition | Seed | Who | m | Led by | Intention | Feelings differ at the end | A decision differs | First divergence |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|");

            var arms = 0;
            var feelingsMoved = 0;
            var decisionsMoved = 0;
            var byIntent = _intentions.ToDictionary(i => i, i => 0, StringComparer.Ordinal);
            var feelingsByIntent = _intentions.ToDictionary(i => i, i => 0, StringComparer.Ordinal);

            foreach (var c in cases)
            foreach (var intent in _intentions)
            {
                var w = Run(intent, c.Variant, c.Seed, OnTheCheckFinishingAt(c.Who, c.Finished, intent), intent);
                var baseFeel = FeelingsAt(c.Baseline, c.Who);
                var armFeel = FeelingsAt(w, c.Who);
                var diverged = FirstDivergence(c.Baseline, w);
                arms++;
                if (baseFeel != armFeel) { feelingsMoved++; feelingsByIntent[intent]++; }
                if (diverged != "none") { decisionsMoved++; byIntent[intent]++; }

                if (diverged != "none" || baseFeel != armFeel)
                    sb.AppendLine("| `" + c.Variant + "` | " + c.Seed + " | " + c.Who + " | " + c.Finished + " | `" + c.Leading
                                  + "` | `" + intent + "` | " + (baseFeel != armFeel ? "**yes**" : "no")
                                  + " | " + (diverged != "none" ? "**yes**" : "no") + " | " + diverged + " |");
            }
            sb.AppendLine();
            sb.AppendLine("Rows where nothing moved at all are left out. **" + cases.Count + " real pantry-checks x "
                          + _intentions.Count + " intentions = " + arms + " arms.**");
            sb.AppendLine();
            sb.AppendLine("| | Count | Share |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Arms where the actor's feelings still differed at the end of the morning | " + feelingsMoved + " | " + Pc(feelingsMoved, arms) + " |");
            sb.AppendLine("| Arms where any decision in the house differed | " + decisionsMoved + " | " + Pc(decisionsMoved, arms) + " |");
            sb.AppendLine();
            sb.AppendLine("Feelings are read at the end of the morning, so a `no` there does not mean nothing was ever felt: a feeling can move a decision and then fade before the morning ends, which is why the second column is larger than the first for every intention that has a reader.");
            sb.AppendLine();
            sb.AppendLine("| Intention | Appraisal readers | Arms where feelings still differed at the end | Arms where a decision moved |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var i in _intentions)
                sb.AppendLine("| `" + i + "` | "
                              + _content.Rules.Appraisal.Count(r => r.When != null && r.When.Meanings != null
                                                                    && r.When.Meanings.Contains(i, StringComparer.Ordinal))
                              + " | " + feelingsByIntent[i] + " of " + cases.Count
                              + " | " + byIntent[i] + " of " + cases.Count + " |");
            Record("M7", sb.ToString());

            Assert.Greater(cases.Count, 0, "there must be real pantry-checks to test");
        }
    }
}
