using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Fallow.Core.Model;
using Fallow.Core.Rules;
using Fallow.Core.Sim;
using Fallow.Core.Tracing;
using NUnit.Framework;

namespace Fallow.Tests.Core
{
    /// <summary>
    /// The decision-sensitivity experiment: how much must a want change before
    /// the act chosen changes, and where is the difference lost when it does not.
    ///
    /// Measures the architecture as it stands. No mechanism, rule or number is
    /// changed; decisions are only weighed again with one want moved (see
    /// <see cref="Sensitivity"/>). Writes
    /// `Docs/experiments/decision-sensitivity/results.md`.
    /// </summary>
    public class SensitivityExperimentTests
    {
        /// <summary>The census grid: every 0.1 of urgency, then each change of preference located to 0.001 by halving.</summary>
        const double CensusStep = 0.1;

        /// <summary>The grid for the cases looked at closely.</summary>
        const double FineStep = 0.01;

        /// <summary>Seed 1 of every design condition, for the census; seeds never used by any earlier measurement, for the replication.</summary>
        const ulong CensusSeed = 1;
        static readonly ulong[] ReplicationSeeds = { 401 };

        static Scenario001Content _primary;
        static Scenario001Content _modelA;
        static Scenario001Content _aFixed;
        static readonly SortedDictionary<string, string> _results = new SortedDictionary<string, string>(StringComparer.Ordinal);

        static IReadOnlyList<string> Design => _primary.Morning.Variants.Select(v => v.Id).ToList();

        /// <summary>
        /// The three architectures compared. The primary baseline; Model A as it
        /// shipped before; and Model A with the two S1.6 fixes, which differs
        /// from the primary baseline in how traits and values enter a want and in
        /// nothing else, so that the comparison is between architectures under
        /// otherwise equivalent circumstances.
        /// </summary>
        static IEnumerable<(string Label, Scenario001Content Content)> Conditions()
        {
            yield return ("B (primary)", _primary);
            yield return ("A + S1.6 fixes", _aFixed);
            yield return ("A (as shipped before)", _modelA);
        }

        [OneTimeSetUp]
        public void Load()
        {
            _primary = Baselines.Primary();
            _modelA = Baselines.ModelA(_primary);
            _aFixed = S15.Mode(_primary, DispositionMode.Standing);
        }

        [OneTimeTearDown]
        public void Write()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Decision sensitivity: results");
            sb.AppendLine();
            sb.AppendLine("Generated by `SensitivityExperimentTests`. Every decision here is a decision a morning actually took, weighed again by the unchanged deliberator with the urgency of **one** want set to another value, everything else identical: the same mind in the state it decided in, the same percept, the same other wants, the same intention carried in, the same random stream. Urgency is swept over [0, 0.995], which is every value the motivator can produce (its curves approach 1 and never reach it), and probed at 1.5, 3 and 10, which it cannot, only to tell \"needs more than the scale allows\" from \"never\".");
            sb.AppendLine();
            sb.AppendLine("**Preferred** is the option first among those considered: no randomness is involved in it. **Chosen** is what was picked with the random stream the morning used, which differs from the preferred option only when the top options are within the ambiguity band (0.08) and the seed settles it.");
            sb.AppendLine();
            foreach (var r in _results.Values) sb.AppendLine(r);
            var dir = Path.Combine(TestPaths.ProjectRoot, "Docs", "experiments", "decision-sensitivity");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "results.md"), sb.ToString());
        }

        static void Record(string key, string text)
        {
            _results[key] = text;
            TestContext.WriteLine(text);
        }

        static string F(double v) => Sensitivity.F(v);
        static string P(double part, double whole) => Sensitivity.P(part, whole);

        // ---------------------------------------------------------------- census

        sealed class Census
        {
            public string Label;
            public readonly List<MomentSweep> Moments = new List<MomentSweep>();
            public double Seconds;
            public int Decides;
            public IEnumerable<WantSweep> Pairs => Moments.Where(m => m.Faithful).SelectMany(m => m.Wants);
        }

        static Census RunCensus(string label, Scenario001Content c, IEnumerable<string> variants, IEnumerable<ulong> seeds)
        {
            var sweeper = new Sweeper(c, CensusStep) { LocateChosen = false };
            var census = new Census { Label = label };
            var clock = Stopwatch.StartNew();
            foreach (var v in variants)
            foreach (var seed in seeds)
            {
                var run = Scenario001.Prepare(c, v, seed);
                run.Morning.Decided = m =>
                {
                    var swept = sweeper.Sweep(Moment.Of(m, label, v, seed, c.Morning.Day));
                    // Only the numbers are kept: a whole decision per point would not fit.
                    foreach (var w in swept.Wants)
                    foreach (var p in w.Points) p.Decision = null;
                    swept.Moment.Mind = null;
                    census.Moments.Add(swept);
                };
                run.Morning.Run(c.Morning.Minutes);
            }
            census.Seconds = clock.Elapsed.TotalSeconds;
            census.Decides = sweeper.Decides;
            return census;
        }

        static readonly Dictionary<string, Census> _censuses = new Dictionary<string, Census>(StringComparer.Ordinal);

        static Census CensusOf(string label)
        {
            if (_censuses.TryGetValue(label, out var c)) return c;
            var content = Conditions().Single(x => x.Label == label).Content;
            c = RunCensus(label, content, Design, new[] { CensusSeed });
            _censuses[label] = c;
            return c;
        }

        static readonly string[] ClassOrder =
        {
            Sweeper.Classes.Moves, Sweeper.Classes.AlreadyItsAct, Sweeper.Classes.OutweighedWithinScale,
            Sweeper.Classes.OutweighedAlways, Sweeper.Classes.Committed, Sweeper.Classes.NoCandidate, Sweeper.Classes.CandidateOnlyPastReach
        };

        static readonly (string Label, double Max)[] DeltaBins =
        {
            ("at most 0.05", 0.05), ("0.05 to 0.10", 0.10), ("0.10 to 0.25", 0.25), ("0.25 to 0.50", 0.50), ("more than 0.50", 10.0)
        };

        static string Quantiles(IReadOnlyList<double> xs)
        {
            if (xs.Count == 0) return "none";
            var s = xs.OrderBy(x => x).ToList();
            double Q(double q) => s[(int)Math.Min(s.Count - 1, Math.Floor(q * (s.Count - 1) + 0.5))];
            return "median " + F(Q(0.5)) + " (quartiles " + F(Q(0.25)) + " to " + F(Q(0.75)) + ")";
        }

        [Test, Timeout(3600000)]
        public void X1_TheCensus_EveryDecisionEveryWant()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 1. The census: every decision, every want");
            sb.AppendLine();
            sb.AppendLine("Every decision of the five design conditions (`" + string.Join("`, `", Design) + "`), seed " + CensusSeed + ", under each architecture. At each decision every want the rules could raise there is moved on its own: the six wants about the situation once each, and wanting to look after somebody once per person present, whether or not it was raised. Grid step " + CensusStep.ToString(CultureInfo.InvariantCulture) + ", each change of the preferred option then located to 0.001 by halving (a change in what the seed chooses is read off the grid only).");
            sb.AppendLine();

            var all = Conditions().Select(x => CensusOf(x.Label)).ToList();

            sb.AppendLine("### 1.1 The instrument");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", all.Select(c => c.Label)) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")));
            sb.AppendLine("| Decisions | " + string.Join(" | ", all.Select(c => c.Moments.Count.ToString())) + " |");
            sb.AppendLine("| ... weighed again unchanged and identical to what the morning did (choice, resolution, commitment, every score to 1e-12) | " + string.Join(" | ", all.Select(c => c.Moments.Count(m => m.Faithful).ToString())) + " |");
            sb.AppendLine("| Want and decision pairs moved | " + string.Join(" | ", all.Select(c => c.Pairs.Count().ToString())) + " |");
            sb.AppendLine("| ... of which the want had been raised | " + string.Join(" | ", all.Select(c => c.Pairs.Count(w => w.Raised).ToString())) + " |");
            sb.AppendLine("| Decisions weighed | " + string.Join(" | ", all.Select(c => c.Decides.ToString("N0", CultureInfo.InvariantCulture))) + " |");
            sb.AppendLine("| Seconds | " + string.Join(" | ", all.Select(c => c.Seconds.ToString("0", CultureInfo.InvariantCulture))) + " |");
            sb.AppendLine();

            foreach (var c in all)
            {
                var bad = c.Moments.Where(m => !m.Faithful).Take(3).Select(m => m.Moment.Circumstance + ": " + m.FaithfulnessNote).ToList();
                Assert.AreEqual(c.Moments.Count, c.Moments.Count(m => m.Faithful), c.Label + " replay is not faithful: " + string.Join("; ", bad));
            }

            sb.AppendLine("### 1.2 What moving one want across its whole range does");
            sb.AppendLine();
            sb.AppendLine("Each pair is one want at one decision, moved from 0 to 0.995 with nothing else changed.");
            sb.AppendLine();
            sb.AppendLine("- **moves the act**: the preferred option is different somewhere in the range.");
            sb.AppendLine("- **already its act**: it adds to what is preferred; raising it confirms the act and removing it changes nothing.");
            sb.AppendLine("- **outweighed within the scale**: it adds to something that is never preferred at any urgency a want can have, but would be past it (1.5, 3 or 10).");
            sb.AppendLine("- **outweighed at any urgency**: never preferred even at 10.");
            sb.AppendLine("- **held off by an intention**: the person arrived with an intention that held throughout, and nothing this want adds to is among what they were deciding between.");
            sb.AppendLine("- **no candidate**: nothing available here is served by this want at any urgency.");
            sb.AppendLine("- **candidate only past reach**: something here would be served by it, but only at an urgency no want can have (a walk refused by foresight until then).");
            sb.AppendLine();
            sb.AppendLine("| Class | " + string.Join(" | ", all.Select(c => c.Label + ", all")) + " | " + string.Join(" | ", all.Select(c => c.Label + ", raised")) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")) + string.Concat(all.Select(_ => "---|")));
            foreach (var cls in ClassOrder)
                sb.AppendLine("| " + cls + " | " +
                              string.Join(" | ", all.Select(c => { var n = c.Pairs.Count(); var k = c.Pairs.Count(w => w.Class == cls); return k + " (" + P(k, n) + ")"; })) + " | " +
                              string.Join(" | ", all.Select(c => { var n = c.Pairs.Count(w => w.Raised); var k = c.Pairs.Count(w => w.Raised && w.Class == cls); return k + " (" + P(k, n) + ")"; })) + " |");
            sb.AppendLine();

            sb.AppendLine("### 1.3 How far a want has to move, when moving it changes the act");
            sb.AppendLine();
            sb.AppendLine("The smallest change, up or down from where the want actually stood, that changes the preferred option. Pairs in the class \"moves the act\" only.");
            sb.AppendLine();
            sb.AppendLine("| Nearest change | " + string.Join(" | ", all.Select(c => c.Label)) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")));
            var lo = 0.0;
            foreach (var bin in DeltaBins)
            {
                var from = lo;
                sb.AppendLine("| " + bin.Label + " | " + string.Join(" | ", all.Select(c =>
                {
                    var moving = c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.Nearest.HasValue).ToList();
                    var k = moving.Count(w => w.Nearest.Value > from && w.Nearest.Value <= bin.Max);
                    return k + " (" + P(k, moving.Count) + ")";
                })) + " |");
                lo = bin.Max;
            }
            sb.AppendLine("| Nearest change, all moving pairs | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.Nearest.HasValue).Select(w => w.Nearest.Value).ToList()))) + " |");
            sb.AppendLine();
            sb.AppendLine("Where the preferred option changes, the two options are level, so the choice there is always the seed's. Three thresholds say more: the change at which another act first becomes **possible** (it enters the ambiguity band of a decision that was clear), the change at which it becomes **preferred** (the crossing above), and the change at which it is chosen **for certain** (preferred and clear of the band, nothing left to the seed). Same pairs; possible is measured only where the decision as taken was clear.");
            sb.AppendLine();
            sb.AppendLine("| Nearest change | " + string.Join(" | ", all.Select(c => c.Label)) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")));
            sb.AppendLine("| another act becomes possible | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.NearestEnter.HasValue).Select(w => w.NearestEnter.Value).ToList()))) + " |");
            sb.AppendLine("| another act becomes preferred | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.Nearest.HasValue).Select(w => w.Nearest.Value).ToList()))) + " |");
            sb.AppendLine("| another act is chosen for certain | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.NearestClear.HasValue).Select(w => w.NearestClear.Value).ToList()))) + " |");
            sb.AppendLine("| ... pairs that move the act but never clear of the band within reach | " + string.Join(" | ", all.Select(c => { var l = c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves).ToList(); var k = l.Count(w => !w.NearestClear.HasValue); return k + " (" + P(k, l.Count) + ")"; })) + " |");
            sb.AppendLine("| Width of the seed's window, certain less possible (same pair, same direction) | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves).SelectMany(Windows).ToList()))) + " |");
            sb.AppendLine();
            foreach (var bin in new[] { 0.05, 0.10, 0.25 })
                sb.AppendLine("- Moving pairs in which a change of at most " + bin.ToString("0.00", CultureInfo.InvariantCulture) + " makes another act **certain**: " +
                              string.Join("; ", all.Select(c => { var l = c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves).ToList(); var k = l.Count(w => w.NearestClear.HasValue && w.NearestClear.Value <= bin); return c.Label + " " + k + " (" + P(k, l.Count) + ")"; })) + ".");
            sb.AppendLine();

            sb.AppendLine("### 1.4 The want that decided, and the others");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", all.Select(c => c.Label)) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")));
            sb.AppendLine("| Decisions led by some want | " + string.Join(" | ", all.Select(c => c.Pairs.Count(w => w.Leads).ToString())) + " |");
            sb.AppendLine("| ... where lowering that want to nothing changes the act | " + string.Join(" | ", all.Select(c => { var l = c.Pairs.Where(w => w.Leads).ToList(); var k = l.Count(w => w.DownTop.HasValue); return k + " (" + P(k, l.Count) + ")"; })) + " |");
            sb.AppendLine("| ... how far it has to fall first | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Leads && w.DeltaDown.HasValue).Select(w => w.DeltaDown.Value).ToList()))) + " |");
            sb.AppendLine("| ... as a share of what it was | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Leads && w.DeltaDown.HasValue && w.U0 > 0).Select(w => w.DeltaDown.Value / w.U0).ToList()))) + " |");
            sb.AppendLine("| Raised wants that did not lead | " + string.Join(" | ", all.Select(c => c.Pairs.Count(w => w.Raised && !w.Leads).ToString())) + " |");
            sb.AppendLine("| ... where raising it within reach changes the act | " + string.Join(" | ", all.Select(c => { var l = c.Pairs.Where(w => w.Raised && !w.Leads).ToList(); var k = l.Count(w => w.UpTop.HasValue && w.UpTop.Value <= Sensitivity.Reach); return k + " (" + P(k, l.Count) + ")"; })) + " |");
            sb.AppendLine("| ... how far it has to rise | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => w.Raised && !w.Leads && w.UpTop.HasValue && w.UpTop.Value <= Sensitivity.Reach).Select(w => w.DeltaUp.Value).ToList()))) + " |");
            sb.AppendLine("| ... and the act it changes to is one this want adds to | " + string.Join(" | ", all.Select(c => { var l = c.Pairs.Where(w => w.Raised && !w.Leads && w.UpTop.HasValue && w.UpTop.Value <= Sensitivity.Reach).ToList(); var k = l.Count(w => w.CreditedWithinReach.Contains(w.UpTopTo)); return k + " of " + l.Count; })) + " |");
            sb.AppendLine("| Wants not raised at all | " + string.Join(" | ", all.Select(c => c.Pairs.Count(w => !w.Raised).ToString())) + " |");
            sb.AppendLine("| ... where raising it from nothing within reach changes the act | " + string.Join(" | ", all.Select(c => { var l = c.Pairs.Where(w => !w.Raised).ToList(); var k = l.Count(w => w.UpTop.HasValue && w.UpTop.Value <= Sensitivity.Reach); return k + " (" + P(k, l.Count) + ")"; })) + " |");
            sb.AppendLine("| ... the urgency it needs | " + string.Join(" | ", all.Select(c => Quantiles(c.Pairs.Where(w => !w.Raised && w.UpTop.HasValue && w.UpTop.Value <= Sensitivity.Reach).Select(w => w.UpTop.Value).ToList()))) + " |");
            sb.AppendLine();

            sb.AppendLine("### 1.5 Preference against the seed");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", all.Select(c => c.Label)) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")));
            sb.AppendLine("| Decisions settled by the seed as taken | " + string.Join(" | ", all.Select(c => { var k = c.Moments.Count(m => m.Ambiguous); return k + " (" + P(k, c.Moments.Count) + ")"; })) + " |");
            sb.AppendLine("| Pairs where the act chosen with the morning's stream changes within reach | " + string.Join(" | ", all.Select(c => { var n = c.Pairs.Count(); var k = c.Pairs.Count(w => ChosenMovesWithinReach(w)); return k + " (" + P(k, n) + ")"; })) + " |");
            sb.AppendLine("| ... while the preferred option never does | " + string.Join(" | ", all.Select(c => { var n = c.Pairs.Count(w => ChosenMovesWithinReach(w)); var k = c.Pairs.Count(w => ChosenMovesWithinReach(w) && w.Class != Sweeper.Classes.Moves); return k + " (" + P(k, n) + ")"; })) + " |");
            sb.AppendLine("| Moving pairs whose preferred option changes more than once across the range | " + string.Join(" | ", all.Select(c => { var l = c.Pairs.Where(w => w.Class == Sweeper.Classes.Moves).ToList(); var k = l.Count(w => w.Flips > 1); return k + " (" + P(k, l.Count) + ")"; })) + " |");
            sb.AppendLine();

            sb.AppendLine("### 1.6 What there is to choose between");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", all.Select(c => c.Label)) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")));
            sb.AppendLine("| Options available, mean per decision | " + string.Join(" | ", all.Select(c => c.Moments.Average(m => m.Available).ToString("0.0", CultureInfo.InvariantCulture))) + " |");
            sb.AppendLine("| ... that some want adds to | " + string.Join(" | ", all.Select(c => c.Moments.Average(m => m.WithAppeal).ToString("0.0", CultureInfo.InvariantCulture))) + " |");
            sb.AppendLine("| ... worth more than nothing (score above 0) | " + string.Join(" | ", all.Select(c => c.Moments.Average(m => m.WorthDoing).ToString("0.0", CultureInfo.InvariantCulture))) + " |");
            foreach (var n in new[] { 1, 2, 3 })
                sb.AppendLine("| Decisions at which the acts some single want can make preferred within reach, the present one included, number " + n + " | " +
                              string.Join(" | ", all.Select(c => { var k = c.Moments.Count(m => m.Faithful && m.Reachable.Count == n); return k + " (" + P(k, c.Moments.Count) + ")"; })) + " |");
            sb.AppendLine("| ... 4 or more | " + string.Join(" | ", all.Select(c => { var k = c.Moments.Count(m => m.Faithful && m.Reachable.Count >= 4); return k + " (" + P(k, c.Moments.Count) + ")"; })) + " |");
            sb.AppendLine("| Acts reachable that way, mean per decision | " + string.Join(" | ", all.Select(c => c.Moments.Where(m => m.Faithful).Average(m => m.Reachable.Count).ToString("0.00", CultureInfo.InvariantCulture))) + " |");
            foreach (var n in new[] { 1, 2, 3, 4 })
                sb.AppendLine("| Decisions at which those acts are of exactly " + n + " kind" + (n == 1 ? "" : "s") + (n == 4 ? " or more" : "") + " | " +
                              string.Join(" | ", all.Select(c => { var k = c.Moments.Count(m => m.Faithful && (n == 4 ? m.Reachable.Select(Sensitivity.KindOf).Distinct().Count() >= 4 : m.Reachable.Select(Sensitivity.KindOf).Distinct().Count() == n)); return k + " (" + P(k, c.Moments.Count) + ")"; })) + " |");
            sb.AppendLine();

            sb.AppendLine("### 1.6b By the act that was preferred");
            sb.AppendLine();
            sb.AppendLine("How sensitive a decision is depends on what it had settled on. Standing still is the one act nothing prices: no cost rule names it.");
            sb.AppendLine();
            sb.AppendLine("| Preferred act | " + string.Join(" | ", all.Select(c => c.Label + ": decisions")) + " | " + string.Join(" | ", all.Select(c => c.Label + ": lowering the leading want to nothing changes it")) + " | " + string.Join(" | ", all.Select(c => c.Label + ": nearest change, moving pairs")) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")) + string.Concat(all.Select(_ => "---|")) + string.Concat(all.Select(_ => "---|")));
            foreach (var kind in ActionOption.AllNames)
            {
                if (!all.Any(c => c.Moments.Any(m => m.Faithful && Sensitivity.KindOf(m.Top) == kind))) continue;
                sb.AppendLine("| " + kind + " | " +
                              string.Join(" | ", all.Select(c => { var k = c.Moments.Count(m => m.Faithful && Sensitivity.KindOf(m.Top) == kind); return k + " (" + P(k, c.Moments.Count) + ")"; })) + " | " +
                              string.Join(" | ", all.Select(c =>
                              {
                                  var l = c.Moments.Where(m => m.Faithful && Sensitivity.KindOf(m.Top) == kind).SelectMany(m => m.Wants.Where(w => w.Leads)).ToList();
                                  var k = l.Count(w => w.DownTop.HasValue);
                                  return l.Count == 0 ? "-" : P(k, l.Count);
                              })) + " | " +
                              string.Join(" | ", all.Select(c => Quantiles(c.Moments.Where(m => m.Faithful && Sensitivity.KindOf(m.Top) == kind).SelectMany(m => m.Wants).Where(w => w.Class == Sweeper.Classes.Moves && w.Nearest.HasValue).Select(w => w.Nearest.Value).ToList()))) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### 1.7 Why a want that has somewhere to go stays behind");
            sb.AppendLine();
            sb.AppendLine("For the pairs outweighed (within the scale or at any urgency): at the top of the scale, is the best thing the want adds to held back by its own **price** (what the want adds cannot cover what it costs, net of other wants' support), or by **competition** (it would be worth doing, and something else is worth more)?");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", all.Select(c => c.Label)) + " |");
            sb.AppendLine("|---|" + string.Concat(all.Select(_ => "---|")));
            foreach (var why in new[] { "price", "competition" })
                sb.AppendLine("| " + why + " | " + string.Join(" | ", all.Select(c =>
                {
                    var l = c.Pairs.Where(w => w.Class == Sweeper.Classes.OutweighedWithinScale || w.Class == Sweeper.Classes.OutweighedAlways).ToList();
                    var k = l.Count(w => w.Reason != null && w.Reason.StartsWith(why, StringComparison.Ordinal));
                    return k + " (" + P(k, l.Count) + ")";
                })) + " |");
            sb.AppendLine();

            sb.AppendLine("### 1.8 Each want, under the primary baseline");
            sb.AppendLine();
            sb.AppendLine("| Want | Pairs | Raised | Urgency when raised | Moves the act | Nearest change when it does | Already its act | Outweighed | Held off | No candidate |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|");
            var b = all[0];
            foreach (var name in b.Pairs.Select(w => w.Name).Distinct().OrderBy(x => x, StringComparer.Ordinal))
            {
                var l = b.Pairs.Where(w => w.Name == name).ToList();
                var raisedU = l.Where(w => w.Raised).Select(w => w.U0).ToList();
                sb.AppendLine("| " + name + " | " + l.Count + " | " + raisedU.Count + " | " + Quantiles(raisedU) + " | " +
                              P(l.Count(w => w.Class == Sweeper.Classes.Moves), l.Count) + " | " +
                              Quantiles(l.Where(w => w.Class == Sweeper.Classes.Moves && w.Nearest.HasValue).Select(w => w.Nearest.Value).ToList()) + " | " +
                              P(l.Count(w => w.Class == Sweeper.Classes.AlreadyItsAct), l.Count) + " | " +
                              P(l.Count(w => w.Class == Sweeper.Classes.OutweighedWithinScale || w.Class == Sweeper.Classes.OutweighedAlways), l.Count) + " | " +
                              P(l.Count(w => w.Class == Sweeper.Classes.Committed), l.Count) + " | " +
                              P(l.Count(w => w.Class == Sweeper.Classes.NoCandidate || w.Class == Sweeper.Classes.CandidateOnlyPastReach), l.Count) + " |");
            }
            sb.AppendLine();

            sb.AppendLine("### 1.9 How much the wants themselves vary");
            sb.AppendLine();
            sb.AppendLine("For scale: the urgency of each want over one person's morning, as raised (primary baseline). The spread is between the 10th and 90th percentile of that person's decisions at which it was raised.");
            sb.AppendLine();
            sb.AppendLine("| Want | " + string.Join(" | ", S16.People) + " |");
            sb.AppendLine("|---|---|---|---|---|");
            foreach (var name in b.Pairs.Select(w => w.Name).Distinct().OrderBy(x => x, StringComparer.Ordinal))
                sb.AppendLine("| " + name + " | " + string.Join(" | ", S16.People.Select(who =>
                {
                    var us = b.Moments.Where(m => m.Faithful && m.Moment.Who == who).SelectMany(m => m.Wants).Where(w => w.Name == name && w.Raised).Select(w => w.U0).OrderBy(x => x).ToList();
                    if (us.Count == 0) return "never raised";
                    double Q(double q) => us[(int)Math.Min(us.Count - 1, Math.Floor(q * (us.Count - 1) + 0.5))];
                    return F(Q(0.1)) + " to " + F(Q(0.9));
                })) + " |");
            sb.AppendLine();

            Record("1", sb.ToString());
        }

        static bool ChosenMovesWithinReach(WantSweep w)
            => (w.UpChosen.HasValue && w.UpChosen.Value <= Sensitivity.Reach) || w.DownChosen.HasValue;

        /// <summary>How much of a want's range the seed decides: certain less possible, in each direction where both were found within reach.</summary>
        static IEnumerable<double> Windows(WantSweep w)
        {
            if (w.UpEnter.HasValue && w.UpClear.HasValue && w.UpClear.Value <= Sensitivity.Reach) yield return w.UpClear.Value - w.UpEnter.Value;
            if (w.DownEnter.HasValue && w.DownClear.HasValue) yield return w.DownEnter.Value - w.DownClear.Value;
        }

        [Test, Timeout(3600000)]
        public void X2_TheCensusReplicatesOnSeedsNeverUsedBefore()
        {
            var first = CensusOf("B (primary)");
            var again = RunCensus("B (primary), seeds " + string.Join(", ", ReplicationSeeds), _primary, Design, ReplicationSeeds);
            Assert.AreEqual(again.Moments.Count, again.Moments.Count(m => m.Faithful));

            var sb = new StringBuilder();
            sb.AppendLine("## 2. The same census on seeds never used before");
            sb.AppendLine();
            sb.AppendLine("The primary baseline, the five design conditions, seed " + string.Join(" and ", ReplicationSeeds) + " (no earlier measurement used it), against seed " + CensusSeed + ".");
            sb.AppendLine();
            sb.AppendLine("| | Seed " + CensusSeed + " | Seed " + string.Join(", ", ReplicationSeeds) + " |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine("| Decisions | " + first.Moments.Count + " | " + again.Moments.Count + " |");
            foreach (var cls in ClassOrder)
                sb.AppendLine("| " + cls + " | " + P(first.Pairs.Count(w => w.Class == cls), first.Pairs.Count()) + " | " + P(again.Pairs.Count(w => w.Class == cls), again.Pairs.Count()) + " |");
            sb.AppendLine("| Nearest change, moving pairs | " + Quantiles(first.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.Nearest.HasValue).Select(w => w.Nearest.Value).ToList()) + " | " +
                          Quantiles(again.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.Nearest.HasValue).Select(w => w.Nearest.Value).ToList()) + " |");
            sb.AppendLine("| Nearest change that makes another act certain, moving pairs | " + Quantiles(first.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.NearestClear.HasValue).Select(w => w.NearestClear.Value).ToList()) + " | " +
                          Quantiles(again.Pairs.Where(w => w.Class == Sweeper.Classes.Moves && w.NearestClear.HasValue).Select(w => w.NearestClear.Value).ToList()) + " |");
            sb.AppendLine("| Leading want: lowering it to nothing changes the act | " + P(first.Pairs.Count(w => w.Leads && w.DownTop.HasValue), first.Pairs.Count(w => w.Leads)) + " | " + P(again.Pairs.Count(w => w.Leads && w.DownTop.HasValue), again.Pairs.Count(w => w.Leads)) + " |");
            sb.AppendLine("| Decisions preferring to stand still | " + P(first.Moments.Count(m => Sensitivity.KindOf(m.Top) == "wait"), first.Moments.Count) + " | " + P(again.Moments.Count(m => Sensitivity.KindOf(m.Top) == "wait"), again.Moments.Count) + " |");
            sb.AppendLine("| Decisions with only the present act reachable | " + P(first.Moments.Count(m => m.Reachable.Count == 1), first.Moments.Count) + " | " + P(again.Moments.Count(m => m.Reachable.Count == 1), again.Moments.Count) + " |");
            sb.AppendLine("| Decisions settled by the seed | " + P(first.Moments.Count(m => m.Ambiguous), first.Moments.Count) + " | " + P(again.Moments.Count(m => m.Ambiguous), again.Moments.Count) + " |");
            Record("2", sb.ToString());
        }

        // ---------------------------------------------------------------- the first decision, A against B

        /// <summary>
        /// The first decision each person takes in a morning. Before anybody has
        /// decided anything, every architecture has produced the same mind in the
        /// same room: the backstory, the night and the opening are the same, and
        /// at minute 0 a memory stamped minute 0 is exactly as fresh as one with
        /// no minute. Only the wants the architecture raises from that mind, and
        /// how it credits a walk, differ. That makes it the one moment at which
        /// the architectures can be compared under identical circumstances.
        /// </summary>
        static List<T> FirstDecisions<T>(Scenario001Content c, string label, string variant, ulong seed, Func<Moment, Scenario001Run, T> look)
        {
            // Everything is done inside the callback, while the mind is in the
            // state it decided in: later in the same minute somebody else's act
            // can reach it.
            var list = new List<T>();
            var run = Scenario001.Prepare(c, variant, seed);
            var taken = new HashSet<string>(StringComparer.Ordinal);
            run.Morning.Decided = m =>
            {
                if (!taken.Add(m.CharacterId)) return;
                list.Add(look(Moment.Of(m, label, variant, seed, c.Morning.Day), run));
            };
            run.Morning.Step();
            return list;
        }

        [Test, Timeout(1800000)]
        public void X3_TheFirstDecision_UnderEachArchitecture()
        {
            var sb = new StringBuilder();
            sb.AppendLine("## 3. The first decision, under each architecture");
            sb.AppendLine();
            sb.AppendLine("Each person's first decision in each design condition (seed " + CensusSeed + "): the one moment at which the architectures see the same mind in the same room (see `FirstDecisions`). Per architecture: what was chosen, the want that led, how many of the wants the rules could raise there move the act when moved alone within reach, the smallest such change, and every act some single want could bring about.");
            sb.AppendLine();
            sb.AppendLine("| Condition | Person | Architecture | Chosen (led by) | Resolution | Wants that move the act / wants | Smallest change | Acts reachable by one want |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|");

            var summary = new Dictionary<string, (int moments, int moving, int pairs, List<double> nearest, int reach)>(StringComparer.Ordinal);
            var sameMind = 0;
            var compared = 0;
            foreach (var v in Design)
            {
                var per = Conditions().ToDictionary(x => x.Label, x => FirstDecisions(x.Content, x.Label, v, CensusSeed, (m, _) =>
                {
                    var swept = new Sweeper(x.Content, FineStep).Sweep(m);
                    // What the person perceived, remembered, felt and believed, to show it is the same.
                    var state = m.Percept + " | " + string.Join(",", m.Mind.Experiences.Select(e => e.EventId + "=" + e.Meaning)) +
                                " | " + string.Join(",", m.Mind.Emotions.Live.Select(e => e.Type + ":" + e.TargetId + "=" + e.Intensity.ToString("R", CultureInfo.InvariantCulture))) +
                                " | " + string.Join(",", m.Mind.Beliefs.All.Select(b => b.Key + "=" + b.Confidence.ToString("R", CultureInfo.InvariantCulture)));
                    swept.Moment.Mind = null;
                    return (swept, state);
                }));
                foreach (var who in S16.People)
                {
                    // The circumstance and the mind are the same under every architecture.
                    var states = per.Values.Select(x => x.First(s => s.swept.Moment.Who == who).state).Distinct().Count();
                    compared++;
                    if (states == 1) sameMind++;

                    foreach (var (label, content) in Conditions())
                    {
                        var sweep = per[label].First(x => x.swept.Moment.Who == who).swept;
                        var m = sweep.Moment;
                        Assert.IsTrue(sweep.Faithful, label + " " + m.Circumstance + ": " + sweep.FaithfulnessNote);
                        var moving = sweep.Wants.Where(w => w.Class == Sweeper.Classes.Moves).ToList();
                        var nearest = moving.Where(w => w.Nearest.HasValue).Select(w => w.Nearest.Value).ToList();
                        sb.AppendLine("| " + v + " | " + who + " | " + label + " | " + sweep.Chosen + " (" + (sweep.Leading ?? "nothing") + ") | " + (sweep.Ambiguous ? "seed" : "clear, by " + F(sweep.Margin)) + " | " +
                                      moving.Count + " / " + sweep.Wants.Count + " | " + (nearest.Count == 0 ? "-" : F(nearest.Min()) + " (" + moving.OrderBy(w => w.Nearest ?? 99).First().Key + ")") + " | " +
                                      string.Join(", ", sweep.Reachable.OrderBy(x => x, StringComparer.Ordinal)) + " |");

                        if (!summary.TryGetValue(label, out var s)) s = (0, 0, 0, new List<double>(), 0);
                        s.moments++;
                        s.moving += moving.Count;
                        s.pairs += sweep.Wants.Count;
                        s.nearest.AddRange(nearest);
                        s.reach += sweep.Reachable.Count;
                        summary[label] = s;
                    }
                }
            }
            Assert.AreEqual(compared, sameMind, "at the first decision every architecture sees the same circumstance with the same mind");

            sb.AppendLine();
            sb.AppendLine("What each person perceived, remembered, felt and believed at their first decision was identical under all three architectures in " + sameMind + " of " + compared + " cases.");
            sb.AppendLine();
            sb.AppendLine("| Architecture | Want and decision pairs that move the act | Nearest change when they do | Acts reachable by one want, mean |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var (label, _) in Conditions())
            {
                var s = summary[label];
                sb.AppendLine("| " + label + " | " + s.moving + " of " + s.pairs + " (" + P(s.moving, s.pairs) + ") | " + Quantiles(s.nearest) + " | " + (s.reach / (double)s.moments).ToString("0.00", CultureInfo.InvariantCulture) + " |");
            }
            Record("3", sb.ToString());
        }

        // ---------------------------------------------------------------- close up

        [Test, Timeout(1800000)]
        public void X4_FourDecisionsCloseUp()
        {
            // The first decision of each person on the canonical condition, under
            // the primary baseline: every want, every change, and the whole sweep
            // of the want that led.
            var sb = new StringBuilder();
            sb.AppendLine("## 4. Four decisions, close up");
            sb.AppendLine();
            sb.AppendLine("Each person's first decision on `daniel_ate_it`, seed " + CensusSeed + ", primary baseline, swept every 0.01. For each want the rules could raise: where it stood, what it adds to here, and the nearest change in each direction that changes the preferred option (and to what).");
            sb.AppendLine();

            var sweeper = new Sweeper(_primary, FineStep);
            var pages = FirstDecisions(_primary, "B (primary)", "daniel_ate_it", CensusSeed, (m, _) => CloseUp(sweeper, m));
            foreach (var page in pages.OrderBy(x => x.Who, StringComparer.Ordinal)) sb.Append(page.Text);
            Record("4", sb.ToString());
        }

        static (string Who, string Text) CloseUp(Sweeper sweeper, Moment m)
        {
            var sb = new StringBuilder();
            {
                var s = sweeper.Sweep(m);
                Assert.IsTrue(s.Faithful, s.FaithfulnessNote);
                sb.AppendLine("### " + m.Who);
                sb.AppendLine();
                sb.AppendLine(m.Circumstance + ". Chose **" + s.Chosen + "**" + (s.Leading == null ? "" : ", led by " + s.Leading) + ", " + (s.Ambiguous ? "settled by the seed among " + string.Join(", ", m.Original.Tied) : "clear by " + F(s.Margin)) + ".");
                sb.AppendLine();
                sb.AppendLine("Options, as weighed: " + string.Join("; ", m.Original.Ranked.Take(6).Select(r => r.Option.Key + " " + r.Score.ToString("+0.000;-0.000", CultureInfo.InvariantCulture))) + (m.Original.Ranked.Count > 6 ? "; and " + (m.Original.Ranked.Count - 6) + " more" : "") + ".");
                sb.AppendLine();
                sb.AppendLine("| Want | Stood at | Adds to here (within reach) | Up: preferred at | to | certain at | Down: preferred at | to | certain at | Class |");
                sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|");
                foreach (var w in s.Wants.OrderByDescending(w => w.U0).ThenBy(w => w.Key, StringComparer.Ordinal))
                    sb.AppendLine("| " + w.Key + (w.Leads ? " **(led)**" : "") + " | " + (w.Raised ? F(w.U0) : "not raised") + " | " +
                                  (w.CreditedWithinReach.Count == 0 ? "nothing" : string.Join(", ", w.CreditedWithinReach.OrderBy(x => x, StringComparer.Ordinal))) + " | " +
                                  (w.UpTop.HasValue ? F(w.UpTop.Value) + (w.UpTop.Value > Sensitivity.Reach ? " (past reach)" : " (+" + F(w.DeltaUp.Value) + ")") : "-") + " | " + (w.UpTopTo ?? "") + " | " +
                                  (w.UpClear.HasValue ? F(w.UpClear.Value) + (w.UpClear.Value > Sensitivity.Reach ? " (past reach)" : "") : "-") + " | " +
                                  (w.DownTop.HasValue ? F(w.DownTop.Value) + " (-" + F(w.DeltaDown.Value) + ")" : "-") + " | " + (w.DownTopTo ?? "") + " | " +
                                  (w.DownClear.HasValue ? F(w.DownClear.Value) : "-") + " | " + w.Class + (w.Reason == null ? "" : ": " + w.Reason) + " |");
                sb.AppendLine();

                // The want that led, across its whole range, with the seed's share.
                var lead = s.Wants.FirstOrDefault(w => w.Leads);
                if (lead != null)
                {
                    sb.AppendLine("The want that led, " + lead.Key + ", across its range (every 0.05 shown; the preferred option, what the morning's stream chose, and the share of 200 other streams that choose the act actually taken):");
                    sb.AppendLine();
                    sb.AppendLine("| Urgency | Preferred | Score | Chosen | Resolution | Base act over 200 streams |");
                    sb.AppendLine("|---|---|---|---|---|---|");
                    foreach (var p in lead.WithinReach.Where(p => Math.Abs(p.U * 20 - Math.Round(p.U * 20)) < 1e-9 || Math.Abs(p.U - lead.U0) < 1e-12 || Math.Abs(p.U - Sensitivity.Reach) < 1e-12))
                    {
                        var share = Share(_primary, m, lead, p.U, s.Chosen, 200);
                        sb.AppendLine("| " + F(p.U) + (Math.Abs(p.U - lead.U0) < 1e-12 ? " (as it stood)" : "") + " | " + p.Top + " | " + p.TopScore.ToString("+0.000;-0.000", CultureInfo.InvariantCulture) + " | " + p.Chosen + " | " + (p.Ambiguous ? "seed, " + p.Band + " tied" : "clear") + " | " + P(share, 1.0) + " |");
                    }
                    sb.AppendLine();
                }
            }
            return (m.Who, sb.ToString());
        }

        /// <summary>The share of random streams that choose a given act at one urgency.</summary>
        static double Share(Scenario001Content c, Moment m, WantSweep w, double u, string act, int streams)
        {
            var motives = Sensitivity.With(m.Motives, w.Name, w.Target, u);
            var hits = 0;
            var d = new Deliberator(c.Rules);
            for (var k = 0; k < streams; k++)
            {
                var rng = new Rng(m.Seed).Fork(m.Who + "@" + m.Minute + "#" + k);
                var decision = d.Decide(m.Mind, m.Percept, motives, m.Day, rng, new TraceLog(), 0, m.Holding);
                if (decision.Chosen.Key == act) hits++;
            }
            return hits / (double)streams;
        }

        // ---------------------------------------------------------------- S1.7

        [Test, Timeout(1800000)]
        public void X5_WhatS17sHistoryDidToTheWantsAgainstWhatTheActNeeded()
        {
            // S1.7 E6: the same two arms (no history, and twelve earlier slights)
            // in twenty-seven immediate circumstances. The history moved wants and
            // the act changed in two, both ties. Here, at each of those decisions:
            // how far did the history move each want, and how far would that want
            // have had to move, on its own, to change the act?
            var sb = new StringBuilder();
            sb.AppendLine("## 5. S1.7's history, against what the act needed");
            sb.AppendLine();
            sb.AppendLine("S1.7 E6 ran one person (Elena) with and without twelve earlier slights by Daniel, in 27 immediate circumstances, and the act differed in 2, both settled by the seed. At each circumstance here: the decision without the history is swept one want at a time, and set against how far the history actually moved that want. Three readings of the same pair: the history's change to **one** want applied alone to the decision without history; **all** the history's changes to the wants applied together to it (the mind, and so every price, left as it was without the history); and the decision with the history, as S1.7 ran it, in which the history also changed what things cost.");
            sb.AppendLine();

            foreach (var (label, content) in new[] { ("A (as S1.7 ran it)", _modelA), ("B (primary)", _primary) })
            {
                sb.AppendLine("### " + label);
                sb.AppendLine();
                sb.AppendLine("| Room | With her | Hunger | Without history: chosen (preferred) | With it: chosen (preferred) | Wants the history moved (by) | Nearest change that would make another act preferred (and certain), same direction | One want alone moves the preferred act | All wants together move it |");
                sb.AppendLine("|---|---|---|---|---|---|---|---|---|");

                var sweeper = new Sweeper(content, FineStep);
                int circumstances = 0, actChanged = 0, preferredChanged = 0, singleWouldMove = 0, allWouldMove = 0, movedWants = 0, movedEnough = 0;
                var historyShift = new List<double>();
                var needed = new List<double>();
                var neededCertain = new List<double>();
                foreach (var room in new[] { "back_room", "kitchen", "living_room" })
                foreach (var present in new[] { new List<string> { "daniel" }, new List<string> { "daniel", "mara" }, new List<string>() })
                foreach (var hunger in new[] { 0.10, 0.60, 0.95 })
                {
                    S17Arm Arm(string l, int slights) => new S17Arm
                    {
                        Label = l, Subject = "elena", Other = "daniel", Answerable = true, LagFades = 40.0, ProbeKind = S17.Search,
                        PriorSlights = slights, Room = room, Present = present, Hunger = hunger
                    };
                    var c = S17.Run(content, Arm("C", 0));
                    var t = S17.Run(content, Arm("T", 12));
                    circumstances++;

                    var m = new Moment { Condition = label, Minute = c.Percept.Minute, Who = "elena", Mind = c.Mind, Percept = c.Percept, Motives = c.Motives, Day = c.Day, Stream = () => new Rng(1) };
                    m.Original = sweeper.Decide(m, m.Motives);
                    Assert.AreEqual(c.Chosen, m.Original.Chosen.Key, "the S1.7 decision is reproduced");

                    if (c.Chosen != t.Chosen) actChanged++;
                    // No intention is carried into these decisions, so the options
                    // considered are all of them, and the first ranked is preferred.
                    var cTop = c.Ranked[0];
                    var tTop = t.Ranked[0];
                    Assert.AreEqual(m.Original.Considered[0].Option.Key, cTop);
                    if (cTop != tTop) preferredChanged++;
                    var keys = c.Motives.Select(x => x.Key).Concat(t.Motives.Select(x => x.Key)).Distinct(StringComparer.Ordinal).OrderBy(x => x, StringComparer.Ordinal).ToList();
                    var moves = new List<string>();
                    var needs = new List<string>();
                    var anySingle = false;
                    foreach (var key in keys)
                    {
                        var before = c.Want(key);
                        var after = t.Want(key);
                        var delta = after - before;
                        if (Math.Abs(delta) < 0.005) continue;
                        movedWants++;
                        historyShift.Add(Math.Abs(delta));
                        var name = key.Split(':')[0];
                        var target = key.Contains(":") ? key.Split(':')[1] : null;
                        var w = sweeper.SweepOne(m, name, target);
                        double? need = delta > 0
                            ? (w.UpTop.HasValue && w.UpTop.Value <= Sensitivity.Reach ? w.DeltaUp : null)
                            : w.DeltaDown;
                        double? certain = delta > 0
                            ? (w.UpClear.HasValue && w.UpClear.Value <= Sensitivity.Reach ? w.DeltaUpClear : null)
                            : w.DeltaDownClear;
                        if (need.HasValue) needed.Add(need.Value);
                        if (certain.HasValue) neededCertain.Add(certain.Value);
                        var alone = sweeper.At(m, name, target, after);
                        var singleMoves = alone.Top != m.Original.Considered[0].Option.Key;
                        if (singleMoves) anySingle = true;
                        if (need.HasValue && need.Value <= Math.Abs(delta)) movedEnough++;
                        moves.Add(key + " " + (delta > 0 ? "+" : "") + F(delta));
                        needs.Add(key + " " + (need.HasValue ? (delta > 0 ? "+" : "-") + F(need.Value) + (certain.HasValue ? ", certain " + (delta > 0 ? "+" : "-") + F(certain.Value) : ", never certain") : "none within reach"));
                    }
                    if (anySingle) singleWouldMove++;
                    var together = sweeper.Decide(m, t.Motives);
                    var allMoves = together.Considered[0].Option.Key != m.Original.Considered[0].Option.Key;
                    if (allMoves) allWouldMove++;

                    sb.AppendLine("| " + room + " | " + (present.Count == 0 ? "nobody" : string.Join(", ", present)) + " | " + hunger.ToString("0.00", CultureInfo.InvariantCulture) + " | " +
                                  c.Chosen + " (" + cTop + ") | " + (t.Chosen == c.Chosen ? "same" : "**" + t.Chosen + "**") + " (" + (tTop == cTop ? "same" : "**" + tTop + "**") + ") | " + string.Join("; ", moves) + " | " + string.Join("; ", needs) + " | " +
                                  (anySingle ? "**yes**" : "no") + " | " + (allMoves ? "**yes** (" + together.Considered[0].Option.Key + ")" : "no") + " |");
                }
                sb.AppendLine();
                sb.AppendLine("**" + label + ".** The act chosen differed with the history in " + actChanged + " of " + circumstances + ", and the act preferred in " + preferredChanged + ". The history moved " + movedWants + " wants by more than 0.005 (" + Quantiles(historyShift) + " in size); the change each would have needed on its own to make another act preferred, where one existed within reach, was " + Quantiles(needed) + ", and to make it certain " + Quantiles(neededCertain) + ". In " + movedEnough + " of " + movedWants + " the history moved the want at least that far in that direction. One of the history's changes, applied alone, would have changed the preferred act in " + singleWouldMove + " of " + circumstances + " circumstances; all of them together, with the prices left as they were, in " + allWouldMove + "; and the history itself, which also changed the prices, in " + preferredChanged + ".");
                sb.AppendLine();
            }
            Record("5", sb.ToString());
        }

        // ---------------------------------------------------------------- traces

        [Test, Timeout(1800000)]
        public void X6_TracesFromCircumstanceToAct()
        {
            // Two decisions, chosen by rule rather than by look: on the canonical
            // condition under the primary baseline, among the first decisions, the
            // first want (people and wants in alphabetical order) that is raised
            // and moves the act, and the first that is raised and does not.
            var sb = new StringBuilder();
            sb.AppendLine("## 6. Traces, from what happened to what was done");
            sb.AppendLine();
            sb.AppendLine("Chosen by rule: among the first decisions on `daniel_ate_it` seed " + CensusSeed + " under the primary baseline (people and wants in alphabetical order), the first raised want that moves the act when moved alone, and the first raised want that does not. Each is followed from the circumstance to the act, and then through the deliberator as its urgency is moved.");
            sb.AppendLine();

            var sweeper = new Sweeper(_primary, FineStep);
            // Each person's candidates, written while their mind is as it decided.
            var found = FirstDecisions(_primary, "B (primary)", "daniel_ate_it", CensusSeed, (m, run) =>
            {
                var s = sweeper.Sweep(m);
                var raised = s.Wants.Where(w => w.Raised).OrderBy(w => w.Key, StringComparer.Ordinal).ToList();
                var mv = raised.FirstOrDefault(w => w.Class == Sweeper.Classes.Moves);
                var st = raised.FirstOrDefault(w => w.Class != Sweeper.Classes.Moves);
                return (Who: m.Who,
                        Moving: mv == null ? null : Trace(run, m, mv, sweeper),
                        MovingKey: mv?.Key,
                        Still: st == null ? null : Trace(run, m, st, sweeper),
                        StillKey: st?.Key);
            }).OrderBy(x => x.Who, StringComparer.Ordinal).ToList();

            var moving = found.FirstOrDefault(x => x.Moving != null);
            var still = found.FirstOrDefault(x => x.Still != null);
            Assert.IsNotNull(moving.Moving, "some raised want moves some first decision");
            Assert.IsNotNull(still.Still, "some raised want does not");

            sb.AppendLine("### 6.1 A want that moves the act: " + moving.MovingKey + ", " + moving.Who);
            sb.AppendLine();
            sb.Append(moving.Moving);
            sb.AppendLine();
            sb.AppendLine("### 6.2 A want that does not: " + still.StillKey + ", " + still.Who);
            sb.AppendLine();
            sb.Append(still.Still);
            sb.AppendLine();
            Record("6", sb.ToString());
        }

        static string Trace(Scenario001Run run, Moment m, WantSweep w, Sweeper sweeper)
        {
            var sb = new StringBuilder();
            var d = m.Original;
            var motive = m.Motives.First(x => x.Key == w.Key);
            var trace = run.Trace;

            sb.AppendLine("**Circumstance.** " + m.Circumstance + ". The morning's opening (`m000-open`): Elena counts the pantry in front of everyone and a can is missing.");
            sb.AppendLine();
            sb.AppendLine("**Perception to motivation, as the trace records it** (the want's record and everything it rests on; the access record for this decision is shared by every want and is shown once):");
            sb.AppendLine();
            sb.AppendLine("```");
            var lines = trace.Why(motive.TraceId).Replace("\r", "").Split('\n').Where(l => l.Length > 0).ToList();
            foreach (var l in lines.Take(40)) sb.AppendLine(l.Length > 240 ? l.Substring(0, 240) + " ..." : l);
            if (lines.Count > 40) sb.AppendLine("... " + (lines.Count - 40) + " more lines");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("**Motivation.** " + motive.Key + " at **" + F(motive.Urgency) + "**, from " + string.Join(", ", motive.RuleIds) + ": " + motive.Because + ". Every other want at this decision: " +
                          string.Join("; ", m.Motives.Where(x => x.Key != w.Key).Select(x => x.Key + " " + F(x.Urgency))) + ".");
            sb.AppendLine();
            var credited = d.Ranked.Where(r => r.Contributions.Any(c => c.MotiveKey == w.Key && c.Amount > 0)).ToList();
            sb.AppendLine("**Candidate generation.** " + d.Ranked.Count + " options available here: " + string.Join(", ", d.Ranked.Select(r => r.Option.Key).OrderBy(x => x, StringComparer.Ordinal)) + ". This want adds to " +
                          (credited.Count == 0 ? "none of them" : string.Join("; ", credited.Select(r => r.Option.Key + " (" + string.Join(", ", r.Contributions.Where(c => c.MotiveKey == w.Key).Select(c => c.ProposalId + ": " + F(c.Urgency) + " x fit " + F(c.Fit) + " = " + F(c.Amount))) + ")"))) + ".");
            var record = trace.Get(d.TraceId);
            if (record.Data.TryGetValue("foresaw", out var foresaw))
            {
                var mine = foresaw.Split(';').Select(x => x.Trim()).Where(x => x.Contains(" for " + w.Key + ":")).ToList();
                if (mine.Count > 0) sb.AppendLine(" Walks weighed for it by their end: " + string.Join("; ", mine) + ".");
            }
            sb.AppendLine();
            sb.AppendLine("**Deliberation.** " + string.Join("; ", d.Ranked.Take(5).Select(r => r.Option.Key + " " + r.Score.ToString("+0.000;-0.000", CultureInfo.InvariantCulture) + " (for " + F(r.Appeal) + ", against " + F(r.Cost) + ")")) + ". " +
                          (d.Resolution == Resolution.Ambiguous ? "Too close to call among " + string.Join(", ", d.Tied) + "; the seed settled it." : "Clear, by " + F(d.Margin) + ".") +
                          (d.Holding == null ? "" : " Carried in: " + d.Holding.MotiveKey + ", " + d.Commitment + "."));
            sb.AppendLine();
            sb.AppendLine("**Act.** " + d.Chosen.Key + (d.Leading == null ? ", led by nothing" : ", led by " + d.Leading.Key) + (d.Forms == null ? "" : "; it leaves the intention " + d.Forms.MotiveKey) + ".");
            sb.AppendLine();
            sb.AppendLine("**Moving it.** " + w.Key + " from 0 to 0.995: " + w.Class + (w.Reason == null ? "" : " (" + w.Reason + ")") + ". " +
                          (w.UpTop.HasValue ? "Raised to " + F(w.UpTop.Value) + " (+" + F(w.DeltaUp.Value) + "), the preferred act becomes " + w.UpTopTo + (w.UpTopAmbiguous ? ", as a tie" : "") + ". " : "Raising it never changes the preferred act within reach. ") +
                          (w.DownTop.HasValue ? "Lowered to " + F(w.DownTop.Value) + " (-" + F(w.DeltaDown.Value) + "), it becomes " + w.DownTopTo + (w.DownTopAmbiguous ? ", as a tie" : "") + "." : "Lowering it to nothing changes nothing."));
            sb.AppendLine();
            var at = w.UpTop.HasValue ? w.UpTop.Value : (w.DownTop.HasValue ? w.DownTop.Value : Sensitivity.Reach);
            var there = sweeper.At(m, w.Name, w.Target, at);
            sb.AppendLine("At " + F(at) + ": " + string.Join("; ", there.Decision.Ranked.Take(4).Select(r => r.Option.Key + " " + r.Score.ToString("+0.000;-0.000", CultureInfo.InvariantCulture))) + ".");
            sb.AppendLine();
            return sb.ToString();
        }

        // ---------------------------------------------------------------- what each want can do

        [Test]
        public void X7_WhatEachWantCanAskFor()
        {
            // Read straight from the proposals: for each want, the fit with which
            // it credits each kind of act. Two wants with the same row can differ
            // in the mind and never in what is done.
            var rules = _primary.Rules;
            var wants = rules.Motivation.Select(r => r.Motive).Distinct().OrderBy(x => x, StringComparer.Ordinal).ToList();
            var kinds = ActionOption.AllNames.ToList();
            double Fit(string want, string kind)
                => rules.Proposals.Where(p => p.Motive == want && p.Action == kind).Select(p => p.Fit).DefaultIfEmpty(0.0).Max();

            var sb = new StringBuilder();
            sb.AppendLine("## 7. What each want can ask for");
            sb.AppendLine();
            sb.AppendLine("From the proposals in `decisions.json`, unchanged: the fit with which each want credits each kind of act (the largest, where a want has several proposals for one kind, with different targets or conditions). A want's change of urgency reaches an act only through these numbers, and reaches the choice between two acts only through their difference.");
            sb.AppendLine();
            sb.AppendLine("| Want | " + string.Join(" | ", kinds) + " |");
            sb.AppendLine("|---|" + string.Concat(kinds.Select(_ => "---|")));
            foreach (var w in wants)
                sb.AppendLine("| " + w + " | " + string.Join(" | ", kinds.Select(k => { var f = Fit(w, k); return f == 0.0 ? "" : f.ToString("0.00", CultureInfo.InvariantCulture); })) + " |");
            sb.AppendLine("| **wants that credit it** | " + string.Join(" | ", kinds.Select(k => "**" + wants.Count(w => Fit(w, k) > 0.0) + "**")) + " |");
            sb.AppendLine("| **what it costs** (cost rules) | " + string.Join(" | ", kinds.Select(k => { var n = rules.Costs.Count(c => c.Action == k); return n == 0 ? "nothing" : n + " rule" + (n == 1 ? "" : "s"); })) + " |");
            sb.AppendLine();

            // How alike two wants are in what they ask for: the cosine of their rows.
            sb.AppendLine("How alike two wants are in what they ask for (the cosine of their rows; 1.00 is the same acts in the same proportions):");
            sb.AppendLine();
            sb.AppendLine("| | " + string.Join(" | ", wants) + " |");
            sb.AppendLine("|---|" + string.Concat(wants.Select(_ => "---|")));
            var pairs = new List<(string A, string B, double Cos)>();
            foreach (var a in wants)
            {
                var cells = new List<string>();
                foreach (var b in wants)
                {
                    var dot = kinds.Sum(k => Fit(a, k) * Fit(b, k));
                    var na = Math.Sqrt(kinds.Sum(k => Fit(a, k) * Fit(a, k)));
                    var nb = Math.Sqrt(kinds.Sum(k => Fit(b, k) * Fit(b, k)));
                    var cos = na == 0 || nb == 0 ? 0.0 : dot / (na * nb);
                    cells.Add(a == b ? "" : cos.ToString("0.00", CultureInfo.InvariantCulture));
                    if (string.CompareOrdinal(a, b) < 0) pairs.Add((a, b, cos));
                }
                sb.AppendLine("| " + a + " | " + string.Join(" | ", cells) + " |");
            }
            sb.AppendLine();
            var closest = pairs.OrderByDescending(x => x.Cos).First();
            sb.AppendLine("The two most alike are **" + closest.A + "** and **" + closest.B + "** (" + closest.Cos.ToString("0.00", CultureInfo.InvariantCulture) + "). Moving urgency from one to the other, which is what S1.7's history did, changes what is wanted and barely changes what any act is worth.");
            Record("7", sb.ToString());

            Assert.AreEqual(7, kinds.Count);
        }

        // ---------------------------------------------------------------- the instrument itself

        [Test]
        public void X0_MovingOneWantLeavesEveryOtherWantAsItWas()
        {
            var checkedMoments = FirstDecisions(_primary, "B (primary)", "daniel_ate_it", CensusSeed, (m, _) =>
            {
                foreach (var original in m.Motives)
                foreach (var u in new[] { 0.0, 0.3, 0.9 })
                {
                    var moved = Sensitivity.With(m.Motives, original.Name, original.TargetId, u);
                    foreach (var other in m.Motives.Where(x => x.Key != original.Key))
                        Assert.AreSame(other, moved.Single(x => x.Key == other.Key), "every other want is the same object");
                    var it = moved.SingleOrDefault(x => x.Key == original.Key);
                    if (u == 0.0) Assert.IsNull(it, "a want at nothing is left out, as the motivator leaves it out");
                    else Assert.AreEqual(u, it.Urgency, 1e-15);
                }

                // Unchanged, the decision is the decision the morning took.
                var sweeper = new Sweeper(_primary, 0.5);
                Assert.IsTrue(sweeper.Faithful(m, out var note), note);
                return m.Who;
            });
            Assert.AreEqual(4, checkedMoments.Count);
        }
    }
}
