"""Writes a finished morning as a story, in the style of Tools/narrate-morning.

Everything here comes from the morning's own record, so the same answers always give
the same bytes: no clock, no call counts, no run time.
"""
import data
from world import hunger_words, trait_words

DAYS_KNOWN = {"did": "did it", "saw": "saw it", "heard": "heard it"}


def fold_runs(log):
    """(turn index, person) -> ("head", n, last minute) | ("hidden",) for routine runs."""
    folds = {}
    for pid in data.ORDER:
        run = []

        def close():
            if len(run) > 1:
                folds[(run[0], pid)] = ("head", len(run), log[run[-1]]["minute"])
                for i in run[1:]:
                    folds[(i, pid)] = ("hidden",)
            run.clear()

        prev = None
        for i, rec in enumerate(log):
            d = next(x for x in rec["decisions"] if x["person"] == pid)
            sig = (d["label"], d["came_of_it"]) if d["mode"] == "routine" else None
            if sig is None or sig != prev:
                close()
            if sig is not None:
                run.append(i)
            prev = sig
        close()
    return folds


def quoted(words):
    return f"“{words}”"


def decision_line(d, fold=None):
    name = data.PEOPLE[d["person"]]["name"]
    if fold:
        _, n, last = fold
        return (f"- **{name}, minutes {d['minute']:02d}–{last:02d} ({n} decisions, the same each "
                f"time).** Rules: nothing social happened to them. **{d['label'][0].upper() + d['label'][1:]}** each "
                f"time. Came of it: {d['came_of_it']}")
    if d["mode"] == "routine":
        return (f"- **{name}.** Rules: nothing social happened to them. **{d['label'][0].upper() + d['label'][1:]}**. "
                f"Came of it: {d['came_of_it']}")
    because = "; ".join(d["triggers"])
    if d["mode"] == "fallback":
        return (f"- **{name}.** Social moment: {because}. **FALLBACK**: the model's answer could not "
                f"be used ({d['invalid']}), so the rules chose: **{d['label']}**. "
                f"Came of it: {d['came_of_it']}")
    said = f", saying {quoted(d['say'])}" if d.get("say") else ""
    return (f"- **{name}.** Social moment: {because}. **Chose: {d['label']}**{said} "
            f"(one of {d['offered']} options). Feeling: *{d['feeling']}*. "
            f"Reason: {quoted(d['reason'])} Came of it: {d['came_of_it']}")


def room_line(rec):
    parts, empty = [], []
    for r, people in rec["rooms"].items():
        if people:
            parts.append(f"{data.ROOMS[r]}: " + ", ".join(f"{n} {what}" for n, what in people))
        else:
            empty.append(data.ROOMS[r])
    if empty:
        parts.append("nobody in " + ", ".join(empty))
    return f"**min {rec['minute']:02d}** · " + " · ".join(parts)


def render(morning, seed, model_name, command):
    log = morning.log
    for rec in log:
        for d in rec["decisions"]:
            d["minute"] = rec["minute"]
    all_d = [d for rec in log for d in rec["decisions"]]
    n_model = sum(d["mode"] == "model" for d in all_d)
    n_fall = sum(d["mode"] == "fallback" for d in all_d)
    n_rout = sum(d["mode"] == "routine" for d in all_d)
    out = []
    w = out.append

    w(f"# The morning as a story: daniel_ate_it, rules and a language model, seed {seed}")
    w("")
    w(f"Generated by `{command}` in `Prototypes/llm-morning/`, a throwaway prototype outside Unity. "
      "Rules keep the house and each person's memory, and list what each of them may do. When "
      f"something social has just happened to someone, the model `{model_name}` chooses among "
      "those options for them, says the words, and names a feeling. Every other turn is settled "
      "by the rules. Do not edit it by hand; run the script again.")
    w("")
    w(f"**{len(all_d)} decisions** in {data.MINUTES} minutes, one per person every "
      f"{data.MINUTES_PER_TURN} minutes: {n_model} by the model at social moments, {n_fall} where "
      f"the model's answer could not be used and the rules chose instead, {n_rout} routine ones "
      f"settled by the rules. {len(morning.said)} lines were spoken aloud. The pantry held "
      f"{data.PORTIONS} portions at the start and {morning.portions} at the end.")
    w("")
    w("## How to read it")
    w("")
    w("- **Social moment**: something social had just happened to this person (someone spoke "
      "where they could hear it, accused them, came to sit with them, ate in front of them, or "
      "looks upset in the same room). Only then is the model asked. What happened is listed.")
    w("- **Chose**: the option the model picked from those the rules offered. Its words are in "
      "quotes. The feeling and the one-sentence reason are the model's, as it wrote them.")
    w("- **Rules**: nothing social happened to this person; they carried on with what they were "
      "doing, or stayed put.")
    w("- **FALLBACK**: the model's answer could not be used (the reason is given); the rules chose "
      "as on a routine turn.")
    w(f"- A feeling that shows on a face (scared, angry, hurt, crying...) is seen by the others in "
      f"the room for {data.MINUTES_PER_TURN * 3} minutes and counts as upset nearby. One that does "
      "not (guilty, ashamed, anxious, tense...) stays with the person who feels it.")
    w("- Voices carry between rooms without the words, except into or out of the bathroom.")
    w("- Each **min** line lists every room at that minute: who is in it and what they are doing. "
      "A minute is shown only when a decision is told there.")
    w("- A line headed with a minute range folds a run of identical routine decisions by one person.")
    w("")

    w("## The cast at minute 0")
    w("")
    names = [data.PEOPLE[p]["name"] for p in data.ORDER]
    w("| | " + " | ".join(names) + " |")
    w("|---|" + "---|" * len(names))
    rows = [
        ("Age", lambda p: str(p["age"])),
        ("Role in the family", lambda p: p["role_short"]),
        ("Where, how hungry", lambda p: f"kitchen, hunger {p['hunger']:.2f} ({hunger_words(p['hunger'])})"),
        ("Temperament", lambda p: trait_words(p["traits"])),
        ("What matters to them", lambda p: ", ".join(p["values"])),
        ("Knows about the can", lambda p: "ate it in the night; nobody saw" if p is data.PEOPLE[data.CULPRIT]
         else "only that it is missing"),
    ]
    for label, f in rows:
        w(f"| {label} | " + " | ".join(f(data.PEOPLE[p]) for p in data.ORDER) + " |")
    w("")
    w("### What each of them remembers at minute 0")
    w("")
    w("One row per thing that happened, with how each of them came to know it. This is all the "
      "model is ever told about the days before.")
    w("")
    w("| Day | What happened | " + " | ".join(names) + " |")
    w("|---|---|" + "---|" * len(names))
    for day, text, who in data.BACKSTORY:
        w(f"| {day} | {text} | " + " | ".join(DAYS_KNOWN.get(who.get(p), "not there") for p in data.ORDER) + " |")
    w(f"| 4 | {data.OPENING} | " + " | ".join("did it" if p == "elena" else "saw it" for p in data.ORDER) + " |")
    w("")

    w("## The morning")
    w("")
    folds = fold_runs(log)
    for i, rec in enumerate(log):
        lines = []
        for d in rec["decisions"]:
            f = folds.get((i, d["person"]))
            if f and f[0] == "hidden":
                continue
            lines.append(decision_line(d, f))
        if not lines:
            continue
        w(room_line(rec))
        out.extend(lines)
        w("")

    w("## What was said")
    w("")
    if not morning.said:
        w("Nobody said anything all morning.")
    for s in morning.said:
        w(f"- min {s['minute']:02d}, {s['room']}. **{s['who']}** {s['act']}: {quoted(s['words'])}")
    w("")

    w("## At the end")
    w("")
    where = []
    for r in data.ROOMS:
        people = [q.name for q in morning.people.values() if q.room == r]
        if people:
            where.append(f"{data.ROOMS[r]}: {', '.join(people)}")
    eaten = [f"{q.name} {q.eaten:g}" for q in morning.people.values() if q.eaten]
    w(f"At minute {data.MINUTES}: {'; '.join(where)}. {morning.portions} of {data.PORTIONS} portions "
      f"left; eaten this morning: {', '.join(eaten) if eaten else 'none'}.")
    w("")
    confessed = [d for d in all_d if d["option"] == "confess" and d["mode"] == "model"]
    w("- Who admitted taking it: " + (", ".join(f"{data.PEOPLE[d['person']]['name']} at minute "
                                                 f"{d['minute']:02d}" for d in confessed) or "nobody") + ".")
    acc = [f"{data.PEOPLE[d['person']]['name']} accused {data.PEOPLE[d['option'][7:]]['name']} "
           f"(minute {d['minute']:02d})" for d in all_d if d["option"].startswith("accuse_")]
    w("- Accusations: " + ("; ".join(acc) if acc else "none") + ".")
    knowers = [q.name for q in morning.people.values() if q.knows_culprit == data.CULPRIT and q.id != data.CULPRIT]
    w("- Who else knows Daniel took it: " + (", ".join(knowers) if knowers else "nobody") + ".")
    last = []
    for pid in data.ORDER:
        mine = [d for d in all_d if d["person"] == pid and d["mode"] == "model"]
        name = data.PEOPLE[pid]["name"]
        last.append(f"{name} *{mine[-1]['feeling']}* (minute {mine[-1]['minute']:02d})" if mine
                    else f"{name}: never asked")
    w("- The last feeling each of them named: " + "; ".join(last) + ".")
    w("")
    return "\n".join(out)
